#include "PondWave.h"
#include <algorithm>
#include <cmath>
#include <stdexcept>

namespace Frontier::ProjectFluid {
PondWave::PondWave(std::uint32_t rows,float length,float width):BaseRows_(rows),Length_(length),Width_(width){if(rows<3||rows>160000||!std::isfinite(length)||!std::isfinite(width)||length<.01f||width<.01f||length>10000||width>10000)throw std::range_error("invalid pond dimensions");
const double columns=std::round((double(rows)-1)*double(width)/length)+1;
if(columns<3||columns*rows>160000)throw std::range_error("pond grid exceeds 160000 cells or has a degenerate axis");MaxRows_=static_cast<std::uint32_t>(std::floor(std::sqrt(160000.0*double(length)/width)));while((static_cast<std::uint32_t>(std::lround((MaxRows_-1)*width/length))+1)*MaxRows_>160000)--MaxRows_;Allocate(rows);}
void PondWave::Allocate(std::uint32_t rows){Rows_=rows;Columns_=static_cast<std::uint32_t>(std::lround((rows-1)*Width_/Length_))+1;Dx_=Width_/(Columns_-1);Dz_=Length_/(Rows_-1);Height_.assign(Columns_*Rows_,0);Velocity_.assign(Columns_*Rows_,0);Acceleration_.assign(Columns_*Rows_,0);Solid_.assign(Columns_*Rows_,0);for(std::uint32_t j=0;j<Rows_;++j)for(std::uint32_t i=0;i<Columns_;++i){const float x=i*Dx_-Width_/2,z=j*Dz_-Length_/2;for(const auto& o:Obstacles_)if((x-o.x)*(x-o.x)+(z-o.z)*(z-o.z)<o.radius*o.radius)Solid_[j*Columns_+i]=1;}}
void PondWave::Reset(){Time_=Accumulator_=DroppedTime_=0;Refinements_=ClampHits_=0;Allocate(BaseRows_);}
float PondWave::SampleField(const std::vector<float>& field,float x,float z,std::uint32_t rows)const{const std::uint32_t columns=static_cast<std::uint32_t>(std::lround((rows-1)*Width_/Length_))+1;const float gx=std::clamp((x/Width_+.5f)*(columns-1),0.0f,static_cast<float>(columns-1)),gz=std::clamp((z/Length_+.5f)*(rows-1),0.0f,static_cast<float>(rows-1));const std::uint32_t i=std::min(columns-2,static_cast<std::uint32_t>(gx)),j=std::min(rows-2,static_cast<std::uint32_t>(gz));const float a=gx-i,b=gz-j;const std::size_t k=static_cast<std::size_t>(j)*columns+i;return(field[k]*(1-a)+field[k+1]*a)*(1-b)+(field[k+columns]*(1-a)+field[k+columns+1]*a)*b;}
float PondWave::Sample(float x,float z)const{return SampleField(Height_,x,z,Rows_);}
Vec3 PondWave::Normal(float x,float z)const{const float gx=(Sample(x+Dx_,z)-Sample(x-Dx_,z))/(2*Dx_),gz=(Sample(x,z+Dz_)-Sample(x,z-Dz_))/(2*Dz_);return Normalized({-gx,1,-gz});}
bool PondWave::IsWet(float x,float z,float margin)const{if(std::abs(x)>=Width_/2-margin||std::abs(z)>=Length_/2-margin)return false;for(const auto&o:Obstacles_)if((x-o.x)*(x-o.x)+(z-o.z)*(z-o.z)<(o.radius+margin)*(o.radius+margin))return false;return true;}
void PondWave::Disturb(float x,float z,float strength,float radius){
if(!std::isfinite(x)||!std::isfinite(z)||!std::isfinite(strength)||!std::isfinite(radius)||radius<1e-6f||radius>std::max(Width_,Length_))throw std::range_error("invalid pond disturbance");if(!IsWet(x,z))return;const int loX=std::max(0,static_cast<int>(std::floor((x-radius*3+Width_/2)/Dx_))),hiX=std::min(static_cast<int>(Columns_)-1,static_cast<int>(std::ceil((x+radius*3+Width_/2)/Dx_))),loZ=std::max(0,static_cast<int>(std::floor((z-radius*3+Length_/2)/Dz_))),hiZ=std::min(static_cast<int>(Rows_)-1,static_cast<int>(std::ceil((z+radius*3+Length_/2)/Dz_)));for(int j=loZ;j<=hiZ;++j)for(int i=loX;i<=hiX;++i){const std::size_t k=static_cast<std::size_t>(j)*Columns_+i;if(Solid_[k])continue;const float dx=i*Dx_-Width_/2-x,dz=j*Dz_-Length_/2-z,q=(dx*dx+dz*dz)/(2*radius*radius);Height_[k]=std::clamp(Height_[k]+strength*.32f*(1-q)*std::exp(-q),-.55f,.55f);}}
float PondWave::MaxSlope()const{float maximum=0;for(std::uint32_t j=1;j+1<Rows_;++j)for(std::uint32_t i=1;i+1<Columns_;++i){const std::size_t k=static_cast<std::size_t>(j)*Columns_+i;if(Solid_[k]||Solid_[k-1]||Solid_[k+1]||Solid_[k-Columns_]||Solid_[k+Columns_])continue;maximum=std::max(maximum,std::hypot((Height_[k+1]-Height_[k-1])/(2*Dx_),(Height_[k+Columns_]-Height_[k-Columns_])/(2*Dz_)));}return maximum;}
bool PondWave::RefineIfNeeded(){if(Rows_>=std::min(BaseRows_*2,MaxRows_))return false;const float slope=MaxSlope();const std::uint32_t desired=slope>.85f?BaseRows_*2:slope>.4f?static_cast<std::uint32_t>(std::lround(BaseRows_*1.5f)):Rows_;if(desired<=Rows_)return false;const auto oldHeight=Height_,oldVelocity=Velocity_;const auto oldRows=Rows_;Allocate(std::min(MaxRows_,desired));for(std::uint32_t j=0;j<Rows_;++j)for(std::uint32_t i=0;i<Columns_;++i){const std::size_t k=static_cast<std::size_t>(j)*Columns_+i;if(Solid_[k])continue;const float x=i*Dx_-Width_/2,z=j*Dz_-Length_/2;Height_[k]=SampleField(oldHeight,x,z,oldRows);Velocity_[k]=SampleField(oldVelocity,x,z,oldRows);}++Refinements_;return true;}
float PondWave::StableDt()const{return std::min(1.0f/90,.35f/(Speed_*std::sqrt(1/(Dx_*Dx_)+1/(Dz_*Dz_))));}
void PondWave::Acceleration(){const float cx=Speed_*Speed_/(Dx_*Dx_),cz=Speed_*Speed_/(Dz_*Dz_);for(std::uint32_t j=0;j<Rows_;++j)for(std::uint32_t i=0;i<Columns_;++i){const std::size_t k=static_cast<std::size_t>(j)*Columns_+i;if(Solid_[k]){Acceleration_[k]=0;continue;}const float centre=Height_[k],left=i>0&&!Solid_[k-1]?Height_[k-1]:centre,right=i+1<Columns_&&!Solid_[k+1]?Height_[k+1]:centre,bottom=j>0&&!Solid_[k-Columns_]?Height_[k-Columns_]:centre,top=j+1<Rows_&&!Solid_[k+Columns_]?Height_[k+Columns_]:centre;Acceleration_[k]=cx*(left+right-2*centre)+cz*(bottom+top-2*centre);}}
void PondWave::Step(float dt){if(!std::isfinite(dt)||dt<=0||dt>StableDt()*1.00001f)throw std::range_error("pond timestep exceeds CFL bound");const float decay=std::exp(-Damping_*dt*.5f);Acceleration();for(std::size_t k=0;k<Height_.size();++k)if(!Solid_[k]){Velocity_[k]=Velocity_[k]*decay+.5f*dt*Acceleration_[k];Height_[k]+=dt*Velocity_[k];}Acceleration();for(std::size_t k=0;k<Height_.size();++k)if(!Solid_[k]){Velocity_[k]=(Velocity_[k]+.5f*dt*Acceleration_[k])*decay;if(std::abs(Height_[k])>.55f){Height_[k]=std::copysign(.55f,Height_[k]);Velocity_[k]=0;++ClampHits_;}}Time_+=dt;}
void PondWave::Advance(float seconds,std::uint32_t maxSteps){if(!std::isfinite(seconds)||seconds<0)throw std::range_error("invalid pond frame duration");const float accepted=std::min(seconds,.1f);DroppedTime_+=seconds-accepted;Accumulator_+=accepted;const float dt=StableDt();std::uint32_t steps=0;while(Accumulator_+1e-12f>=dt&&steps<maxSteps){Step(dt);Accumulator_=std::max(0.0f,Accumulator_-dt);++steps;}if(Accumulator_>=dt){const float keep=std::fmod(Accumulator_,dt);DroppedTime_+=Accumulator_-keep;Accumulator_=keep;}}
float PondWave::Energy()const{double energy=0;const float c2=Speed_*Speed_;for(std::uint32_t j=0;j<Rows_;++j)for(std::uint32_t i=0;i<Columns_;++i){const std::size_t k=static_cast<std::size_t>(j)*Columns_+i;if(Solid_[k])continue;energy+=Velocity_[k]*Velocity_[k];if(i+1<Columns_&&!Solid_[k+1])energy+=c2*std::pow((Height_[k+1]-Height_[k])/Dx_,2);if(j+1<Rows_&&!Solid_[k+Columns_])energy+=c2*std::pow((Height_[k+Columns_]-Height_[k])/Dz_,2);}return static_cast<float>(.5*energy*Dx_*Dz_);}
}
