#include "PondWave.h"
#include "PondBody.h"
#include <algorithm>
#include <array>
#include <cmath>
#include <cstdint>
#include <fstream>
#include <iostream>
#include <limits>
#include <string>
#include <vector>
namespace PF=Frontier::ProjectFluid;
namespace {
struct Pixel{float r,g,b;};struct Screen{float x,y,z;bool visible;};
PF::Vec3 Cross(PF::Vec3 a,PF::Vec3 b){return{a.y*b.z-a.z*b.y,a.z*b.x-a.x*b.z,a.x*b.y-a.y*b.x};}
Pixel Mix(Pixel a,Pixel b,float t){t=std::clamp(t,0.f,1.f);return{a.r+(b.r-a.r)*t,a.g+(b.g-a.g)*t,a.b+(b.b-a.b)*t};}
struct Optics{Pixel colour,absorption;float scattering,roughness;};
Optics Material(const std::string& key){if(key=="ocean")return{{.03f,.30f,.42f},{1.8f,.35f,.16f},.18f,.16f};if(key=="swamp")return{{.20f,.30f,.10f},{1.2f,.55f,1.8f},.55f,.30f};if(key=="puddle")return{{.14f,.34f,.38f},{.8f,.25f,.18f},.12f,.08f};if(key=="dirty")return{{.30f,.20f,.08f},{1.0f,1.4f,2.4f},.82f,.38f};return{{.06f,.38f,.48f},{.55f,.16f,.10f},.08f,.10f};}
class Renderer{public:Renderer(int w,int h):W(w),H(h),C(W*H),D(W*H,std::numeric_limits<float>::max()){Camera={10,7.2f,10.5f};PF::Vec3 target{0,0,0};F=PF::Normalized(target-Camera);R=PF::Normalized(Cross(F,{0,1,0}));U=PF::Normalized(Cross(R,F));Focal=H*.5f/std::tan(50*3.14159265f/360);for(int y=0;y<H;++y)for(int x=0;x<W;++x)C[y*W+x]=Mix({.035f,.055f,.08f},{.32f,.38f,.42f},float(y)/H);}
Screen Project(PF::Vec3 p)const{PF::Vec3 q=p-Camera;float z=PF::Dot(q,F);return{W*.5f+PF::Dot(q,R)*Focal/z,H*.5f-PF::Dot(q,U)*Focal/z,z,z>.05f};}
void Triangle(PF::Vec3 pa,PF::Vec3 pb,PF::Vec3 pc,PF::Vec3 na,PF::Vec3 nb,PF::Vec3 nc,const Optics& optical,float depth){Screen a=Project(pa),b=Project(pb),c=Project(pc);if(!a.visible||!b.visible||!c.visible)return;float area=(b.x-a.x)*(c.y-a.y)-(b.y-a.y)*(c.x-a.x);if(std::abs(area)<1e-6f)return;int x0=std::clamp(int(std::floor(std::min({a.x,b.x,c.x}))),0,W-1),x1=std::clamp(int(std::ceil(std::max({a.x,b.x,c.x}))),0,W-1),y0=std::clamp(int(std::floor(std::min({a.y,b.y,c.y}))),0,H-1),y1=std::clamp(int(std::ceil(std::max({a.y,b.y,c.y}))),0,H-1);PF::Vec3 light=PF::Normalized({-.4f,.8f,.25f});for(int y=y0;y<=y1;++y)for(int x=x0;x<=x1;++x){float px=x+.5f,py=y+.5f,w0=((b.x-px)*(c.y-py)-(b.y-py)*(c.x-px))/area,w1=((c.x-px)*(a.y-py)-(c.y-py)*(a.x-px))/area,w2=1-w0-w1;if(w0<0||w1<0||w2<0)continue;float z=w0*a.z+w1*b.z+w2*c.z;std::size_t at=y*W+x;if(z>=D[at])continue;D[at]=z;PF::Vec3 n=PF::Normalized(na*w0+nb*w1+nc*w2);float fresnel=.0204f+.9796f*std::pow(1-std::max(0.f,PF::Dot(n,(Camera-(pa*w0+pb*w1+pc*w2))/z)),5.f),diffuse=.15f+.6f*std::max(0.f,PF::Dot(n,light)),spec=std::pow(std::max(0.f,PF::Dot(n,PF::Normalized(light+(Camera-pa)/z))),100*(1-optical.roughness)+8);Pixel bed{.17f,.13f,.085f},transmit{bed.r*std::exp(-(optical.absorption.r+optical.scattering)*depth),bed.g*std::exp(-(optical.absorption.g+optical.scattering)*depth),bed.b*std::exp(-(optical.absorption.b+optical.scattering)*depth)},body{optical.colour.r*diffuse,optical.colour.g*diffuse,optical.colour.b*diffuse},reflection{.38f,.48f,.58f};Pixel out=Mix(transmit,body,std::min(.85f,.20f+optical.scattering*.5f));out=Mix(out,reflection,fresnel);out.r+=spec*.8f;out.g+=spec*.75f;out.b+=spec*.68f;C[at]=out;}}
void Sphere(PF::Vec3 centre,float radius,Pixel colour){Screen s=Project(centre);int rr=std::max(1,int(Focal*radius/s.z));for(int oy=-rr;oy<=rr;++oy)for(int ox=-rr;ox<=rr;++ox){float nx=float(ox)/rr,ny=-float(oy)/rr,q=nx*nx+ny*ny;if(q>1)continue;int x=int(s.x)+ox,y=int(s.y)+oy;if(x<0||y<0||x>=W||y>=H)continue;float nz=std::sqrt(1-q),z=s.z-radius*nz;std::size_t at=y*W+x;if(z<D[at]){D[at]=z;float l=.2f+.8f*std::max(0.f,nx*-.3f+ny*.7f+nz*.5f);C[at]={colour.r*l,colour.g*l,colour.b*l};}}}
void Line(PF::Vec3 a,PF::Vec3 b,Pixel c){Screen p=Project(a),q=Project(b);int steps=std::max(1,int(std::max(std::abs(q.x-p.x),std::abs(q.y-p.y))));for(int i=0;i<=steps;++i){float t=float(i)/steps;int x=int(p.x+(q.x-p.x)*t),y=int(p.y+(q.y-p.y)*t);if(x>=0&&y>=0&&x<W&&y<H)C[y*W+x]=c;}}
bool Save(const std::string& path){std::ofstream f(path,std::ios::binary);f<<"P6\n"<<W<<' '<<H<<"\n255\n";for(auto p:C)for(float v:{p.r,p.g,p.b}){unsigned char q=static_cast<unsigned char>(std::pow(std::clamp(v,0.f,1.f),1/2.2f)*255+.5f);f.write(reinterpret_cast<char*>(&q),1);}return bool(f);}private:int W,H;std::vector<Pixel>C;std::vector<float>D;PF::Vec3 Camera,F,R,U;float Focal;};}
int main(int argc,char**argv){std::string output=argc>1?argv[1]:"pond.ppm",material=argc>2?argv[2]:"clean";PF::PondWave pond;PF::PondBody body;body.Reset();body.Grab(.15f,.65f);pond.Disturb(-1.3f,-.4f,.75f,.42f);pond.Disturb(1.8f,.8f,-.48f,.34f);for(int frame=0;frame<180;++frame){if(frame==45)pond.Disturb(.2f,1.1f,.6f,.28f);if(frame==45)body.Release();body.Update(pond,1.f/60);pond.Advance(1.f/60);if(frame%30==0)pond.RefineIfNeeded();}Renderer r(1280,720);Optics optics=Material(material);float bedDepth=material=="puddle"?.065f:.62f;const auto& h=pond.Heights();for(std::uint32_t z=0;z+1<pond.Rows();++z)for(std::uint32_t x=0;x+1<pond.Columns();++x){auto point=[&](std::uint32_t i,std::uint32_t j){return PF::Vec3{i*pond.Dx()-pond.Width()/2,h[j*pond.Columns()+i],j*pond.Dz()-pond.Length()/2};};PF::Vec3 a=point(x,z),b=point(x+1,z),c=point(x+1,z+1),d=point(x,z+1),na=pond.Normal(a.x,a.z),nb=pond.Normal(b.x,b.z),nc=pond.Normal(c.x,c.z),nd=pond.Normal(d.x,d.z);r.Triangle(a,b,c,na,nb,nc,optics,bedDepth);r.Triangle(a,c,d,na,nc,nd,optics,bedDepth);}for(const auto&o:pond.Obstacles())r.Sphere({o.x,.12f,o.z},o.radius,{.20f,.18f,.15f});r.Sphere({body.X(),body.Y()+.27f,body.Z()},.28f,{1,.62f,.03f});const float x=pond.Width()/2,z=pond.Length()/2;r.Line({-x,0,-z},{x,0,-z},{1,.32f,.05f});r.Line({x,0,-z},{x,0,z},{1,.32f,.05f});r.Line({x,0,z},{-x,0,z},{1,.32f,.05f});r.Line({-x,0,z},{-x,0,-z},{1,.32f,.05f});if(!r.Save(output))return 2;std::cout<<"Ripple pond C++ mirror | "<<pond.Columns()<<'x'<<pond.Rows()<<" samples | t "<<pond.Time()<<" s | dt "<<pond.StableDt()<<" | energy "<<pond.Energy()<<" | refinements "<<pond.Refinements()<<" | clamps "<<pond.ClampHits()<<" | duck wakes "<<body.Wakes()<<"\nproof frame: "<<output<<'\n';}
