// Offline viewport render (software raster of the panel's Canvas 2D calls): node Verification/render.js [fillet|cyl] [matcap|plastic|flat] → Verification/view.png
// software rasterizer for the panel's canvas 2D calls → PNG
process.env.SMOKE_BOOT_ONLY='1';
const W=900,H=700;const px=new Float32Array(W*H*3).fill(24);
let path=[],cur=null,fillStyle='#000',strokeStyle='#000',lineWidth=1;
const col=c=>{if(typeof c!=='string')return null;let m=/rgba?\(([\d.]+),\s*([\d.]+),\s*([\d.]+)(?:,\s*([\d.]+))?\)/.exec(c);if(m)return [+m[1],+m[2],+m[3],m[4]===undefined?1:+m[4]];m=/^#([0-9a-f]{6})$/i.exec(c);if(m){const v=parseInt(m[1],16);return [v>>16,(v>>8)&255,v&255,1];}m=/^#([0-9a-f]{3})$/i.exec(c);if(m){return [parseInt(m[1][0]+m[1][0],16),parseInt(m[1][1]+m[1][1],16),parseInt(m[1][2]+m[1][2],16),1];}return null;};
const blend=(x,y,c)=>{if(x<0||y<0||x>=W||y>=H)return;const i=(y*W+x)*3;const a=c[3];px[i]=px[i]*(1-a)+c[0]*a;px[i+1]=px[i+1]*(1-a)+c[1]*a;px[i+2]=px[i+2]*(1-a)+c[2]*a;};
function fillPoly(P,c){if(P.length<3)return;let y0=Math.max(0,Math.floor(Math.min(...P.map(p=>p[1])))),y1=Math.min(H-1,Math.ceil(Math.max(...P.map(p=>p[1]))));for(let y=y0;y<=y1;y++){const xs=[];const yc=y+.5;for(let i=0;i<P.length;i++){const a=P[i],b=P[(i+1)%P.length];if((a[1]<=yc&&b[1]>yc)||(b[1]<=yc&&a[1]>yc)){xs.push(a[0]+(yc-a[1])/(b[1]-a[1])*(b[0]-a[0]));}}xs.sort((a,b)=>a-b);for(let k=0;k+1<xs.length;k+=2){for(let x=Math.max(0,Math.round(xs[k]));x<Math.min(W,Math.round(xs[k+1]));x++)blend(x,y,c);}}}
function strokePoly(P,closed,c,w){const n=P.length;for(let i=0;i<n-(closed?0:1);i++){const a=P[i],b=P[(i+1)%n];if(!a||!b)continue;const L=Math.hypot(b[0]-a[0],b[1]-a[1]);const steps=Math.max(1,Math.ceil(L));for(let s=0;s<=steps;s++){const t=s/steps;const x=a[0]+(b[0]-a[0])*t,y=a[1]+(b[1]-a[1])*t;const r=Math.max(0,Math.round(w/2)-1);for(let dx=-r;dx<=r;dx++)for(let dy=-r;dy<=r;dy++)blend(Math.round(x)+dx,Math.round(y)+dy,c);}}}
const subpaths=[];
const ctx=new Proxy({},{get:(t,k)=>{
  if(k==='fillStyle')return fillStyle;if(k==='strokeStyle')return strokeStyle;if(k==='lineWidth')return lineWidth;if(k==='canvas')return {width:W,height:H};
  if(k==='measureText')return()=>({width:10});if(k==='createLinearGradient'||k==='createRadialGradient')return()=>({addColorStop(){},_g:true});
  if(k==='beginPath')return()=>{subpaths.length=0;cur=null;};if(k==='moveTo')return(x,y)=>{cur=[[x,y]];subpaths.push(cur);};if(k==='lineTo')return(x,y)=>{if(!cur){cur=[];subpaths.push(cur);}cur.push([x,y]);};if(k==='closePath')return()=>{if(cur)cur.closed=true;};
  if(k==='arc')return(x,y,r)=>{const p=[];for(let i=0;i<24;i++)p.push([x+Math.cos(i/24*6.283)*r,y+Math.sin(i/24*6.283)*r]);p.closed=true;subpaths.push(p);cur=null;};if(k==='roundRect'||k==='rect')return(x,y,w,h)=>{const p=[[x,y],[x+w,y],[x+w,y+h],[x,y+h]];p.closed=true;subpaths.push(p);cur=null;};
  if(k==='fill')return()=>{const c=col(fillStyle);if(!c)return;subpaths.forEach(p=>fillPoly(p,c));};if(k==='stroke')return()=>{const c=col(strokeStyle);if(!c)return;subpaths.forEach(p=>strokePoly(p,!!p.closed,c,lineWidth));};
  return()=>{};},set:(t,k,v)=>{if(k==='fillStyle')fillStyle=v;else if(k==='strokeStyle')strokeStyle=v;else if(k==='lineWidth')lineWidth=v;return true;}});
global.__CTX=ctx;
try{require(__dirname+'/smoke.js');}catch(e){console.log('boot',e.message);}
M.resize();M.createWorkplane({base:'XY',offset:0,tilt:0,size:120,show:true});M.view.target=[0,0,0];M.view.dist=260;M.setView('top');
const scene=process.argv[2]||'fillet';
if(scene==='fillet'){M.startOp('rect');M.toolClick(380,300);M.toolClick(520,380);const R=M.doc.figures.filter(f=>f.kind==='curve').pop();M.selectTool();M.doc.sel=new Set([R.id]);M.startOp('extrude');M.solidKey({key:'3'});M.solidKey({key:'0'});M.solidKey({key:'Enter'});const b=M.doc.figures.filter(f=>f.kind==='body').pop();b.edits=[{type:'fillet',key:'top:all',r:12}];M.invalidate(b.id);M.topoCache.clear();M.doc.sel.clear();}
else if(scene==='push'){M.startOp('rect');M.toolClick(380,300);M.toolClick(520,380);const R=M.doc.figures.filter(f=>f.kind==='curve').pop();M.selectTool();M.doc.sel=new Set([R.id]);M.startOp('extrude');M.solidKey({key:'3'});M.solidKey({key:'0'});M.solidKey({key:'Enter'});const b=M.doc.figures.filter(f=>f.kind==='body').pop();b.edits=[{type:'fillet',key:'top:all',r:5},{type:'fillet',key:'side:0:1',r:8}];M.invalidate(b.id);M.topoCache.clear();
  if(process.env.PRE){const ti0=M.topo(b).faces.findIndex(f=>f.key==='cap:top');M.faceOpApply([M.faceInfoWorld(b,ti0)],'inset',3);M.invalidate(b.id);M.topoCache.clear();console.log(M.topo(b).faces.map(f=>f.key).join(' '));}const ti=M.topo(b).faces.findIndex(f=>f.key===(process.env.KEY||'cap:top'));const h=M.faceInfoWorld(b,ti);console.log('face',h.key,h.n);if(process.env.TOOL){M.sub_.sel.clear();M.sub_.sel.set('k',{fig:b.id,kind:'face',idx:ti});M.solidStart('extrude');M.solidMove(450,300);M.solidMove(450,200);M.solidKey({key:'2'});M.solidKey({key:'0'});M.solidKey({key:'Enter'});}else M.faceOpApply([h],'push',+(process.env.PUSH||20));M.invalidate(b.id);M.topoCache.clear();console.log(JSON.stringify(b.params),JSON.stringify(b.faceOps));M.doc.sel.clear();}
else if(scene==='uslot'){M.view.dist=420;M.startOp('pslot');[[380,300],[380,420],[520,420],[520,300]].forEach(([x,y])=>M.toolClick(x,y));M.finishTool&&M.finishTool();const R=M.doc.figures.filter(f=>f.kind==='curve').pop();console.log('curve',R&&R.ctype,R&&R.params.pts.length,R&&(R.params.bulge||[]).filter(b=>b).length);M.selectTool();M.doc.sel=new Set([R.id]);M.startOp('extrude');M.solidKey({key:'3'});M.solidKey({key:'0'});M.solidKey({key:'Enter'});const b=M.doc.figures.filter(f=>f.kind==='body').pop();console.log('faces',M.topo(b).faces.map(f=>f.key).join(' '));
  if(process.env.EDIT){b.edits=JSON.parse(process.env.EDIT);M.invalidate(b.id);M.topoCache.clear();}
  if(process.env.PUSH){const ti=M.topo(b).faces.findIndex(f=>f.key==='cap:top');M.faceOpApply([M.faceInfoWorld(b,ti)],'push',+process.env.PUSH);M.invalidate(b.id);M.topoCache.clear();console.log(JSON.stringify(b.params),JSON.stringify(b.faceOps));}
  M.doc.sel.clear();}
else if(scene==='lcc'){M.startOp('rect');M.toolClick(380,300);M.toolClick(520,380);const R=M.doc.figures.filter(f=>f.kind==='curve').pop();R.params.pts=JSON.parse(process.env.PTS||'[[-20,-15],[20,-15],[20,0],[0,0],[0,15],[-20,15]]');R.params.bulge=[];M.invalidate(R.id);M.selectTool();M.doc.sel=new Set([R.id]);M.startOp('extrude');M.solidKey({key:'2'});M.solidKey({key:'0'});M.solidKey({key:'Enter'});const b=M.doc.figures.filter(f=>f.kind==='body').pop();b.edits=JSON.parse(process.env.EDIT||'[{"type":"fillet","key":"side:0:3","r":6}]');M.invalidate(b.id);M.topoCache.clear();M.doc.sel.clear();}
else if(scene==='mix'){M.startOp('rect');M.toolClick(380,300);M.toolClick(520,380);const R=M.doc.figures.filter(f=>f.kind==='curve').pop();M.selectTool();M.doc.sel=new Set([R.id]);M.startOp('extrude');M.solidKey({key:'3'});M.solidKey({key:'0'});M.solidKey({key:'Enter'});const b=M.doc.figures.filter(f=>f.kind==='body').pop();b.edits=[{type:'fillet',key:'top:1',r:12},{type:'fillet',key:'side:0:1',r:8}];M.invalidate(b.id);M.topoCache.clear();M.doc.sel.clear();}
else if(scene==='vbevel'){M.startOp('rect');M.toolClick(380,300);M.toolClick(520,380);const R=M.doc.figures.filter(f=>f.kind==='curve').pop();M.selectTool();M.doc.sel=new Set([R.id]);M.startOp('extrude');M.solidKey({key:'3'});M.solidKey({key:'0'});M.solidKey({key:'Enter'});const b=M.doc.figures.filter(f=>f.kind==='body').pop();const t=M.topo(b);const tops=t.verts.map((v,i)=>v.p[2]>1?i:-1).filter(i=>i>=0);b.faceOps=tops.map((i,k)=>({op:'vbevel',v:[...t.verts[i].p],d:12,type:'fillet'}));M.invalidate(b.id);M.topoCache.clear();M.doc.sel=new Set([b.id]);}
else{M.startOp('circle');M.toolClick(450,340);M.toolClick(520,340);const C=M.doc.figures.filter(f=>f.kind==='curve').pop();M.selectTool();M.doc.sel=new Set([C.id]);M.startOp('extrude');M.solidKey({key:'4'});M.solidKey({key:'0'});M.solidKey({key:'Enter'});M.doc.sel.clear();}
M.view.az=+(process.env.AZ||44);M.view.el=+(process.env.EL||34);M.view.dist=+(process.env.DIST||110);M.view.target=[0,0,+(process.env.TZ||10)];M.view.shade=process.argv[3]||'matcap';M.draw();
const fs=require('fs'),zlib=require('zlib');const raw=Buffer.alloc((W*3+1)*H);for(let y=0;y<H;y++){raw[y*(W*3+1)]=0;for(let x=0;x<W*3;x++)raw[y*(W*3+1)+1+x]=Math.max(0,Math.min(255,px[y*W*3+x]))|0;}
const crc=(b)=>{let c=~0;for(const v of b){c^=v;for(let k=0;k<8;k++)c=(c>>>1)^(0xEDB88320&-(c&1));}return ~c>>>0;};const chunk=(t,d)=>{const l=Buffer.alloc(4);l.writeUInt32BE(d.length);const td=Buffer.concat([Buffer.from(t),d]);const c=Buffer.alloc(4);c.writeUInt32BE(crc(td));return Buffer.concat([l,td,c]);};
const ihdr=Buffer.alloc(13);ihdr.writeUInt32BE(W,0);ihdr.writeUInt32BE(H,4);ihdr[8]=8;ihdr[9]=2;fs.writeFileSync(__dirname+'/view.png',Buffer.concat([Buffer.from([137,80,78,71,13,10,26,10]),chunk('IHDR',ihdr),chunk('IDAT',zlib.deflateSync(raw)),chunk('IEND',Buffer.alloc(0))]));console.log('rendered');
