import React, {useState} from 'react';
import {TreePine, TreeDeciduous, Sprout, Leaf, Box, SlidersHorizontal, ChevronRight, Plus, X, MoveUpRight, Droplets} from 'lucide-react';
import {Sun} from './celestial-icons.jsx';

export const speciesTypes={
 pine:{name:'Scots Pine',latin:'Pinus sylvestris',layer:'Canopy tree',icon:TreePine,color:'#a5c98b',defaults:{speciesWeight:45,spacing:7,maxSlope:35,instanceScale:1,scaleVariation:20}},
 birch:{name:'Silver Birch',latin:'Betula pendula',layer:'Deciduous tree',icon:TreeDeciduous,color:'#c4ce91',defaults:{speciesWeight:25,spacing:4,clusterSize:5,instanceScale:1,scaleVariation:25}},
 fern:{name:'Bracken Fern',latin:'Pteridium aquilinum',layer:'Understory',icon:Leaf,color:'#85c3a0',defaults:{speciesWeight:20,shade:75,moisture:65,instanceScale:1,scaleVariation:30}},
 grass:{name:'Tufted Hairgrass',latin:'Deschampsia cespitosa',layer:'Ground cover',icon:Sprout,color:'#b3c480',defaults:{speciesWeight:10,patchSize:2.5,patchDensity:70,instanceScale:1,scaleVariation:35}},
};
export const speciesObjects=Object.entries(speciesTypes).map(([id,s])=>({id,name:s.name,type:s.layer,parent:'forest',group:'World',icon:s.icon,color:s.color}));
export const speciesDefaults={generatorAsset:'',speciesWeight:25,instanceScale:1,scaleVariation:20,spacing:5,maxSlope:35,clusterSize:5,shade:75,moisture:65,patchSize:2.5,patchDensity:70};

export function SpeciesCollection({children,values,isHidden,onSelect,onAdd}) {
 const [adding,setAdding]=useState(false);
 const weights=children.map(c=>isHidden(c.id)?0:(values[c.id]?.speciesWeight??speciesTypes[c.base||c.id]?.defaults.speciesWeight??25));
 const total=weights.reduce((a,b)=>a+b,0);
 return <><p className="muted collection-note">Generator assets define the plant. Species layers control where and how often it is placed.</p><div className="species-collection">{children.map((c,i)=>{const type=speciesTypes[c.base||c.id];return <button key={c.id} className={`species-collection-row ${isHidden(c.id)?'muted-species':''}`} onClick={()=>onSelect(c.id)}><c.icon size={21} strokeWidth={1.4} style={{color:c.color}}/><span><strong>{c.name}</strong><small>{type?.layer} · {values[c.id]?.generatorAsset?.trim()?'Asset reference set':'Assign generator asset'}</small></span><span className="species-share">{total?Math.round(weights[i]/total*100):0}<small>%</small></span><ChevronRight size={14}/></button>})}</div><div className="species-weights-bar">{children.map((c,i)=><i key={c.id} style={{width:total?weights[i]/total*100+'%':'0%',background:c.color}}/>)}</div><div className="collection-actions"><span>Normalized relative placement weights</span><button onClick={()=>setAdding(!adding)}>{adding?<X size={13}/>:<Plus size={13}/>}Species</button></div>{adding&&<div className="species-add-options">{Object.entries(speciesTypes).map(([key,type])=><button key={key} onClick={()=>{onAdd(key);setAdding(false)}}><type.icon size={15} style={{color:type.color}}/>{type.name}</button>)}</div>}</>;
}

export function SpeciesInspector({kind,card,v,set,slider,num,disabled}) {
 const type=speciesTypes[kind];if(!type)return null;
 const Icon=type.icon;
 const ranges=(a,b)=><div className="range-labels"><span>{a}</span><span>{b}</span></div>;
 return <>
 {card('Generator asset',Box,<><div className="plant-asset-heading"><div className="plant-asset-icon"><Icon size={46} strokeWidth={1.2}/></div><div><h3>{type.name}</h3><p>{type.latin}</p><span>{type.layer} · instanced generator output</span></div></div><label className="generator-reference"><span>Asset reference</span><input aria-label="Plant generator asset reference" value={v('generatorAsset')} placeholder={`plants/${kind}/generated-mesh`} onChange={e=>set('generatorAsset',e.target.value)}/></label><div className="generator-boundary"><Box size={12}/><span>Reference only · plant generator is not connected in this UI.</span></div><div className="control-line current-bearing"><span>Placement weight</span><span>{v('speciesWeight')}</span></div>{slider('speciesWeight',0,100)}{ranges('Exclude from distribution','Higher share')}<p className="generator-note">Branching, leaf shape, materials, and growth stay in your plant generator. This layer only places its output.</p></>,'wide-card generator-asset-card')}
 {kind==='pine'&&card('Pine spacing',TreePine,<><div className="metric">{num('spacing','m',1)}</div><p className="muted">Minimum trunk-to-trunk separation</p><div className="plant-spacing" style={{gap:12+v('spacing')*3}}>{[0,1,2].map(i=><TreePine key={i} size={48-i*5} strokeWidth={1}/>)}</div>{slider('spacing',1,20,.5)}<div className="control-line current-bearing"><span>Maximum planting slope</span><span>{v('maxSlope')}°</span></div>{slider('maxSlope',0,60)}<p className="muted">Steeper terrain is excluded.</p></>)}
 {kind==='birch'&&card('Birch clusters',TreeDeciduous,<><div className="metric">{num('clusterSize','trees')}</div><p className="muted">Trees per scattering cluster</p><div className="birch-cluster">{Array.from({length:v('clusterSize')},(_,i)=><TreeDeciduous key={i} size={24+i%3*7} strokeWidth={1.2} style={{left:15+i*29%65+'%',top:13+i*19%53+'%'}}/>)}</div>{slider('clusterSize',1,12)}<div className="control-line current-bearing"><span>Minimum separation</span><span>{v('spacing')} m</span></div>{slider('spacing',1,12,.5)}</>)}
 {kind==='fern'&&card('Fern habitat',Leaf,<><div className="metric">{num('shade','%')}</div><p className="muted">Preference for shaded locations</p><div className="fern-habitat"><Sun size={28} strokeWidth={1} style={{opacity:1-v('shade')/120}}/><div style={{width:v('shade')+'%'}}/><Leaf size={54} strokeWidth={1}/></div>{slider('shade',0,100)}<div className="control-line current-bearing"><span><Droplets size={12}/> Moisture preference</span><span>{v('moisture')}%</span></div>{slider('moisture',0,100)}</>)}
 {kind==='grass'&&card('Grass patches',Sprout,<><div className="metric">{num('patchSize','m',1)}</div><p className="muted">Diameter of each ground-cover patch</p><div className="grass-patch" style={{transform:`scale(${.7+v('patchSize')/20})`}}>{Array.from({length:25},(_,i)=><Sprout key={i} size={17+i%3*4} style={{left:7+i*29%80+'%',top:5+i*19%75+'%',opacity:i<v('patchDensity')/4?.65:.04}}/>)}</div>{slider('patchSize',.5,8,.5)}<div className="control-line current-bearing"><span>Patch coverage</span><span>{v('patchDensity')}%</span></div>{slider('patchDensity',0,100)}</>)}
 {card('Instance variation',SlidersHorizontal,<><div className="metric">{num('instanceScale','×',1)}</div><p className="muted">Placement scale · leaves source geometry unchanged</p><div className="instance-variation">{[.7,1,.85].map((s,i)=><Icon key={i} size={Math.min(78,44*v('instanceScale')*(1-(1-s)*v('scaleVariation')/100))} strokeWidth={1}/>)}</div>{slider('instanceScale',.5,2,.1)}<div className="control-line current-bearing"><span>Random scale variation</span><span>± {v('scaleVariation')}%</span></div>{slider('scaleVariation',0,50)}<div className="generator-note">Effective range {(v('instanceScale')*(1-v('scaleVariation')/100)).toFixed(2)}–{(v('instanceScale')*(1+v('scaleVariation')/100)).toFixed(2)}×</div>{disabled&&<p className="muted">Parent Forest is disabled. Placement is inactive.</p>}</>)}
 </>;
}
