import React from 'react';
import {Box,Move3D,Palette,ChevronRight} from 'lucide-react';
export const meshDefaults={meshWidth:2,meshHeight:2,meshDepth:2,meshRadius:1,positionX:0,positionY:0,positionZ:0,objectMaterial:'material',meshSegments:32};
export function PrimitiveDiagram({shape,v}){
 const w=45+v('meshWidth')*8,h=35+v('meshHeight')*9,r=30+v('meshRadius')*12;
 return <svg className="primitive-diagram" viewBox="0 0 360 215" role="img" aria-label={`${shape} geometry schematic`}><path d="M35 173 H325 M180 20 V192" stroke="#ffffff0b" strokeDasharray="3 5"/>
 {shape==='sphere'?<><circle cx="180" cy="103" r={r} fill="#8aa9c80b" stroke="#a4bfd8"/><ellipse cx="180" cy="103" rx={r} ry={r*.3} fill="none" stroke="#8ba5c488"/><ellipse cx="180" cy="103" rx={r*.37} ry={r} fill="none" stroke="#8ba5c455"/><path d={`M180 103 H${180+r}`} stroke="#b8d1ea"/></>:shape==='cylinder'?<><path d={`M${180-r} ${104-h/2} V${104+h/2} A${r} 15 0 0 0 ${180+r} ${104+h/2} V${104-h/2}`} fill="#8aa9c80b" stroke="#a4bfd8"/><ellipse cx="180" cy={104-h/2} rx={r} ry="15" fill="none" stroke="#a4bfd8"/><ellipse cx="180" cy={104+h/2} rx={r} ry="15" fill="none" stroke="#a4bfd844" strokeDasharray="3 4"/></>:shape==='plane'?<><path d={`M${180-w} 96 L180 ${96-v('meshDepth')*7} L${180+w} 127 L180 ${127+v('meshDepth')*7}Z`} fill="#8aa9c80b" stroke="#a4bfd8"/>{[.25,.5,.75].map(t=><path key={t} d={`M${180-w*(1-t)} ${96+t*(31+v('meshDepth')*7)} L${180+w*t} ${96-v('meshDepth')*7+t*(31+v('meshDepth')*7)}`} stroke="#8ba5c444"/>)}</>:<><path d={`M${180-w} ${110-h/2} L180 ${85-h/2} L${180+w} ${110-h/2} V${110+h/2} L180 ${135+h/2} L${180-w} ${110+h/2}Z`} fill="#8aa9c80b" stroke="#a4bfd8"/><path d={`M${180-w} ${110-h/2} L180 ${135-h/2} L${180+w} ${110-h/2} M180 ${135-h/2} V${135+h/2}`} fill="none" stroke="#a4bfd8"/><path d={`M180 ${85-h/2} V${85+h/2}`} stroke="#8ba5c444" strokeDasharray="3 4"/></>}
 <text x="180" y="208" textAnchor="middle" fontSize="9" fill="#8094aa">LOCAL GEOMETRY · METERS</text></svg>;
}
export default function ObjectInspector({shape,card,v,set,slider,materials,onSelect,values}){
 const material=materials.find(m=>m.id===v('objectMaterial'));
 const controls=shape==='sphere'?[['meshRadius','Radius']]:shape==='cylinder'?[['meshRadius','Radius'],['meshHeight','Height']]:shape==='plane'?[['meshWidth','Width'],['meshDepth','Depth']]:[['meshWidth','Width'],['meshHeight','Height'],['meshDepth','Depth']];
 return <>
 {card('Geometry',Box,<><div className="scattering-top"><div className="metric">{shape[0].toUpperCase()+shape.slice(1)}</div><span className="small-pill">Primitive mesh</span></div><PrimitiveDiagram shape={shape} v={v}/><div className="geometry-controls">{controls.map(([key,label])=><label key={key}><span>{label}<strong>{v(key)} m</strong></span>{slider(key,.1,5,.1)}</label>)}</div></>,'wide-card')}
 {card('Position',Move3D,<><p className="muted">Local translation relative to scene origin</p><div className="position-inputs">{['X','Y','Z'].map((axis,i)=><label key={axis}><span style={{color:['#d69692','#9bc18c','#8eaedd'][i]}}>{axis}</span><input type="number" step=".1" aria-label={`Position ${axis}`} value={v('position'+axis)} onChange={e=>set('position'+axis,Number(e.target.value))}/><small>m</small></label>)}</div><button className="channel-reset" onClick={()=>['X','Y','Z'].forEach(a=>set('position'+a,0))}>Reset position</button></>)}
 {card('Material assignment',Palette,<><div className="assigned-material"><i style={{background:material?(values[material.id]?.['mat:baseColor']||'#a7b6c8'):'#444'}}/><span>{material?.name||'No material'}<small>Shared PBR material asset</small></span></div><label className="material-assignment-label">Material<select aria-label="Assigned material" value={v('objectMaterial')} onChange={e=>set('objectMaterial',e.target.value)}><option value="">None</option>{materials.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select></label>{material&&<button className="open-material" onClick={()=>onSelect(material.id)}>Edit material<ChevronRight size={14}/></button>}</>)}
 </>;
}
