import React, {useState,useEffect} from 'react';
import {createRoot} from 'react-dom/client';
import {Palette, Circle, Cylinder, Square, Folder, Rainbow, ArrowDown, CloudFog, CloudRain, CloudSnow, CloudHail, Cloud, Trees, Mountain, Waves, Camera, Search, ChevronDown, ChevronRight, Eye, EyeOff, Plus, X, Box, ArrowUpRight, RotateCcw, MoveUpRight, Wind, SlidersHorizontal, Check, Layers, Orbit, Leaf, Sparkles, Droplets, Aperture, ScanLine} from 'lucide-react';
import {Moon, Stars, Sun} from './celestial-icons.jsx';
import './style.css';
import ConstructMenu,{nativeWorld,constructItems,NativeEntityInspector} from './construct-menu.jsx';
import OutlinerIcon from './outliner-icons.jsx';
import {CloudControls,FogControls} from './atmosphere-shared-controls.jsx';
import LocalVolumeInspector,{localVolumeObjects} from './local-volumes.jsx';
import BakeQuickTiles from './bake-quick-tiles.jsx';
import MaterialInspector from './material-inspector.jsx';
import {materialDefaults} from './material-model.js';
import ObjectInspector,{meshDefaults} from './object-inspector.jsx';
import {migrateOrganization,organizationNode,SceneTree,OrganizationInspector} from './organization.jsx';
import {speciesTypes, speciesObjects, speciesDefaults, SpeciesCollection, SpeciesInspector} from './foliage-inspectors.jsx';
import ExtraInspectors, {extraDefaults, extraSwitches, extraDescriptions} from './extra-inspectors.jsx';
import {ParticleGauge, FallSpeed, WaterSection, WaveProfile, WaterTransmission, WaterCurrent, ShoreFoam} from './fluid-graphics.jsx';
import {cameraOptics, formatDistance} from './optics.js';
import {SensorField, DepthOfField} from './camera-graphics.jsx';
import {WindFlow, HazeTransmission, PrecipitationField, OzoneAbsorption} from './weather-graphics.jsx';
import {Iris, TerrainContours, RoughnessProfile, ErosionChannels} from './property-graphics.jsx';
import {SunGizmo, ScatteringGraph, IlluminanceCurve} from './environment-graphics.jsx';

const objects=[{id:'sun',name:'Sun',type:'Directional light',group:'Environment',icon:Sun,color:'#e8b65f'},{id:'flare',name:'Lens Flare',type:'Sun optical effect',parent:'sun',group:'Environment',icon:Sparkles,color:'#e2b58a'},{id:'moon',name:'Moon',type:'Lunar light',group:'Environment',icon:Moon,color:'#b5c4df'},{id:'stars',name:'Stars',type:'Celestial field',group:'Environment',icon:Stars,color:'#bea4e1'},{id:'sky',name:'Atmosphere',type:'Procedural sky',group:'Environment',icon:Orbit,color:'#99aafa'},{id:'rainbow',name:'Rainbow',type:'Atmospheric optical effect',parent:'sky',group:'Environment',icon:Rainbow,color:'#d5a4c4'},{id:'cloud',name:'Clouds',type:'Volumetric clouds',group:'Environment',icon:Cloud,color:'#8ebce8'},{id:'precip',name:'Precipitation',type:'Cloud subcomponent',parent:'cloud',group:'Environment',icon:Droplets,color:'#75c7df'},...localVolumeObjects,{id:'air',name:'Air / Wind',type:'Global wind field',group:'Environment',icon:Wind,color:'#72c8b3'},{id:'forest',name:'Forest',type:'Foliage collection',group:'World',icon:Trees,color:'#93c779'},...speciesObjects,{id:'terrain',name:'Terrain',type:'Landscape',group:'World',icon:Mountain,color:'#d6a078'},{id:'water',name:'Lake',type:'Water surface',group:'Water bodies',icon:Waves,color:'#74bdd4'},{id:'ocean',name:'Ocean',type:'Open water body',group:'Water bodies',icon:Waves,color:'#82abc9'},{id:'river',name:'River',type:'Flowing water body',group:'Water bodies',icon:MoveUpRight,color:'#87c1ba'},{id:'liquid',name:'Liquid Volume',type:'Contained fluid',group:'Water bodies',icon:Box,color:'#98b6d2'},{id:'cube',name:'Cube',type:'Mesh object',group:'World',icon:Box,color:'#a7bbd4'},{id:'sphere',name:'Sphere',type:'Mesh object',group:'World',icon:Circle,color:'#a8c2cc'},{id:'cylinder',name:'Cylinder',type:'Mesh object',group:'World',icon:Cylinder,color:'#b3b3d5'},{id:'plane',name:'Plane',type:'Mesh object',group:'World',icon:Square,color:'#a5b8c7'},{id:'material',name:'Standard PBR',type:'Surface material',group:'Materials',icon:Palette,color:'#c5a6d7'},{id:'camera',name:'Camera',type:'Perspective camera',group:'Scene',icon:Camera,color:'#bb9ae4'}];
// Semantic accents stay on icons; surfaces remain neutral graphite.
const cardIconColors={
 'Sun direction':'#e8b65f','Illuminance':'#e8c76a','Temperature':'#e69c79',
 'Daylight cycle':'#d4b970','Sun disc':'#f0bd72',
 'Atmospheric scattering':'#99aafa','Aerosol haze':'#d4b583','Ozone absorption':'#bd97db',
 'Ground fog':'#8fc2c6','Density falloff':'#8eaddb','Ground reflectance':'#d8c077',
 'Cloud coverage':'#8ebce8','Cloud base':'#a1b3e2','Layer thickness':'#a6a0d9',
 'Wind field':'#72c8b3','Precipitation':'#75c7df','Particle size':'#96bbe9','Fall speed':'#79b7d5',
 'Forest distribution':'#93c779','Species blend':'#b4c875','Growth variation':'#c2b783','Wind response':'#72c8b3',
 'Elevation & contours':'#d6a078','Surface detail':'#cab281','Erosion channels':'#81b8c8',
 'Snow line':'#a4c6e6','Rock exposure':'#c29583','Water level':'#74bdd4','Surface ripples':'#80c8bd','Water clarity':'#9cbde7','Water current':'#7dc3bf','Shoreline foam':'#bfd0ad',
 'Lens & field of view':'#bb9ae4','Aperture':'#d2a0cc','Focus distance':'#98abe2',
};
const propertySwitches={...extraSwitches,
 sun:[['Illuminance','Sunlight',Sun],['Sun disc','Sun disc',Sun],['Daylight cycle','Day cycle',Orbit]],
 sky:[['Atmospheric scattering','Scattering',Orbit],['Aerosol haze','Aerosols',Sparkles],['Ozone absorption','Ozone',Layers],['Ground fog','Fog',CloudFog]],
 cloud:[['Cloud coverage','Cloud layer',Cloud],['Layer thickness','Volume',Layers]],
 air:[['Wind field','Wind field',Wind]],
 precip:[['Precipitation','Falling particles',Droplets],['Fall speed','Falling motion',ArrowDown]],
 forest:[['Forest distribution','Distribution',Trees]],
 ...Object.fromEntries(Object.keys(speciesTypes).map(key=>[key,[['Instance variation','Variation',SlidersHorizontal]]])),
 terrain:[['Erosion channels','Erosion',Droplets],['Snow line','Snow cover',Mountain],['Rock exposure','Exposed rock',Layers]],
 water:[['Surface ripples','Ripples',Waves],['Water clarity','Transmission',Droplets],['Water current','Current',MoveUpRight],['Shoreline foam','Foam',Sparkles]],
 camera:[['Aperture','Depth of field',Aperture]],
};
function readProject(){try{return JSON.parse(localStorage.getItem('frontier-project')||'{}')}catch{return {}}}
const stored=readProject();
function App(){
 const [nativeRows,setNativeRows]=useState([]);
 const [constructInspect,setConstructInspect]=useState(null);
 const syncNative=data=>{
  setNativeRows(data.entities.map(entity=>({id:entity.id,base:'native',name:entity.name,type:constructItems[entity.kind].name,group:'World',icon:entity.camera?Camera:Box,color:'#a8bbeb',native:entity})));
  setOrganization(groups=>{const ids=data.entities.map(e=>e.id);const next=groups.map(g=>({...g,members:g.members.filter(id=>!id.startsWith('native-')||ids.includes(id))}));const owned=new Set(next.filter(g=>g.kind==='folder').flatMap(g=>g.members));const missing=ids.filter(id=>!owned.has(id));let folder=next.find(g=>g.id==='folder-native-authoring');if(!folder){folder={id:'folder-native-authoring',kind:'folder',name:'Native authoring scene',members:[]};next.push(folder)}folder.members=[...folder.members,...missing];return next});
 };
 useEffect(()=>{let active=true;nativeWorld().then(data=>{if(active)syncNative(data)}).catch(()=>{});return()=>{active=false}},[]);
 useEffect(()=>{const shortcut=e=>{if(e.shiftKey&&e.code==='KeyA'&&!/INPUT|TEXTAREA|SELECT/.test(e.target.tagName)&&!e.target.isContentEditable){e.preventDefault();setAdd(true)}};window.addEventListener('keydown',shortcut);return()=>window.removeEventListener('keydown',shortcut)},[]);
 const [organization,setOrganization]=useState(()=>migrateOrganization(stored,objects));
 const [selected,setSelected]=useState('sun'),[query,setQuery]=useState(''),[collapsed,setCollapsed]=useState({}),[hidden,setHidden]=useState(stored.hidden||{}),[values,setValues]=useState(stored.values||{}),[add,setAdd]=useState(false),[extras,setExtras]=useState((stored.extras||[]).map(o=>({...objects.find(b=>b.id===o.base),...o}))),[saved,setSaved]=useState(true);
 const existing=[...objects,...extras,...nativeRows];
 const derived=existing.filter(o=>!o.parent).flatMap(parent=>objects.filter(template=>template.parent===(parent.base||parent.id)&&!existing.some(child=>child.parent===parent.id&&(child.base||child.id)===template.id)).map(template=>({...template,id:parent.id+'-'+template.id,base:template.id,parent:parent.id})));
 const unsorted=[...existing,...derived],all=[...unsorted.filter(o=>!o.parent).flatMap(o=>[o,...unsorted.filter(c=>c.parent===o.id)]),...organization.map(organizationNode)],obj=all.find(o=>o.id===selected),kind=obj.base||obj.id;
 const defaults={...materialDefaults,...meshDefaults,...extraDefaults,...speciesDefaults,...(speciesTypes[kind]?.defaults||{}),intensity:110,temperature:5600,azimuth:135,elevation:38,rainRate:6,dropSize:2,precipType:'Rain',fallSpeed:6,currentSpeed:.4,currentBearing:120,foam:35,discSize:.53,fog:18,falloff:1.6,albedo:30,snowline:120,slope:42,rayleigh:1.2,ozone:65,bearing:225,gusts:35,cloudBase:1.8,thickness:2.4,time:16.5,density:68,scale:1.2,seed:428,wind:2.4,biodiversity:65,haze:25,clouds:35,altitude:180,roughness:62,erosion:40,waterLevel:12,ripple:35,clarity:78,focal:35,aperture:2.8,focus:15};
 const v=(key)=>values[selected]?.[key]??defaults[key];
 const set=(key,val)=>{setValues(s=>({...s,[selected]:{...s[selected],[key]:val}}));setSaved(false)};
 const reset=()=>{setValues(s=>({...s,[selected]:{}}));setSaved(false)};
 const isHidden=(id,seen=new Set())=>{if(seen.has(id))return false;seen.add(id);const item=all.find(o=>o.id===id);return !!(hidden[id]||(item?.parent&&isHidden(item.parent,new Set(seen)))||organization.some(g=>g.members.includes(id)&&isHidden(g.id,new Set(seen))));};
 const renameOrganization=name=>{setOrganization(groups=>groups.map(g=>g.id===selected?{...g,name}:g));setSaved(false)};
 const updateMember=(id,adding)=>{setOrganization(groups=>groups.map(g=>{if(g.id===selected)return {...g,members:adding?[...new Set([...g.members,id])]:g.members.filter(m=>m!==id)};if(adding&&obj.base==='folder'&&g.kind==='folder')return {...g,members:g.members.filter(m=>m!==id)};return g}));setSaved(false)};
 const addOrganization=kind=>{const id=kind+'-'+Date.now(),item={id,kind,name:(kind==='folder'?'Folder':'Collection')+' '+(organization.filter(o=>o.kind===kind).length+1),members:[]};setOrganization(g=>[...g,item]);setSelected(id);setAdd(false);setSaved(false)};
 const forestSpecies=all.filter(o=>o.parent===selected&&speciesTypes[o.base||o.id]);
 const toggleHidden=(id)=>{setHidden(s=>({...s,[id]:!s[id]}));setSaved(false)};
 const num=(key,unit='',digits=0)=><><span>{Number(v(key)).toLocaleString('en-US',{maximumFractionDigits:digits})}</span><small>{unit}</small></>;
 const slider=(key,min,max,step=1)=><input aria-label={key} type="range" min={min} max={max} step={step} value={v(key)} onChange={e=>set(key,+e.target.value)} style={{'--progress':`${(v(key)-min)/(max-min)*100}%`}}/>;
 const optics=cameraOptics(v('focal'),v('aperture'),v('focus'));
 const featureOn=title=>values[selected]?.['feature:'+title]!==false;
 const card=(title,Icon,body,cls='')=><section className={`card ${cls} ${!featureOn(title)?'feature-disabled':''}`} style={{'--card-icon':cardIconColors[title]||obj.color}}><div className="card-heading"><span><Icon size={16}/>{title}</span>{!featureOn(title)&&<span className="card-off-label">OFF</span>}</div><fieldset className="card-body" disabled={!featureOn(title)} inert={!featureOn(title)?'':undefined}>{body}</fieldset></section>;
 const inspector=(<section className="inspector" style={{'--accent':obj.color}}>
   <header className="inspector-top"><div>Inspector <ChevronRight size={13}/><span>{obj.group}</span></div><button className={`save-status ${saved?'saved':''}`} onClick={()=>{try{localStorage.setItem('frontier-project',JSON.stringify({values,hidden,organization,organizationVersion:2,extras:extras.map(({icon,...o})=>o)}));setSaved(true)}catch{setSaved(false);window.alert('Unable to save locally. Remove a baked image or free browser storage, then try again.')}}}>{saved?<Check size={13}/>:<span className="unsaved-dot"/>}{saved?'All changes saved':'Save changes'}</button></header>
   <div className="inspector-content">
   <div className="object-header"><div className="object-title"><div><div className="eyebrow">{obj.type}</div><h1>{obj.name}</h1></div></div><div className="object-actions">{!obj.isContainer&&!obj.native&&<button className="reset" title="Reset object properties" onClick={reset}><RotateCcw size={14}/>Reset</button>}<button className={`enabled-pill ${isHidden(selected)?'disabled':''}`} title={isHidden(selected)&&!hidden[selected]?'Enable the containing folder, collection, or parent first':undefined} disabled={!!obj.native||(isHidden(selected)&&!hidden[selected])} onClick={()=>toggleHidden(selected)}><span/>{obj.native?'Native record':isHidden(selected)?'Disabled':'Enabled'}</button></div></div>
   <div className="section-label"><span>{obj.isContainer?'ORGANIZATION':'PROPERTIES'}</span><span>{(obj.native?'Native authoring record · read-only inspector':null)||(kind==='material'?'Surface channels & studio sphere':null)||(['cube','sphere','cylinder','plane'].includes(kind)?'Geometry, position & shared material':null)||(obj.isContainer?'Organization, membership & visibility':null)||(['local-cloud','local-fog'].includes(kind)?'Local volume · shared effects, bounds & position':null)||extraDescriptions[kind]||(speciesTypes[kind]&&'Forest / Species · generator asset & placement')||(kind==='sun'?'Light, direction & atmosphere':kind==='forest'?'Collection distribution & species layers':kind==='sky'?'Molecules, aerosols & absorption':kind==='cloud'?'Coverage, altitude & structure':kind==='air'?'Direction, speed & gusts':kind==='precip'?'Clouds / Precipitation · type, intensity & motion':kind==='terrain'?'Shape, surface & erosion':kind==='water'?'Surface, movement & depth':'Lens, focus & framing')}</span></div>
   <div className="property-switches" role="group" aria-label="Property switches">{(kind==='local-fog'?propertySwitches.sky.filter(([title])=>title==='Ground fog'):propertySwitches[kind==='local-cloud'?'cloud':kind]||[]).map(([title,label,ToggleIcon])=><button key={title} className={`property-switch ${featureOn(title)?'is-on':'is-off'}`} aria-label={`Toggle ${label}`} aria-pressed={featureOn(title)} onClick={()=>set('feature:'+title,!featureOn(title))}><span className="switch-icon"><ToggleIcon size={18} strokeWidth={1.7}/></span><span className="switch-name">{label}</span><span className="switch-state">{featureOn(title)?'ON':'OFF'}</span></button>)}</div>
   <div className={`cards ${kind}`}>
   {obj.native&&<NativeEntityInspector entity={obj.native}/>}
   {kind==='material'&&<MaterialInspector key={selected} card={card} v={v} set={set} values={values[selected]}/>}
   {['cube','sphere','cylinder','plane'].includes(kind)&&<ObjectInspector shape={kind} card={card} v={v} set={set} slider={slider} materials={all.filter(o=>(o.base||o.id)==='material')} onSelect={setSelected} values={values}/>}
   {obj.isContainer&&<OrganizationInspector key={obj.id} node={obj} all={all} card={card} onRename={renameOrganization} onMember={updateMember} onSelect={setSelected} isHidden={isHidden}/>}
   <SpeciesInspector kind={kind} card={card} v={v} set={set} slider={slider} num={num} disabled={isHidden(selected)}/>
   <ExtraInspectors kind={kind} card={card} v={v} set={set} slider={slider} num={num} featureOn={featureOn} active={!isHidden(selected)}/>
   {['sun','sky'].includes(kind)&&<div className="effect-child-links">{all.filter(child=>child.parent===selected).map(child=><button key={child.id} className="cloud-child-link" onClick={()=>setSelected(child.id)}><span><child.icon size={16} style={{color:child.color}}/><span>{child.name}<small>Optical effect subcomponent</small></span></span><ChevronRight size={16}/></button>)}</div>}
   {kind==='sun'&&<>
    {card('Sun direction',Orbit,<><div className="direction-top"><div className="metric">{num('elevation','°')}</div><span className="metric-caption">{v('elevation')<0?'Below the horizon':'Above the horizon'}</span></div><SunGizmo azimuth={v('azimuth')} elevation={v('elevation')} onChange={(a,e)=>{set('azimuth',a);set('elevation',e)}}/><div className="direction-controls"><label><span>Azimuth <MoveUpRight size={12}/></span><div>{v('azimuth')}<small>°</small></div>{slider('azimuth',0,360)}</label><label><span>Elevation <ArrowUpRight size={12}/></span><div>{v('elevation')}<small>°</small></div>{slider('elevation',-90,90)}</label></div></>,'direction-card')}
    {card('Illuminance',Sun,<><div className="metric">{num('intensity','klux')}</div><p className="muted">Direct sunlight intensity</p><IlluminanceCurve intensity={v('intensity')}/>{slider('intensity',0,150)}<div className="range-labels"><span>0 klux</span><span>150 klux</span></div></>,'intensity-card')}
    {card('Temperature',Sparkles,<><div className="metric">{num('temperature','K')}</div><div className="temperature-track">{slider('temperature',2000,10000,100)}</div><div className="range-labels"><span>Warm</span><span>Cool</span></div><div className="temperature-footer"><span className="color-chip" style={{background:v('temperature')<4500?'#efd0a3':v('temperature')>7000?'#b9d4f3':'#efe6d3'}}/><span>{v('temperature')<4500?'Golden warmth':v('temperature')>7000?'Cool daylight':'Natural daylight'}</span></div></>,'temperature-card')}
    {card('Daylight cycle',Sun,<><div className="cycle-title"><div className="metric time">{String(Math.floor(v('time'))).padStart(2,'0')}<span>:{v('time')%1>=.5?'30':'00'}</span></div><span className="small-pill">{v('time')<6||v('time')>=18?'Night':v('time')<12?'Morning':v('time')<17?'Afternoon':'Evening'}</span></div><DayCurve time={v('time')}/>{slider('time',0,24,.5)}<div className="range-labels"><span>00:00</span><span>06:00</span><span>12:00</span><span>18:00</span><span>24:00</span></div></>,'cycle-card')}
    {card('Sun disc',Sun,<><div className="disc-layout"><div><div className="metric">{num('discSize','°',2)}</div><p className="muted">Angular diameter</p></div><div className="solar-disc"><i style={{width:18+v('discSize')*30,height:18+v('discSize')*30}}/><span/></div></div>{slider('discSize',.1,2,.01)}<div className="range-labels"><span>Pinpoint</span><span>Broad disc</span></div><div className="disc-note"><span className="color-chip"/>Apparent size of the sun in the sky</div></>,'disc-card')}

   </>}
   {kind==='forest'&&<>
    {card('Forest distribution',Trees,<><div className="metric">{num('density','%')}</div><p className="muted">Collection coverage · weighted species distribution</p><div className="forest-map">{Array.from({length:65},(_,i)=>{const species=forestSpecies.filter(c=>!isHidden(c.id));const weights=species.map(c=>values[c.id]?.speciesWeight??speciesTypes[c.base||c.id].defaults.speciesWeight);const total=weights.reduce((a,b)=>a+b,0);if(!total)return null;let pick=((i*37)%65)/65*total,index=0;while(index<weights.length-1&&pick>=weights[index]){pick-=weights[index];index++;}const item=species[index],PlantIcon=item.icon;return <PlantIcon key={i} size={13+(i*7%15)} style={{left:`${5+((i*29+v('seed')*7)%88)}%`,top:`${8+((i*43+v('seed')*3)%78)}%`,color:item.color,opacity:i<v('density')*.65?.3+(i%4)*.16:.04}}/>})}</div>{slider('density',0,100)}<div className="range-labels"><span>Sparse planting</span><span>Dense planting</span></div><div className="control-line seed"><span>Distribution seed</span><button onClick={()=>set('seed',Math.floor(Math.random()*9999))}>{v('seed')}<RotateCcw size={12}/></button></div></>,'wide-card forest-distribution')}
    {card('Species collection',Leaf,<SpeciesCollection children={forestSpecies} values={values} isHidden={isHidden} onSelect={setSelected} onAdd={base=>{const template=speciesObjects.find(o=>o.id===base);const count=forestSpecies.filter(o=>(o.base||o.id)===base).length+1;const item={...template,base,id:base+'-'+Date.now(),parent:selected,name:template.name+' '+count};setExtras(a=>[...a,item]);setSelected(item.id);setSaved(false)}}/>,'wide-card')}
   </>}
   {kind==='sky'&&<>
    {card('Atmospheric scattering',Orbit,<><div className="scattering-top"><div><div className="eyebrow">RAYLEIGH STRENGTH</div><div className="metric">{num('rayleigh','×',1)}</div><p className="muted">How air molecules scatter sunlight</p></div><div className="scattering-legend"><span><i/>Molecules</span><span><i/>Aerosols</span></div></div><ScatteringGraph rayleigh={v('rayleigh')} haze={featureOn('Aerosol haze')?v('haze'):0}/><div className="scattering-bottom"><span>Short wavelengths scatter more strongly</span><span>λ⁻⁴</span></div>{slider('rayleigh',0,3,.1)}<div className="range-labels"><span>Subtle blue</span><span>Deep blue</span></div></>,'wide-card scattering-card')}
    {card('Aerosol haze',Sparkles,<><div className="scattering-top"><div className="metric">{num('haze','%')}</div><span className="small-pill">Mie scattering</span></div><p className="muted">Suspended particles soften and attenuate light</p><HazeTransmission haze={featureOn('Aerosol haze')?v('haze'):0}/>{slider('haze',0,100)}<div className="range-labels"><span>Clear air</span><span>Dense haze</span></div></>)}
    {card('Ozone absorption',Layers,<><div className="metric">{num('ozone','%')}</div><p className="muted">Selective absorption across visible wavelengths</p><OzoneAbsorption amount={v('ozone')}/>{slider('ozone',0,100)}<div className="range-labels"><span>Neutral</span><span>Rich twilight</span></div></>)}
    <FogControls card={card} v={v} slider={slider} num={num}/>
    {card('Density falloff',MoveUpRight,<><div className="metric">{num('falloff','km',1)}</div><p className="muted">Atmospheric density scale height</p><div className="falloff-chart">{Array.from({length:10},(_,i)=><div key={i}><span>{9-i}</span><i style={{width:`${8+Math.exp(-(9-i)/v('falloff'))*85}%`}}/></div>)}</div>{slider('falloff',.5,8,.1)}<div className="range-labels"><span>Low layer</span><span>High atmosphere</span></div></>)}
    {card('Ground reflectance',Sun,<><div className="reflectance-content"><div><div className="metric">{num('albedo','%')}</div><p className="muted">Light scattered back into the atmosphere</p></div><div className="albedo-swatch" style={{background:`rgb(${40+v('albedo')*1.9},${40+v('albedo')*1.9},${40+v('albedo')*1.9})`}}><ArrowUpRight size={24}/></div></div>{slider('albedo',0,100)}<div className="range-labels"><span>Dark ground</span><span>Reflective surface</span></div></>,'wide-card')}
   </>}
   {kind==='local-fog'&&<FogControls card={card} v={v} slider={slider} num={num}/>}
   {['cloud','local-cloud'].includes(kind)&&<>
    <CloudControls card={card} v={v} set={set} slider={slider} num={num}/>
    {kind==='cloud'&&<button className="cloud-child-link" onClick={()=>setSelected(all.find(o=>o.parent===selected)?.id||'precip')}><span><Droplets size={16}/><span>Precipitation<small>Cloud subcomponent</small></span></span><ChevronRight size={16}/></button>}
   </>}
   <LocalVolumeInspector key={'local-volume:'+selected} kind={kind} card={card} v={v} set={set}/>
   {kind==='air'&&<>
    {card('Wind field',Wind,<><div className="scattering-top"><div><div className="metric">{num('wind','m/s',1)}</div><p className="muted">{v('wind')===0?'Calm':v('wind')<4?'Light breeze':v('wind')<12?'Moderate wind':'Strong wind'} · sustained speed</p></div><span className="small-pill">{v('bearing')}° · {['N','NE','E','SE','S','SW','W','NW'][Math.round(v('bearing')/45)%8]}</span></div><WindFlow speed={v('wind')} bearing={v('bearing')} gusts={v('gusts')} active={!isHidden(selected)&&featureOn('Wind field')} onChange={(bearing,speed)=>{set('bearing',bearing);set('wind',speed)}}/><div className="wind-controls"><label><span>Speed <strong>{v('wind')} <small>m/s</small></strong></span>{slider('wind',0,30,.1)}<em>Calm to strong</em></label><label><span>Travel direction <strong>{v('bearing')}°</strong></span>{slider('bearing',0,360)}<em>Clockwise from north</em></label><label><span>Gust variation <strong>{v('gusts')}<small>%</small></strong></span>{slider('gusts',0,100)}<em>Steady to turbulent</em></label></div></>,'wide-card wind-field-card')}
   </>}
   {kind==='precip'&&<>
    {card('Precipitation',Droplets,<><div className="scattering-top"><div><div className="metric">{num('rainRate','mm/h',1)}</div><p className="muted">{v('precipType')==='Rain'?'Rainfall intensity':`Liquid-equivalent ${v('precipType')==='Hail'?'hail':'snowfall'} rate`}</p></div><div className="weather-segments" role="group" aria-label="Precipitation type">{[{type:'Rain',icon:CloudRain},{type:'Snow',icon:CloudSnow},{type:'Hail',icon:CloudHail}].map(({type,icon:ModeIcon})=><button key={type} aria-pressed={v('precipType')===type} onClick={()=>{set('precipType',type);set('fallSpeed',type==='Snow'?1.2:type==='Hail'?12:6);set('dropSize',Math.min(v('dropSize'),type==='Rain'?6:type==='Snow'?12:30))}}><ModeIcon size={14}/>{type}</button>)}</div></div><PrecipitationField rate={v('rainRate')} type={v('precipType')} size={v('dropSize')} fallSpeed={v('fallSpeed')} moving={featureOn('Fall speed')} active={!isHidden(selected)&&featureOn('Precipitation')}/>{isHidden(selected)&&<p className="weather-disabled">{hidden[obj.parent]?'Clouds are disabled. Enable the parent to resume precipitation.':'Precipitation is disabled.'}</p>}{slider('rainRate',0,30,.5)}<div className="range-labels"><span>None</span><span>Heavy precipitation</span></div></>,'wide-card')}
    {card('Particle size',Droplets,<><div className="metric">{num('dropSize','mm',1)}</div><p className="muted">{v('precipType')==='Snow'?'Snowflake diameter':v('precipType')==='Hail'?'Hailstone diameter':'Droplet diameter'}</p><ParticleGauge type={v('precipType')} size={v('dropSize')}/>{slider('dropSize',.5,v('precipType')==='Hail'?30:v('precipType')==='Snow'?12:6,.1)}<div className="range-labels"><span>Fine particles</span><span>Large particles</span></div></>)}
    {card('Fall speed',ArrowDown,<><div className="metric">{num('fallSpeed','m/s',1)}</div><p className="muted">Vertical particle velocity</p><FallSpeed speed={v('fallSpeed')} type={v('precipType')}/>{slider('fallSpeed',.2,30,.1)}<div className="range-labels"><span>Slow descent</span><span>Fast fall</span></div><div className="fall-speed-note">10 m descent <strong>{(10/v('fallSpeed')).toFixed(1)} s</strong></div></>)}
   </>}
   {kind==='terrain'&&<>
    {card('Elevation & contours',Mountain,<><div className="scattering-top"><div><div className="metric">{num('altitude','m')}</div><p className="muted">Peak elevation above the base plane</p></div><span className="small-pill">Topography</span></div><TerrainContours altitude={v('altitude')} roughness={v('roughness')} erosion={v('erosion')}/>{slider('altitude',0,500)}<div className="range-labels"><span>Lowlands</span><span>Alpine</span></div></>,'wide-card')}
    {card('Surface detail',SlidersHorizontal,<><div className="metric">{num('roughness','%')}</div><p className="muted">Fine-scale ridges & surface variation</p><RoughnessProfile roughness={v('roughness')}/>{slider('roughness',0,100)}<div className="range-labels"><span>Rolling</span><span>Jagged</span></div></>)}
    {card('Erosion channels',Droplets,<><div className="metric">{num('erosion','%')}</div><p className="muted">Runoff carves branching drainage paths</p><ErosionChannels erosion={v('erosion')}/>{slider('erosion',0,100)}<div className="range-labels"><span>Untouched</span><span>Weathered</span></div></>)}
    {card('Snow line',Mountain,<><div className="metric">{num('snowline','m')}</div><p className="muted">Snow begins above this elevation</p><div className="snowline-diagram"><div style={{background:`linear-gradient(#dedddd 0%,#dedddd ${Math.max(0,100-v('snowline')/5)}%,#665f54 ${Math.max(0,100-v('snowline')/5)}%,#393732 100%)`}}/><i style={{bottom:`${v('snowline')/5}%`}}/></div>{slider('snowline',0,500)}<div className="range-labels"><span>Snow-covered</span><span>Bare peaks</span></div></>)}
    {card('Rock exposure',Layers,<><div className="metric">{num('slope','°')}</div><p className="muted">Slope threshold for exposed rock</p><div className="slope-diagram"><div style={{transform:`rotate(-${v('slope')}deg)`}}/><span/><i/></div>{slider('slope',0,90)}<div className="range-labels"><span>Gentle slopes</span><span>Steep faces</span></div></>)}
   </>}
   {kind==='water'&&<>
    {card('Water level',Waves,<><div className="scattering-top"><div><div className="metric">{num('waterLevel','m',1)}</div><p className="muted">Surface elevation above the scene datum</p></div><span className="small-pill">Lake basin</span></div><WaterSection level={v('waterLevel')} onChange={height=>set('waterLevel',height)}/>{slider('waterLevel',0,25,.5)}<div className="range-labels"><span>0 m · datum</span><span>25 m</span></div></>,'wide-card')}
    {card('Surface ripples',Waves,<><div className="metric">{num('ripple','%')}</div><p className="muted">Small-wave amplitude</p><WaveProfile amount={v('ripple')} active={featureOn('Surface ripples')&&!isHidden(selected)}/>{slider('ripple',0,100)}<div className="range-labels"><span>Still surface</span><span>Choppy</span></div></>)}
    {card('Water clarity',Droplets,<><div className="metric">{num('clarity','%')}</div><p className="muted">Light attenuation through water</p><WaterTransmission clarity={v('clarity')}/>{slider('clarity',0,100)}<div className="range-labels"><span>Turbid</span><span>Clear</span></div><div className="water-detail">Light at 5 m <strong>{Math.round(Math.exp(-(.02+(1-v('clarity')/100)*.78)*5)*100)}%</strong></div></>)}
    {card('Water current',MoveUpRight,<><div className="scattering-top"><div className="metric">{num('currentSpeed','m/s',1)}</div><span className="small-pill">{v('currentBearing')}°</span></div><p className="muted">Surface flow · clockwise from north</p><WaterCurrent speed={featureOn('Water current')&&!isHidden(selected)?v('currentSpeed'):0} bearing={v('currentBearing')}/><div className="control-line"><span>Speed</span><span>{v('currentSpeed')} m/s</span></div>{slider('currentSpeed',0,3,.1)}<div className="control-line current-bearing"><span>Direction</span><span>{v('currentBearing')}°</span></div>{slider('currentBearing',0,360)}</>)}
    {card('Shoreline foam',Sparkles,<><div className="metric">{num('foam','%')}</div><p className="muted">Foam coverage at the water’s edge</p><ShoreFoam amount={v('foam')}/>{slider('foam',0,100)}<div className="range-labels"><span>Clean edge</span><span>Foamy shore</span></div></>)}
   </>}
   {kind==='camera'&&<>
    {card('Lens & field of view',Camera,<><div className="scattering-top"><div><div className="metric">{num('focal','mm')}</div><p className="muted">Focal length · full-frame sensor</p></div><span className="small-pill">{optics.horizontalFov.toFixed(1)}° horizontal</span></div><SensorField focal={v('focal')} aperture={v('aperture')} focus={v('focus')} optics={optics}/>{slider('focal',16,120)}<div className="range-labels"><span>Wide angle · 16 mm</span><span>Telephoto · 120 mm</span></div><div className="camera-linked-stats"><div><span>Vertical FOV</span><strong>{optics.verticalFov.toFixed(1)}°</strong></div><div><span>Frame at focus</span><strong>{optics.frameWidth.toFixed(1)} × {optics.frameHeight.toFixed(1)}<small> m</small></strong></div><div><span>Entrance pupil</span><strong>{optics.pupil.toFixed(1)}<small> mm</small></strong></div></div></>,'wide-card sensor-card')}
    {card('Aperture',Aperture,<><div className="metric"><small>ƒ / </small>{num('aperture','',1)}</div><p className="muted">Controls light intake & depth of field</p><div className="aperture-iris"><Iris opening={(16/v('aperture')-1)/(16/1.4-1)} label="Aperture blades opening and closing"/></div>{slider('aperture',1.4,16,.1)}<div className="range-labels"><span>Wide open</span><span>Stopped down</span></div><div className="camera-linked-stats two"><div><span>Pupil diameter</span><strong>{optics.pupil.toFixed(1)}<small> mm</small></strong></div><div><span>In-focus depth</span><strong>{formatDistance(optics.depth)}</strong></div></div></>)}
    {card('Focus distance',ScanLine,<><div className="metric">{num('focus','m')}</div><p className="muted">Drag the focal plane to set subject distance</p><DepthOfField focus={v('focus')} optics={optics} enabled={featureOn('Aperture')} onChange={distance=>set('focus',distance)}/>{slider('focus',1,100)}<div className="range-labels"><span>Near · 1 m</span><span>Far · 100 m</span></div><div className="camera-linked-stats two"><div><span>Near limit</span><strong>{featureOn('Aperture')?formatDistance(optics.near):'—'}</strong></div><div><span>Far limit</span><strong>{featureOn('Aperture')?formatDistance(optics.far):'—'}</strong></div></div><div className="focus-footnote">{featureOn('Aperture')?`Hyperfocal ${formatDistance(optics.hyperfocal)} · CoC 0.03 mm`:'Depth of field is disabled · all distances remain sharp'}</div></>,'focus-distance-card')}
   </>}
   </div>
   <BakeQuickTiles key={selected} object={obj} kind={kind} values={values[selected]||{}} settings={{...defaults,...values[selected]}} onSet={set} allValues={values}/>
   <footer className="inspector-footer"><span><span className="footer-dot"/>{obj.native?'Native record · saved to authoring scene':'Changes apply in real time'}</span><span>{obj.name} <span className="footer-slash">/</span> {obj.type}</span></footer>
   </div>
  </section>);
 return <main className="shell">
  <aside className="outliner">
   <div className="brand"><div className="brand-symbol"><Layers size={24} strokeWidth={1.5}/></div><span>frontier<span className="brand-dot">.</span></span><span className="version">ENGINE / 01</span></div>
   <div className="scene-label">WORKSPACE <span className="status-dot"/></div>
   <div className="scene-title"><span>Untitled world</span><span className="scene-extension">.scene</span></div>
   <div className="outliner-heading"><h2>Outliner <span>{all.length.toString().padStart(2,'0')}</span></h2><button className="icon-button" aria-label="Open Construct" title="Construct · Shift+A" onClick={()=>setAdd(!add)}>{add?<X size={17}/>:<Plus size={17}/>}</button></div>
   {add&&<ConstructMenu entities={objects} properties={constructInspect?inspector:null} onInspect={id=>{setConstructInspect(id);if(id)setSelected(id)}} onClose={()=>{setAdd(false);setConstructInspect(null)}} onOrganize={addOrganization} onCreated={data=>{syncNative(data);setSelected(data.entities.at(-1).id);setQuery('');setCollapsed(s=>({...s,Folders:false,'folder-native-authoring':false}));setSaved(false)}}/>}
   <label className="search"><Search size={15}/><input placeholder="Find an object..." value={query} onChange={e=>setQuery(e.target.value)}/>{query?<button aria-label="Clear search" onClick={()=>setQuery('')}><X size={13}/></button>:<span>⌕</span>}</label>
   <SceneTree all={all} organization={organization} selected={selected} onSelect={setSelected} collapsed={collapsed} setCollapsed={setCollapsed} isHidden={isHidden} toggleHidden={toggleHidden} query={query} values={values}/>
   <div className="outliner-bottom"><div className="world-icon"><OutlinerIcon object={{id:'project',icon:Box}} size={30}/></div><div><strong>Evergreen valley</strong><span>Local project</span></div><span className="little-dot"/></div>
  </aside>
  {add&&constructInspect?<section className="inspector"/>:inspector}
 </main>
}
function DayCurve({time}){
 const height=t=>60-42*Math.sin((t-6)/24*Math.PI*2),x=18+time/24*464,y=height(time);
 const path=Array.from({length:97},(_,i)=>`${i?'L':'M'}${18+i/96*464} ${height(i/4)}`).join(' ');
 return <svg className="day-curve full-day-curve" viewBox="0 0 500 123" role="img" aria-label={`24-hour daylight cycle, selected time ${Math.floor(time)}:${time%1?'30':'00'}`}>
 <rect x="18" y="10" width="116" height="98" rx="4" fill="#8397c109"/><rect x="366" y="10" width="116" height="98" rx="4" fill="#8397c109"/>
 <path d="M18 60 H482" stroke="#8c806b44" strokeDasharray="3 5"/>
 <path d={path} stroke="#a8a1a1" strokeOpacity=".45" fill="none" strokeWidth="1.3"/>
 <path d={Array.from({length:49},(_,i)=>`${i?'L':'M'}${134+i/48*232} ${height(6+i/4)}`).join(' ')} stroke="#dac18a" fill="none" strokeWidth="1.5"/>
 <path d={`M${x} 10 V110`} stroke="#c0ad8c" strokeDasharray="2 4" strokeOpacity=".45"/><circle cx={x} cy={y} r="11" fill={time<6||time>=18?'#a7b7df':'#e9c889'} opacity=".1"/><circle cx={x} cy={y} r="4" fill={time<6||time>=18?'#b3c2df':'#efd19a'}/>
 <g fill="#7a7770" fontSize="8"><text x="28" y="115">NIGHT</text><text x="235" y="115">DAY</text><text x="442" y="115">NIGHT</text></g>
 </svg>;
}
function WindLines({amount}){return <svg className="wind-lines" viewBox="0 0 400 110">{[0,1,2,3].map(i=><path key={i} d={`M${20+i*15} ${25+i*20} Q120 ${i*20-amount*2} 215 ${25+i*20} T${360-i*17} ${15+i*20}`} fill="none" stroke="currentColor" opacity={.2+i*.15} strokeWidth="1.2"/>)}</svg>}


createRoot(document.getElementById('root')).render(<App/>);
