#include "CelestialSequence.h"
#include "InspectorPanel.h"
#include "ControlPanel.h"
#include "WeatherDiagnostics.h"
#include "CpuDraw.h"
#include "PngWriteCounterpart.h"
#include <imgui_internal.h>
#include <memory>
#include <cstring>
#include <cstdio>
#include <limits>
#include <stdexcept>
using namespace Frontier;using namespace Frontier::ProjectZero;
static unsigned Checks=0;
static void Check(bool V,const char* N){++Checks;if(!V)throw std::runtime_error(N);}
static EditorProperty& Find(EditorSheet& S,const char* N){for(auto& G:S.Groups)for(unsigned I=0;I<G.PropertyCount;++I)if(!std::strcmp(G.Properties[I].Label,N))return G.Properties[I];throw std::runtime_error(N);}
static ImGuiWindow* Window(const char* N){for(auto* W:ImGui::GetCurrentContext()->Windows)if(W->Active&&std::strstr(W->Name,N))return W;throw std::runtime_error(N);}
static uint64_t BowHash(){for(auto* T:ImGui::GetCurrentContext()->UserTextures)if(T->Width==768&&T->Height==448){uint64_t H=1469598103934665603ull;for(int I=0;I<T->Width*T->Height*4;++I)H=(H^T->Pixels[I])*1099511628211ull;return H;}throw std::runtime_error("rainbow texture absent");}
static void Models(){
 WindSettings W;W.Speed=10;W.Bearing=90;W.Shear=.5f;W.Veer=0;float V[3];WindField::SampleStep(W,0,V);Check(std::abs(V[0]-10)<1e-5&&std::abs(V[1])<1e-5,"wind toward east");WindField::SampleStep(W,1000,V);Check(std::abs(V[0]-15)<1e-5,"altitude shear");W.Veer=90;WindField::SampleStep(W,1000,V);Check(V[1]<-14.9,"clockwise altitude veer");W.Steadiness=0;Check(WindField::SampleGust(W)==1,"zero variation removes gust");float P[]={0,0,2};WindField::SampleSwirl(W,P,0,V);Check(V[0]==0&&V[1]==0&&V[2]==0,"zero variation removes turbulence");
 auto Rain=std::make_unique<PrecipitationSystem>();Rain->Configure(256);PrecipitationSettings S;S.Enabled=true;S.SpawnFromClouds=false;S.GroundCollision=false;S.SizeScale=2;S.WindDrift=1;CloudLayerSettings C;C.CeilingMetres=10000;W.Veer=0;W.Shear=0;
 for(unsigned K=0;K<5;++K){Rain->Reset();S.Category=static_cast<PrecipitationCategory>(K);for(int I=0;I<20;++I)Rain->Step(S,C,W,P,.02f,I*.02f,0);Check(!Rain->Pool().empty()&&Rain->Pool().size()<=256,"all five backend types simulate within budget");for(const auto& Drop:Rain->Pool()){Check(std::isfinite(Drop.Position[0])&&Drop.Velocity[2]<0,"real falling particle");Check(Drop.Size>=1.4f&&Drop.Size<=2.6f,"size multiplier reaches particle pool");}Check(Rain->Pool()[0].Velocity[0]>0,"wind drives actual particle velocity");}
 Rain->Reset();S.SpawnFromClouds=true;C.Enabled=false;Rain->Step(S,C,W,P,.1f,0,0);Check(Rain->Pool().empty()&&Rain->Telemetry().RejectedClearSky>0,"cloud-source gate rejects missing clouds");S.SpawnFromClouds=false;float Orbit[]={0,0,400000};Rain->Step(S,C,W,Orbit,.1f,0,0);Check(Rain->Telemetry().AboveWeather&&Rain->Pool().empty(),"no precipitation in space");
 Rain->Reset();S.Category=PrecipitationCategory::Snow;S.GroundCollision=true;S.Accumulation=1;S.EmitterFallSeconds=1;S.EmitterRadius=3;for(int I=0;I<500;++I)Rain->Step(S,C,W,P,.04f,I*.04f,0);Check(Rain->Field().DeepestMetres()>0,"snow retires into real depth field");Check(Rain->Pool().size()<=256,"settled snow never expands particle budget");S.Enabled=false;Rain->Step(S,C,W,P,.1f,0,0);Check(Rain->Pool().empty(),"disabled emitter clears particles");
 RainbowSettings B;float A=AtmosphericOptics::RainbowAngle(650,1),Sun[]={0,-.98480775f,.17364818f},D[]={std::sin(A),std::cos(A)*.98480775f,-std::cos(A)*.17364818f},RGB[3],Off[3];AtmosphericOptics::Rainbow(B,D,Sun,1,500,RGB);Check(RGB[0]+RGB[1]+RGB[2]>0,"shared spectral bow has radiance");AtmosphericOptics::Rainbow(B,D,Sun,0,500,Off);Check(Off[0]+Off[1]+Off[2]==0,"no rain no bow");AtmosphericOptics::Rainbow(B,D,Sun,1,0,Off);Check(Off[0]+Off[1]+Off[2]==0,"zero rain path no bow");B.Intensity=2;AtmosphericOptics::Rainbow(B,D,Sun,1,500,Off);Check(std::abs(Off[0]-2*RGB[0])<1e-6,"intensity drives real optical kernel");B.Enabled=false;AtmosphericOptics::Rainbow(B,D,Sun,1,500,Off);Check(Off[0]+Off[1]+Off[2]==0,"disabled bow transparent");
 B.Enabled=true;float BandAngle=(AtmosphericOptics::RainbowAngle(400,1)+AtmosphericOptics::RainbowAngle(700,2))*.5f;Check(AtmosphericOptics::AlexanderAttenuation(B,BandAngle)<1,"Alexander band attenuates background");B.AlexanderBand=false;Check(AtmosphericOptics::AlexanderAttenuation(B,BandAngle)==1,"band switch removes attenuation");
}
static void Bindings(CelestialSequence& Scene,EditorSheet& Sheet){
 for(auto E:{CelestialEntity::Wind,CelestialEntity::Precipitation,CelestialEntity::Rainbow}){
 Scene.BuildSheet(E,Sheet);Check(Sheet.Appearance==(E==CelestialEntity::Wind?EditorSheetAppearance::Wind:E==CelestialEntity::Precipitation?EditorSheetAppearance::Precipitation:EditorSheetAppearance::Rainbow),"dedicated native routes");auto Saved=std::make_unique<EditorSheet>(Sheet);
 for(auto& G:Sheet.Groups)for(unsigned I=0;I<G.PropertyCount;++I){auto& P=G.Properties[I];if(P.Category!=EditorPropertyCategory::Slider)continue;char N[48];std::snprintf(N,sizeof(N),"%s",P.Label);float Target=P.Minimum+(P.Maximum-P.Minimum)*.6f;P.Figure=Target;Scene.ApplySheet(E,Sheet);Scene.BuildSheet(E,Sheet);Check(std::abs(Find(Sheet,N).Figure-Target)<1e-5,"authored scalar round trip");Find(Sheet,N).Figure=std::numeric_limits<float>::quiet_NaN();Scene.ApplySheet(E,Sheet);Scene.BuildSheet(E,Sheet);Check(Find(Sheet,N).Figure==Target,"nonfinite edit rejected");Find(Sheet,N).Figure=-10000;Scene.ApplySheet(E,Sheet);Scene.BuildSheet(E,Sheet);Check(Find(Sheet,N).Figure==Find(Sheet,N).Minimum,"lower bound");Find(Sheet,N).Figure=100000;Scene.ApplySheet(E,Sheet);Scene.BuildSheet(E,Sheet);Check(Find(Sheet,N).Figure==Find(Sheet,N).Maximum,"upper bound");}
 Scene.ApplySheet(E,*Saved);}
 Scene.BuildSheet(CelestialEntity::Precipitation,Sheet);auto Old=Scene.Precip.Category;Find(Sheet,"Precipitation").Picked=99;Scene.ApplySheet(CelestialEntity::Precipitation,Sheet);Check(Scene.Precip.Category==Old,"invalid precipitation enum rejected");
 auto Rows=std::make_unique<EditorInstance[]>(32);unsigned Count=Scene.AppendRoster(Rows.get(),0,32);Check(Count==15,"all environment entities accessible in native roster");for(unsigned I=1;I<Count;++I){CelestialEntity E;Check(Scene.Owns(I,0,E),"roster mapping preserved");if(E==CelestialEntity::Precipitation){Check(Rows[I].Depth==2&&!std::strcmp(Rows[I-1].Label,CelestialEntityName(CelestialEntity::CloudLayer))&&Rows[I-1].KidCount==1,"precipitation is a child of clouds");}}
 const float Forward[]={0,1,0},Right[]={1,0,0},Up[]={0,0,1},Camera[]={0,0,2};Scene.Shown[unsigned(CelestialEntity::Precipitation)]=true;Scene.Shown[unsigned(CelestialEntity::Rainbow)]=true;Scene.Precip.Enabled=true;Scene.Precip.SpawnFromClouds=false;Scene.Rainbow.Enabled=true;Scene.Rainbow.Intensity=1.2f;Scene.Rainbow.MinimumPathMetres=600;Scene.Precip.RateMillimetresPerHour=12;
 for(unsigned K=0;K<5;++K){Scene.Precip.Category=static_cast<PrecipitationCategory>(K);auto R=Scene.PackPostRecord(Forward,Right,Up,1,2,280,1);Check(R.PostBow[3]==(K==0?1:K==1?.5f:0),"liquid-only rain visibility reaches post record");Check(R.PostBow[0]==1.2f&&R.PostBow2[1]==600&&R.PostBow2[2]==1,"rainbow values reach renderer ABI");}
 Scene.Precip.Category=PrecipitationCategory::Rain;Scene.Shown[unsigned(CelestialEntity::Precipitation)]=false;Check(Scene.PackPostRecord(Forward,Right,Up,1,2,280,1).PostBow[3]==0,"hidden precipitation cannot feed rainbow");Scene.Tick(.1f,Camera,0);Check(Scene.Weather().Pool().empty(),"hidden precipitation stops simulation");Scene.Shown[unsigned(CelestialEntity::Precipitation)]=true;Scene.Enabled=false;Scene.Tick(.1f,Camera,0);Check(Scene.Weather().Pool().empty(),"global disable stops precipitation");Scene.Enabled=true;Scene.Tick(.1f,Camera,0);Check(!Scene.Weather().Pool().empty(),"project ticks actual particle simulation");
 auto Raster=std::make_unique<VisibilityRaster>();Scene.ApplyTo(*Raster,CelestialBudget{});Check(Raster->QueryCelestial().Wind.Speed==Scene.Wind.Speed&&Raster->QueryCelestial().Wind.Bearing==Scene.Wind.Bearing,"same authored wind reaches CPU volumetric renderer");
}
int main(){
 Models();auto Scene=std::make_unique<CelestialSequence>();auto Sheet=std::make_unique<EditorSheet>();Scene->Enabled=true;Scene->Clock.Animate=false;Bindings(*Scene,*Sheet);const float Camera[]={0,0,2};CelestialEntity Entity=CelestialEntity::Wind;Scene->BuildSheet(Entity,*Sheet);
 ImGui::CreateContext();auto& IO=ImGui::GetIO();IO.IniFilename=nullptr;IO.DeltaTime=1.f/60;IO.BackendFlags|=ImGuiBackendFlags_RendererHasTextures|ImGuiBackendFlags_RendererHasVtxOffset;ImGui::StyleColorsDark();auto& Style=ImGui::GetStyle();Style.WindowPadding={0,0};Style.WindowRounding=0;Style.WindowBorderSize=0;Style.Colors[ImGuiCol_WindowBg]={.105f,.105f,.105f,1};Style.Colors[ImGuiCol_TitleBgActive]={.075f,.075f,.075f,1};auto Controls=std::make_unique<ControlPanel>();auto Inspector=std::make_unique<InspectorPanel>();Inspector->AssignControls(Controls.get());auto Row=std::make_unique<EditorInstance>();Row->Category=EditorInstanceCategory::Geometry;int Width=1024,Height=1240;float Scale=1;
 auto Tick=[&](){IO.DisplaySize={float(Width),float(Height)};IO.DisplayFramebufferScale={Scale,Scale};ImGui::NewFrame();ImGui::SetNextWindowPos({0,0});ImGui::SetNextWindowSize(IO.DisplaySize);Inspector->Record(Row.get(),0,Sheet.get());Scene->ApplySheet(Entity,*Sheet);Scene->Tick(1.f/60,Camera,0);Scene->BuildSheet(Entity,*Sheet);ImGui::Render();FrontierProof::AcknowledgeTextures();};auto Rest=[&](){for(int I=0;I<3;++I)Tick();};auto Click=[&](ImVec2 P){IO.AddMousePosEvent(P.x,P.y);Tick();IO.AddMouseButtonEvent(0,true);Tick();IO.AddMouseButtonEvent(0,false);Tick();IO.AddMousePosEvent(-100,-100);Rest();};auto Capture=[&](const char* N){int PW=int(Width*Scale),PH=int(Height*Scale);std::vector<unsigned char> Pixels(size_t(PW)*PH*3,24);for(auto* D:ImGui::GetDrawData()->CmdLists)FrontierProof::Draw(D,Pixels.data(),PW,PH,{0,0},{Scale,Scale});std::string Path=std::string("Exhibits/Gallery/WeatherNative/")+N+".png";Check(stbi_write_png(Path.c_str(),PW,PH,3,Pixels.data(),PW*3)!=0,"native capture");};
 Rest();Capture("Weather-Wind");auto* Props=Window("##weather-properties");ImVec2 O=Props->DC.CursorStartPos;O.x+=20;O.y+=20;float CW=(Props->WorkRect.GetWidth()-40-16)/2;Click({O.x+CW*.5f+100,O.y+342});Check(std::abs(Scene->Wind.Bearing-90)<.1f&&Scene->Wind.Speed>25,"compass pointer changes direction AND magnitude");IO.AddKeyEvent(ImGuiKey_UpArrow,true);Tick();IO.AddKeyEvent(ImGuiKey_UpArrow,false);Tick();Check(Scene->Wind.Speed>28,"compass keyboard changes magnitude");Capture("Weather-Wind-East");auto* Slider=Window("/Shear_");Click({Slider->Pos.x+Slider->Size.x*.7f,Slider->Pos.y+15});Check(Scene->Wind.Shear>.7f,"native wind slider input");
 Height=1510;Entity=CelestialEntity::Precipitation;Scene->BuildSheet(Entity,*Sheet);Rest();Capture("Weather-Rain");float TypeY=110+151+16;float TW=(Props->WorkRect.GetWidth()-40-64)/3;Click({O.x+24+(TW+8)+TW*.5f,O.y+TypeY+100});Check(Scene->Precip.Category==PrecipitationCategory::Snow,"native snow selection");Capture("Weather-Snow");Click({O.x+24+2*(TW+8)+TW*.5f,O.y+TypeY+100});Check(Scene->Precip.Category==PrecipitationCategory::Hail,"native hail selection");Capture("Weather-Hail");Slider=Window("/Particle Size_");Click({Slider->Pos.x+Slider->Size.x*.8f,Slider->Pos.y+15});Check(Scene->Precip.SizeScale>1.5,"native particle size input");Click({O.x+65,O.y+190});Check(!Scene->Precip.Enabled&&Scene->Weather().Pool().empty(),"native enabled tile stops emitter");Capture("Weather-Precipitation-Off");
 Height=1850;Entity=CelestialEntity::Rainbow;Scene->BuildSheet(Entity,*Sheet);Rest();Capture("Weather-Rainbow");uint64_t Hash=BowHash();Rest();Check(BowHash()==Hash,"unchanged optical inputs reuse identical preview pixels");bool BowEnabled=Scene->Rainbow.Enabled;Click({O.x+70,O.y+190});Check(Scene->Rainbow.Enabled==BowEnabled,"disabled bake tile does not edit or claim baked output");Slider=Window("/Secondary_");Click({Slider->Pos.x+Slider->Size.x*.3f,Slider->Pos.y+15});Check(Scene->Rainbow.SecondaryGain<.3,"native secondary bow slider");Capture("Weather-Rainbow-Primary");Check(BowHash()!=Hash,"secondary slider invalidates actual optical texture");
 for(auto E:{CelestialEntity::Wind,CelestialEntity::Precipitation,CelestialEntity::Rainbow}){Entity=E;Scene->BuildSheet(Entity,*Sheet);Width=480;Height=2300;Rest();Capture(E==CelestialEntity::Wind?"Weather-Wind-Narrow":E==CelestialEntity::Precipitation?"Weather-Precipitation-Narrow":"Weather-Rainbow-Narrow");Width=320;Height=750;Rest();Check(Window("##weather-properties")->ScrollMax.y>500,"compact weather panel scrolls");}
 ImGui::SetScrollY(Window("##weather-properties"),650);Rest();Capture("Weather-Scrolled");Width=1024;Height=800;Scale=2;ImGui::SetScrollY(Window("##weather-properties"),0);Rest();Capture("Weather-2x");Scene->BuildSheet(CelestialEntity::Count,*Sheet);Check(Sheet->Appearance==EditorSheetAppearance::Generic&&Sheet->WeatherPreview.Alive==0,"sheet metadata resets on reuse");ImGui::DestroyContext();std::printf("PASS %u checks: native Wind, Precipitation and Rainbow; actual wind and particle simulation, spectral optics, renderer ABI, hierarchy, finite inputs, pointer/keyboard, narrow/2x and teardown. No GPU execution or bake claim.\n",Checks);
}
