// Slate SatMap Satellite Color Map Library
// Inspired by QuadSpinner Gaea's iconic SatMap CLUT collection
// Sampled from real-world satellite imagery across global geological formations

import type { SatMapPreset } from '../../types/terrain';

export const SATMAP_PRESETS: SatMapPreset[] = [
  // --- ROCKY CATEGORY ---
  {
    id: 'rocky_grand_canyon',
    name: 'Grand Canyon Redwall',
    category: 'rocky',
    description: 'Layered Permian sandstone, redwall limestone, and iron-oxidized shale.',
    stops: [
      { position: 0.0, color: '#3b2f2f' },
      { position: 0.15, color: '#593e30' },
      { position: 0.35, color: '#8c4830' },
      { position: 0.55, color: '#bd6a42' },
      { position: 0.75, color: '#d98b59' },
      { position: 0.9, color: '#e8aa78' },
      { position: 1.0, color: '#f3c99f' },
    ],
    rockTint: '#ffd1a4',
    siltTint: '#8a5a3c',
    wetnessTint: '#2b1b16',
  },
  {
    id: 'rocky_alpine_granite',
    name: 'Alpine Granite Horn',
    category: 'rocky',
    description: 'Chiseled gray granite, glacial moraines, and high altitude lichen.',
    stops: [
      { position: 0.0, color: '#2d3732' },
      { position: 0.2, color: '#434b45' },
      { position: 0.4, color: '#5d6460' },
      { position: 0.6, color: '#7a817d' },
      { position: 0.8, color: '#9fa6a2' },
      { position: 0.95, color: '#c7cdc9' },
      { position: 1.0, color: '#edf2ee' },
    ],
    rockTint: '#ffffff',
    siltTint: '#505652',
    wetnessTint: '#1c221f',
  },
  {
    id: 'rocky_dolomite_crags',
    name: 'Dolomite Limestone',
    category: 'rocky',
    description: 'Pale jagged carbonate cliffs with warm ochre scree aprons.',
    stops: [
      { position: 0.0, color: '#383b37' },
      { position: 0.25, color: '#5e5a52' },
      { position: 0.5, color: '#8f887b' },
      { position: 0.7, color: '#b8b09f' },
      { position: 0.88, color: '#ded7c8' },
      { position: 1.0, color: '#fbf8f0' },
    ],
    rockTint: '#fffdf5',
    siltTint: '#968875',
    wetnessTint: '#292823',
  },
  {
    id: 'rocky_scottish_highlands',
    name: 'Glencoe Highlands',
    category: 'rocky',
    description: 'Dark peat valleys, weathered schist cliffs, and autumnal bracken.',
    stops: [
      { position: 0.0, color: '#252119' },
      { position: 0.2, color: '#3d3827' },
      { position: 0.45, color: '#574c32' },
      { position: 0.68, color: '#736141' },
      { position: 0.85, color: '#8a7754' },
      { position: 1.0, color: '#a69572' },
    ],
    rockTint: '#c2b393',
    siltTint: '#4a402a',
    wetnessTint: '#17140f',
  },

  // --- DESERT CATEGORY ---
  {
    id: 'desert_sahara_erg',
    name: 'Sahara Golden Erg',
    category: 'desert',
    description: 'Wind-blown quartz dunes with deep terracotta shadow troughs.',
    stops: [
      { position: 0.0, color: '#5e381b' },
      { position: 0.2, color: '#8c5324' },
      { position: 0.45, color: '#be7839' },
      { position: 0.7, color: '#e09a53' },
      { position: 0.88, color: '#f5be76' },
      { position: 1.0, color: '#ffdea8' },
    ],
    rockTint: '#ffe9c4',
    siltTint: '#ad6730',
    wetnessTint: '#40230e',
  },
  {
    id: 'desert_namib_apricot',
    name: 'Namib Sossusvlei',
    category: 'desert',
    description: 'High oxidized iron red-orange sands contrasting with bleached clay pans.',
    stops: [
      { position: 0.0, color: '#4a1e12' },
      { position: 0.25, color: '#85351c' },
      { position: 0.5, color: '#ba4e27' },
      { position: 0.75, color: '#e47137' },
      { position: 0.9, color: '#f79954' },
      { position: 1.0, color: '#f5e4cc' },
    ],
    rockTint: '#ffb37a',
    siltTint: '#e6dac8',
    wetnessTint: '#38140a',
  },
  {
    id: 'desert_atacama_salt',
    name: 'Atacama Salar Basin',
    category: 'desert',
    description: 'Hyper-arid mineral crusts, lithium brines, and pale sulfur soils.',
    stops: [
      { position: 0.0, color: '#473c33' },
      { position: 0.25, color: '#736353' },
      { position: 0.5, color: '#a3907c' },
      { position: 0.72, color: '#cfbea8' },
      { position: 0.9, color: '#ebe0d1' },
      { position: 1.0, color: '#fdfbfa' },
    ],
    rockTint: '#ffffff',
    siltTint: '#b5a18b',
    wetnessTint: '#332921',
  },

  // --- LUSH / GREEN CATEGORY ---
  {
    id: 'lush_cascades_pine',
    name: 'Cascades Mountain Forest',
    category: 'lush',
    description: 'Temperate coniferous valley floor rising to alpine meadows and snow.',
    stops: [
      { position: 0.0, color: '#162b1b' },
      { position: 0.2, color: '#27472d' },
      { position: 0.4, color: '#44663c' },
      { position: 0.6, color: '#668249' },
      { position: 0.78, color: '#7d7a60' },
      { position: 0.9, color: '#a8a89c' },
      { position: 1.0, color: '#eef2ee' },
    ],
    rockTint: '#dbe0d7',
    siltTint: '#59694b',
    wetnessTint: '#0d1a10',
  },
  {
    id: 'lush_swiss_meadow',
    name: 'Swiss Pre-Alps Meadow',
    category: 'lush',
    description: 'Emerald pasture slopes, limestone crags, and wildflower plateaus.',
    stops: [
      { position: 0.0, color: '#23381a' },
      { position: 0.25, color: '#3d6123' },
      { position: 0.5, color: '#5f8a32' },
      { position: 0.7, color: '#8cb349' },
      { position: 0.85, color: '#999982' },
      { position: 1.0, color: '#deded7' },
    ],
    rockTint: '#ecece6',
    siltTint: '#526639',
    wetnessTint: '#15240e',
  },
  {
    id: 'lush_new_zealand_fiord',
    name: 'Milford Sound Fiord',
    category: 'lush',
    description: 'Deep rainforest gullies, mossy sheer diorite walls, and cascading waterfalls.',
    stops: [
      { position: 0.0, color: '#11211b' },
      { position: 0.2, color: '#1c3629' },
      { position: 0.45, color: '#2f573c' },
      { position: 0.7, color: '#4a6b4a' },
      { position: 0.88, color: '#6b6e5b' },
      { position: 1.0, color: '#9ea399' },
    ],
    rockTint: '#bcc4b7',
    siltTint: '#394a3a',
    wetnessTint: '#081410',
  },

  // --- ARCTIC / GLACIAL CATEGORY ---
  {
    id: 'arctic_patagonia_glacier',
    name: 'Patagonian Ice Sheet',
    category: 'arctic',
    description: 'Deep glacial cerulean crevasses, moraine gravels, and perennial blue ice.',
    stops: [
      { position: 0.0, color: '#222d38' },
      { position: 0.2, color: '#3a4b59' },
      { position: 0.45, color: '#5b758a' },
      { position: 0.7, color: '#88adc7' },
      { position: 0.88, color: '#bce0f5' },
      { position: 1.0, color: '#e8f6ff' },
    ],
    rockTint: '#ffffff',
    siltTint: '#4e5e6b',
    wetnessTint: '#14202b',
  },
  {
    id: 'arctic_iceland_ice',
    name: 'Icelandic Black Sand & Ice',
    category: 'arctic',
    description: 'Volcanic basalt sand covered in glacial tongue deposits and frosted rims.',
    stops: [
      { position: 0.0, color: '#121417' },
      { position: 0.25, color: '#262a30' },
      { position: 0.5, color: '#414752' },
      { position: 0.7, color: '#687482' },
      { position: 0.88, color: '#a6b8c9' },
      { position: 1.0, color: '#edf5fa' },
    ],
    rockTint: '#ffffff',
    siltTint: '#313840',
    wetnessTint: '#0b0c0d',
  },

  // --- VOLCANIC / DARK CATEGORY ---
  {
    id: 'volcanic_iceland_moss',
    name: 'Iceland Eldhraun Moss',
    category: 'volcanic',
    description: 'Ancient basalt aa-lava covered in spongy chartreuse woolly moss.',
    stops: [
      { position: 0.0, color: '#141416' },
      { position: 0.25, color: '#2b2a26' },
      { position: 0.5, color: '#4a4c33' },
      { position: 0.7, color: '#6f7842' },
      { position: 0.85, color: '#97a353' },
      { position: 1.0, color: '#b8c769' },
    ],
    rockTint: '#c9d977',
    siltTint: '#36382b',
    wetnessTint: '#0d0d0f',
  },
  {
    id: 'volcanic_tephra_fuji',
    name: 'Mount Fuji Basalt Tephra',
    category: 'volcanic',
    description: 'Dark scoria ash, obsidian glass scree, and summit frost.',
    stops: [
      { position: 0.0, color: '#181719' },
      { position: 0.3, color: '#302d30' },
      { position: 0.55, color: '#524c52' },
      { position: 0.75, color: '#787075' },
      { position: 0.9, color: '#aba4ab' },
      { position: 1.0, color: '#e8e5e8' },
    ],
    rockTint: '#ffffff',
    siltTint: '#3d393d',
    wetnessTint: '#0f0e0f',
  },

  // --- COLORFUL / BADLANDS CATEGORY ---
  {
    id: 'badlands_danxia_rainbow',
    name: 'Danxia Rainbow Strata',
    category: 'badlands',
    description: 'Spectacular multi-hued mineral bands: carmine, ochre, malachite, and gold.',
    stops: [
      { position: 0.0, color: '#592525' },
      { position: 0.18, color: '#8f3c2c' },
      { position: 0.38, color: '#ba6e38' },
      { position: 0.58, color: '#c79c4a' },
      { position: 0.75, color: '#7a8c54' },
      { position: 0.9, color: '#94667d' },
      { position: 1.0, color: '#debcd0' },
    ],
    rockTint: '#ffe4c2',
    siltTint: '#a3634c',
    wetnessTint: '#331515',
  },
  {
    id: 'badlands_painted_desert',
    name: 'Painted Desert Chinle',
    category: 'badlands',
    description: 'Bentonite clay hills with purple siltstone, lavender ash, and gold sandstone.',
    stops: [
      { position: 0.0, color: '#382a3b' },
      { position: 0.22, color: '#593a52' },
      { position: 0.42, color: '#875163' },
      { position: 0.65, color: '#b87b6a' },
      { position: 0.82, color: '#d9a97e' },
      { position: 1.0, color: '#f5d9b5' },
    ],
    rockTint: '#ffe9cf',
    siltTint: '#80596b',
    wetnessTint: '#211824',
  },
];

export function getSatMapPresetById(id: string): SatMapPreset {
  const found = SATMAP_PRESETS.find((p) => p.id === id);
  return found ?? SATMAP_PRESETS[0];
}
