#!/usr/bin/env python3
"""Package actual native captures. No generated scenery or browser-rendered inspector stand-ins."""
from pathlib import Path
import json,re,struct,zlib
R=Path(__file__).resolve().parents[3];O=R/'Exhibits/Gallery/NativeBillboards'
for name in ['Proof','Sanitized']:
 report=json.loads((O/(name+'.json')).read_text());assert report['exit']==0
 assert re.search(r'PASS 154 checks',report['output']), 'Update displayed check counts to match new evidence'
# Lossless IDAT recompression; preserves every decoded pixel, needs no image library.
for p in O.glob('*.png'):
 raw=p.read_bytes();assert raw[:8]==b'\x89PNG\r\n\x1a\n';parts=[];data=[];at=8
 while at<len(raw):
  n=struct.unpack('>I',raw[at:at+4])[0];kind=raw[at+4:at+8];value=raw[at+8:at+8+n];at+=n+12
  if kind==b'IDAT':data.append(value)
  else:parts.append((kind,value))
 pixels=zlib.decompress(b''.join(data));compressed=zlib.compress(pixels,9);assert zlib.decompress(compressed)==pixels
 def chunk(k,v):return struct.pack('>I',len(v))+k+v+struct.pack('>I',zlib.crc32(k+v)&0xffffffff)
 output=raw[:8]
 for k,v in parts:
  if k==b'IEND':output+=chunk(b'IDAT',compressed)
  output+=chunk(k,v)
 p.write_bytes(output)
metrics=[line.split('\t') for line in (O/'Deltas.tsv').read_text().splitlines() if line]
rows=''.join(f'<tr><td>{n}</td><td>{float(v):.3f}</td><td class="pass">PASS</td></tr>' for n,v in metrics)
html='''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Frontier · Native viewport verification</title>
<style>
*{box-sizing:border-box}body{margin:0;background:#101416;color:#e7eeec;font:15px/1.6 system-ui,sans-serif}main{max-width:1280px;margin:auto;padding:38px 28px 64px}header{display:flex;justify-content:space-between;border-bottom:1px solid #303839;padding-bottom:20px}.brand{font-weight:750;letter-spacing:3px}.tag{color:#9cdbb9;font-size:12px;letter-spacing:1px}h1{font-size:clamp(28px,4vw,46px);letter-spacing:-1.8px;line-height:1.12;margin:32px 0 15px}h2{font-size:24px;letter-spacing:-.5px;margin:0 0 12px}h3{font-size:16px}.intro{max-width:780px;color:#abb7b4}.badges{display:flex;flex-wrap:wrap;gap:10px;margin:24px 0}.badge{padding:8px 13px;border:1px solid #3c5248;border-radius:20px;background:#19251f;color:#b5e1c8;font-size:12px}.section{margin:36px 0 0}.bar{display:flex;justify-content:space-between;align-items:center;gap:15px;flex-wrap:wrap;margin:18px 0}button,select{font:inherit;color:#d1dbd7;background:#20282b;border:1px solid #394347;border-radius:7px;padding:9px 13px;cursor:pointer}button.on{background:#27463a;border-color:#73bb97;color:white}button:focus-visible,select:focus-visible{outline:2px solid #a6dfbe;outline-offset:3px}.tabs{display:flex;gap:8px;flex-wrap:wrap}.frame{border:1px solid #354045;border-radius:12px;overflow:hidden;background:#171c1f}.frame img{width:100%;display:block}.caption{color:#9baea6;font-size:13px;margin-top:10px}.grid{display:grid;grid-template-columns:1fr 1fr;gap:22px}.compare{position:relative;aspect-ratio:1.3;overflow:hidden;background:#263239;border-radius:12px;border:1px solid #465250}.compare img{position:absolute;inset:0;width:100%;height:100%}.compare #before{clip-path:inset(0 50% 0 0)}.divider{position:absolute;left:50%;top:0;bottom:0;border-left:2px solid #d2f5df;pointer-events:none}.label{position:absolute;top:14px;padding:5px 10px;border-radius:5px;background:#101917d9;font-size:12px}.label.a{left:14px}.label.b{right:14px}input[type=range]{width:100%;accent-color:#92d4af;margin:15px 0}article{padding:25px;background:#192023;border:1px solid #303e40;border-radius:12px}p{margin:10px 0}code{color:#c7e0d2}table{width:100%;border-collapse:collapse;font-size:13px}td,th{text-align:left;padding:10px;border-bottom:1px solid #303d3e}th{color:#97aaa1;font-weight:500}.pass{color:#a1d6b6}ul{padding-left:20px;color:#b6c3bc}a{color:#a8dbc0}footer{border-top:1px solid #303839;padding-top:22px;margin-top:38px;color:#8a9d93;font-size:12px}@media(max-width:760px){main{padding:22px 15px}.grid{grid-template-columns:1fr}.tag{max-width:160px;text-align:right}}
</style><main><header><div class="brand">FRONTIER</div><div class="tag">NATIVE C++ · CPU RENDER PROOF</div></header>
<h1>Select the proxy.<br>Edit the actual environment.</h1><p class="intro">Billboards share the same entity identity as the outliner and inspector. These are captures of the native ImGui editor with a real <code>VisibilityRaster</code> scene—not a browser recreation or an inspector preview painted onto a background.</p>
<div class="badges"><span class="badge">154 release checks passed</span><span class="badge">154 ASan / UBSan checks passed</span><span class="badge">Fresh reconstruction passed</span><span class="badge">GameExecution syntax passed</span></div>
<section class="section"><h2>01 / Selection → outliner → inspector</h2><div class="bar"><div class="tabs" id="tabs"></div><span class="caption">Recorded native captures · not a live engine session</span></div><div class="frame"><a id="captureLink" href="Editor-Wind.png" target="_blank"><img id="editor" src="Editor-Wind.png" alt="Native Wind billboard selected, Wind row highlighted, actual Wind inspector open"></a></div><p class="caption" id="editorCaption"></p></section>
<section class="section"><h2>02 / Inspector changes → rendered pixels</h2><div class="bar"><select id="test" aria-label="Rendered comparison"></select><span class="caption">Drag the divider to compare the actual renders</span></div><div class="grid"><div><div class="compare"><img id="after" alt="After inspector edit"><img id="before" alt="Before inspector edit"><div class="divider" id="divider"></div><span class="label a" id="labelA"></span><span class="label b" id="labelB"></span></div><input type="range" min="0" max="100" value="50" id="split" aria-label="Before and after divider"></div><article><h3 id="testTitle"></h3><p id="testDescription"></p><p class="caption">Same camera, geometry, renderer and quality settings. Each pair changes the named property through the native inspector exchange. The mouse-driven Fog pair also exercises the actual ImGui slider.</p><p class="caption">Wind is shown through cloud advection, not a visible “wind object”. The zero-speed control produced identical pixels at both times.</p><p><a id="openA" target="_blank">Open before PNG</a> · <a id="openB" target="_blank">Open after PNG</a></p></article></div></section>
<section class="section grid"><article><h2>Measured differences</h2><p class="caption">Mean absolute RGB difference, 0–255. Local effects occupy fewer pixels, so their whole-frame mean is smaller.</p><table><thead><tr><th>Test</th><th>Δ RGB</th><th>Result</th></tr></thead><tbody>ROWS</tbody></table></article><article><h2>What is established</h2><ul><li>Billboard clicks select the actual entity and its real inspector; the same click is not sent to the mesh picker.</li><li>Stable identity survives row reorder and rename. Hidden ancestors suppress markers. The Markers toggle works.</li><li>Local cloud and fog markers use their actual centres. Nearest overlapping marker wins; behind-camera, near-plane and offscreen points are rejected.</li><li>Global systems have no physical centre: their labelled editor proxies occupy the camera-facing shelf.</li><li>Modal input is respected, and a billboard selection cancels an older pending GPU mesh-selection answer.</li><li>Weather time is independent of the day cycle. Static Sun no longer freezes CPU cloud advection.</li></ul></article></section>
<section class="section"><article><h2>Explicit limits</h2><p><strong>This is native CPU verification, not a Windows/Vulkan execution claim.</strong> The Vulkan application uses a separate cloud-shadow staging/upload path. These A/B renders do not establish that all volumetric cloud, fog and wind controls affect that GPU path.</p><p class="caption">This fixture renders atmosphere, global/local clouds, height/aerial fog and local volumetric fog over real mesh geometry. It does not verify precipitation particles, a rainbow, lens compositing, moon textures or star-catalogue rendering. Marker icons for those entities are editor proxies, not evidence of those effects rendering. Low-resolution CPU renders retain the renderer’s sampling/shadow artifacts; they have not been painted or AI-enhanced. Local markers are editor overlays and are not depth-occluded by meshes.</p></article></section>
<footer><a href="Proof.json">Release output & source hashes</a> · <a href="Sanitized.json">Sanitizer output</a> · <a href="GameSyntax.json">Application syntax check</a> · <a href="Deltas.tsv">Pixel measurements</a><br>Reproduce: <code>python3 Exhibits/Workbench/Billboards/RunProof.py</code> then <code>python3 Exhibits/Workbench/Billboards/PackEvidence.py</code>.</footer>
<script>
const shots=[['Wind','Editor-Wind','The Wind proxy is selected in the viewport; its stable identity selects the Wind row and opens the real direction/speed inspector.'],['Wind edited','Editor-Wind-edited','A real mouse click on the native Speed slider commits back to CelestialSequence and the renderer settings.'],['Fog','Editor-Fog','Height Fog selected through its proxy. The visibility graph is an inspector diagnostic; the viewport is a separate scene render.'],['Fog edited','Editor-Fog-edited','After a mouse edit of the native Density slider: the inspector, outliner visibility distance and scene all change.'],['Atmosphere','Editor-Atmosphere','The Atmosphere inspector operates on the medium used by the real sky integral.'],['Local cloud','Editor-Local-cloud','This local-volume proxy projects the actual world-space centre, rather than using the global-system shelf.']];
const tabs=document.querySelector('#tabs');shots.forEach(([name,file,caption],i)=>{const b=document.createElement('button');b.textContent=name;b.onclick=()=>{document.querySelectorAll('#tabs button').forEach(x=>x.classList.remove('on'));b.classList.add('on');editor.src=file+'.png';captureLink.href=editor.src;editor.alt=caption;editorCaption.textContent=caption;};tabs.append(b);if(!i)b.click();});
const cases=[['Cloud coverage','Clouds-before','Clouds-after','Coverage 0.34','Coverage 0.65','The same cloud-layer settings authored by the Clouds inspector feed the volumetric march.'],['Atmosphere scattering','Scene','Atmosphere-after','Baseline air','Mie strength 4','The Mie coefficient is changed through the inspector exchange, then the native atmosphere integral is rendered again.'],['Height fog','Fog-before','Fog-after','Density 0.001 /m','Density 0.012 /m','Fog is integrated over real near and distant geometry, not just drawn in the inspector card.'],['Fog · actual mouse input','Fog-mouse-before','Fog-mouse-after','Before slider click','After slider click','The proof clicked the real native Density slider. This pair verifies the complete mouse → inspector → model → scene path.'],['Wind · Static Sun','Wind-t0','Wind-t45','Simulation 0 seconds','Simulation 45 seconds','Wind speed is 18 m/s. The Sun remains Static at the same local hour; elapsed simulation time moves the cloud field.'],['Local cloud','Local-cloud-before','Local-cloud-after','Density 2.5','Density 0','Disabling the local cloud density removes its contribution while preserving the global cloud layer.'],['Local fog','Local-fog-before','Local-fog-after','Density 0.35','Density 3','A localized density edit affects rays crossing the fog volume. Its small whole-frame delta is reported, not exaggerated.']];
const select=document.querySelector('#test');cases.forEach((c,i)=>select.add(new Option(c[0],i)));function show(){const [title,a,b,la,lb,desc]=cases[+select.value];before.src=a+'.png';after.src=b+'.png';labelA.textContent=la;labelB.textContent=lb;testTitle.textContent=title;testDescription.textContent=desc;openA.href=before.src;openB.href=after.src;}select.onchange=show;show();split.oninput=()=>{before.style.clipPath='inset(0 '+(100-split.value)+'% 0 0)';divider.style.left=split.value+'%';};
</script></main></html>'''
(O/'index.html').write_text(html.replace('ROWS',rows))
print(f'Packed {len(list(O.glob("*.png")))} native captures and {len(metrics)} comparisons: {O}/index.html')
