#include "InspectorPanel.h"
#include "ControlPanel.h"
#include "CpuDraw.h"
#include "PngWriteCounterpart.h"
#include <imgui_internal.h>
#include <filesystem>
#include <vector>
#include <cstdio>
#include <cstring>
using namespace Frontier;
static void Row(EditorInstance& R,uint64_t Key,const char* Name,uint32_t Depth,EditorInstanceCategory Category,bool Visible=true){R.InspectorKey=Key;std::snprintf(R.Label,sizeof(R.Label),"%s",Name);R.Depth=Depth;R.Category=Category;R.Visible=Visible;R.Tint[0]=.63f;R.Tint[1]=.70f;R.Tint[2]=.73f;}
int main(){std::filesystem::create_directories("Exhibits/Gallery/FolderNative");ImGui::CreateContext();auto& IO=ImGui::GetIO();IO.IniFilename=nullptr;IO.DeltaTime=1.f/60;IO.BackendFlags|=ImGuiBackendFlags_RendererHasTextures|ImGuiBackendFlags_RendererHasVtxOffset;ImFontConfig FontConfig;std::snprintf(FontConfig.Name,sizeof(FontConfig.Name),"Sun reference / regular");auto* Ui=IO.Fonts->AddFontFromFileTTF("EngineContent/Fonts/SunReference/DMSans-Regular.ttf",14,&FontConfig);ImGui::StyleColorsDark();auto& Style=ImGui::GetStyle();Style.WindowPadding={14,14};Style.WindowRounding=0;Style.WindowBorderSize=0;ControlPanel Controls;Controls.AssignFonts(Ui,Ui,Ui,Ui,Ui,Ui);InspectorPanel Inspector;std::vector<EditorInstance> Rows(18);Row(Rows[0],1,"World",0,EditorInstanceCategory::Folder);Row(Rows[1],2,"Atmosphere",1,EditorInstanceCategory::Geometry);Row(Rows[2],3,"Sun",1,EditorInstanceCategory::Light);Row(Rows[3],4,"Sky",1,EditorInstanceCategory::Geometry);Row(Rows[4],5,"Moons",1,EditorInstanceCategory::Folder);Row(Rows[5],6,"Moon A",2,EditorInstanceCategory::Geometry);Row(Rows[6],7,"Stars",1,EditorInstanceCategory::Geometry);Row(Rows[7],8,"Wind",1,EditorInstanceCategory::Geometry);Row(Rows[8],9,"Height Fog",1,EditorInstanceCategory::Geometry);Row(Rows[9],10,"Atmospheric Fog",1,EditorInstanceCategory::Geometry);Row(Rows[10],11,"Local Fog",1,EditorInstanceCategory::Geometry);Row(Rows[11],12,"Clouds",1,EditorInstanceCategory::Folder);Row(Rows[12],13,"Local Cloud",2,EditorInstanceCategory::Geometry);Row(Rows[13],14,"Precipitation",2,EditorInstanceCategory::Geometry);Row(Rows[14],15,"Lighting",1,EditorInstanceCategory::Folder);Row(Rows[15],16,"Key Spot",2,EditorInstanceCategory::Light);Row(Rows[16],17,"Fill Point",2,EditorInstanceCategory::Light,false);Row(Rows[17],18,"Editor Camera",1,EditorInstanceCategory::Camera);
 int W=339,H=732;float ScrollY=0;auto Tick=[&](){IO.DisplaySize={float(W),float(H)};ImGui::NewFrame();ImGui::SetNextWindowPos({0,0});ImGui::SetNextWindowSize(IO.DisplaySize);ImGui::Begin("Inspector",nullptr,ImGuiWindowFlags_NoTitleBar|ImGuiWindowFlags_NoScrollbar);ImGui::BeginChild("##collection-content",{0,0},ImGuiChildFlags_None,ImGuiWindowFlags_NoScrollbar);ImGui::SetScrollY(ScrollY);Inspector.RecordCollectionProof(Controls,Rows.data(),uint32_t(Rows.size()),0);ImGui::EndChild();ImGui::End();ImGui::Render();FrontierProof::AcknowledgeTextures();};auto Capture=[&](const char* Name){for(int I=0;I<3;++I)Tick();std::vector<unsigned char>P(size_t(W)*H*3,24);for(auto* L:ImGui::GetDrawData()->CmdLists)FrontierProof::Draw(L,P.data(),W,H,{0,0},{1,1});std::string Path="Exhibits/Gallery/FolderNative/"+std::string(Name)+".png";if(!stbi_write_png(Path.c_str(),W,H,3,P.data(),W*3))return false;return true;};if(!Capture("Folder-Collection-Viewport"))return 2;W=328;H=2200;if(!Capture("Folder-Collection"))return 3;W=300;H=2400;if(!Capture("Folder-Collection-Narrow"))return 4;std::vector<EditorInstance> Large(2509);Row(Large[0],10000,"Asset archive",0,EditorInstanceCategory::Folder);size_t Cursor=1,AssetNumber=1;for(unsigned Folder=0;Folder<8;++Folder){char Name[32];std::snprintf(Name,sizeof(Name),"Batch %u",Folder+1);Row(Large[Cursor],11000+Cursor,Name,1,EditorInstanceCategory::Folder);++Cursor;const unsigned Count=Folder<4?313:312;for(unsigned Item=0;Item<Count;++Item){char Asset[32];std::snprintf(Asset,sizeof(Asset),"Asset %05zu",AssetNumber++);Row(Large[Cursor],11000+Cursor,Asset,2,EditorInstanceCategory::Geometry,Cursor!=2508);++Cursor;}}Rows=std::move(Large);W=339;H=732;ScrollY=0;if(!Capture("Folder-Large-Viewport"))return 5;ScrollY=892;if(!Capture("Folder-Browser-Viewport"))return 6;ImGui::DestroyContext();std::puts("PASS native folder collection: source-aligned hierarchy, totals, visibility, composition, search/filter/sort, manifest and notes layout.");}
