#include "EditorFeedSequence.h"
#include "InspectorPanel.h"
#include "ControlPanel.h"
#include "InspectorReferenceDraw.h"
#include "CpuDraw.h"
#include "PngWriteCounterpart.h"
#include <imgui_internal.h>
#include <memory>
#include <cstring>
#include <cstdio>
#include <stdexcept>
#include <limits>
using namespace Frontier;using namespace Frontier::ProjectZero;
static unsigned Checks=0;static void Check(bool V,const char* N){++Checks;if(!V)throw std::runtime_error(N);}
static EditorProperty& Find(EditorSheet& S,const char* N){for(auto& G:S.Groups)for(unsigned I=0;I<G.PropertyCount;++I)if(!std::strcmp(G.Properties[I].Label,N))return G.Properties[I];throw std::runtime_error(N);}
static ImGuiWindow* Window(const char* N){for(auto* W:ImGui::GetCurrentContext()->Windows)if(W->Active&&std::strstr(W->Name,N))return W;throw std::runtime_error(N);}
int main(){
 Check(std::abs(InspectorReference::IrisRadius(1.4f)-57)<1e-4,"HTML iris fully open radius");Check(InspectorReference::IrisRadius(16)==10,"HTML iris stopped radius");Check(InspectorReference::IrisRadius(22)==10,"extended backend f-stop stays within reference iris geometry");
 for(float D:{1.f,3.f,10.f,30.f,100.f})Check(InspectorReference::FocusFromX(InspectorReference::FocusX(D))==D,"HTML logarithmic distance mapping and round trip");

 auto Feed=std::make_unique<EditorFeedSequence>();auto Level=std::make_unique<SceneStructure>();auto Camera=std::make_unique<FlyThroughSolver>();auto Sheet=std::make_unique<EditorSheet>();auto Rows=std::make_unique<EditorInstance[]>(kMaxEditorInstances);unsigned Count=Feed->FillRoster(Rows.get(),*Level),Main=0,Cine=0;for(unsigned I=0;I<Count;++I){if(!std::strcmp(Rows[I].Label,"Main Camera"))Main=I;if(!std::strcmp(Rows[I].Label,"Cine Camera"))Cine=I;}Check(Main&&Cine&&Main!=Cine,"real camera roster rows");unsigned Pick=Main;
 auto Build=[&](){(void)Feed->BuildSheet(Pick,Rows.get(),Count,Sheet.get(),*Camera,*Level,Level->QueryInstances());};auto Apply=[&](){Feed->ApplyCameraSheet(Pick,Count,*Level,*Sheet,*Camera);Build();};Build();Check(Sheet->Appearance==EditorSheetAppearance::Camera&&Sheet->CameraLive,"live camera route");
 for(const char* N:{"Focal Length","Sensor Width","Aperture","Subject Distance"}){auto& P=Find(*Sheet,N);float V=!std::strcmp(N,"Focal Length")?70:P.Minimum+(P.Maximum-P.Minimum)*.4f;P.Figure=V;Apply();Check(std::abs(Find(*Sheet,N).Figure-V)<.001,"real field round trip");Find(*Sheet,N).Figure=std::numeric_limits<float>::quiet_NaN();Apply();Check(std::isfinite(Find(*Sheet,N).Figure)&&std::abs(Find(*Sheet,N).Figure-V)<.001,"nonfinite rejected");}
 Find(*Sheet,"Focal Length").Figure=35;Find(*Sheet,"Sensor Width").Figure=36;Find(*Sheet,"Aperture").Figure=2.8f;Find(*Sheet,"Subject Distance").Figure=4;Apply();auto Wide=Camera->ConstructRay(1,.5f);Find(*Sheet,"Focal Length").Figure=100;Apply();auto Tele=Camera->ConstructRay(1,.5f);Check(std::abs(Tele.UnitDirection.x)<std::abs(Wide.UnitDirection.x),"focal edit narrows actual generated camera rays");auto Center=Camera->ConstructRay(.5f,.5f);Check(std::abs(Center.UnitDirection.y-1)<1e-6,"centre ray retains camera pose");float FOV=Camera->QueryFieldOfViewRadians();Find(*Sheet,"Aperture").Figure=16;Apply();Find(*Sheet,"Subject Distance").Figure=30;Apply();Check(Camera->QueryFieldOfViewRadians()==FOV,"diagnostic aperture/focus do not fake changes to pinhole rendering");
 Camera->AssignAspectRatio(1.5f);Build();Check(Sheet->CameraAspect==1.5f,"viewport resize reflected");CameraOpticsSettings S;S.Focal=50;S.Subject=5;S.Aperture=2;auto A=EvaluateCameraOptics(S,1.5f);Check(std::abs(A.Horizontal-39.5978f)<.01f&&std::abs(A.Vertical-26.9915f)<.01f,"full-frame FOV reference");Check(A.Near<5&&A.Far>5&&A.Pupil==25,"thin lens reference");S.Aperture=16;auto B=EvaluateCameraOptics(S,1.5f);Check(B.Near<A.Near&&B.Far>A.Far&&B.Pupil<A.Pupil,"aperture updates pupil and sharpness together");S.Subject=100;B=EvaluateCameraOptics(S,1.5f);Check(std::isinf(B.Far),"hyperfocal far infinity safe");
 Pick=Cine;Build();Check(!Sheet->CameraLive,"cine is explicitly inactive study");Find(*Sheet,"Focal Length").Figure=120;Apply();Check(Camera->QueryFieldOfViewRadians()==FOV,"cine study cannot modify active projection");Pick=Main;Build();Check(std::abs(Find(*Sheet,"Focal Length").Figure-Feed->CineLens.Focal)>1,"independent study state");
 Find(*Sheet,"Focal Length").Figure=35;Find(*Sheet,"Aperture").Figure=2.8f;Find(*Sheet,"Subject Distance").Figure=4;Apply();
 Camera->AssignAspectRatio(16.f/9);Build();Find(*Sheet,"Focal Length").Figure=35;Apply();
 ImGui::CreateContext();auto& IO=ImGui::GetIO();IO.IniFilename=nullptr;IO.DeltaTime=1.f/60;IO.BackendFlags|=ImGuiBackendFlags_RendererHasTextures|ImGuiBackendFlags_RendererHasVtxOffset;ImGui::StyleColorsDark();auto& Style=ImGui::GetStyle();Style.WindowPadding={0,0};Style.WindowRounding=0;Style.WindowBorderSize=0;Style.Colors[ImGuiCol_WindowBg]={.105f,.105f,.105f,1};Style.Colors[ImGuiCol_TitleBgActive]={.075f,.075f,.075f,1};auto Controls=std::make_unique<ControlPanel>();auto Inspector=std::make_unique<InspectorPanel>();Inspector->AssignControls(Controls.get());int Width=1024,Height=1750;float Scale=1;
 auto Tick=[&](){IO.DisplaySize={float(Width),float(Height)};IO.DisplayFramebufferScale={Scale,Scale};ImGui::NewFrame();ImGui::SetNextWindowPos({0,0});ImGui::SetNextWindowSize(IO.DisplaySize);Inspector->Record(&Rows[Pick],Pick,Sheet.get());Apply();ImGui::Render();FrontierProof::AcknowledgeTextures();};auto Rest=[&](){for(int I=0;I<3;++I)Tick();};auto Click=[&](ImVec2 P){IO.AddMousePosEvent(P.x,P.y);Tick();IO.AddMouseButtonEvent(0,true);Tick();IO.AddMouseButtonEvent(0,false);Tick();IO.AddMousePosEvent(-100,-100);Rest();};auto Capture=[&](const char* N){int PW=int(Width*Scale),PH=int(Height*Scale);std::vector<unsigned char> Pixels(size_t(PW)*PH*3,24);for(auto* D:ImGui::GetDrawData()->CmdLists)FrontierProof::Draw(D,Pixels.data(),PW,PH,{0,0},{Scale,Scale});std::string Path=std::string("Exhibits/Gallery/CameraNative/")+N+".png";Check(stbi_write_png(Path.c_str(),PW,PH,3,Pixels.data(),PW*3)!=0,"native capture");};
 Rest();Capture("Camera-Main");auto* Slider=Window("/Focal Length_");float Before=Camera->QueryFieldOfViewRadians();Click({Slider->Pos.x+Slider->Size.x*.55f,Slider->Pos.y+15});Check(Camera->QueryFieldOfViewRadians()<Before,"native lens slider edits actual camera");Capture("Camera-Telephoto");Find(*Sheet,"Focal Length").Figure=35;Apply();Slider=Window("/Aperture_");Click({Slider->Pos.x+Slider->Size.x*.8f,Slider->Pos.y+15});Check(Feed->MainLens.Aperture>10,"native aperture study control");Capture("Camera-StoppedDown");auto* Props=Window("##camera-properties");ImVec2 O=Props->DC.CursorStartPos;O.x+=20;O.y+=20;float W=Props->WorkRect.GetWidth()-40,CW=(W-16)/2,H=(W-48)*290/640,Y=110+H+270+16;Click({O.x+CW+16+24+(CW-48)*.75f,O.y+Y+210});Check(Feed->MainLens.Subject>20,"subject plane pointer writeback");float Old=Feed->MainLens.Subject;IO.AddKeyEvent(ImGuiKey_RightArrow,true);Tick();IO.AddKeyEvent(ImGuiKey_RightArrow,false);Tick();Check(Feed->MainLens.Subject>Old,"subject plane keyboard writeback");Capture("Camera-SubjectPlane");Pick=Cine;Build();Rest();Capture("Camera-CineStudy");Pick=Main;Build();Width=480;Height=2350;Rest();Capture("Camera-Narrow");Width=320;Height=750;Rest();Check(Window("##camera-properties")->ScrollMax.y>900,"compact scroll extent");ImGui::SetScrollY(Window("##camera-properties"),600);Rest();Capture("Camera-Scrolled");Width=1024;Height=800;Scale=2;ImGui::SetScrollY(Window("##camera-properties"),0);Rest();Capture("Camera-2x");Pick=0;Build();Check(Sheet->Appearance==EditorSheetAppearance::Generic&&!Sheet->CameraLive,"generic feed clears camera route");ImGui::DestroyContext();std::printf("PASS %u checks: native Camera, real feed writeback and projection rays, optical diagnostics, independent cine study, input, narrow/2x and teardown. No rendered DOF/GPU claim.\n",Checks);
}
