// Phase 32l — preserve one exact axis-parallel blind cylindrical cavity while rounding a complete prism family.
#include "Kernel/BlendSolver.h"
#include "Kernel/IntersectionSolver.h"
#include "Console/ConsoleHost.h"
#include "VerificationPanel.h"
#include <algorithm>
#include <cmath>
#include <filesystem>
#include <string>
#include <vector>
using namespace Frontier;
namespace{
Deliver<BrepBody> Fixture(bool High=true,double Y=7,double Z=5,double Bore=1.5,double Depth=12){auto Box=BrepBody::Box({0,0,0},{20,16,12});auto Cutter=BrepBody::Cylinder(High?Vec3{22,Y,Z}:Vec3{-2,Y,Z},High?Vec3{-1,0,0}:Vec3{1,0,0},Bore,Depth+2);if(!Box||!Cutter)return Deliver<BrepBody>::Reject(RefusalReason::DegenerateInput,"fixture");return IntersectionSolver::Combine(Box.Payload,Cutter.Payload,BodyOperation::Subtract);}
Deliver<BrepBody> SideFixture(){auto Box=BrepBody::Box({0,0,0},{20,16,12});auto Cutter=BrepBody::Cylinder({10,-2,6},{0,1,0},1.5,10);if(!Box||!Cutter)return Deliver<BrepBody>::Reject(RefusalReason::DegenerateInput,"fixture");return IntersectionSolver::Combine(Box.Payload,Cutter.Payload,BodyOperation::Subtract);}
std::vector<int> Rails(const BrepBody&B){std::vector<int>R;for(size_t I=0;I<B.Edges.size();++I){auto&E=B.Edges[I];if(E.Curve.Classification!=CurveClassification::Line||E.VertexStart<0||E.VertexEnd<0)continue;Vec3 P=B.Vertices[E.VertexStart].Point,Q=B.Vertices[E.VertexEnd].Point;if(std::fabs(std::fabs((Q-P).Normalised().Dot({1,0,0}))-1)>1e-8)continue;if((std::fabs(P.Y)<1e-8||std::fabs(P.Y-16)<1e-8)&&(std::fabs(P.Z)<1e-8||std::fabs(P.Z-12)<1e-8))R.push_back(static_cast<int>(I));}return R;}
struct Inspection{bool Topology=false,Supports=false,Caps=false,Circles=false,Dimensions=false;};Inspection Inspect(const BrepBody&B,bool High,double Y,double Z,double Bore,double Depth){Inspection Q;auto V=B.Validate();Q.Topology=V.Solid()&&V.Hulls==1&&V.Genus==0&&B.Vertices.size()==18&&B.Edges.size()==27&&B.Coedges.size()==54&&B.Loops.size()==13&&B.Faces.size()==12;int Planes=0,Rolls=0,Cavity=0,Annular=0,Closed=0;std::vector<double>X;for(auto&F:B.Faces){auto&S=F.Surface;if(S.Classification==SurfaceClassification::Plane){++Planes;Annular+=F.Loops.size()==2;}if(S.Classification==SurfaceClassification::Cylinder&&S.Rational()){Rolls+=std::fabs(S.RadiusMajor-2)<1e-9;if(std::fabs(S.RadiusMajor-Bore)<1e-9)++Cavity;}}for(auto&E:B.Edges)if(E.Closed()){++Closed;Q.Circles|=E.Curve.Classification!=CurveClassification::Circle||!E.Curve.Rational();X.push_back(E.Curve.Sample(E.Curve.DomainStart()).X);}Q.Circles=!Q.Circles&&Closed==2;std::sort(X.begin(),X.end());double Entry=High?20:0,Bottom=High?20-Depth:Depth;Q.Dimensions=X.size()==2&&std::fabs(X.front()-std::min(Entry,Bottom))<1e-7&&std::fabs(X.back()-std::max(Entry,Bottom))<1e-7;for(auto&F:B.Faces)if(F.Surface.Classification==SurfaceClassification::Cylinder&&std::fabs(F.Surface.RadiusMajor-Bore)<1e-9)Q.Dimensions&=std::fabs((F.Surface.Origin-Vec3{0,Y,Z}).Y)<1e-8&&std::fabs((F.Surface.Origin-Vec3{0,Y,Z}).Z)<1e-8;Q.Supports=Planes==7&&Rolls==4&&Cavity==1;Q.Caps=Annular==1;return Q;}
double Exact(double Bore,double Depth){return 20*(16*12-4*4*(1-ScalarCriteria::Pi/4))-ScalarCriteria::Pi*Bore*Bore*Depth;}
}
int main(){VerificationPanel P("SolidArc · Phase 32l · Blind-Bore Rounded-Prism Verification");auto S=Fixture();auto E=Rails(S.Payload);auto Source=S.Payload.Validate();P.Section("Exact blind-cavity reconstruction");P.Expect("Blind-bore source is canonical V10/E15/C30/L9/F8 genus-zero topology",S&&Source.Solid()&&Source.Hulls==1&&Source.Genus==0&&S.Payload.Vertices.size()==10&&S.Payload.Edges.size()==15&&S.Payload.Coedges.size()==30&&S.Payload.Loops.size()==9&&S.Payload.Faces.size()==8);int SourceExact=0,SourceFitted=0;for(auto&X:S.Payload.Edges)if(X.Closed()){SourceExact+=X.Curve.Classification==CurveClassification::Circle&&X.Curve.Rational();SourceFitted+=X.Curve.Classification==CurveClassification::Freeform&&!X.Curve.Rational();}P.Expect("Source evidence contains one exact floor rim and one fitted Boolean entrance rim",SourceExact==1&&SourceFitted==1);P.Expect("Exactly four outer axial rails remain selectable",E.size()==4);int Applied=-1;auto R=BlendSolver::FilletEdges(S.Payload,E,2,&Applied);P.Expect("The blind cavity commits with all four outer rolls",R&&Applied==4);auto Q=R?Inspect(R.Payload,true,7,5,1.5,12):Inspection{};P.Expect("Output reaches exact V18/E27/C54/L13/F12 genus-zero topology",Q.Topology);P.Expect("Seven planes, four rolls, and one rational cavity cylinder remain",Q.Supports);P.Expect("Only the entrance end cap is annular",Q.Caps);P.Expect("Both cavity rims are restored as exact rational circles",Q.Circles);P.Expect("Bore radius, offset, entry end, and depth remain unchanged",Q.Dimensions);P.Within("Blind-bore rounded-prism volume follows the exact cavity formula",R?std::fabs(R.Payload.Validate().Volume-Exact(1.5,12)):1e9,.5);P.Expect("Outer bounds and source topology remain unchanged",R&&R.Payload.Bounds().Low.Distance(S.Payload.Bounds().Low)<1e-9&&R.Payload.Bounds().High.Distance(S.Payload.Bounds().High)<1e-9&&S.Payload.Edges.size()==15);
P.Section("Entry direction, offsets, transforms, and refusal");auto Low=Fixture(false);int LA=-1;auto LR=BlendSolver::FilletEdges(Low.Payload,Rails(Low.Payload),2,&LA);P.Expect("The opposite prism end supports the same exact blind route",LR&&LA==4&&Inspect(LR.Payload,false,7,5,1.5,12).Topology&&Inspect(LR.Payload,false,7,5,1.5,12).Dimensions);auto Offset=Fixture(true,5,4,1,9);int OA=-1;auto OR=BlendSolver::FilletEdges(Offset.Payload,Rails(Offset.Payload),2,&OA);P.Expect("A safe offset blind bore preserves its requested depth",OR&&OA==4&&Inspect(OR.Payload,true,5,4,1,9).Dimensions);std::vector<int>Reverse{E[3],E[0],E[2],E[1],E[3]};int RA=-1;auto RR=BlendSolver::FilletEdges(S.Payload,Reverse,2,&RA);P.Expect("Repeated reordered rail seeds are deterministic",RR&&RA==4&&std::fabs(RR.Payload.Validate().Volume-R.Payload.Validate().Volume)<1e-9);Mat4 M=Mat4::Translation({3,-4,6})*Mat4::Rotation({1,3,2},.59);BrepBody T=S.Payload.Transformed(M);int TA=-1;auto TR=BlendSolver::FilletEdges(T,E,2,&TA);P.Expect("Rigid transforms preserve blind-cylinder classification",TR&&TA==4&&TR.Payload.Validate().Genus==0&&TR.Payload.Faces.size()==12);P.Within("Rigid transforms preserve blind-cavity volume",R&&TR?std::fabs(R.Payload.Validate().Volume-TR.Payload.Validate().Volume):1e9,.5);auto Wall=Fixture(true,1.2,1.2,1,9);int Refused=99;auto WR=BlendSolver::FilletEdges(Wall.Payload,Rails(Wall.Payload),2,&Refused);P.Expect("A blind bore crossing the rounded wall refuses transactionally",!WR&&Refused==0);auto Side=SideFixture();int SideApplied=-1;auto SR=BlendSolver::FilletEdges(Side.Payload,Rails(Side.Payload),2,&SideApplied);P.Expect("An orthogonal side cavity delegates to the retained-wall route",Side&&SR&&SideApplied==4&&SR.Payload.Faces.size()==12);
P.Section("Console and proof");
#ifndef SOLIDARC_PROOF_FOLDER
#error proof folder required
#endif
ConsoleHost H(SOLIDARC_PROOF_FOLDER,1280,800);auto&F=H.Document().AddBody("Blind",S.Payload);F.Matcap=6;std::string List;for(int I:E){if(!List.empty())List+=",";List+=std::to_string(I);}bool OK=H.Execute("fillet Blind 2 --edges="+List+" --name=BlindRound");auto*Output=H.Document().Find("BlindRound");P.Expect("Console fillet commits one exact blind-cavity solid",OK&&Output&&Output->Body.Validate().Genus==0&&Output->Body.Faces.size()==12);
std::filesystem::path Proof=std::filesystem::path(SOLIDARC_PROOF_FOLDER)/"Phase32l_BlindBorePrism.png";std::error_code Error;std::filesystem::remove(Proof,Error);ConsoleHost V(SOLIDARC_PROOF_FOLDER,1280,800);auto Reset=[&](){return V.Execute("reset")&&V.Execute("gizmo off");};auto Add=[&](const char*N,BrepBody B,uint8_t C){auto&G=V.Document().AddBody(N,std::move(B));G.Matcap=C;return true;};bool Rendered=Reset()&&Add("BlindSharp",S.Payload.Transformed(Mat4::Translation({-24,0,0})),6)&&Add("BlindRound",R.Payload.Transformed(Mat4::Translation({8,0,0})),3)&&V.Execute("view iso")&&V.Execute("view fit")&&V.Execute("render sheet 0")&&Reset()&&Add("BlindEntrance",R.Payload,3)&&V.Execute("view right")&&V.Execute("view fit")&&V.Execute("render sheet 1")&&Reset()&&Add("BlindOffset",OR.Payload,2)&&V.Execute("view right")&&V.Execute("view fit")&&V.Execute("render sheet 2")&&Reset()&&Add("BlindTilt",TR.Payload,5)&&V.Execute("view iso")&&V.Execute("view fit")&&V.Execute("render sheet 3")&&V.Execute("render sheet finalize Phase32l_BlindBorePrism");P.Expect("C++ blind-bore proof commands complete",Rendered);P.Expect("C++ blind-bore proof is written",std::filesystem::exists(Proof)&&std::filesystem::file_size(Proof,Error)>100000);return P.Conclude();}
