// Phase 32i — preserve one offset axis-parallel circular through-hole through a complete rounded-prism family.
#include "Kernel/BlendSolver.h"
#include "Console/ConsoleHost.h"
#include "VerificationPanel.h"
#include <cmath>
#include <filesystem>
#include <string>
#include <vector>
using namespace Frontier;
namespace{
Deliver<BrepBody> Fixture(double Y=5,double Z=4,double Bore=1.25){auto Outer=NurbsCurve::Polyline({{0,0,0},{0,16,0},{0,16,12},{0,0,12}},true);auto Hole=NurbsCurve::Circle({0,Y,Z},{1,0,0},Bore);if(!Outer||!Hole)return Deliver<BrepBody>::Reject(RefusalReason::DegenerateInput,"fixture");return BrepBody::Extrude(std::vector<NurbsCurve>{Outer.Payload,Hole.Payload},{1,0,0},20);}
Deliver<BrepBody> NineHoles(){auto Outer=NurbsCurve::Polyline({{0,0,0},{0,16,0},{0,16,12},{0,0,12}},true);if(!Outer)return Deliver<BrepBody>::Reject(RefusalReason::DegenerateInput,"fixture");std::vector<NurbsCurve>Loops{Outer.Payload};for(double Y:{4.,8.,12.})for(double Z:{3.,6.,9.}){auto C=NurbsCurve::Circle({0,Y,Z},{1,0,0},.5);if(!C)return Deliver<BrepBody>::Reject(C.Denial.Reason,C.Denial.Detail);Loops.push_back(std::move(C.Payload));}return BrepBody::Extrude(Loops,{1,0,0},20);}
std::vector<int> Rails(const BrepBody&B){std::vector<int>R;for(size_t I=0;I<B.Edges.size();++I){auto&E=B.Edges[I];if(E.Curve.Classification!=CurveClassification::Line||E.VertexStart<0||E.VertexEnd<0)continue;Vec3 P=B.Vertices[E.VertexStart].Point,Q=B.Vertices[E.VertexEnd].Point;if(std::fabs(std::fabs((Q-P).Normalised().Dot({1,0,0}))-1)>1e-8)continue;if((std::fabs(P.Y)<1e-8||std::fabs(P.Y-16)<1e-8)&&(std::fabs(P.Z)<1e-8||std::fabs(P.Z-12)<1e-8))R.push_back(static_cast<int>(I));}return R;}
struct Inspection{bool Topology=false,Supports=false,Caps=false,Location=false;};Inspection Inspect(const BrepBody&B,double Bore,Vec3 Centre){Inspection Q;auto V=B.Validate();Q.Topology=V.Solid()&&V.Hulls==1&&V.Genus==1&&B.Vertices.size()==18&&B.Edges.size()==27&&B.Coedges.size()==54&&B.Loops.size()==13&&B.Faces.size()==11;int Planes=0,Rolls=0,Holes=0,Annular=0,Circles=0;for(auto&F:B.Faces){auto&S=F.Surface;if(S.Classification==SurfaceClassification::Plane){++Planes;Annular+=F.Loops.size()==2;}if(S.Classification==SurfaceClassification::Cylinder){if(S.Rational()&&std::fabs(S.RadiusMajor-2)<1e-9)++Rolls;if(S.Rational()&&std::fabs(S.RadiusMajor-Bore)<1e-9){++Holes;Q.Location=S.Origin.Distance(Centre)<1e-8&&std::fabs(std::fabs(S.Axis.Normalised().Dot({1,0,0}))-1)<1e-8;}}}for(auto&E:B.Edges)Circles+=E.Closed()&&E.Curve.Classification==CurveClassification::Circle&&E.Curve.Rational();Q.Supports=Planes==6&&Rolls==4&&Holes==1;Q.Caps=Annular==2&&Circles==2;return Q;}
double Exact(double Bore){return 20*(16*12-4*4*(1-ScalarCriteria::Pi/4)-ScalarCriteria::Pi*Bore*Bore);}
}
int main(){VerificationPanel P("SolidArc · Phase 32i · Offset Bore Rounded-Prism Verification");auto S=Fixture();auto E=Rails(S.Payload);auto Source=S.Payload.Validate();P.Section("Offset exact bore reconstruction");P.Expect("The offset-bore source is one canonical genus-one extrusion",S&&Source.Solid()&&Source.Genus==1&&S.Payload.Vertices.size()==10&&S.Payload.Edges.size()==15);P.Expect("The four outer axial rails remain unambiguous",E.size()==4);int Applied=-1;auto R=BlendSolver::FilletEdges(S.Payload,E,2,&Applied);P.Expect("A safe offset bore commits with all four outer rolls",R&&Applied==4);auto Q=R?Inspect(R.Payload,1.25,{0,5,4}):Inspection{};P.Expect("Offset output reaches exact V18/E27/C54/L13/F11 genus-one topology",Q.Topology);P.Expect("All planar, rolling-cylinder, and bore supports remain exact rational geometry",Q.Supports);P.Expect("The bore axis remains at its requested offset",Q.Location);P.Expect("Both rounded end caps retain one exact circular inner loop",Q.Caps);P.Within("Offset placement preserves the analytic perforated volume",R?std::fabs(R.Payload.Validate().Volume-Exact(1.25)):1e9,0.5);P.Expect("Outer bounds and source topology remain unchanged",R&&R.Payload.Bounds().Low.Distance(S.Payload.Bounds().Low)<1e-9&&R.Payload.Bounds().High.Distance(S.Payload.Bounds().High)<1e-9&&S.Payload.Edges.size()==15);
P.Section("Offset clearance and bounded scope");std::vector<int>Reverse{E[3],E[0],E[2],E[1],E[3]};int Reordered=-1;auto RR=BlendSolver::FilletEdges(S.Payload,Reverse,2,&Reordered);P.Expect("Repeated reordered outer seeds deduplicate deterministically",RR&&Reordered==4);P.Within("Offset result volume is seed-order invariant",R&&RR?std::fabs(R.Payload.Validate().Volume-RR.Payload.Validate().Volume):1e9,1e-9);auto Near=Fixture(1.8,1.8,1);int NearApplied=-1;auto NR=BlendSolver::FilletEdges(Near.Payload,Rails(Near.Payload),2,&NearApplied);P.Expect("A bore inside the exact rounded-corner offset commits",NR&&NearApplied==4&&Inspect(NR.Payload,1,{0,1.8,1.8}).Topology);auto Large=Fixture(8,6,2.5);int LargeApplied=-1;auto LR=BlendSolver::FilletEdges(Large.Payload,Rails(Large.Payload),2,&LargeApplied);P.Expect("A safe bore larger than the outer roll uses strict side clearance",LR&&LargeApplied==4&&Inspect(LR.Payload,2.5,{0,8,6}).Topology);auto Corner=Fixture(1.2,1.2,1);int Refused=99;auto CR=BlendSolver::FilletEdges(Corner.Payload,Rails(Corner.Payload),2,&Refused);P.Expect("A bore crossing the inward corner offset refuses transactionally",!CR&&Refused==0&&std::string(CR.Denial.Detail)=="rounded-prism hole intersects the inward-offset wall");auto Side=Fixture(1.4,6,1.5);Refused=99;auto SR=BlendSolver::FilletEdges(Side.Payload,Rails(Side.Payload),2,&Refused);P.Expect("A bore crossing a retained side wall refuses transactionally",!SR&&Refused==0&&std::string(SR.Denial.Detail)=="rounded-prism hole consumes the radial wall");Mat4 M=Mat4::Translation({4,-3,7})*Mat4::Rotation({1,4,2},0.63);BrepBody T=S.Payload.Transformed(M);int TA=-1;auto TR=BlendSolver::FilletEdges(T,E,2,&TA);P.Expect("Rigid transforms preserve offset-bore classification",TR&&TA==4&&TR.Payload.Validate().Genus==1);P.Within("Rigid transforms preserve offset-bore volume",R&&TR?std::fabs(R.Payload.Validate().Volume-TR.Payload.Validate().Volume):1e9,0.5);auto Nine=NineHoles();Refused=99;auto MR=BlendSolver::FilletEdges(Nine.Payload,Rails(Nine.Payload),2,&Refused);P.Expect("Nine bores remain outside the bounded route",Nine&&Nine.Payload.Validate().Genus==9&&!MR&&Refused==0);
P.Section("Console and proof");
#ifndef SOLIDARC_PROOF_FOLDER
#error proof folder required
#endif
ConsoleHost H(SOLIDARC_PROOF_FOLDER,1280,800);auto&F=H.Document().AddBody("OffsetBore",S.Payload);F.Matcap=6;std::string List;for(int I:E){if(!List.empty())List+=",";List+=std::to_string(I);}bool OK=H.Execute("fillet OffsetBore 2 --edges="+List+" --name=OffsetRound");auto*Output=H.Document().Find("OffsetRound");P.Expect("Console fillet preserves the offset genus-one bore",OK&&Output&&Output->Body.Validate().Genus==1);
std::filesystem::path Proof=std::filesystem::path(SOLIDARC_PROOF_FOLDER)/"Phase32i_OffsetBorePrism.png";std::error_code Error;std::filesystem::remove(Proof,Error);ConsoleHost V(SOLIDARC_PROOF_FOLDER,1280,800);auto Reset=[&](){return V.Execute("reset")&&V.Execute("gizmo off");};auto Add=[&](const char*N,BrepBody B,uint8_t C){auto&G=V.Document().AddBody(N,std::move(B));G.Matcap=C;return true;};bool Rendered=Reset()&&Add("OffsetSharp",S.Payload.Transformed(Mat4::Translation({-24,0,0})),6)&&Add("OffsetRound",R.Payload.Transformed(Mat4::Translation({8,0,0})),3)&&V.Execute("view iso")&&V.Execute("view fit")&&V.Execute("render sheet 0")&&Reset()&&Add("OffsetEnd",R.Payload,3)&&V.Execute("view right")&&V.Execute("view fit")&&V.Execute("render sheet 1")&&Reset()&&Add("NearCorner",NR.Payload,2)&&V.Execute("view right")&&V.Execute("view fit")&&V.Execute("render sheet 2")&&Reset()&&Add("OffsetTilt",TR.Payload,5)&&V.Execute("view iso")&&V.Execute("view fit")&&V.Execute("render sheet 3")&&V.Execute("render sheet finalize Phase32i_OffsetBorePrism");P.Expect("C++ offset-bore proof commands complete",Rendered);P.Expect("C++ offset-bore proof is written",std::filesystem::exists(Proof)&&std::filesystem::file_size(Proof,Error)>100000);return P.Conclude();}
