// Phase 32h — preserve one coaxial circular through-hole while rounding a complete parallel edge family.
#include "Kernel/BlendSolver.h"
#include "Console/ConsoleHost.h"
#include "VerificationPanel.h"
#include <algorithm>
#include <cmath>
#include <filesystem>
#include <string>
#include <vector>
using namespace Frontier;
namespace{
Deliver<BrepBody> Fixture(double Width=16,double Height=12,double HoleY=8,double HoleZ=6,double HoleRadius=1.5){auto Outer=NurbsCurve::Polyline({{0,0,0},{0,Width,0},{0,Width,Height},{0,0,Height}},true);auto Hole=NurbsCurve::Circle({0,HoleY,HoleZ},{1,0,0},HoleRadius);if(!Outer||!Hole)return Deliver<BrepBody>::Reject(RefusalReason::DegenerateInput,"fixture");return BrepBody::Extrude(std::vector<NurbsCurve>{Outer.Payload,Hole.Payload},{1,0,0},20);}
std::vector<int> OuterRails(const BrepBody&B,double W,double H){std::vector<int>R;for(size_t I=0;I<B.Edges.size();++I){auto&E=B.Edges[I];if(E.Curve.Classification!=CurveClassification::Line||E.VertexStart<0||E.VertexEnd<0)continue;Vec3 A=B.Vertices[E.VertexStart].Point,Z=B.Vertices[E.VertexEnd].Point;if(std::fabs(std::fabs((Z-A).Normalised().Dot({1,0,0}))-1)>1e-8)continue;if((std::fabs(A.Y)<1e-8||std::fabs(A.Y-W)<1e-8)&&(std::fabs(A.Z)<1e-8||std::fabs(A.Z-H)<1e-8))R.push_back(static_cast<int>(I));}return R;}
struct Check{bool Topology=false,Supports=false,Hole=false;};Check Inspect(const BrepBody&B,double Roll,double Bore){Check Q;auto V=B.Validate();Q.Topology=V.Solid()&&V.Hulls==1&&V.Genus==1&&B.Vertices.size()==18&&B.Edges.size()==27&&B.Coedges.size()==54&&B.Loops.size()==13&&B.Faces.size()==11;int P=0,R=0,H=0,HoledCaps=0,Circles=0;bool Exact=true;for(auto&F:B.Faces){auto&S=F.Surface;if(S.Classification==SurfaceClassification::Plane){++P;if(F.Loops.size()==2)++HoledCaps;}if(S.Classification==SurfaceClassification::Cylinder){Exact&=S.Rational();if(std::fabs(S.RadiusMajor-Roll)<1e-9)++R;if(std::fabs(S.RadiusMajor-Bore)<1e-9)++H;}}for(auto&E:B.Edges)if(E.Closed()&&E.Curve.Classification==CurveClassification::Circle&&E.Curve.Rational())++Circles;Q.Supports=P==6&&R==4&&H==1&&Exact;Q.Hole=HoledCaps==2&&Circles==2;return Q;}
double Exact(double L,double W,double H,double R,double Bore){return L*(W*H-4*R*R*(1-ScalarCriteria::Pi/4)-ScalarCriteria::Pi*Bore*Bore);}
}
int main(){VerificationPanel P("SolidArc · Phase 32h · Perforated Rounded Prism Verification");auto S=Fixture();auto Rails=S?OuterRails(S.Payload,16,12):std::vector<int>{};auto Before=S?S.Payload.Validate():BodyReport{};
P.Section("Hole-preserving exact reconstruction");P.Expect("The source is a genus-one through-hole solid",S&&Before.Solid()&&Before.Genus==1);P.Expect("Exactly four outer axial rails are selectable",Rails.size()==4);int Applied=-1;auto R=Rails.size()==4?BlendSolver::FilletEdges(S.Payload,Rails,2,&Applied):Deliver<BrepBody>::Reject(RefusalReason::Unsupported,"rails");P.Expect("The complete outer family commits while preserving the bore",R&&Applied==4);Check Q=R?Inspect(R.Payload,2,1.5):Check{};P.Expect("The result has exact V18/E27/C54/L13/F11 genus-one topology",Q.Topology);P.Expect("Six planes, four outer rolls, and one bore cylinder remain",Q.Supports);P.Expect("Both rounded end caps retain one circular hole loop",Q.Hole);P.Expect("The operation removes only outer-corner material",R&&R.Payload.Validate().Volume<Before.Volume);P.Within("Perforated rounded-prism volume follows the exact area extrusion",R?std::fabs(R.Payload.Validate().Volume-Exact(20,16,12,2,1.5)):1e9,0.5);P.Expect("The outer extents and source body remain unchanged",R&&R.Payload.Bounds().Low.Distance(S.Payload.Bounds().Low)<1e-9&&R.Payload.Bounds().High.Distance(S.Payload.Bounds().High)<1e-9&&S.Payload.Edges.size()==15);
P.Section("Determinism, transforms, and refusal boundary");std::vector<int>Reverse{Rails[3],Rails[1],Rails[0],Rails[2],Rails[3]};int RC=-1;auto RR=BlendSolver::FilletEdges(S.Payload,Reverse,2,&RC);P.Expect("Reordered and repeated outer rails deduplicate to four",RR&&RC==4);P.Within("Both seed orders produce identical volume",R&&RR?std::fabs(R.Payload.Validate().Volume-RR.Payload.Validate().Volume):1e9,1e-9);Mat4 M=Mat4::Translation({3,-2,5})*Mat4::Rotation({2,1,4},0.58);BrepBody T=S.Payload.Transformed(M);int TC=-1;auto TR=BlendSolver::FilletEdges(T,Rails,2,&TC);P.Expect("Rigid transforms preserve the hole-aware classifier",TR&&TC==4&&TR.Payload.Validate().Genus==1);P.Within("Rigid transformation preserves perforated volume",R&&TR?std::fabs(R.Payload.Validate().Volume-TR.Payload.Validate().Volume):1e9,0.5);auto Off=Fixture(16,12,7,6,1.5);auto OffRails=OuterRails(Off.Payload,16,12);int Refused=99;auto OffResult=BlendSolver::FilletEdges(Off.Payload,OffRails,2,&Refused);P.Expect("A safe offset bore uses the same exact genus-one route",OffResult&&Refused==4&&Inspect(OffResult.Payload,2,1.5).Topology);auto NoWall=Fixture(16,12,8,6,6);auto NoWallRails=OuterRails(NoWall.Payload,16,12);Refused=99;auto NoWallResult=BlendSolver::FilletEdges(NoWall.Payload,NoWallRails,2,&Refused);P.Expect("A bore consuming the radial wall refuses transactionally",NoWall&&NoWall.Payload.Validate().Solid()&&!NoWallResult&&Refused==0&&std::string(NoWallResult.Denial.Detail)=="rounded-prism hole consumes the radial wall");auto Thin=Fixture(4,12,2,6,1);auto ThinRails=OuterRails(Thin.Payload,4,12);Refused=99;auto ThinResult=BlendSolver::FilletEdges(Thin.Payload,ThinRails,2,&Refused);P.Expect("A fillet consuming the cross-wall refuses transactionally",!ThinResult&&Refused==0);
P.Section("Console and proof");
#ifndef SOLIDARC_PROOF_FOLDER
#error proof folder required
#endif
ConsoleHost H(SOLIDARC_PROOF_FOLDER,1280,800);auto&SourceFigure=H.Document().AddBody("Bored",S.Payload);SourceFigure.Matcap=6;std::string List;for(int E:Rails){if(!List.empty())List+=",";List+=std::to_string(E);}bool OK=H.Execute("fillet Bored 2 --edges="+List+" --name=BoredRound");auto*F=H.Document().Find("BoredRound");P.Expect("The console commits the hole-preserving family",OK);P.Expect("The console result remains genus one",F&&F->Body.Validate().Genus==1);std::filesystem::path Proof=std::filesystem::path(SOLIDARC_PROOF_FOLDER)/"Phase32h_PerforatedPrism.png";std::error_code E;std::filesystem::remove(Proof,E);ConsoleHost V(SOLIDARC_PROOF_FOLDER,1280,800);auto Reset=[&](){return V.Execute("reset")&&V.Execute("gizmo off");};auto Add=[&](const char*N,BrepBody B,uint8_t C){auto&G=V.Document().AddBody(N,std::move(B));G.Matcap=C;return true;};bool Rendered=Reset()&&Add("BoredSharp",S.Payload.Transformed(Mat4::Translation({-24,0,0})),6)&&Add("BoredRound",R.Payload.Transformed(Mat4::Translation({8,0,0})),3)&&V.Execute("view iso")&&V.Execute("view fit")&&V.Execute("render sheet 0")&&Reset()&&Add("BoreEnd",R.Payload,3)&&V.Execute("view right")&&V.Execute("view fit")&&V.Execute("render sheet 1")&&Reset()&&Add("BoreIso",R.Payload,2)&&V.Execute("view iso")&&V.Execute("view fit")&&V.Execute("render sheet 2")&&Reset()&&Add("BoreTilt",TR.Payload,5)&&V.Execute("view iso")&&V.Execute("view fit")&&V.Execute("render sheet 3")&&V.Execute("render sheet finalize Phase32h_PerforatedPrism");P.Expect("C++ perforated-prism proof commands complete",Rendered);P.Expect("C++ perforated-prism proof is written",std::filesystem::exists(Proof)&&std::filesystem::file_size(Proof,E)>100000);return P.Conclude();}
