// Phase 32f — complete equal-radius rounded rectangular solid.
#include "Kernel/BlendSolver.h"
#include "Console/ConsoleHost.h"
#include "VerificationPanel.h"
#include <algorithm>
#include <cmath>
#include <filesystem>
#include <numeric>
#include <string>
#include <vector>
using namespace Frontier;
namespace {
struct Inspection{bool Topology=false,Supports=false,Exact=false;double SphereResidual=1e9;};
Inspection Inspect(const BrepBody&B,double R){Inspection I;auto Q=B.Validate();I.Topology=Q.Solid()&&Q.Hulls==1&&Q.Genus==0&&B.Vertices.size()==24&&B.Edges.size()==48&&B.Coedges.size()==96&&B.Loops.size()==26&&B.Faces.size()==26;int P=0,C=0,S=0;I.SphereResidual=0;bool Exact=true;for(auto&F:B.Faces){auto&N=F.Surface;if(N.Classification==SurfaceClassification::Plane)++P;if(N.Classification==SurfaceClassification::Cylinder){++C;Exact&=N.Rational()&&std::fabs(N.RadiusMajor-R)<1e-10;}if(N.Classification==SurfaceClassification::Sphere){++S;Exact&=N.Rational()&&std::fabs(N.RadiusMajor-R)<1e-10;for(int U=0;U<=4;U++)for(int V=0;V<=4;V++){double A=N.DomainStartU()+(N.DomainEndU()-N.DomainStartU())*U/4.0,D=N.DomainStartV()+(N.DomainEndV()-N.DomainStartV())*V/4.0;I.SphereResidual=std::max(I.SphereResidual,std::fabs(N.Sample(A,D).Distance(N.Origin)-R));}}}I.Supports=P==6&&C==12&&S==8;I.Exact=Exact;return I;}
double ExactVolume(double A,double B,double C,double R){double X=A-2*R,Y=B-2*R,Z=C-2*R;return X*Y*Z+2*R*(X*Y+X*Z+Y*Z)+ScalarCriteria::Pi*R*R*(X+Y+Z)+4.0*ScalarCriteria::Pi*R*R*R/3.0;}
}
int main(){VerificationPanel P("SolidArc · Phase 32f · Complete Rounded Box Verification");auto S=BrepBody::Box({0,0,0},{20,16,12});std::vector<int>E(12);std::iota(E.begin(),E.end(),0);auto Before=S.Payload.Validate();
P.Section("Complete interacting edge network");int Applied=-1;auto R=BlendSolver::FilletEdges(S.Payload,E,2,&Applied);P.Expect("All twelve box edges commit transactionally",R&&Applied==12);Inspection Q=R?Inspect(R.Payload,2):Inspection{};P.Expect("The rounded box has exact V24/E48/C96/L26/F26 topology",Q.Topology);P.Expect("Six planes, twelve cylinders, and eight spherical octants remain",Q.Supports);P.Expect("Every curved support retains exact rational radius identity",Q.Exact);P.Within("Worst spherical-octant radius residual",Q.SphereResidual,1e-9);P.Expect("The complete network removes material",R&&R.Payload.Validate().Volume<Before.Volume);P.Within("Rounded-box volume follows the exact Minkowski-sum formula",R?std::fabs(R.Payload.Validate().Volume-ExactVolume(20,16,12,2)):1e9,0.5);P.Expect("Rounded and sharp boxes have identical bounds",R&&R.Payload.Bounds().Low.Distance(S.Payload.Bounds().Low)<1e-9&&R.Payload.Bounds().High.Distance(S.Payload.Bounds().High)<1e-9);P.Expect("The source body remains unchanged",S.Payload.Edges.size()==12&&std::fabs(S.Payload.Validate().Volume-Before.Volume)<1e-12);
P.Section("Order, transform, and transactional refusal");std::reverse(E.begin(),E.end());E.insert(E.end(),{11,4,0});int Recount=-1;auto Reverse=BlendSolver::FilletEdges(S.Payload,E,2,&Recount);P.Expect("Reverse order and repeated seeds still apply twelve chains",Reverse&&Recount==12);P.Within("Canonical and reordered volumes are identical",R&&Reverse?std::fabs(R.Payload.Validate().Volume-Reverse.Payload.Validate().Volume):1e9,1e-9);Mat4 M=Mat4::Translation({4,-3,7})*Mat4::Rotation({2,1,3},0.71);BrepBody T=S.Payload.Transformed(M);std::vector<int>TE(12);std::iota(TE.begin(),TE.end(),0);int TC=-1;auto TR=BlendSolver::FilletEdges(T,TE,2,&TC);P.Expect("A rigidly transformed box retains the complete rounded topology",TR&&TC==12&&Inspect(TR.Payload,2).Topology);P.Within("Rigid transformation preserves rounded volume within integration tolerance",R&&TR?std::fabs(R.Payload.Validate().Volume-TR.Payload.Validate().Volume):1e9,0.5);std::vector<int>Missing(11);std::iota(Missing.begin(),Missing.end(),0);int Refused=99;auto Partial=BlendSolver::FilletEdges(S.Payload,Missing,2,&Refused);P.Expect("An incomplete interacting network refuses without a partial result",!Partial&&Refused==0);Refused=99;auto Huge=BlendSolver::FilletEdges(S.Payload,std::vector<int>{0,1,2,3,4,5,6,7,8,9,10,11},6,&Refused);P.Expect("A radius consuming inset planes refuses cleanly",!Huge&&Refused==0&&std::string(Huge.Denial.Detail)=="all-edge box fillet radius consumes an inset planar support");
P.Section("Console and deterministic proof");
#ifndef SOLIDARC_PROOF_FOLDER
#error proof folder required
#endif
ConsoleHost H(SOLIDARC_PROOF_FOLDER,1280,800);bool OK=H.Execute("box (0,0,0) (20,16,12) --name=Box")&&H.Execute("fillet Box 2 --edges=0,1,2,3,4,5,6,7,8,9,10,11 --name=Rounded");auto*CF=H.Document().Find("Rounded");P.Expect("The console commits the twelve-edge network",OK);P.Expect("The console result contains all twenty curved patches",CF&&Inspect(CF->Body,2).Supports);std::filesystem::path Proof=std::filesystem::path(SOLIDARC_PROOF_FOLDER)/"Phase32f_RoundedBox.png";std::error_code X;std::filesystem::remove(Proof,X);ConsoleHost V(SOLIDARC_PROOF_FOLDER,1280,800);auto Reset=[&](){return V.Execute("reset")&&V.Execute("gizmo off");};auto Add=[&](const char*N,BrepBody B,uint8_t C){auto&F=V.Document().AddBody(N,std::move(B));F.Matcap=C;return true;};bool Rendered=Reset()&&Add("Sharp",S.Payload.Transformed(Mat4::Translation({-24,0,0})),0)&&Add("Rounded",R.Payload.Transformed(Mat4::Translation({8,0,0})),3)&&V.Execute("view iso")&&V.Execute("view fit")&&V.Execute("render sheet 0")&&Reset()&&Add("RoundedClose",R.Payload,3)&&V.Execute("view iso")&&V.Execute("view fit")&&V.Execute("view dolly 0.7")&&V.Execute("render sheet 1")&&Reset()&&Add("RoundedTop",R.Payload,2)&&V.Execute("view top")&&V.Execute("view fit")&&V.Execute("render sheet 2")&&Reset()&&Add("RoundedTilt",TR.Payload,5)&&V.Execute("view iso")&&V.Execute("view fit")&&V.Execute("render sheet 3")&&V.Execute("render sheet finalize Phase32f_RoundedBox");P.Expect("C++ rounded-box proof commands complete",Rendered);P.Expect("C++ rounded-box proof is written",std::filesystem::exists(Proof)&&std::filesystem::file_size(Proof,X)>100000);return P.Conclude();}
