// Phase 32j — preserve exactly two non-overlapping axis-parallel through-holes through a complete rounded-prism family.
#include "Kernel/BlendSolver.h"
#include "Console/ConsoleHost.h"
#include "VerificationPanel.h"
#include <cmath>
#include <filesystem>
#include <string>
#include <vector>
using namespace Frontier;
namespace{
struct Bore{double Y,Z,R;};
Deliver<BrepBody> Fixture(const std::vector<Bore>& Holes={{5,4,1},{11,8,1.5}}){auto Outer=NurbsCurve::Polyline({{0,0,0},{0,16,0},{0,16,12},{0,0,12}},true);if(!Outer)return Deliver<BrepBody>::Reject(RefusalReason::DegenerateInput,"fixture");std::vector<NurbsCurve>Loops{Outer.Payload};for(auto H:Holes){auto C=NurbsCurve::Circle({0,H.Y,H.Z},{1,0,0},H.R);if(!C)return Deliver<BrepBody>::Reject(C.Denial.Reason,C.Denial.Detail);Loops.push_back(std::move(C.Payload));}return BrepBody::Extrude(Loops,{1,0,0},20);}
std::vector<int> Rails(const BrepBody&B){std::vector<int>R;for(size_t I=0;I<B.Edges.size();++I){auto&E=B.Edges[I];if(E.Curve.Classification!=CurveClassification::Line||E.VertexStart<0||E.VertexEnd<0)continue;Vec3 P=B.Vertices[E.VertexStart].Point,Q=B.Vertices[E.VertexEnd].Point;if(std::fabs(std::fabs((Q-P).Normalised().Dot({1,0,0}))-1)>1e-8)continue;if((std::fabs(P.Y)<1e-8||std::fabs(P.Y-16)<1e-8)&&(std::fabs(P.Z)<1e-8||std::fabs(P.Z-12)<1e-8))R.push_back(static_cast<int>(I));}return R;}
struct Inspection{bool Topology=false,Supports=false,Caps=false,Locations=false;};Inspection Inspect(const BrepBody&B){Inspection Q;auto V=B.Validate();Q.Topology=V.Solid()&&V.Hulls==1&&V.Genus==2&&B.Vertices.size()==20&&B.Edges.size()==30&&B.Coedges.size()==60&&B.Loops.size()==16&&B.Faces.size()==12;int Planes=0,Rolls=0,One=0,OneHalf=0,Annular=0,Circles=0,Located=0;for(auto&F:B.Faces){auto&S=F.Surface;if(S.Classification==SurfaceClassification::Plane){++Planes;Annular+=F.Loops.size()==3;}if(S.Classification==SurfaceClassification::Cylinder&&S.Rational()){if(std::fabs(S.RadiusMajor-2)<1e-9)++Rolls;if(std::fabs(S.RadiusMajor-1)<1e-9){++One;Located+=S.Origin.Distance({0,5,4})<1e-8;}if(std::fabs(S.RadiusMajor-1.5)<1e-9){++OneHalf;Located+=S.Origin.Distance({0,11,8})<1e-8;}}}for(auto&E:B.Edges)Circles+=E.Closed()&&E.Curve.Classification==CurveClassification::Circle&&E.Curve.Rational();Q.Supports=Planes==6&&Rolls==4&&One==1&&OneHalf==1;Q.Caps=Annular==2&&Circles==4;Q.Locations=Located==2;return Q;}
double Exact(){return 20*(16*12-4*4*(1-ScalarCriteria::Pi/4)-ScalarCriteria::Pi*(1+2.25));}
}
int main(){VerificationPanel P("SolidArc · Phase 32j · Twin-Bore Rounded-Prism Verification");auto S=Fixture();auto E=Rails(S.Payload);auto Source=S.Payload.Validate();P.Section("Exact two-bore reconstruction");P.Expect("The source is canonical V12/E18/C36/L12/F8 genus-two topology",S&&Source.Solid()&&Source.Hulls==1&&Source.Genus==2&&S.Payload.Vertices.size()==12&&S.Payload.Edges.size()==18&&S.Payload.Coedges.size()==36&&S.Payload.Loops.size()==12&&S.Payload.Faces.size()==8);P.Expect("Exactly four outer axial rails remain selectable",E.size()==4);int Applied=-1;auto R=BlendSolver::FilletEdges(S.Payload,E,2,&Applied);P.Expect("Two safe bores commit with the complete four-roll family",R&&Applied==4);auto Q=R?Inspect(R.Payload):Inspection{};P.Expect("The result reaches V20/E30/C60/L16/F12 genus-two topology",Q.Topology);P.Expect("Six planes, four rolls, and both rational bore cylinders remain",Q.Supports);P.Expect("Both end caps retain two exact circular inner loops",Q.Caps);P.Expect("Both distinct bore axes retain their original offsets",Q.Locations);P.Within("Twin-bore rounded-prism volume follows the exact area extrusion",R?std::fabs(R.Payload.Validate().Volume-Exact()):1e9,0.5);P.Expect("Outer bounds and source topology remain unchanged",R&&R.Payload.Bounds().Low.Distance(S.Payload.Bounds().Low)<1e-9&&R.Payload.Bounds().High.Distance(S.Payload.Bounds().High)<1e-9&&S.Payload.Edges.size()==18);
P.Section("Pairing, clearance, transforms, and bounded refusal");std::vector<int>Reverse{E[2],E[0],E[3],E[1],E[2]};int Reordered=-1;auto RR=BlendSolver::FilletEdges(S.Payload,Reverse,2,&Reordered);P.Expect("Repeated reordered rail seeds deduplicate deterministically",RR&&Reordered==4);P.Within("Rail seed order preserves twin-bore volume",R&&RR?std::fabs(R.Payload.Validate().Volume-RR.Payload.Validate().Volume):1e9,1e-9);auto Swapped=Fixture({{11,8,1.5},{5,4,1}});int SwapApplied=-1;auto SwapResult=BlendSolver::FilletEdges(Swapped.Payload,Rails(Swapped.Payload),2,&SwapApplied);P.Expect("Reversed profile-loop order pairs both rims geometrically",SwapResult&&SwapApplied==4&&Inspect(SwapResult.Payload).Topology);auto Near=Fixture({{1.8,1.8,1},{10,7,1}});int NearApplied=-1;auto NearResult=BlendSolver::FilletEdges(Near.Payload,Rails(Near.Payload),2,&NearApplied);P.Expect("Two separated bores may include one safe corner-adjacent bore",NearResult&&NearApplied==4&&NearResult.Payload.Validate().Genus==2);auto Clash=Fixture({{6,6,2},{9.5,6,2}});int Refused=99;auto ClashResult=BlendSolver::FilletEdges(Clash.Payload,Rails(Clash.Payload),2,&Refused);P.Expect("Intersecting bore disks refuse with no inter-hole ligament",!ClashResult&&Refused==0&&std::string(ClashResult.Denial.Detail)=="rounded-prism holes consume the inter-hole ligament");auto Wall=Fixture({{1.4,6,1.5},{11,8,1}});Refused=99;auto WallResult=BlendSolver::FilletEdges(Wall.Payload,Rails(Wall.Payload),2,&Refused);P.Expect("Either bore crossing the outer wall refuses the transaction",!WallResult&&Refused==0);auto Nine=Fixture({{4,3,.5},{4,6,.5},{4,9,.5},{8,3,.5},{8,6,.5},{8,9,.5},{12,3,.5},{12,6,.5},{12,9,.5}});Refused=99;auto NineResult=BlendSolver::FilletEdges(Nine.Payload,Rails(Nine.Payload),2,&Refused);P.Expect("Nine bores remain outside the bounded classifier",Nine&&Nine.Payload.Validate().Genus==9&&!NineResult&&Refused==0);Mat4 M=Mat4::Translation({3,-5,6})*Mat4::Rotation({2,1,4},.57);BrepBody T=S.Payload.Transformed(M);int TA=-1;auto TR=BlendSolver::FilletEdges(T,E,2,&TA);P.Expect("Rigid transforms preserve geometric two-rim pairing",TR&&TA==4&&TR.Payload.Validate().Genus==2);P.Within("Rigid transforms preserve twin-bore volume",R&&TR?std::fabs(R.Payload.Validate().Volume-TR.Payload.Validate().Volume):1e9,.5);
P.Section("Console and proof");
#ifndef SOLIDARC_PROOF_FOLDER
#error proof folder required
#endif
ConsoleHost H(SOLIDARC_PROOF_FOLDER,1280,800);auto&F=H.Document().AddBody("TwinBore",S.Payload);F.Matcap=6;std::string List;for(int I:E){if(!List.empty())List+=",";List+=std::to_string(I);}bool OK=H.Execute("fillet TwinBore 2 --edges="+List+" --name=TwinRound");auto*Output=H.Document().Find("TwinRound");P.Expect("Console fillet commits one genus-two twin-bore solid",OK&&Output&&Output->Body.Validate().Genus==2);
std::filesystem::path Proof=std::filesystem::path(SOLIDARC_PROOF_FOLDER)/"Phase32j_TwinBorePrism.png";std::error_code Error;std::filesystem::remove(Proof,Error);ConsoleHost V(SOLIDARC_PROOF_FOLDER,1280,800);auto Reset=[&](){return V.Execute("reset")&&V.Execute("gizmo off");};auto Add=[&](const char*N,BrepBody B,uint8_t C){auto&G=V.Document().AddBody(N,std::move(B));G.Matcap=C;return true;};bool Rendered=Reset()&&Add("TwinSharp",S.Payload.Transformed(Mat4::Translation({-24,0,0})),6)&&Add("TwinRound",R.Payload.Transformed(Mat4::Translation({8,0,0})),3)&&V.Execute("view iso")&&V.Execute("view fit")&&V.Execute("render sheet 0")&&Reset()&&Add("TwinEnd",R.Payload,3)&&V.Execute("view right")&&V.Execute("view fit")&&V.Execute("render sheet 1")&&Reset()&&Add("CornerPair",NearResult.Payload,2)&&V.Execute("view right")&&V.Execute("view fit")&&V.Execute("render sheet 2")&&Reset()&&Add("TwinTilt",TR.Payload,5)&&V.Execute("view iso")&&V.Execute("view fit")&&V.Execute("render sheet 3")&&V.Execute("render sheet finalize Phase32j_TwinBorePrism");P.Expect("C++ twin-bore proof commands complete",Rendered);P.Expect("C++ twin-bore proof is written",std::filesystem::exists(Proof)&&std::filesystem::file_size(Proof,Error)>100000);return P.Conclude();}
