/**
 * Couture Dress Presets, Debug Render Channels, Colour Palettes, and Control Definitions
 * for the Frontier Experimental WebGPU Cloth & Dress Simulator.
 */

export const DEBUG_CHANNELS = [
  { id: 0, label: "Physically shaded fabric" },
  { id: 1, label: "Warp / weft strain heatmap" },
  { id: 2, label: "2D pattern panels & seams" },
  { id: 3, label: "Procedural weave normals" },
  { id: 4, label: "Cloth velocity vectors" },
  { id: 5, label: "Avatar SDF collision field" },
];

export const COLOR_PALETTES = [
  { id: 0, label: "Emerald charmeuse", primary: [0.09, 0.42, 0.31], sheen: [0.55, 0.92, 0.76], trim: [0.88, 0.76, 0.48] },
  { id: 1, label: "Champagne gold satin", primary: [0.76, 0.66, 0.54], sheen: [0.98, 0.92, 0.80], trim: [0.94, 0.82, 0.56] },
  { id: 2, label: "Crimson opera velvet", primary: [0.46, 0.06, 0.12], sheen: [0.92, 0.32, 0.40], trim: [0.85, 0.68, 0.38] },
  { id: 3, label: "Midnight sapphire", primary: [0.08, 0.16, 0.38], sheen: [0.48, 0.68, 0.98], trim: [0.78, 0.84, 0.94] },
  { id: 4, label: "Rose quartz organza", primary: [0.72, 0.42, 0.48], sheen: [0.98, 0.78, 0.84], trim: [0.92, 0.78, 0.72] },
  { id: 5, label: "Obsidian atelier noir", primary: [0.11, 0.11, 0.13], sheen: [0.52, 0.54, 0.60], trim: [0.86, 0.74, 0.48] },
  { id: 6, label: "Wisteria silk chiffon", primary: [0.44, 0.36, 0.62], sheen: [0.82, 0.74, 0.98], trim: [0.88, 0.84, 0.94] },
  { id: 7, label: "Ivory bridal brocade", primary: [0.86, 0.84, 0.79], sheen: [1.00, 0.98, 0.94], trim: [0.90, 0.78, 0.52] },
];

export const AVATAR_FINISHES = [
  { id: 0, label: "Warm porcelain mannequin" },
  { id: 1, label: "Sculpted bronze atelier" },
  { id: 2, label: "Charcoal studio matte" },
  { id: 3, label: "Alabaster satin form" },
];

export const DEFAULT_PARAMS = {
  // Garment pattern & tailoring
  garmentEnabled: true,
  dressStyle: 0,
  skirtLength: 0.92,
  skirtFlare: 0.62,
  waistCinch: 0.84,
  necklineDepth: 0.14,
  strapWidth: 0.065,
  sleeveDrape: 0.12,
  pleatCount: 16,
  pleatDepth: 0.018,
  asymmetry: 0.0,

  // WebGPU XPBD Solver & Physics
  gridResolution: 56,
  substeps: 12,
  stretchCompliance: 0.006,
  shearCompliance: 0.018,
  bendStiffness: 0.42,
  gravity: 9.81,
  damping: 0.22,
  clothThickness: 0.012,
  bodyFriction: 0.28,
  windEnabled: true,
  windSpeed: 1.65,
  windDirection: 28,
  windTurbulence: 0.85,
  timeScale: 1.0,
  paused: false,

  // Human Avatar Collider
  avatarVisible: true,
  avatarPose: 0,
  avatarMotionSpeed: 1.0,
  avatarFinish: 0,

  // Procedural Fabric & Shading
  colorPalette: 0,
  weaveType: 0,
  weaveScale: 28,
  weaveBump: 0.45,
  sheenIntensity: 1.35,
  fabricRoughness: 0.28,
  hemTrim: 0.55,
  subsurfaceScatter: 0.65,
  sunIntensity: 2.6,
  sunElevation: 44,
  sunAzimuth: 36,
  ambientIntensity: 0.75,
  exposure: 1.15,
  renderScale: 1.0,
  renderChannel: 0,

  // Viewport Overlays & Interaction
  showWireframe: false,
  showSeamLines: true,
  showBoundingBox: false,
  showFloorGrid: true,
  showAtlasMinimap: false,
  autoTurntable: false,
  interactionMode: "orbit",
};

export const CONTROL_GROUPS = [
  {
    title: "Pattern & Silhouette",
    controls: [
      { key: "garmentEnabled", label: "Enable dress garment", type: "toggle" },
      {
        key: "dressStyle",
        label: "Dress silhouette",
        type: "select",
        options: [
          { id: 0, label: "Bias-cut evening gown" },
          { id: 1, label: "Sunburst pleated midi" },
          { id: 2, label: "Princess couture ballgown" },
          { id: 3, label: "Satin cocktail slip" },
          { id: 4, label: "Mermaid trumpet gown" },
          { id: 5, label: "Grecian chiffon column" },
          { id: 6, label: "Asymmetric wrap dress" },
          { id: 7, label: "Velvet opera gown" },
        ],
      },
      { key: "skirtLength", label: "Skirt length", type: "range", min: 0.35, max: 1.02, step: 0.01 },
      { key: "skirtFlare", label: "Skirt flare", type: "range", min: 0.10, max: 1.35, step: 0.01 },
      { key: "waistCinch", label: "Waist cinch", type: "range", min: 0.0, max: 1.0, step: 0.01 },
      { key: "necklineDepth", label: "Neckline drop", type: "range", min: 0.03, max: 0.24, step: 0.005 },
      { key: "strapWidth", label: "Shoulder strap width", type: "range", min: 0.02, max: 0.14, step: 0.005 },
      { key: "sleeveDrape", label: "Shoulder cape drape", type: "range", min: 0.0, max: 0.40, step: 0.01 },
      { key: "pleatCount", label: "Radial pleat count", type: "range", min: 0, max: 36, step: 2 },
      { key: "pleatDepth", label: "Pleat crease depth", type: "range", min: 0.0, max: 0.045, step: 0.001 },
      { key: "asymmetry", label: "Hemline asymmetry", type: "range", min: -0.60, max: 0.60, step: 0.02 },
    ],
  },
  {
    title: "Human Avatar & Pose",
    controls: [
      { key: "avatarVisible", label: "Show human mannequin", type: "toggle" },
      {
        key: "avatarPose",
        label: "Character motion",
        type: "select",
        options: [
          { id: 0, label: "Studio contrapposto" },
          { id: 1, label: "Runway catwalk stride" },
          { id: 2, label: "Couture 360° twirl" },
          { id: 3, label: "Gentle breeze sway" },
        ],
      },
      { key: "avatarMotionSpeed", label: "Motion tempo", type: "range", min: 0.2, max: 2.5, step: 0.05 },
      {
        key: "avatarFinish",
        label: "Mannequin surface",
        type: "select",
        options: AVATAR_FINISHES,
      },
      { key: "clothThickness", label: "Collision offset", type: "range", min: 0.004, max: 0.028, step: 0.001 },
      { key: "bodyFriction", label: "Skin / cloth friction", type: "range", min: 0.0, max: 0.9, step: 0.02 },
    ],
  },
  {
    title: "XPBD Solver & Wind",
    controls: [
      { key: "gridResolution", label: "Mesh circumference", type: "range", min: 32, max: 80, step: 4 },
      { key: "substeps", label: "XPBD substeps", type: "range", min: 4, max: 20, step: 1 },
      { key: "stretchCompliance", label: "Warp / weft stretch", type: "range", min: 0.0, max: 0.08, step: 0.001 },
      { key: "shearCompliance", label: "Bias shear drape", type: "range", min: 0.0, max: 0.15, step: 0.002 },
      { key: "bendStiffness", label: "Fold stiffness", type: "range", min: 0.05, max: 1.0, step: 0.02 },
      { key: "gravity", label: "Gravity", type: "range", min: 0.0, max: 18.0, step: 0.1 },
      { key: "damping", label: "Air damping", type: "range", min: 0.02, max: 0.85, step: 0.01 },
      { key: "timeScale", label: "Simulation speed", type: "range", min: 0.25, max: 2.0, step: 0.05 },
      { key: "windEnabled", label: "Aerodynamic wind", type: "toggle" },
      { key: "windSpeed", label: "Wind velocity", type: "range", min: 0.0, max: 8.0, step: 0.1 },
      { key: "windDirection", label: "Wind azimuth", type: "range", min: -180, max: 180, step: 5 },
      { key: "windTurbulence", label: "Gust turbulence", type: "range", min: 0.0, max: 3.0, step: 0.05 },
    ],
  },
  {
    title: "Procedural Weave & Shading",
    controls: [
      { key: "colorPalette", label: "Dye palette", type: "select", options: COLOR_PALETTES },
      {
        key: "weaveType",
        label: "Procedural weave",
        type: "select",
        options: [
          { id: 0, label: "Silk charmeuse" },
          { id: 1, label: "Satin twill" },
          { id: 2, label: "Pleated crepe" },
          { id: 3, label: "Velvet pile" },
          { id: 4, label: "Sheer organza" },
          { id: 5, label: "Sequined brocade" },
        ],
      },
      { key: "weaveScale", label: "Thread density", type: "range", min: 8, max: 64, step: 2 },
      { key: "weaveBump", label: "Micro-weave relief", type: "range", min: 0.0, max: 1.0, step: 0.02 },
      { key: "sheenIntensity", label: "Anisotropic sheen", type: "range", min: 0.0, max: 2.5, step: 0.05 },
      { key: "fabricRoughness", label: "Surface roughness", type: "range", min: 0.08, max: 0.95, step: 0.02 },
      { key: "hemTrim", label: "Metallic couture trim", type: "range", min: 0.0, max: 1.0, step: 0.05 },
      { key: "subsurfaceScatter", label: "Silk translucency", type: "range", min: 0.0, max: 1.5, step: 0.05 },
      { key: "sunIntensity", label: "Key light intensity", type: "range", min: 0.0, max: 5.0, step: 0.1 },
      { key: "sunElevation", label: "Key light elevation", type: "range", min: 5, max: 85, step: 1 },
      { key: "sunAzimuth", label: "Key light azimuth", type: "range", min: -180, max: 180, step: 5 },
      { key: "ambientIntensity", label: "Studio fill light", type: "range", min: 0.1, max: 2.0, step: 0.05 },
      { key: "exposure", label: "Exposure", type: "range", min: 0.4, max: 2.5, step: 0.05 },
      { key: "renderScale", label: "Viewport scale", type: "range", min: 0.5, max: 1.25, step: 0.05 },
      { key: "renderChannel", label: "Render channel", type: "select", options: DEBUG_CHANNELS },
      { key: "showWireframe", label: "Cloth mesh wireframe", type: "toggle" },
      { key: "showSeamLines", label: "Pattern seam stitching", type: "toggle" },
      { key: "showBoundingBox", label: "Avatar SDF capsules", type: "toggle" },
      { key: "showFloorGrid", label: "Studio runway grid", type: "toggle" },
      { key: "showAtlasMinimap", label: "2D weave & UV minimap", type: "toggle" },
    ],
  },
];

export const PRESETS = {
  emerald_evening_gown: {
    description: "Floor-length bias-cut emerald silk charmeuse evening gown with fluid drape and gold trim.",
    params: {
      dressStyle: 0,
      skirtLength: 0.94,
      skirtFlare: 0.68,
      waistCinch: 0.85,
      necklineDepth: 0.15,
      strapWidth: 0.06,
      sleeveDrape: 0.14,
      pleatCount: 14,
      pleatDepth: 0.016,
      asymmetry: 0.0,
      colorPalette: 0,
      weaveType: 0,
      weaveScale: 32,
      sheenIntensity: 1.55,
      fabricRoughness: 0.24,
      stretchCompliance: 0.005,
      shearCompliance: 0.022,
      bendStiffness: 0.35,
      windSpeed: 1.6,
      avatarPose: 0,
    },
  },
  sunburst_pleated_midi: {
    description: "High-waisted champagne knife-pleated midi dress that fans open during runway twirls.",
    triggerTwirlOnLoad: true,
    params: {
      dressStyle: 1,
      skirtLength: 0.72,
      skirtFlare: 0.78,
      waistCinch: 0.92,
      necklineDepth: 0.10,
      strapWidth: 0.075,
      sleeveDrape: 0.06,
      pleatCount: 32,
      pleatDepth: 0.034,
      asymmetry: 0.0,
      colorPalette: 1,
      weaveType: 2,
      weaveScale: 40,
      sheenIntensity: 1.25,
      fabricRoughness: 0.32,
      stretchCompliance: 0.004,
      shearCompliance: 0.012,
      bendStiffness: 0.68,
      windSpeed: 2.1,
      avatarPose: 2,
    },
  },
  couture_ballgown: {
    description: "Voluminous midnight sapphire princess-seam ballgown with structured corset and bell skirt.",
    params: {
      dressStyle: 2,
      skirtLength: 0.98,
      skirtFlare: 1.18,
      waistCinch: 0.96,
      necklineDepth: 0.16,
      strapWidth: 0.055,
      sleeveDrape: 0.18,
      pleatCount: 20,
      pleatDepth: 0.026,
      asymmetry: 0.0,
      colorPalette: 3,
      weaveType: 1,
      weaveScale: 26,
      sheenIntensity: 1.75,
      fabricRoughness: 0.22,
      stretchCompliance: 0.003,
      shearCompliance: 0.008,
      bendStiffness: 0.78,
      windSpeed: 1.4,
      avatarPose: 0,
    },
  },
  satin_cocktail_slip: {
    description: "Knee-length rose quartz bias-cut satin cocktail slip dress on a runway catwalk stride.",
    params: {
      dressStyle: 3,
      skirtLength: 0.52,
      skirtFlare: 0.38,
      waistCinch: 0.76,
      necklineDepth: 0.175,
      strapWidth: 0.035,
      sleeveDrape: 0.02,
      pleatCount: 8,
      pleatDepth: 0.008,
      asymmetry: 0.0,
      colorPalette: 4,
      weaveType: 0,
      weaveScale: 36,
      sheenIntensity: 1.85,
      fabricRoughness: 0.18,
      stretchCompliance: 0.008,
      shearCompliance: 0.032,
      bendStiffness: 0.24,
      windSpeed: 1.8,
      avatarPose: 1,
    },
  },
  mermaid_trumpet_gown: {
    description: "Sculpted crimson velvet mermaid gown fitted through the hips with a dramatic lower flare.",
    params: {
      dressStyle: 4,
      skirtLength: 0.96,
      skirtFlare: 0.95,
      waistCinch: 0.94,
      necklineDepth: 0.165,
      strapWidth: 0.06,
      sleeveDrape: 0.10,
      pleatCount: 18,
      pleatDepth: 0.022,
      asymmetry: 0.0,
      colorPalette: 2,
      weaveType: 3,
      weaveScale: 24,
      sheenIntensity: 1.95,
      fabricRoughness: 0.44,
      stretchCompliance: 0.004,
      shearCompliance: 0.014,
      bendStiffness: 0.52,
      windSpeed: 1.5,
      avatarPose: 0,
    },
  },
  grecian_chiffon_column: {
    description: "Lightweight wisteria silk chiffon column dress billowing gracefully in a studio breeze.",
    params: {
      dressStyle: 5,
      skirtLength: 0.93,
      skirtFlare: 0.46,
      waistCinch: 0.88,
      necklineDepth: 0.12,
      strapWidth: 0.09,
      sleeveDrape: 0.28,
      pleatCount: 24,
      pleatDepth: 0.020,
      asymmetry: 0.0,
      colorPalette: 6,
      weaveType: 4,
      weaveScale: 48,
      sheenIntensity: 1.15,
      fabricRoughness: 0.36,
      subsurfaceScatter: 1.15,
      stretchCompliance: 0.010,
      shearCompliance: 0.028,
      bendStiffness: 0.18,
      windSpeed: 3.4,
      windTurbulence: 1.45,
      avatarPose: 3,
    },
  },
  asymmetric_wrap_dress: {
    description: "Avant-garde obsidian atelier dress with diagonal wrap cut and high-low hemline.",
    params: {
      dressStyle: 6,
      skirtLength: 0.68,
      skirtFlare: 0.64,
      waistCinch: 0.86,
      necklineDepth: 0.15,
      strapWidth: 0.07,
      sleeveDrape: 0.16,
      pleatCount: 12,
      pleatDepth: 0.015,
      asymmetry: 0.42,
      colorPalette: 5,
      weaveType: 1,
      weaveScale: 30,
      sheenIntensity: 1.40,
      fabricRoughness: 0.26,
      stretchCompliance: 0.005,
      shearCompliance: 0.016,
      bendStiffness: 0.48,
      windSpeed: 2.2,
      avatarPose: 1,
    },
  },
  ivory_bridal_brocade: {
    description: "Regal ivory bridal gown with sequined brocade relief, wide train flare, and golden trim.",
    params: {
      dressStyle: 2,
      skirtLength: 1.00,
      skirtFlare: 1.08,
      waistCinch: 0.92,
      necklineDepth: 0.13,
      strapWidth: 0.08,
      sleeveDrape: 0.22,
      pleatCount: 16,
      pleatDepth: 0.024,
      asymmetry: -0.18,
      colorPalette: 7,
      weaveType: 5,
      weaveScale: 20,
      weaveBump: 0.72,
      sheenIntensity: 1.65,
      fabricRoughness: 0.25,
      hemTrim: 0.85,
      stretchCompliance: 0.004,
      shearCompliance: 0.010,
      bendStiffness: 0.64,
      windSpeed: 1.5,
      avatarPose: 0,
    },
  },
};
