import { chromium } from '../../../.cache/browser/node_modules/playwright-core/index.mjs';
import chromiumBinary from '../../../.cache/browser/node_modules/@sparticuz/chromium/build/index.js';
import fs from 'node:fs';
const browser=await chromium.launch({executablePath:await chromiumBinary.executablePath(),args:chromiumBinary.args,headless:true});
const page=await browser.newPage({viewport:{width:1440,height:1080},deviceScaleFactor:1});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto('http://127.0.0.1:5173');
await page.getByRole('button',{name:'Open Construct',exact:true}).click();
await page.getByRole('dialog').waitFor();
fs.mkdirSync('Exhibits/Gallery/Construct',{recursive:true});
await page.screenshot({path:'Exhibits/Gallery/Construct/Construct-menu.png'});
await page.getByRole('button',{name:'Configure Cube',exact:true}).click();
const entityName='Construct proof cube '+Date.now();
await page.getByLabel('New entity name').fill(entityName);
await page.getByLabel('Position X',{exact:true}).fill('3');
await page.getByRole('button',{name:'Create Cube',exact:true}).click();
await page.getByText(entityName+' added to native world and outliner',{exact:true}).waitFor();
await page.getByRole('button',{name:'Close Construct',exact:true}).click();
await page.getByRole('heading',{name:entityName,exact:true}).waitFor();
await page.screenshot({path:'Exhibits/Gallery/Construct/Created-native-entity.png'});
const scene=await page.evaluate(async()=>await(await fetch('/api/construct')).json());
if(scene.entities.at(-1).name!==entityName||scene.entities.at(-1).triangles!==12||scene.entities.at(-1).position[0]!==3)throw Error('Native create mismatch');
await page.reload();
await page.getByRole('button',{name:entityName,exact:true}).click();
await page.getByRole('heading',{name:entityName,exact:true}).waitFor();
await page.keyboard.press('Shift+A');
await page.getByRole('dialog').waitFor();
await page.getByLabel('Search construct catalogue').fill('torus');
if(await page.locator('.construct-tile').count()!==1)throw Error('Search failed');
await page.keyboard.press('Escape');
await page.setViewportSize({width:390,height:844});
await page.getByRole('button',{name:'Open Construct',exact:true}).click();
if(await page.locator('.construct-panel').evaluate(e=>e.scrollWidth>e.clientWidth))throw Error('Menu overflow');
await page.screenshot({path:'Exhibits/Gallery/Construct/Construct-mobile.png'});
await page.getByRole('button',{name:'Configure Cube',exact:true}).click();
const beforeFailure=await page.locator('.tree-row').count();
await page.route('**/api/construct',route=>route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:'Native worker unavailable'})}));
await page.getByRole('button',{name:'Create Cube',exact:true}).click();
await page.getByText('Native worker unavailable',{exact:true}).waitFor();
if(await page.locator('.tree-row').count()!==beforeFailure)throw Error('Failed native request created a phantom row');
if(errors.length)throw Error(errors.join('\n'));
console.log('PASS browser: open, create, native response, automatic selection, reload, shortcut, search, Escape, mobile width, failed native request creates no phantom row; no page errors.');
await browser.close();
