/* Automotive IES, rectangular area and tube emitters — distribution-first lighting controls. */
import { el, colorChip } from '../kit.js';
import { tape, stepper, pillToggle } from './controls.js';
import { typeOf } from '../world.js';
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const rgb=c=>{const n=parseInt((c||'#fff2cf').slice(1),16);return[n>>16&255,n>>8&255,n&255]};
const css=(c,a=1)=>`rgba(${c.map(Math.round).join(',')},${a})`;
const profiles=['ECE Low Beam','SAE Low Beam','High Beam','Fog Lamp','Parking Lamp','Custom .IES'];

export function advancedLightPanel(node,ctx){
 const{compact=false,setProp,register}=ctx,P=node.props,kind=node.type,ies=kind==='ieslight',area=kind==='arealight',tube=kind==='tubelight',host=el('div','mpanel advlightpanel');
 const flux=()=>P.lumens??1800,range=()=>P.range??P.distance??(area?80:24),pos=()=>P.pos||[0,2,0];
 const canvas=(cv,h)=>{const w=cv.clientWidth||290,d=Math.min(devicePixelRatio||1,2);if(cv.width!==w*d||cv.height!==h*d){cv.width=w*d;cv.height=h*d}cv.style.height=h+'px';const g=cv.getContext('2d');g.setTransform(d,0,0,d,0,0);return[g,w,h]};

 const hero=el('div','pcard mp-hero al-hero'),cv=el('canvas'),cap=el('div','mp-cap',`<div class="l"><b>${typeOf(node).label}</b><span class="mp-illum al-sub">—</span></div><div class="r">DRAG EMITTER</div>`);hero.append(cv,cap);host.append(hero);let mark=null;
 function paintHero(){const[g,w,h]=canvas(cv,compact?145:174),col=rgb(P.color),cx=w/2,cy=h*.44;g.clearRect(0,0,w,h);g.fillStyle='#040404';g.fillRect(0,0,w,h);
  if(ies){const cone=(P.cone??58)*Math.PI/360,cut=(P.cutoff??-1)*Math.PI/180;for(let y=8;y<h-25;y+=3)for(let x=4;x<w-4;x+=3){const nx=(x-cx)/(w*.47),ny=(y-cy)/(h*.42),ang=Math.atan2(ny,nx),r=Math.hypot(nx,ny),inside=Math.abs(ang-cut)<cone;let beam=inside?Math.exp(-r*r*(P.profile==='High Beam'?6:2.2)):0;if(P.profile?.includes('Low Beam')&&ny<-.04)beam*=.06;if(P.profile==='Fog Lamp')beam*=Math.exp(-ny*ny*18);if(P.profile==='Parking Lamp')beam=.18*Math.exp(-r*r*1.3);g.fillStyle=css(col,beam*.58*(P.multiplier??1));g.fillRect(x,y,3.2,3.2)}
   g.strokeStyle='rgba(255,255,255,.55)';g.beginPath();g.moveTo(cx,cy);g.lineTo(w-8,cy-Math.tan(cone-cut)*(w*.47));g.moveTo(cx,cy);g.lineTo(w-8,cy+Math.tan(cone+cut)*(w*.47));g.stroke();g.setLineDash([3,3]);g.strokeStyle='rgba(255,255,255,.25)';g.beginPath();g.moveTo(8,cy);g.lineTo(w-8,cy);g.stroke();g.setLineDash([]);g.fillStyle='rgba(255,255,255,.38)';g.font='8px ui-sans-serif';g.fillText('H–V PHOTOMETRIC PLANE',8,13);
  }else if(area){const ww=clamp((P.width??2)/20,0,1)*(w*.65)+25,hh=clamp((P.height??1)/20,0,1)*(h*.55)+14,x=cx-ww/2,y=cy-hh/2,grad=g.createRadialGradient(cx,cy,2,cx,cy,Math.max(ww,hh));grad.addColorStop(0,css(col,.95));grad.addColorStop(1,css(col,.22));g.fillStyle=grad;g.fillRect(x,y,ww,hh);g.strokeStyle='#fff';g.strokeRect(x+.5,y+.5,ww-1,hh-1);for(let i=1;i<4;i++){g.strokeStyle='rgba(255,255,255,.12)';g.beginPath();g.ellipse(cx,cy+hh/2,ww*.3*i,hh*.16*i,0,0,Math.PI*2);g.stroke()}
  }else{const len=clamp((P.length??1.5)/20,0,1)*(w*.72)+30,rad=clamp((P.radius??.04),.01,1)*12+2,x=cx-len/2;const glow=g.createLinearGradient(x,0,x+len,0);glow.addColorStop(0,css(col,.25));glow.addColorStop(.15,css(col,.95));glow.addColorStop(.85,css(col,.95));glow.addColorStop(1,css(col,.25));g.shadowColor=css(col);g.shadowBlur=22;g.fillStyle=glow;g.fillRect(x,cy-rad,len,rad*2);g.shadowBlur=0;g.strokeStyle='rgba(255,255,255,.8)';g.strokeRect(x,cy-rad,len,rad*2)}
  if(mark){g.strokeStyle='rgba(255,255,255,.4)';g.setLineDash([2,3]);g.beginPath();g.moveTo(mark.x,0);g.lineTo(mark.x,h);g.moveTo(0,mark.y);g.lineTo(w,mark.y);g.stroke();g.setLineDash([])}
  cap.querySelector('.al-sub').textContent=ies?`${P.profile} · ${(P.temperature??4300).toFixed(0)} K`:area?`${(P.width??2).toFixed(1)} × ${(P.height??1).toFixed(1)} m emitter`:`${(P.length??1.5).toFixed(2)} m luminous tube`;cap.querySelector('.r').textContent=`${flux().toFixed(0)} lm`;
 }
 const heroFrom=e=>{const r=cv.getBoundingClientRect(),x=clamp((e.clientX-r.left)/r.width,0,1),y=clamp((e.clientY-r.top)/r.height,0,1);mark={x:x*r.width,y:y*r.height};if(ies){setProp(node,'cone',+(5+x*95).toFixed(1));setProp(node,'cutoff',+(-5+y*10).toFixed(1))}else if(area){setProp(node,'width',+(.1+x*19.9).toFixed(2));setProp(node,'height',+(.1+(1-y)*19.9).toFixed(2))}else{setProp(node,'length',+(.1+x*19.9).toFixed(2));setProp(node,'radius',+(.01+(1-y)*.99).toFixed(2))}paintAll()};cv.onpointerdown=e=>{cv.setPointerCapture(e.pointerId);cv.classList.add('grabbing');heroFrom(e)};cv.onpointermove=e=>{if(cv.hasPointerCapture?.(e.pointerId))heroFrom(e)};cv.onpointerup=()=>{mark=null;cv.classList.remove('grabbing');paintHero()};

 const rail=el('div','mp-rail');const metric=k=>{const e=el('div','mp-pill',`<b class="v">—</b><span class="k">${k}</span>`);rail.append(e);return e.querySelector('.v')};const mFlux=metric('Flux'),mCd=metric('Peak cd'),mEff=metric('Efficacy'),mRange=metric('Range');host.append(rail);

 /* distribution map / profile selector */
 const dc=el('div','pcard mp-metric al-dist');dc.innerHTML=`<div class="mp-chead"><div class="l"><span class="t">${ies?'IES distribution':'Emitter geometry'}</span><span class="s">${ies?'Candela map · homologation view':'Luminous aperture · projected solid angle'}</span></div></div><div class="mp-num"><span class="i">—</span><span class="d"></span><span class="u">lm</span></div><div class="mp-k mp-target">Luminous flux <span class="v">—</span></div>`;const dw=el('div','mp-chartwrap'),dist=el('canvas');dw.append(dist);dc.append(dw);host.append(dc);
 function paintDist(){const[g,w,h]=canvas(dist,118);g.clearRect(0,0,w,h);g.fillStyle='#050505';g.fillRect(0,0,w,h);const col=rgb(P.color),cx=w/2,cy=h/2;if(ies){for(let a=-80;a<=80;a+=2){const low=P.profile?.includes('Low Beam'),peak=low?Math.exp(-Math.pow((a-8)/25,2))*(a>-2?1:.16):Math.exp(-Math.pow(a/(P.profile==='High Beam'?12:35),2));const r=8+peak*45*(P.multiplier??1),th=(a-90)*Math.PI/180;g.strokeStyle=css(col,.18+peak*.65);g.beginPath();g.moveTo(cx,cy);g.lineTo(cx+Math.cos(th)*r,cy+Math.sin(th)*r);g.stroke()}g.strokeStyle='rgba(255,255,255,.15)';[15,30,45].forEach(r=>{g.beginPath();g.arc(cx,cy,r,0,Math.PI*2);g.stroke()});g.fillStyle='rgba(255,255,255,.3)';g.font='8px ui-sans-serif';g.fillText('LEFT',6,cy);g.textAlign='right';g.fillText('RIGHT',w-6,cy)}else{const ar=area?(P.width??2)/(P.height??1):(P.length??1.5)/Math.max(.02,(P.radius??.04)*2);g.fillStyle=css(col,.5);g.fillRect(cx-clamp(ar,1,12)*8,cy-9,clamp(ar,1,12)*16,18);g.strokeStyle='#fff';g.strokeRect(cx-clamp(ar,1,12)*8,cy-9,clamp(ar,1,12)*16,18);g.fillStyle='rgba(255,255,255,.3)';g.font='8px ui-sans-serif';g.textAlign='center';g.fillText(`${ar.toFixed(1)} : 1 ASPECT`,cx,h-7)}}
 if(ies){const profilesEl=el('div','mp-tags al-profiles');profiles.forEach(name=>{const b=el('button',`mp-tag${P.profile===name?' on':''}`,name.toUpperCase());b.onclick=()=>{setProp(node,'profile',name);paintAll()};profilesEl.append(b)});dc.append(profilesEl)}

 /* photometric output */
 const oc=el('div','pcard mp-light al-output');oc.innerHTML=`<div class="mp-chead"><div class="l"><span class="t">Photometric output</span><span class="s">Calibrated source values</span></div></div>`;const ob=el('div','pbody');oc.append(ob);
 const fluxTape=tape({label:'Luminous flux',min:0,max:ies?8000:area?20000:12000,value:flux(),dec:0,step:50,unit:'lm',marks:[{t:0,l:'OFF'},{t:ies?.206:area?.12:.15,l:ies?'ECE 1 650':'NOMINAL'},{t:1,l:'MAX'}],onInput:v=>{setProp(node,'lumens',Math.round(v));paintAll()}});ob.append(fluxTape);let controls=[];
 if(ies){controls=[tape({label:'Profile multiplier',min:0,max:4,value:P.multiplier,dec:2,step:.05,unit:'×',marks:[{t:0,l:'OFF'},{t:.25,l:'1×'},{t:1,l:'4×'}],onInput:v=>{setProp(node,'multiplier',v);paintAll()}}),tape({label:'Photometric range',min:1,max:250,value:P.range,dec:0,step:1,unit:'m',marks:[{t:0,l:'1 m'},{t:.48,l:'120 m'},{t:1,l:'250 m'}],onInput:v=>{setProp(node,'range',Math.round(v));paintAll()}}),tape({label:'Field angle',min:5,max:100,value:P.cone,dec:1,step:.5,unit:'°',marks:[{t:0,l:'5°'},{t:.558,l:'58°'},{t:1,l:'100°'}],onInput:v=>{setProp(node,'cone',v);paintAll()}}),tape({label:'Cut-off pitch',min:-5,max:5,value:P.cutoff,dec:1,step:.1,unit:'°',marks:[{t:0,l:'−5°'},{t:.4,l:'ECE −1°'},{t:1,l:'+5°'}],onInput:v=>{setProp(node,'cutoff',v);paintAll()}})]}else if(area){controls=[tape({label:'Width',min:.1,max:20,value:P.width,dec:2,step:.1,unit:'m',onInput:v=>{setProp(node,'width',v);paintAll()}}),tape({label:'Height',min:.1,max:20,value:P.height,dec:2,step:.1,unit:'m',onInput:v=>{setProp(node,'height',v);paintAll()}}),tape({label:'Beam spread',min:1,max:180,value:P.spread,dec:0,step:1,unit:'°',marks:[{t:0,l:'1°'},{t:.665,l:'120°'},{t:1,l:'180°'}],onInput:v=>{setProp(node,'spread',Math.round(v));paintAll()}})]}else{controls=[tape({label:'Length',min:.1,max:20,value:P.length,dec:2,step:.1,unit:'m',onInput:v=>{setProp(node,'length',v);paintAll()}}),tape({label:'Tube radius',min:.01,max:1,value:P.radius,dec:2,step:.01,unit:'m',onInput:v=>{setProp(node,'radius',v);paintAll()}}),tape({label:'Reach',min:1,max:120,value:P.distance,dec:0,step:1,unit:'m',onInput:v=>{setProp(node,'distance',Math.round(v));paintAll()}})]}ob.append(...controls);
 const temp=tape({label:'Colour temperature',min:1800,max:12000,value:P.temperature??(area?3200:5600),dec:0,step:100,unit:'K',marks:[{t:0,l:'1800 K'},{t:.245,l:'4300 K'},{t:1,l:'12000 K'}],onInput:v=>{setProp(node,'temperature',Math.round(v));paintAll()}});if(!area)ob.append(temp);const ch=el('div','mp-subhead','<span class="k">emission colour</span>'),chip=colorChip(P.color,v=>{setProp(node,'color',v);paintAll()});ch.append(chip);ob.append(ch);
 const tags=el('div','mp-tags'),shadow=pillToggle('CAST SHADOWS',!!P.shadows,v=>{setProp(node,'shadows',v);paintAll()}),shape=pillToggle(ies?'DRAW DISTRIBUTION':'DRAW EMITTER',ies?P.showDistribution!==false:P.showShape!==false,v=>{setProp(node,ies?'showDistribution':'showShape',v);paintAll()});tags.append(shadow,shape);if(area)tags.append(pillToggle('TWO SIDED',!!P.twoSided,v=>{setProp(node,'twoSided',v);paintAll()}));ob.append(tags);host.append(oc);oc.querySelector('.mp-chead .l').onclick=()=>oc.classList.toggle('shut');

 /* vectors */
 const pc=el('div','pcard mp-light al-place');pc.innerHTML=`<div class="mp-chead"><div class="l"><span class="t">Mounting</span><span class="s">World transform · optical axis</span></div></div>`;const pb=el('div','pbody'),vecs=[];pc.append(pb);
 const addVec=(label,key,get)=>{const h=el('div','mp-subhead',`<span class="k">${label}</span>`),row=el('div','al-steppers');['X','Y','Z'].forEach((k,i)=>{const x=el('div','al-axis',`<span>${k}</span>`),s=stepper({value:get()[i],min:-999,max:999,dec:2,step:.05,unit:i===0?'m':'',onInput:v=>{const a=[...get()];a[i]=v;setProp(node,key,a);paintAll()}});x.append(s);x._step=s;row.append(x)});pb.append(h,row);vecs.push([row,get])};addVec('position','pos',pos);if(!tube)addVec('target','target',()=>P.target||[0,0,0]);else addVec('rotation','rot',()=>P.rot||[0,0,0]);host.append(pc);pc.querySelector('.mp-chead .l').onclick=()=>pc.classList.toggle('shut');

 function paintAll(){paintHero();paintDist();const f=flux(),peak=ies?f*(P.multiplier??1)*1.8:f/(area?Math.max(.1,(P.width??2)*(P.height??1)):Math.max(.1,(P.length??1.5)))*.45;mFlux.innerHTML=`${f.toFixed(0)}<em>lm</em>`;mCd.innerHTML=`${peak.toFixed(0)}<em>cd</em>`;mEff.textContent=Math.min(160,70+(P.temperature??4300)/100).toFixed(0);mRange.innerHTML=`${range().toFixed(0)}<em>m</em>`;dc.querySelector('.mp-num .i').textContent=Math.floor(f);dc.querySelector('.mp-num .d').textContent='';dc.querySelector('.mp-target .v').textContent=ies?`${P.profile} · ${(P.multiplier??1).toFixed(2)}×`:area?`${(P.width??2).toFixed(2)} × ${(P.height??1).toFixed(2)} m aperture`:`${(P.length??1.5).toFixed(2)} m line source`;fluxTape._set(f);controls.forEach((t,i)=>t._set(ies?[P.multiplier,P.range,P.cone,P.cutoff][i]:area?[P.width,P.height,P.spread][i]:[P.length,P.radius,P.distance][i]));if(!area)temp._set(P.temperature);chip._set?.(P.color);shadow._set(!!P.shadows);shape._set(ies?P.showDistribution!==false:P.showShape!==false);vecs.forEach(([r,get])=>[...r.children].forEach((x,i)=>x._step._set(get()[i])));if(ies)[...dc.querySelectorAll('.al-profiles .mp-tag')].forEach((b,i)=>b.classList.toggle('on',profiles[i]===P.profile))}
 register?.(paintAll);const ro=new ResizeObserver(()=>{paintHero();paintDist();[fluxTape,...controls,...(!area?[temp]:[])].forEach(t=>t._paint?.())});ro.observe(host);host._dispose=()=>ro.disconnect();requestAnimationFrame(paintAll);paintAll();return host;
}
