/* Point and spot light photometric instruments. Distribution, falloff and aim are the controls. */
import { el, colorChip } from '../kit.js';
import { tape, stepper, pillToggle } from './controls.js';
import { typeOf } from '../world.js';

const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const rgb=c=>{const n=parseInt((c||'#ffd9a0').slice(1),16);return[n>>16&255,n>>8&255,n&255]};
const css=(c,a=1)=>`rgba(${c.map(Math.round).join(',')},${a})`;
const luxAt=(I,d,decay=2)=>I/Math.pow(Math.max(1,d),decay);

export function lightPanel(node,ctx){
  const{compact=false,setProp,register}=ctx,P=node.props,spot=node.type==='spotlight',host=el('div','mpanel lightpanel');
  const I=()=>P.intensity??(spot?62:14),R=()=>P.distance??26,ANG=()=>P.angle??26,SOFT=()=>P.penumbra??.42,DEC=()=>P.decay??2,pos=()=>P.pos||[0,2,0],target=()=>P.target||[0,0,0];
  const canvas=(cv,h)=>{const w=cv.clientWidth||290,d=Math.min(devicePixelRatio||1,2);if(cv.width!==w*d||cv.height!==h*d){cv.width=w*d;cv.height=h*d}cv.style.height=h+'px';const g=cv.getContext('2d');g.setTransform(d,0,0,d,0,0);return[g,w,h]};

  /* photometric hero */
  const hero=el('div','pcard mp-hero li-hero'),cv=el('canvas');cv.title=spot?'Drag across for cone angle; vertically for intensity':'Drag across for reach; vertically for intensity';const cap=el('div','mp-cap',`<div class="l"><b>${typeOf(node).label}</b><span class="mp-illum li-sub">PHOTOMETRIC DISTRIBUTION</span></div><div class="r">—</div>`);hero.append(cv,cap);host.append(hero);let mark=null;
  function paintHero(){const[g,w,h]=canvas(cv,compact?145:172),c=rgb(P.color),cx=spot?w*.22:w/2,cy=spot?h*.5:h*.47;g.clearRect(0,0,w,h);g.fillStyle='#050505';g.fillRect(0,0,w,h);
    if(spot){const len=w*.65,a=ANG()*Math.PI/360,top=cy-Math.tan(a)*len,bot=cy+Math.tan(a)*len,grad=g.createLinearGradient(cx,0,w,0);grad.addColorStop(0,css(c,.65));grad.addColorStop(1,css(c,.03));g.fillStyle=grad;g.beginPath();g.moveTo(cx,cy);g.lineTo(w-10,top);g.quadraticCurveTo(w-3,cy,w-10,bot);g.closePath();g.fill();
      const inner=a*(1-SOFT());g.strokeStyle='rgba(255,255,255,.28)';g.setLineDash([3,3]);g.beginPath();g.moveTo(cx,cy);g.lineTo(w-10,cy-Math.tan(inner)*len);g.moveTo(cx,cy);g.lineTo(w-10,cy+Math.tan(inner)*len);g.stroke();g.setLineDash([]);
      g.strokeStyle='rgba(255,255,255,.65)';g.beginPath();g.moveTo(cx,cy);g.lineTo(w-10,top);g.moveTo(cx,cy);g.lineTo(w-10,bot);g.stroke();
    }else{for(let r=70;r>4;r-=3){const d=r/70*R(),a=clamp(luxAt(I(),d,DEC())/Math.max(1,I()),0,1)*.35;g.fillStyle=css(c,a);g.beginPath();g.arc(cx,cy,r,0,Math.PI*2);g.fill()}[.25,.5,.75,1].forEach(f=>{g.strokeStyle='rgba(255,255,255,.11)';g.beginPath();g.arc(cx,cy,70*f,0,Math.PI*2);g.stroke();if(f===.5||f===1){g.fillStyle='rgba(255,255,255,.3)';g.font='8px ui-sans-serif';g.fillText(`${Math.round(R()*f)} m`,cx+70*f+3,cy-4)}})}
    const glow=g.createRadialGradient(cx,cy,0,cx,cy,16);glow.addColorStop(0,'rgba(255,255,255,.98)');glow.addColorStop(.25,css(c,.9));glow.addColorStop(1,css(c,0));g.fillStyle=glow;g.beginPath();g.arc(cx,cy,16,0,Math.PI*2);g.fill();
    g.font='8px ui-sans-serif,system-ui';g.fillStyle='rgba(255,255,255,.32)';g.textAlign='left';g.fillText(spot?'0° AXIS':'ISOTROPIC 360°',8,13);g.textAlign='right';g.fillText(`${I().toFixed(spot?0:1)} cd`,w-8,13);
    if(mark){g.strokeStyle='rgba(255,255,255,.45)';g.setLineDash([2,3]);g.beginPath();g.moveTo(mark.x,0);g.lineTo(mark.x,h);g.moveTo(0,mark.y);g.lineTo(w,mark.y);g.stroke();g.setLineDash([])}cap.querySelector('.r').textContent=spot?`${ANG().toFixed(1)}° cone`:`${R().toFixed(0)} m reach`;
  }
  const heroFrom=e=>{const r=cv.getBoundingClientRect(),x=clamp((e.clientX-r.left)/r.width,0,1),y=clamp((e.clientY-r.top)/r.height,0,1);mark={x:x*r.width,y:y*r.height};if(spot)setProp(node,'angle',+(2+x*78).toFixed(1));else setProp(node,'distance',Math.round(1+x*119));setProp(node,'intensity',+((1-y)*(spot?200:60)).toFixed(spot?0:1));paintAll()};cv.onpointerdown=e=>{cv.setPointerCapture(e.pointerId);cv.classList.add('grabbing');heroFrom(e)};cv.onpointermove=e=>{if(cv.hasPointerCapture?.(e.pointerId))heroFrom(e)};cv.onpointerup=()=>{mark=null;cv.classList.remove('grabbing');paintHero()};

  const rail=el('div','mp-rail');const metric=k=>{const e=el('div','mp-pill',`<b class="v">—</b><span class="k">${k}</span>`);rail.append(e);return e.querySelector('.v')};const rI=metric('Intensity'),rOne=metric('At 1 m'),rTen=metric('At 10 m'),rShape=metric(spot?'Cone':'Decay');host.append(rail);
  const duo=el('div','mp-duo');const stat=(label)=>{const e=el('div','pcard mp-stat',`<span class="i">●</span><span class="l">${label}</span><b class="n">—</b>`);duo.append(e);return e};const exposure=stat('Exposure at 5 m'),diameter=stat(spot?'Pool at 5 m':'Reach limit');host.append(duo);

  /* photometry curve */
  const pc=el('div','pcard mp-metric li-photo');pc.innerHTML=`<div class="mp-chead"><div class="l"><span class="t">Photometry</span><span class="s">Illuminance over distance</span></div></div><div class="mp-num"><span class="i">—</span><span class="d"></span><span class="u">lx</span></div><div class="mp-k mp-target">At five metres <span class="v">inverse power law</span></div>`;const pw=el('div','mp-chartwrap'),curve=el('canvas');pw.append(curve);pc.append(pw);host.append(pc);
  function paintCurve(){const[g,w,h]=canvas(curve,112);g.clearRect(0,0,w,h);const L=8,Rr=31,T=8,B=17,max=Math.max(1,I()),px=d=>L+d/Math.max(spot?30:R(),10)*(w-L-Rr),py=e=>T+(1-clamp(Math.log10(e+.01)/Math.log10(max+.01),0,1))*(h-T-B);[.25,.5,.75,1].forEach(f=>{const y=T+(1-f)*(h-T-B);g.strokeStyle='rgba(255,255,255,.07)';g.setLineDash([2,5]);g.beginPath();g.moveTo(L,y);g.lineTo(w-Rr,y);g.stroke();g.setLineDash([])});const maxD=spot?30:R(),col=rgb(P.color);g.beginPath();g.moveTo(px(1),py(0));for(let d=1;d<=maxD;d+=.3)g.lineTo(px(d),py(luxAt(I(),d,spot?2:DEC())));g.lineTo(px(maxD),h-B);g.closePath();g.fillStyle=css(col,.22);g.fill();g.beginPath();for(let d=1;d<=maxD;d+=.3)d===1?g.moveTo(px(d),py(luxAt(I(),d,spot?2:DEC()))):g.lineTo(px(d),py(luxAt(I(),d,spot?2:DEC())));g.strokeStyle='rgba(255,255,255,.9)';g.stroke();g.font='8px ui-sans-serif';g.fillStyle='rgba(255,255,255,.28)';[1,5,10,maxD].forEach((d,i)=>{g.textAlign=i===0?'left':i===3?'right':'center';g.fillText(d===maxD?`${d.toFixed(0)} m`:d,px(d),h-3)});const y=py(luxAt(I(),5,spot?2:DEC()));g.fillStyle='#fff';g.beginPath();g.arc(px(5),y,3,0,Math.PI*2);g.fill()}

  /* output controls */
  const oc=el('div','pcard mp-light li-output');oc.innerHTML=`<div class="mp-chead"><div class="l"><span class="t">Output</span><span class="s">Distribution · attenuation</span></div></div>`;const ob=el('div','pbody');oc.append(ob);
  const intensity=tape({label:'Intensity',min:0,max:spot?200:60,value:I(),dec:spot?0:1,step:spot?1:.5,unit:'cd',marks:[{t:0,l:'OFF'},{t:spot?.31:.233,l:spot?'KEY 62':'POINT 14'},{t:1,l:spot?'200 cd':'60 cd'}],onInput:v=>{setProp(node,'intensity',v);paintAll()}});ob.append(intensity);
  let shape1,shape2;if(spot){shape1=tape({label:'Cone angle',min:2,max:80,value:ANG(),dec:1,step:.5,unit:'°',marks:[{t:0,l:'PIN 2°'},{t:.308,l:'SPOT 26°'},{t:1,l:'FLOOD 80°'}],onInput:v=>{setProp(node,'angle',v);paintAll()}});shape2=tape({label:'Penumbra',min:0,max:1,value:SOFT(),dec:2,step:.01,marks:[{t:0,l:'HARD'},{t:.42,l:'SOFT .42'},{t:1,l:'FEATHER'}],onInput:v=>{setProp(node,'penumbra',v);paintAll()}})}else{shape1=tape({label:'Reach',min:1,max:120,value:R(),dec:0,step:1,unit:'m',marks:[{t:0,l:'1 m'},{t:.21,l:'26 m'},{t:1,l:'120 m'}],onInput:v=>{setProp(node,'distance',Math.round(v));paintAll()}});shape2=tape({label:'Decay exponent',min:0,max:4,value:DEC(),dec:2,step:.05,marks:[{t:0,l:'NONE'},{t:.5,l:'PHYSICAL 2'},{t:1,l:'4'}],onInput:v=>{setProp(node,'decay',v);paintAll()}})}ob.append(shape1,shape2);
  const ch=el('div','mp-subhead','<span class="k">emission colour</span>'),chip=colorChip(P.color,v=>{setProp(node,'color',v);paintAll()});ch.append(chip);ob.append(ch);const tags=el('div','mp-tags'),shadows=pillToggle('CAST SHADOWS',!!P.shadows,v=>{setProp(node,'shadows',v);paintAll()}),gizmo=pillToggle(spot?'DRAW CONE':'SHOW GLOW',spot?P.showCone!==false:P.gizmoGlow!==false,v=>{setProp(node,spot?'showCone':'gizmoGlow',v);paintAll()});tags.append(shadows,gizmo);ob.append(tags);host.append(oc);oc.querySelector('.mp-chead .l').onclick=()=>oc.classList.toggle('shut');

  /* placement and aim */
  const ac=el('div','pcard mp-light li-place');ac.innerHTML=`<div class="mp-chead"><div class="l"><span class="t">${spot?'Aim':'Placement'}</span><span class="s">World coordinates${spot?' · source to target':''}</span></div></div>`;const ab=el('div','pbody'),aim=el('div','mp-meter li-aim','<div class="hd"><span class="k">world plan · ±20 m</span></div>'),aimCv=el('canvas');aim.append(aimCv);ab.append(aim);ac.append(ab);
  const vectors=[];const addVec=(name,get,key)=>{const title=el('div','mp-subhead',`<span class="k">${name}</span>`),rows=el('div','li-steppers');['X','Y','Z'].forEach((k,i)=>{const r=el('div','li-axis',`<span>${k}</span>`),st=stepper({value:get()[i],min:-999,max:999,dec:2,step:.05,unit:'m',onInput:v=>{const a=[...get()];a[i]=v;setProp(node,key,a);paintAll()}});r.append(st);r._step=st;rows.append(r)});ab.append(title,rows);vectors.push([rows,get])};addVec('position',pos,'pos');if(spot)addVec('target',target,'target');host.append(ac);ac.querySelector('.mp-chead .l').onclick=()=>ac.classList.toggle('shut');
  function paintAim(){const[g,w,h]=canvas(aimCv,118),cx=w/2,cy=h/2,span=Math.min(w,h)-20,xy=a=>[cx+clamp(a[0]/20,-1,1)*span/2,cy+clamp(a[2]/20,-1,1)*span/2];g.clearRect(0,0,w,h);g.fillStyle='#050505';g.fillRect(0,0,w,h);for(let i=-4;i<=4;i++){g.strokeStyle=i?'rgba(255,255,255,.06)':'rgba(255,255,255,.18)';g.beginPath();g.moveTo(cx+i*span/8,10);g.lineTo(cx+i*span/8,h-10);g.moveTo(cx-span/2,cy+i*span/8);g.lineTo(cx+span/2,cy+i*span/8);g.stroke()}const a=xy(pos()),b=xy(target());if(spot){g.strokeStyle=css(rgb(P.color),.75);g.beginPath();g.moveTo(...a);g.lineTo(...b);g.stroke();g.fillStyle='#fff';g.beginPath();g.arc(...b,4,0,Math.PI*2);g.fill()}g.fillStyle=css(rgb(P.color));g.beginPath();g.arc(...a,6,0,Math.PI*2);g.fill();g.strokeStyle='#fff';g.beginPath();g.arc(...a,9,0,Math.PI*2);g.stroke()}
  const aimFrom=e=>{const r=aimCv.getBoundingClientRect(),span=Math.min(r.width,r.height)-20,x=clamp((e.clientX-r.left-r.width/2)/(span/2),-1,1)*20,z=clamp((e.clientY-r.top-r.height/2)/(span/2),-1,1)*20;const key=spot&&e.shiftKey?'target':'pos',a=[...(key==='target'?target():pos())];a[0]=+x.toFixed(2);a[2]=+z.toFixed(2);setProp(node,key,a);paintAll()};aimCv.onpointerdown=e=>{aimCv.setPointerCapture(e.pointerId);aimCv.classList.add('drag');aimFrom(e)};aimCv.onpointermove=e=>{if(aimCv.hasPointerCapture?.(e.pointerId))aimFrom(e)};aimCv.onpointerup=e=>aimCv.releasePointerCapture?.(e.pointerId);

  function paintAll(){paintHero();paintCurve();paintAim();const decay=spot?2:DEC(),e5=luxAt(I(),5,decay);rI.innerHTML=`${I().toFixed(spot?0:1)}<em>cd</em>`;rOne.innerHTML=`${I().toFixed(0)}<em>lx</em>`;rTen.innerHTML=`${luxAt(I(),10,decay).toFixed(2)}<em>lx</em>`;rShape.innerHTML=spot?`${ANG().toFixed(1)}<em>°</em>`:`${DEC().toFixed(1)}<em>n</em>`;exposure.querySelector('.n').innerHTML=`${e5.toFixed(2)}<em>lx</em>`;diameter.querySelector('.n').innerHTML=spot?`${(2*5*Math.tan(ANG()*Math.PI/360)).toFixed(1)}<em>m</em>`:`${R().toFixed(0)}<em>m</em>`;const whole=Math.floor(e5),tenth=Math.round(e5*10)%10;pc.querySelector('.mp-num .i').textContent=whole;pc.querySelector('.mp-num .d').textContent='.'+tenth;intensity._set(I());shape1._set(spot?ANG():R());shape2._set(spot?SOFT():DEC());chip._set?.(P.color);shadows._set(!!P.shadows);gizmo._set(spot?P.showCone!==false:P.gizmoGlow!==false);vectors.forEach(([rows,get])=>[...rows.children].forEach((r,i)=>r._step._set(get()[i])))}
  register?.(paintAll);const ro=new ResizeObserver(()=>{paintHero();paintCurve();paintAim();[intensity,shape1,shape2].forEach(t=>t._paint?.())});ro.observe(host);host._dispose=()=>ro.disconnect();requestAnimationFrame(paintAll);paintAll();return host;
}
