#include "CelestialSequence.h"
#include "InspectorPanel.h"
#include "ControlPanel.h"
#include "FogModel.h"
#include "CpuDraw.h"
#include "GeometricRaster/SceneStructure.h"
#include "PngWriteCounterpart.h"
#include <imgui_internal.h>
#include <memory>
#include <cstring>
#include <cstdio>
#include <limits>
#include <stdexcept>
using namespace Frontier;using namespace Frontier::ProjectZero;
static unsigned Checks=0;static void Check(bool V,const char* N){++Checks;if(!V)throw std::runtime_error(N);}
static EditorProperty& Find(EditorSheet& S,const char* N){for(auto& G:S.Groups)for(unsigned I=0;I<G.PropertyCount;++I)if(!std::strcmp(G.Properties[I].Label,N))return G.Properties[I];throw std::runtime_error(N);}
static ImGuiWindow* Window(const char* N){for(auto* W:ImGui::GetCurrentContext()->Windows)if(W->Active&&std::strstr(W->Name,N))return W;throw std::runtime_error(N);}
static void RasterPixels(){
 auto Level=std::make_unique<SceneStructure>();GeometryStructure Mesh;VertexRecord Vertices[4]{};
 const float Positions[4][3]={{-200,100,-200},{200,100,-200},{200,100,200},{-200,100,200}};
 for(int I=0;I<4;++I){Vertices[I].SpatialLocation={Positions[I][0],Positions[I][1],Positions[I][2]};Vertices[I].NormalDirection={0,-1,0};}
 const uint32_t Indices[]={0,1,2,0,2,3};Mesh.AppendVertices(Vertices,4);Mesh.AppendIndices(Indices,6);
 MaterialDescriptor Material;Material.Slabs.emplace_back();Material.Slabs[0].EmissionLuminance=1;Material.Slabs[0].BaseWeight=0;Material.Slabs[0].SpecularWeight=0;
 Level->RegisterInstance(Mesh,Matrix4x4::Identity(),Level->RegisterMaterial(Material),0);Level->Finalise();
 auto Raster=std::make_unique<VisibilityRaster>();auto C=std::make_unique<VisibilityRaster::CelestialSettings>();C->Enabled=true;C->Light.Intensity=0;
 const float Eye[]={0,0,2},Forward[]={0,1,0},Right[]={1,0,0},Up[]={0,0,1};unsigned char Pixels[8*8*4];double Lum=0;
 auto Render=[&](){Raster->AssignCelestial(*C);Check(Raster->Render(*Level,Eye,Forward,Right,Up,1,8,8,Pixels,Lum),"real CPU raster fixture renders");return Lum;};
 const double Clear=Render();Check(Clear>0,"emissive fixture has measurable radiance");
 C->Fog.HeightEnabled=true;C->Fog.HeightDensity=.02f;C->Fog.SunScatter=0;for(float& V:C->Fog.HeightColour)V=0;
 Check(Render()<Clear*.1,"height fog attenuates actual geometry pixels");C->Fog.HeightEnabled=false;Check(std::abs(Render()-Clear)<1e-9,"disabled height restores geometry pixels");
 C->Fog.AerialEnabled=true;C->Fog.AerialStart=0;C->Fog.AerialMie=1;C->Fog.AerialDensity=4;C->Medium.MieScattering=.002f;
 Check(Render()<Clear*.95,"aerial fog attenuates actual geometry pixels");C->Fog.AerialStart=2000;Check(std::abs(Render()-Clear)<1e-9,"aerial onset beyond geometry preserves pixels");
 C->Fog.AerialEnabled=false;C->LocalFog.Enabled=true;C->LocalFog.Centre[0]=0;C->LocalFog.Centre[1]=50;C->LocalFog.Centre[2]=2;for(float& V:C->LocalFog.HalfSize)V=200;C->LocalFog.Coverage=1;C->LocalFog.Density=4;
 Check(Render()<Clear,"local volumetric fog changes actual geometry pixels");C->LocalFog.Enabled=false;Check(std::abs(Render()-Clear)<1e-9,"disabled local fog restores geometry pixels");
}
int main(){
 RasterPixels();
 auto Scene=std::make_unique<CelestialSequence>();auto Sheet=std::make_unique<EditorSheet>();auto Raster=std::make_unique<VisibilityRaster>();const float Camera[]={0,0,2};Scene->Enabled=true;Scene->Clock.Animate=false;Scene->Fog.HeightEnabled=Scene->Fog.AerialEnabled=Scene->LocalFog.Enabled=true;for(auto E:{CelestialEntity::HeightFog,CelestialEntity::AtmosphericFog,CelestialEntity::LocalFog})Scene->Shown[unsigned(E)]=true;CelestialEntity Entity=CelestialEntity::HeightFog;
 auto Apply=[&](){Scene->ApplySheet(Entity,*Sheet);Scene->Tick(0,Camera,0);Scene->BuildSheet(Entity,*Sheet);};Scene->Tick(0,Camera,0);
 for(auto E:{CelestialEntity::HeightFog,CelestialEntity::AtmosphericFog,CelestialEntity::LocalFog}){Entity=E;Scene->BuildSheet(E,*Sheet);Check(Sheet->Appearance==(E==CelestialEntity::HeightFog?EditorSheetAppearance::HeightFog:E==CelestialEntity::AtmosphericFog?EditorSheetAppearance::AerialFog:EditorSheetAppearance::LocalFog),"native route for each fog scope");auto Saved=std::make_unique<EditorSheet>(*Sheet);for(auto& G:Sheet->Groups)for(unsigned I=0;I<G.PropertyCount;++I){auto& P=G.Properties[I];if(P.Category!=EditorPropertyCategory::Slider)continue;char N[48];std::snprintf(N,sizeof(N),"%s",P.Label);float V=P.Minimum+(P.Maximum-P.Minimum)*.6f;P.Figure=V;Apply();Check(std::abs(Find(*Sheet,N).Figure-V)<1e-5,"scalar round trip");Find(*Sheet,N).Figure=std::numeric_limits<float>::infinity();Apply();Check(Find(*Sheet,N).Figure==V,"nonfinite scalar rejected");Find(*Sheet,N).Figure=-100;Apply();Check(Find(*Sheet,N).Figure==Find(*Sheet,N).Minimum,"lower clamp");Find(*Sheet,N).Figure=100000;Apply();Check(Find(*Sheet,N).Figure==Find(*Sheet,N).Maximum,"upper clamp");}Scene->ApplySheet(E,*Saved);Scene->BuildSheet(E,*Sheet);}
 Find(*Sheet,"Half Size").Axes[0]=-1;float Old=Scene->LocalFog.HalfSize[1];Find(*Sheet,"Half Size").Axes[1]=std::numeric_limits<float>::quiet_NaN();Apply();Check(Scene->LocalFog.HalfSize[0]==.1f&&Scene->LocalFog.HalfSize[1]==Old,"local bounds reject invalid dimensions");Find(*Sheet,"Half Size").Axes[0]=150;Find(*Sheet,"Half Size").Axes[1]=150;Find(*Sheet,"Half Size").Axes[2]=80;Find(*Sheet,"Coverage").Figure=.8f;Find(*Sheet,"Density").Figure=1;Apply();float Move[]={70,90,120};Scene->MoveMarker(unsigned(CelestialEntity::LocalFog),Move);Scene->BuildSheet(Entity,*Sheet);Check(Find(*Sheet,"Centre").Axes[2]==120,"local marker shares authored position");VolumeMarker Markers[2];Check(Scene->CollectMarkers(Markers,2)>=1,"local fog keeps existing volume marker");
 Entity=CelestialEntity::HeightFog;Scene->BuildSheet(Entity,*Sheet);Find(*Sheet,"Density").Figure=.006f;Find(*Sheet,"Falloff Height").Figure=400;Find(*Sheet,"Colour").ColourTint[0]=std::numeric_limits<float>::quiet_NaN();float Red=Scene->Fog.HeightColour[0];Apply();Check(Scene->Fog.HeightColour[0]==Red,"nonfinite tint rejected");Find(*Sheet,"Colour").ColourTint[0]=2;Apply();Check(Scene->Fog.HeightColour[0]==1,"tint bounded to linear 0..1");Find(*Sheet,"Colour").ColourTint[0]=.62f;Apply();Scene->ApplyTo(*Raster,CelestialBudget{});const auto& C=Raster->QueryCelestial();Check(C.Fog.HeightEnabled&&C.Fog.AerialEnabled&&C.LocalFog.Enabled,"all fog scopes reach CPU settings together");Check(C.Fog.HeightDensity==Scene->Fog.HeightDensity&&C.Fog.AerialMie==Scene->Fog.AerialMie&&C.LocalFog.Coverage==Scene->LocalFog.Coverage,"real CPU staging matches authored settings");Scene->Shown[unsigned(CelestialEntity::HeightFog)]=false;Scene->ApplyTo(*Raster,CelestialBudget{});Check(!Raster->QueryCelestial().Fog.HeightEnabled&&Raster->QueryCelestial().Fog.AerialEnabled,"height visibility gate is independent");Scene->Shown[unsigned(CelestialEntity::HeightFog)]=true;
 FogSettings F;AtmosphereMedium Air;float T[3],U[3];FogModel::Transmission(F,Air,2,2,100,T);Check(T[0]==1&&T[1]==1&&T[2]==1,"disabled analytic media transparent");F.HeightEnabled=true;F.HeightDensity=.01f;FogModel::Transmission(F,Air,0,0,100,T);Check(std::abs(T[0]-std::exp(-1.f))<1e-6,"reference exp squared height law");FogModel::Transmission(F,Air,400,400,100,U);Check(U[0]>T[0],"altitude reduces fog");float Last=1;for(int I=0;I<=30;++I){FogModel::Transmission(F,Air,2,2,I*10,T);Check(T[0]<=Last+1e-6f&&T[0]>=0,"height transmission decreases with distance");Last=T[0];}FogModel::Transmission(F,Air,-1000000,-1000000,100000,T);Check(std::isfinite(T[0]),"below-datum diagnostic remains finite");
 F.HeightEnabled=false;F.AerialEnabled=true;F.AerialStart=500;F.AerialMie=0;FogModel::Transmission(F,Air,2,2,400,T);Check(T[0]==1&&T[2]==1,"aerial onset has no foreground attenuation");FogModel::Transmission(F,Air,2,2,5000,T);Check(T[2]<T[1]&&T[1]<T[0],"Rayleigh aerial extinction is spectral");F.AerialMie=1;FogModel::Transmission(F,Air,2,2,5000,U);Check(U[0]==U[1]&&U[1]==U[2],"Mie endpoint gives grey extinction");Air.MieStrength=2;FogModel::Transmission(F,Air,2,2,5000,T);Check(T[0]<U[0],"actual atmosphere strength affects aerial fog");
 float Dir[]={0,1,0},Ambient[]={.2f,.2f,.2f},RGB[]={.8f,.8f,.8f};AtmosphereLight Light;F={};F.HeightEnabled=true;FogModel::Apply(F,Air,Light,2,2,200,Dir,Ambient,RGB);Check(RGB[0]<.8f,"real analytic composite changes radiance");auto V=Scene->LocalFog;V.Coverage=1;V.Density=2;auto Dense=FogModel::LocalProbe(V,2*V.HalfSize[1]);V.Enabled=false;auto Clear=FogModel::LocalProbe(V,2*V.HalfSize[1]);Check(Dense.Transmittance<1&&Dense.Scatter[0]>0&&Dense.ShadowMarches>0,"actual local fog march attenuates and scatters");Check(Clear.Transmittance==1&&Clear.StepsTaken==0,"disabled local fog skips march");
 Scene->Medium.MieStrength=2;Entity=CelestialEntity::AtmosphericFog;Scene->BuildSheet(Entity,*Sheet);Check(Sheet->FogPreview.Mie==Scene->Medium.MieScattering*2,"editor uses actual scaled atmosphere coefficients");Entity=CelestialEntity::HeightFog;Scene->BuildSheet(Entity,*Sheet);
 ImGui::CreateContext();auto& IO=ImGui::GetIO();IO.IniFilename=nullptr;IO.DeltaTime=1.f/60;IO.BackendFlags|=ImGuiBackendFlags_RendererHasTextures|ImGuiBackendFlags_RendererHasVtxOffset;ImGui::StyleColorsDark();auto& Style=ImGui::GetStyle();Style.WindowPadding={0,0};Style.WindowRounding=0;Style.WindowBorderSize=0;Style.Colors[ImGuiCol_WindowBg]={.105f,.105f,.105f,1};Style.Colors[ImGuiCol_TitleBgActive]={.075f,.075f,.075f,1};auto Controls=std::make_unique<ControlPanel>();auto Inspector=std::make_unique<InspectorPanel>();Inspector->AssignControls(Controls.get());auto Row=std::make_unique<EditorInstance>();std::snprintf(Row->Label,sizeof(Row->Label),"Fog");Row->Category=EditorInstanceCategory::Geometry;int Width=1024,Height=1490;float Scale=1;
 auto Tick=[&](){IO.DisplaySize={float(Width),float(Height)};IO.DisplayFramebufferScale={Scale,Scale};ImGui::NewFrame();ImGui::SetNextWindowPos({0,0});ImGui::SetNextWindowSize(IO.DisplaySize);Inspector->Record(Row.get(),0,Sheet.get());Apply();ImGui::Render();FrontierProof::AcknowledgeTextures();};auto Rest=[&](){for(int I=0;I<3;++I)Tick();};auto Click=[&](ImVec2 V0){IO.AddMousePosEvent(V0.x,V0.y);Tick();IO.AddMouseButtonEvent(0,true);Tick();IO.AddMouseButtonEvent(0,false);Tick();IO.AddMousePosEvent(-100,-100);Rest();};auto Capture=[&](const char* N){int PW=int(Width*Scale),PH=int(Height*Scale);std::vector<unsigned char> Pixels(size_t(PW)*PH*3,24);for(auto* D:ImGui::GetDrawData()->CmdLists)FrontierProof::Draw(D,Pixels.data(),PW,PH,{0,0},{Scale,Scale});std::string Path=std::string("Exhibits/Gallery/FogNative/")+N+".png";Check(stbi_write_png(Path.c_str(),PW,PH,3,Pixels.data(),PW*3)!=0,"native capture");};
 Rest();Capture("Fog-Height");auto* Props=Window("##fog-properties");ImVec2 O=Props->DC.CursorStartPos;O.x+=20;O.y+=20;float Density=Scene->Fog.HeightDensity;Click({O.x+700,O.y+520});IO.AddKeyEvent(ImGuiKey_LeftArrow,true);Tick();IO.AddKeyEvent(ImGuiKey_LeftArrow,false);Tick();Check(Scene->Fog.HeightDensity==Density,"diagnostic probe never edits scene density");auto* Slider=Window("/Density_");Click({Slider->Pos.x+Slider->Size.x*.6f,Slider->Pos.y+15});Check(Scene->Fog.HeightDensity>.04f,"native height density slider changes real settings");Capture("Fog-Height-Dense");Find(*Sheet,"Density").Figure=.006f;Apply();
 Entity=CelestialEntity::AtmosphericFog;Scene->BuildSheet(Entity,*Sheet);Rest();Capture("Fog-Aerial");Slider=Window("/Mie Blend_");Click({Slider->Pos.x+Slider->Size.x*.8f,Slider->Pos.y+15});Check(Scene->Fog.AerialMie>.6f,"native aerial spectral blend input");Capture("Fog-Aerial-Mie");Entity=CelestialEntity::LocalFog;Scene->BuildSheet(Entity,*Sheet);Rest();Capture("Fog-Local");auto* Axis=Window("/Centre_");float X=Scene->LocalFog.Centre[0];IO.AddMousePosEvent(Axis->Pos.x+10,Axis->Pos.y+13);Tick();IO.AddMouseButtonEvent(0,true);Tick();IO.AddMousePosEvent(Axis->Pos.x+70,Axis->Pos.y+13);Tick();IO.AddMouseButtonEvent(0,false);Tick();Rest();Check(Scene->LocalFog.Centre[0]!=X,"native local-fog position drag");Capture("Fog-Local-Moved");Click({O.x+70,O.y+190});Check(!Scene->LocalFog.Enabled&&Scene->Fog.HeightEnabled,"local enable tile preserves global fog");Capture("Fog-Local-Disabled");Click({O.x+70,O.y+190});
 Width=480;Height=2000;Rest();Capture("Fog-Local-Narrow");Entity=CelestialEntity::HeightFog;Scene->BuildSheet(Entity,*Sheet);Rest();Capture("Fog-Height-Narrow");Width=320;Height=750;Rest();Check(Window("/Density_")->Size.x<=320,"compact density slider fits");Check(Window("##fog-properties")->ScrollMax.y>800,"narrow fog inspector scrolls");ImGui::SetScrollY(Window("##fog-properties"),900);Rest();Capture("Fog-Scrolled");Width=1024;Height=750;Scale=2;ImGui::SetScrollY(Window("##fog-properties"),0);Rest();Capture("Fog-2x");Scene->BuildSheet(CelestialEntity::Count,*Sheet);Check(Sheet->Appearance==EditorSheetAppearance::Generic&&Sheet->FogPreview.Mie==21e-6f,"sheet reuse resets optical metadata");ImGui::DestroyContext();std::printf("PASS %u checks: native height, aerial and local volumetric fog; analytic optics, real local march, CPU staging and actual raster pixels, finite inputs, pointer/keyboard controls and teardown. No GPU fog claim.\n",Checks);
}
