// EEVEE Next architectural study for WebGL2: deferred PBR, baked volume probes,
// screen-space BSDF tracing with probe fallback, temporal/spatial denoising,
// sphere-probe reflections, and light-shape rays through directional/local shadow maps.

const Root = "../../Assets/ShaderBall/ShaderBall.mesh";
const ShaderFiles = ["GBuffer.vert","GBuffer.frag","Shadow.vert","Shadow.frag","PointShadow.frag","ProbeCapture.vert","ProbeCapture.frag","Fullscreen.vert","Direct.frag","Raytrace.frag","Denoise.frag","Present.frag","ProbeDebug.vert","ProbeDebug.frag"];
const ShadowAtlasSize = 4096;
const ShadowTileSize = 2048;
const PointShadowSize = 512;
const PointLightRange = 18.0;
const CacheAddress = "EeveeProbeCache.bin";

const Canvas=document.getElementById("Canvas"),Status=document.getElementById("Status"),StatusText=document.getElementById("StatusText"),ErrorPanel=document.getElementById("ErrorPanel");
const ViewMode=document.getElementById("ViewMode"),AnimateWorld=document.getElementById("AnimateWorld"),AnimateSun=document.getElementById("AnimateSun"),ScreenTrace=document.getElementById("ScreenTrace"),VolumeProbes=document.getElementById("VolumeProbes"),LeakRejection=document.getElementById("LeakRejection"),Temporal=document.getElementById("Temporal"),SpatialReuse=document.getElementById("SpatialReuse"),Reflections=document.getElementById("Reflections"),Shadows=document.getElementById("Shadows"),SoftShadows=document.getElementById("SoftShadows"),ShadowRays=document.getElementById("ShadowRays"),ShadowRayOutput=document.getElementById("ShadowRayOutput"),ShadowSteps=document.getElementById("ShadowSteps"),ShadowStepOutput=document.getElementById("ShadowStepOutput"),SunAngle=document.getElementById("SunAngle"),SunAngleOutput=document.getElementById("SunAngleOutput"),LightRadius=document.getElementById("LightRadius"),LightRadiusOutput=document.getElementById("LightRadiusOutput"),FastGI=document.getElementById("FastGI"),Emissive=document.getElementById("Emissive"),ProbeDebug=document.getElementById("ProbeDebug"),RayCount=document.getElementById("RayCount"),RayOutput=document.getElementById("RayOutput"),TraceSteps=document.getElementById("TraceSteps"),StepOutput=document.getElementById("StepOutput"),Thickness=document.getElementById("Thickness"),ThicknessOutput=document.getElementById("ThicknessOutput"),RenderScale=document.getElementById("RenderScale"),ScaleOutput=document.getElementById("ScaleOutput"),Exposure=document.getElementById("Exposure"),ExposureOutput=document.getElementById("ExposureOutput"),PauseButton=document.getElementById("PauseButton"),ResetButton=document.getElementById("ResetButton"),RecaptureButton=document.getElementById("RecaptureButton"),GpuMetric=document.getElementById("GpuMetric"),CacheMetric=document.getElementById("CacheMetric"),CacheState=document.getElementById("CacheState"),PanelLabels=document.getElementById("PanelLabels");

const Clamp=(v,a,b)=>Math.min(b,Math.max(a,v));
const Add=(a,b)=>[a[0]+b[0],a[1]+b[1],a[2]+b[2]];
const Sub=(a,b)=>[a[0]-b[0],a[1]-b[1],a[2]-b[2]];
const Scale=(v,s)=>[v[0]*s,v[1]*s,v[2]*s];
const Dot=(a,b)=>a[0]*b[0]+a[1]*b[1]+a[2]*b[2];
const Cross=(a,b)=>[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]];
function Normalise(v){const l=Math.hypot(...v);return l>1e-8?Scale(v,1/l):[0,0,1];}
function Multiply(a,b){const r=new Float32Array(16);for(let c=0;c<4;++c)for(let row=0;row<4;++row)r[c*4+row]=a[row]*b[c*4]+a[4+row]*b[c*4+1]+a[8+row]*b[c*4+2]+a[12+row]*b[c*4+3];return r;}
function Perspective(fov,aspect,near,far){const f=1/Math.tan(fov*.5),r=new Float32Array(16);r[0]=f/aspect;r[5]=f;r[10]=(far+near)/(near-far);r[11]=-1;r[14]=2*far*near/(near-far);return r;}
function Orthographic(l,r,b,t,n,f){const m=new Float32Array(16);m[0]=2/(r-l);m[5]=2/(t-b);m[10]=-2/(f-n);m[12]=-(r+l)/(r-l);m[13]=-(t+b)/(t-b);m[14]=-(f+n)/(f-n);m[15]=1;return m;}
function ViewMatrix(eye,target,up){const z=Normalise(Sub(eye,target)),x=Normalise(Cross(up,z)),y=Cross(z,x),m=new Float32Array(16);m[0]=x[0];m[1]=y[0];m[2]=z[0];m[4]=x[1];m[5]=y[1];m[6]=z[1];m[8]=x[2];m[9]=y[2];m[10]=z[2];m[12]=-Dot(x,eye);m[13]=-Dot(y,eye);m[14]=-Dot(z,eye);m[15]=1;return m;}

async function FetchText(address){const r=await fetch(`${address}?revision=4`,{cache:"no-store"});if(!r.ok)throw new Error(`${address}: HTTP ${r.status}`);return r.text();}
async function FetchBinary(address){const r=await fetch(address,{cache:"no-store"});if(!r.ok)throw new Error(`${address}: HTTP ${r.status}`);return r.arrayBuffer();}
function DecodeShaderBall(data){const h=new DataView(data);if(h.getUint32(0,true)!==0x314d4253)throw new Error("ShaderBall is not SBM1");const vc=h.getUint32(4,true),ic=h.getUint32(8,true),source=new Float32Array(data,16,vc*8),vertices=new Float32Array(vc*8);for(let i=0;i<vc;++i){const a=i*8;vertices[a]=source[a];vertices[a+1]=source[a+1];vertices[a+2]=source[a+2];vertices[a+4]=source[a+3];vertices[a+5]=source[a+4];vertices[a+6]=source[a+5];}const io=16+vc*32;return{vertices,indices:new Uint32Array(data.slice(io,io+ic*4)),count:ic};}
function CubeGeometry(){const faces=[{n:[1,0,0],p:[[.5,-.5,-.5],[.5,.5,-.5],[.5,-.5,.5],[.5,.5,.5]]},{n:[-1,0,0],p:[[-.5,.5,-.5],[-.5,-.5,-.5],[-.5,.5,.5],[-.5,-.5,.5]]},{n:[0,1,0],p:[[-.5,.5,-.5],[-.5,.5,.5],[.5,.5,-.5],[.5,.5,.5]]},{n:[0,-1,0],p:[[.5,-.5,-.5],[.5,-.5,.5],[-.5,-.5,-.5],[-.5,-.5,.5]]},{n:[0,0,1],p:[[-.5,-.5,.5],[.5,-.5,.5],[-.5,.5,.5],[.5,.5,.5]]},{n:[0,0,-1],p:[[-.5,.5,-.5],[.5,.5,-.5],[-.5,-.5,-.5],[.5,-.5,-.5]]}];const v=[],i=[];for(const f of faces){const base=v.length/8;for(const p of f.p)v.push(...p,0,...f.n,0);i.push(base,base+1,base+2,base+2,base+1,base+3);}return{vertices:new Float32Array(v),indices:new Uint32Array(i),count:i.length};}
function PushInstance(target,p,c,metal,s,rough,emission=0){target.push(p[0],p[1],p[2],emission,c[0],c[1],c[2],metal,s[0],s[1],s[2],rough);}
function EmitterPosition(t){return[Math.sin(t*.37)*1.1,-6.5,1.35];}
function SceneInstances(t,staticOnly=false){const c=[];PushInstance(c,[0,0,-.34],[.30,.34,.33],0,[36,36,.68],.96);PushInstance(c,[0,0,.025],[.08,.105,.11],0,[5.2,34,.05],.86);PushInstance(c,[-6.3,2.2,1.65],[.54,.12,.075],0,[.48,8.4,3.3],.72);PushInstance(c,[6.3,2.2,1.65],[.055,.25,.50],0,[.48,8.4,3.3],.62);PushInstance(c,[-9.6,7.5,2.7],[.32,.37,.33],0,[5.4,4.7,5.4],.86);PushInstance(c,[9.8,8.5,3.7],[.39,.34,.26],0,[5.2,5.5,7.4],.82);PushInstance(c,[-10.8,-8.8,2],[.22,.31,.28],0,[4,4.6,4],.90);PushInstance(c,[10.9,-8.4,2.9],[.28,.27,.36],0,[4.6,5.1,5.8],.76);PushInstance(c,[-3.8,9.4,1],[.73,.45,.10],0,[2.2,2.2,2],.58);PushInstance(c,[3.9,10.2,1.25],[.08,.46,.31],0,[2.5,2.5,2.5],.55);PushInstance(c,[-2.7,-6.5,1],[.43,.45,.46],.05,[.7,.7,2],.38);PushInstance(c,[2.7,-6.5,1],[.43,.45,.46],.05,[.7,.7,2],.38);if(!staticOnly){PushInstance(c,EmitterPosition(t),[.025,.68,1],0,[3.7,.2,.3],.22,Emissive.checked?5.5:0);PushInstance(c,[0,5.1,1.2+Math.sin(t*1.15)*1.05],[.62,.09,.07],0,[3.8,.42,2.4],.48);PushInstance(c,[-4.1+Math.sin(t*.77)*2.2,-2.2,.75],[.08,.58,.42],0,[1.5,1.5,1.5],.44);PushInstance(c,[4.5,-1.4+Math.cos(t*.61)*2.7,.6],[.85,.48,.06],0,[1.2,1.2,1.2],.36);PushInstance(c,[Math.sin(t*.48)*7.5,12.7,.9],[.26,.55,.70],.1,[2.4,1.2,1.8],.28);}const b=[];if(!staticOnly){PushInstance(b,[-4+Math.sin(t*.72)*2,-.6,.08],[.82,.10,.045],0,[1.75,1.75,1.75],.30);PushInstance(b,[3.8,.2+Math.cos(t*.66)*2,.08],[.035,.34,.76],.18,[1.75,1.75,1.75],.20);PushInstance(b,[-1.8,7.1,.08+(Math.sin(t*1.1)*.5+.5)*.75],[.95,.50,.06],.56,[1.72,1.72,1.72],.15);PushInstance(b,[2.2+Math.sin(t*.41)*1.3,-7.7,.08],[.06,.66,.37],0,[1.85,1.85,1.85],.46);}return{cubes:new Float32Array(c),balls:new Float32Array(b),cubeCount:c.length/12,ballCount:b.length/12};}

function Compile(gl,type,source,label){const shader=gl.createShader(type);gl.shaderSource(shader,source);gl.compileShader(shader);if(!gl.getShaderParameter(shader,gl.COMPILE_STATUS))throw new Error(`${label}: ${gl.getShaderInfoLog(shader)}`);return shader;}
function Program(gl,vs,fs,label){const p=gl.createProgram();gl.attachShader(p,Compile(gl,gl.VERTEX_SHADER,vs,`${label} vertex`));gl.attachShader(p,Compile(gl,gl.FRAGMENT_SHADER,fs,`${label} fragment`));gl.linkProgram(p);if(!gl.getProgramParameter(p,gl.LINK_STATUS))throw new Error(`${label}: ${gl.getProgramInfoLog(p)}`);return p;}
function Uniform(gl,p,name){const value=gl.getUniformLocation(p,name);if(value===null)throw new Error(`Missing active uniform ${name}`);return value;}
function OptionalUniform(gl,p,name){return gl.getUniformLocation(p,name);}
function BindTexture(gl,p,name,texture,unit,target=gl.TEXTURE_2D){const l=Uniform(gl,p,name);gl.activeTexture(gl.TEXTURE0+unit);gl.bindTexture(target,texture);gl.uniform1i(l,unit);}

function CreateMesh(gl,geometry,maxInstances){const vao=gl.createVertexArray();gl.bindVertexArray(vao);const vertex=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,vertex);gl.bufferData(gl.ARRAY_BUFFER,geometry.vertices,gl.STATIC_DRAW);gl.enableVertexAttribArray(0);gl.vertexAttribPointer(0,3,gl.FLOAT,false,32,0);gl.enableVertexAttribArray(1);gl.vertexAttribPointer(1,3,gl.FLOAT,false,32,16);const index=gl.createBuffer();gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER,index);gl.bufferData(gl.ELEMENT_ARRAY_BUFFER,geometry.indices,gl.STATIC_DRAW);const instances=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,instances);gl.bufferData(gl.ARRAY_BUFFER,maxInstances*48,gl.DYNAMIC_DRAW);for(let a=0;a<3;++a){const location=2+a;gl.enableVertexAttribArray(location);gl.vertexAttribPointer(location,4,gl.FLOAT,false,48,a*16);gl.vertexAttribDivisor(location,1);}gl.bindVertexArray(null);return{vao,vertex,index,instances,count:geometry.count,instanceCount:0};}
function UploadInstances(gl,mesh,data,count){gl.bindBuffer(gl.ARRAY_BUFFER,mesh.instances);gl.bufferSubData(gl.ARRAY_BUFFER,0,data);mesh.instanceCount=count;}
function DrawMesh(gl,mesh){if(mesh.instanceCount===0)return;gl.bindVertexArray(mesh.vao);gl.drawElementsInstanced(gl.TRIANGLES,mesh.count,gl.UNSIGNED_INT,0,mesh.instanceCount);}
function DrawScene(gl,cube,ball){DrawMesh(gl,cube);DrawMesh(gl,ball);}

function ColourTexture(gl,width,height,internal=gl.RGBA16F,format=gl.RGBA,type=gl.HALF_FLOAT,filter=gl.NEAREST){const t=gl.createTexture();gl.bindTexture(gl.TEXTURE_2D,t);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,filter);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MAG_FILTER,filter);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_S,gl.CLAMP_TO_EDGE);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_T,gl.CLAMP_TO_EDGE);gl.texImage2D(gl.TEXTURE_2D,0,internal,width,height,0,format,type,null);return t;}
function DepthTexture(gl,width,height){const t=gl.createTexture();gl.bindTexture(gl.TEXTURE_2D,t);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,gl.NEAREST);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MAG_FILTER,gl.NEAREST);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_S,gl.CLAMP_TO_EDGE);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_T,gl.CLAMP_TO_EDGE);gl.texImage2D(gl.TEXTURE_2D,0,gl.DEPTH_COMPONENT24,width,height,0,gl.DEPTH_COMPONENT,gl.UNSIGNED_INT,null);return t;}
function CheckFramebuffer(gl,label){const status=gl.checkFramebufferStatus(gl.FRAMEBUFFER);if(status!==gl.FRAMEBUFFER_COMPLETE)throw new Error(`${label} framebuffer incomplete: 0x${status.toString(16)}`);}
function DeleteTexture(gl,t){if(t)gl.deleteTexture(t);}

function ParseProbeCache(gl,data){const d=new DataView(data);if(d.getUint32(0,true)!==0x49475645||d.getUint32(4,true)!==1)throw new Error("Invalid EVGI probe cache");const dims=[d.getUint32(8,true),d.getUint32(12,true),d.getUint32(16,true)],origin=[d.getFloat32(20,true),d.getFloat32(24,true),d.getFloat32(28,true)],spacing=[d.getFloat32(32,true),d.getFloat32(36,true),d.getFloat32(40,true)],visibilityDistance=d.getFloat32(44,true),rayCount=d.getUint32(48,true),count=dims[0]*dims[1]*dims[2];if(data.byteLength!==52+count*80)throw new Error("EVGI cache byte count mismatch");const r=new Float32Array(count*4),g=new Float32Array(count*4),b=new Float32Array(count*4),v0=new Float32Array(count*4),v1=new Float32Array(count*4);let o=52;for(let i=0;i<count;++i){for(let c=0;c<4;++c){r[i*4+c]=d.getFloat32(o,true);o+=4;}for(let c=0;c<4;++c){g[i*4+c]=d.getFloat32(o,true);o+=4;}for(let c=0;c<4;++c){b[i*4+c]=d.getFloat32(o,true);o+=4;}for(let c=0;c<4;++c){v0[i*4+c]=d.getFloat32(o,true);o+=4;}v1[i*4]=d.getFloat32(o,true);o+=4;v1[i*4+1]=d.getFloat32(o,true);o+=4;v1[i*4+2]=d.getFloat32(o,true);o+=4;v1[i*4+3]=d.getFloat32(o,true);o+=4;}function texture(values){const t=gl.createTexture();gl.bindTexture(gl.TEXTURE_3D,t);gl.texParameteri(gl.TEXTURE_3D,gl.TEXTURE_MIN_FILTER,gl.NEAREST);gl.texParameteri(gl.TEXTURE_3D,gl.TEXTURE_MAG_FILTER,gl.NEAREST);gl.texParameteri(gl.TEXTURE_3D,gl.TEXTURE_WRAP_S,gl.CLAMP_TO_EDGE);gl.texParameteri(gl.TEXTURE_3D,gl.TEXTURE_WRAP_T,gl.CLAMP_TO_EDGE);gl.texParameteri(gl.TEXTURE_3D,gl.TEXTURE_WRAP_R,gl.CLAMP_TO_EDGE);gl.texImage3D(gl.TEXTURE_3D,0,gl.RGBA16F,...dims,0,gl.RGBA,gl.FLOAT,values);return t;}return{dims,origin,spacing,visibilityDistance,rayCount,count,red:texture(r),green:texture(g),blue:texture(b),visibility0:texture(v0),visibility1:texture(v1)};}

function StabilizedShadow(camera,sun,nearDistance,farDistance,resolution){const tangent=Math.tan(.78*.5),aspect=camera.aspect,hh=tangent*farDistance,hw=hh*aspect,hd=(farDistance-nearDistance)*.5;let radius=Math.sqrt(hw*hw+hh*hh+hd*hd);radius=Math.ceil(radius*16)/16;let center=Add(camera.eye,Scale(camera.forward,(nearDistance+farDistance)*.5));const right=Normalise(Cross([0,0,1],sun)),up=Normalise(Cross(sun,right)),texel=radius*2/resolution,lx=Dot(center,right),ly=Dot(center,up);center=Add(center,Scale(right,Math.floor(lx/texel)*texel-lx));center=Add(center,Scale(up,Math.floor(ly/texel)*texel-ly));const eye=Add(center,Scale(sun,radius+70));return Multiply(Orthographic(-radius,radius,-radius,radius,.1,radius*2+140),ViewMatrix(eye,center,[0,0,1]));}

async function Main(){
    const gl=Canvas.getContext("webgl2",{alpha:false,antialias:false,depth:true,preserveDrawingBuffer:false});if(!gl)throw new Error("WebGL2 is unavailable");if(!gl.getExtension("EXT_color_buffer_float"))throw new Error("EXT_color_buffer_float is required for the EEVEE G-buffer");if(!gl.getExtension("OES_texture_float_linear"))throw new Error("OES_texture_float_linear is required for filtered half-float GI history");
    const timerExtension=gl.getExtension("EXT_disjoint_timer_query_webgl2");StatusText.textContent="Loading EEVEE shaders, ShaderBall, and baked probe cache";
    const loaded=await Promise.all([...ShaderFiles.map(FetchText),FetchBinary(Root),FetchBinary(CacheAddress)]);const shader={};ShaderFiles.forEach((name,i)=>shader[name]=loaded[i]);const geometry=DecodeShaderBall(loaded[ShaderFiles.length]),probeCache=ParseProbeCache(gl,loaded[ShaderFiles.length+1]);CacheMetric.textContent=`${probeCache.dims.join("×")} · ${probeCache.count.toLocaleString()} probes`;
    const programs={gbuffer:Program(gl,shader["GBuffer.vert"],shader["GBuffer.frag"],"G-buffer"),shadow:Program(gl,shader["Shadow.vert"],shader["Shadow.frag"],"directional shadow"),pointShadow:Program(gl,shader["Shadow.vert"],shader["PointShadow.frag"],"point shadow"),capture:Program(gl,shader["ProbeCapture.vert"],shader["ProbeCapture.frag"],"sphere probe capture"),direct:Program(gl,shader["Fullscreen.vert"],shader["Direct.frag"],"deferred direct"),ray:Program(gl,shader["Fullscreen.vert"],shader["Raytrace.frag"],"screen ray trace"),denoise:Program(gl,shader["Fullscreen.vert"],shader["Denoise.frag"],"ray denoise"),present:Program(gl,shader["Fullscreen.vert"],shader["Present.frag"],"presentation"),probeDebug:Program(gl,shader["ProbeDebug.vert"],shader["ProbeDebug.frag"],"probe debug")};
    const cube=CreateMesh(gl,CubeGeometry(),32),ball=CreateMesh(gl,geometry,8),fullscreen=gl.createVertexArray();

    const shadowAtlas=DepthTexture(gl,ShadowAtlasSize,ShadowAtlasSize);const shadowFbo=gl.createFramebuffer();gl.bindFramebuffer(gl.FRAMEBUFFER,shadowFbo);gl.framebufferTexture2D(gl.FRAMEBUFFER,gl.DEPTH_ATTACHMENT,gl.TEXTURE_2D,shadowAtlas,0);gl.drawBuffers([gl.NONE]);gl.readBuffer(gl.NONE);CheckFramebuffer(gl,"directional shadow atlas");
    const pointShadow=gl.createTexture();gl.bindTexture(gl.TEXTURE_CUBE_MAP,pointShadow);for(let face=0;face<6;++face)gl.texImage2D(gl.TEXTURE_CUBE_MAP_POSITIVE_X+face,0,gl.DEPTH_COMPONENT24,PointShadowSize,PointShadowSize,0,gl.DEPTH_COMPONENT,gl.UNSIGNED_INT,null);gl.texParameteri(gl.TEXTURE_CUBE_MAP,gl.TEXTURE_MIN_FILTER,gl.NEAREST);gl.texParameteri(gl.TEXTURE_CUBE_MAP,gl.TEXTURE_MAG_FILTER,gl.NEAREST);gl.texParameteri(gl.TEXTURE_CUBE_MAP,gl.TEXTURE_WRAP_S,gl.CLAMP_TO_EDGE);gl.texParameteri(gl.TEXTURE_CUBE_MAP,gl.TEXTURE_WRAP_T,gl.CLAMP_TO_EDGE);gl.texParameteri(gl.TEXTURE_CUBE_MAP,gl.TEXTURE_WRAP_R,gl.CLAMP_TO_EDGE);const pointFbo=gl.createFramebuffer();gl.bindFramebuffer(gl.FRAMEBUFFER,pointFbo);gl.drawBuffers([gl.NONE]);gl.readBuffer(gl.NONE);

    const reflectionProbe=gl.createTexture();gl.bindTexture(gl.TEXTURE_CUBE_MAP,reflectionProbe);gl.texStorage2D(gl.TEXTURE_CUBE_MAP,9,gl.RGBA16F,256,256);gl.texParameteri(gl.TEXTURE_CUBE_MAP,gl.TEXTURE_MIN_FILTER,gl.LINEAR_MIPMAP_LINEAR);gl.texParameteri(gl.TEXTURE_CUBE_MAP,gl.TEXTURE_MAG_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_CUBE_MAP,gl.TEXTURE_WRAP_S,gl.CLAMP_TO_EDGE);gl.texParameteri(gl.TEXTURE_CUBE_MAP,gl.TEXTURE_WRAP_T,gl.CLAMP_TO_EDGE);gl.texParameteri(gl.TEXTURE_CUBE_MAP,gl.TEXTURE_WRAP_R,gl.CLAMP_TO_EDGE);const captureFbo=gl.createFramebuffer(),captureDepth=gl.createRenderbuffer();gl.bindRenderbuffer(gl.RENDERBUFFER,captureDepth);gl.renderbufferStorage(gl.RENDERBUFFER,gl.DEPTH_COMPONENT24,256,256);gl.bindFramebuffer(gl.FRAMEBUFFER,captureFbo);gl.framebufferRenderbuffer(gl.FRAMEBUFFER,gl.DEPTH_ATTACHMENT,gl.RENDERBUFFER,captureDepth);

    let targets=null,width=0,height=0,historyIndex=0,frame=0,worldTime=0,sunTime=.72,paused=false,lastTime=performance.now(),previousViewProjection=null,orbitYaw=.66,orbitPitch=.40,orbitDistance=20,pointer=null,pointerPosition=[0,0],cacheStale=false;
    const queries=[];let smoothedGpu=0;
    function DestroyTargets(){if(!targets)return;for(const name of ["position","normal","albedo","depth","direct","raw"])DeleteTexture(gl,targets[name]);for(const t of [...targets.histories,...targets.historyPositions])DeleteTexture(gl,t);for(const f of targets.fbos||[])gl.deleteFramebuffer(f);targets=null;}
    function Resize(){const scale=Number(RenderScale.value)*.01,dpr=Math.min(devicePixelRatio||1,2),w=Math.max(1,Math.min(1920,Math.round(Canvas.clientWidth*dpr*scale))),h=Math.max(1,Math.min(1080,Math.round(Canvas.clientHeight*dpr*scale)));if(w===width&&h===height)return;width=w;height=h;Canvas.width=w;Canvas.height=h;DestroyTargets();const position=ColourTexture(gl,w,h),normal=ColourTexture(gl,w,h),albedo=ColourTexture(gl,w,h,gl.RGBA8,gl.RGBA,gl.UNSIGNED_BYTE),depth=DepthTexture(gl,w,h),direct=ColourTexture(gl,w,h),gbufferFbo=gl.createFramebuffer();gl.bindFramebuffer(gl.FRAMEBUFFER,gbufferFbo);gl.framebufferTexture2D(gl.FRAMEBUFFER,gl.COLOR_ATTACHMENT0,gl.TEXTURE_2D,position,0);gl.framebufferTexture2D(gl.FRAMEBUFFER,gl.COLOR_ATTACHMENT1,gl.TEXTURE_2D,normal,0);gl.framebufferTexture2D(gl.FRAMEBUFFER,gl.COLOR_ATTACHMENT2,gl.TEXTURE_2D,albedo,0);gl.framebufferTexture2D(gl.FRAMEBUFFER,gl.DEPTH_ATTACHMENT,gl.TEXTURE_2D,depth,0);gl.drawBuffers([gl.COLOR_ATTACHMENT0,gl.COLOR_ATTACHMENT1,gl.COLOR_ATTACHMENT2]);CheckFramebuffer(gl,"G-buffer");const directFbo=gl.createFramebuffer();gl.bindFramebuffer(gl.FRAMEBUFFER,directFbo);gl.framebufferTexture2D(gl.FRAMEBUFFER,gl.COLOR_ATTACHMENT0,gl.TEXTURE_2D,direct,0);gl.drawBuffers([gl.COLOR_ATTACHMENT0]);CheckFramebuffer(gl,"direct");const hw=Math.ceil(w/2),hh=Math.ceil(h/2),raw=ColourTexture(gl,hw,hh),rawFbo=gl.createFramebuffer();gl.bindFramebuffer(gl.FRAMEBUFFER,rawFbo);gl.framebufferTexture2D(gl.FRAMEBUFFER,gl.COLOR_ATTACHMENT0,gl.TEXTURE_2D,raw,0);gl.drawBuffers([gl.COLOR_ATTACHMENT0]);CheckFramebuffer(gl,"ray");const histories=[ColourTexture(gl,hw,hh,gl.RGBA16F,gl.RGBA,gl.HALF_FLOAT,gl.LINEAR),ColourTexture(gl,hw,hh,gl.RGBA16F,gl.RGBA,gl.HALF_FLOAT,gl.LINEAR)],historyPositions=[ColourTexture(gl,hw,hh),ColourTexture(gl,hw,hh)],historyFbos=[0,1].map(i=>{const f=gl.createFramebuffer();gl.bindFramebuffer(gl.FRAMEBUFFER,f);gl.framebufferTexture2D(gl.FRAMEBUFFER,gl.COLOR_ATTACHMENT0,gl.TEXTURE_2D,histories[i],0);gl.framebufferTexture2D(gl.FRAMEBUFFER,gl.COLOR_ATTACHMENT1,gl.TEXTURE_2D,historyPositions[i],0);gl.drawBuffers([gl.COLOR_ATTACHMENT0,gl.COLOR_ATTACHMENT1]);CheckFramebuffer(gl,`history ${i}`);return f;});targets={position,normal,albedo,depth,direct,raw,histories,historyPositions,gbufferFbo,directFbo,rawFbo,historyFbos,fbos:[gbufferFbo,directFbo,rawFbo,...historyFbos]};historyIndex=0;frame=0;previousViewProjection=null;}
    function Camera(){const target=[0,1.2,1.35],cp=Math.cos(orbitPitch),eye=[target[0]+Math.sin(orbitYaw)*cp*orbitDistance,target[1]-Math.cos(orbitYaw)*cp*orbitDistance,target[2]+Math.sin(orbitPitch)*orbitDistance],forward=Normalise(Sub(target,eye)),right=Normalise(Cross(forward,[0,0,1])),up=Normalise(Cross(right,forward)),aspect=width/height,view=ViewMatrix(eye,target,[0,0,1]),projection=Perspective(.78,aspect,.08,120);return{eye,target,forward,right,up,aspect,viewProjection:Multiply(projection,view)};}
    function UpdateScene(staticOnly=false){const scene=SceneInstances(worldTime,staticOnly);UploadInstances(gl,cube,scene.cubes,scene.cubeCount);UploadInstances(gl,ball,scene.balls,scene.ballCount);}
    function UseGeometry(program,matrix){gl.useProgram(program);gl.uniformMatrix4fv(Uniform(gl,program,program===programs.shadow||program===programs.pointShadow?"uLightViewProjection":"uViewProjection"),false,matrix);}
    const cubeDirections=[[1,0,0],[-1,0,0],[0,1,0],[0,-1,0],[0,0,1],[0,0,-1]],cubeUps=[[0,-1,0],[0,-1,0],[0,0,1],[0,0,-1],[0,-1,0],[0,-1,0]];
    function CaptureReflection(){UpdateScene(false);gl.bindFramebuffer(gl.FRAMEBUFFER,captureFbo);gl.viewport(0,0,256,256);gl.enable(gl.DEPTH_TEST);gl.enable(gl.CULL_FACE);gl.cullFace(gl.BACK);gl.useProgram(programs.capture);const center=[0,0,3],projection=Perspective(Math.PI/2,1,.1,80),sun=SunDirection();gl.uniform3fv(Uniform(gl,programs.capture,"uSunDirection"),sun);gl.uniform3f(Uniform(gl,programs.capture,"uSunColour"),1,.90,.72);for(let face=0;face<6;++face){gl.framebufferTexture2D(gl.FRAMEBUFFER,gl.COLOR_ATTACHMENT0,gl.TEXTURE_CUBE_MAP_POSITIVE_X+face,reflectionProbe,0);gl.drawBuffers([gl.COLOR_ATTACHMENT0]);CheckFramebuffer(gl,"sphere probe");const direction=cubeDirections[face],z=direction[2]*.5+.5;gl.clearColor(.025*(z)+.18*(1-z),.075*z+.26*(1-z),.13*z+.30*(1-z),1);gl.clearDepth(1);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);gl.uniformMatrix4fv(Uniform(gl,programs.capture,"uViewProjection"),false,Multiply(projection,ViewMatrix(center,Add(center,direction),cubeUps[face])));DrawScene(gl,cube,ball);}gl.bindTexture(gl.TEXTURE_CUBE_MAP,reflectionProbe);gl.generateMipmap(gl.TEXTURE_CUBE_MAP);UpdateScene(false);}
    function SunDirection(){return Normalise([Math.cos(sunTime)*.62,Math.sin(sunTime)*.62,.64+Math.sin(sunTime*.63)*.12]);}
    function PointPosition(){return[3.8,-2.0+Math.cos(worldTime*.61)*2.0,4.2];}
    function RenderShadows(camera,sun,point){const splits=[38,76,120],matrices=[StabilizedShadow(camera,sun,.08,splits[0],ShadowTileSize),StabilizedShadow(camera,sun,splits[0],splits[1],ShadowTileSize),StabilizedShadow(camera,sun,splits[1],splits[2],ShadowTileSize)];gl.enable(gl.DEPTH_TEST);gl.enable(gl.CULL_FACE);gl.cullFace(gl.FRONT);gl.colorMask(false,false,false,false);gl.bindFramebuffer(gl.FRAMEBUFFER,shadowFbo);gl.viewport(0,0,ShadowAtlasSize,ShadowAtlasSize);gl.disable(gl.SCISSOR_TEST);gl.clearDepth(1);gl.clear(gl.DEPTH_BUFFER_BIT);gl.enable(gl.SCISSOR_TEST);const tiles=[[0,0],[ShadowTileSize,0],[0,ShadowTileSize]];gl.useProgram(programs.shadow);for(let i=0;i<3;++i){gl.viewport(tiles[i][0],tiles[i][1],ShadowTileSize,ShadowTileSize);gl.scissor(tiles[i][0],tiles[i][1],ShadowTileSize,ShadowTileSize);gl.uniformMatrix4fv(Uniform(gl,programs.shadow,"uLightViewProjection"),false,matrices[i]);DrawScene(gl,cube,ball);}gl.disable(gl.SCISSOR_TEST);gl.bindFramebuffer(gl.FRAMEBUFFER,pointFbo);gl.viewport(0,0,PointShadowSize,PointShadowSize);gl.useProgram(programs.pointShadow);gl.uniform3fv(Uniform(gl,programs.pointShadow,"uLightPosition"),point);gl.uniform1f(Uniform(gl,programs.pointShadow,"uLightRange"),PointLightRange);const projection=Perspective(Math.PI/2,1,.08,PointLightRange);for(let face=0;face<6;++face){gl.framebufferTexture2D(gl.FRAMEBUFFER,gl.DEPTH_ATTACHMENT,gl.TEXTURE_CUBE_MAP_POSITIVE_X+face,pointShadow,0);gl.clear(gl.DEPTH_BUFFER_BIT);gl.uniformMatrix4fv(Uniform(gl,programs.pointShadow,"uLightViewProjection"),false,Multiply(projection,ViewMatrix(point,Add(point,cubeDirections[face]),cubeUps[face])));DrawScene(gl,cube,ball);}gl.colorMask(true,true,true,true);gl.cullFace(gl.BACK);return{splits,matrices};}
    function BindProbeTextures(program,start){BindTexture(gl,program,"uProbeRed",probeCache.red,start,gl.TEXTURE_3D);BindTexture(gl,program,"uProbeGreen",probeCache.green,start+1,gl.TEXTURE_3D);BindTexture(gl,program,"uProbeBlue",probeCache.blue,start+2,gl.TEXTURE_3D);BindTexture(gl,program,"uProbeVisibility0",probeCache.visibility0,start+3,gl.TEXTURE_3D);BindTexture(gl,program,"uProbeVisibility1",probeCache.visibility1,start+4,gl.TEXTURE_3D);gl.uniform3fv(Uniform(gl,program,"uProbeOrigin"),probeCache.origin);gl.uniform3fv(Uniform(gl,program,"uProbeSpacing"),probeCache.spacing);gl.uniform3iv(Uniform(gl,program,"uProbeDimensions"),probeCache.dims);gl.uniform1f(Uniform(gl,program,"uProbeVisibilityDistance"),probeCache.visibilityDistance);}
    function Fullscreen(){gl.bindVertexArray(fullscreen);gl.drawArrays(gl.TRIANGLES,0,3);}
    function PollTimers(){if(!timerExtension)return;while(queries.length){const q=queries[0];if(!gl.getQueryParameter(q,gl.QUERY_RESULT_AVAILABLE))break;queries.shift();const disjoint=gl.getParameter(timerExtension.GPU_DISJOINT_EXT);if(!disjoint){const ms=gl.getQueryParameter(q,gl.QUERY_RESULT)/1e6;smoothedGpu=smoothedGpu?smoothedGpu*.9+ms*.1:ms;GpuMetric.textContent=`${smoothedGpu.toFixed(2)} ms GPU`;}gl.deleteQuery(q);}}
    function BeginTimer(){if(!timerExtension||queries.length>=3)return null;const q=gl.createQuery();gl.beginQuery(timerExtension.TIME_ELAPSED_EXT,q);return q;}
    function EndTimer(q){if(q){gl.endQuery(timerExtension.TIME_ELAPSED_EXT);queries.push(q);}}

    function Render(timestamp){Resize();const delta=Math.min((timestamp-lastTime)*.001,.05);lastTime=timestamp;if(!paused){if(AnimateWorld.checked)worldTime+=delta;if(AnimateSun.checked){sunTime+=delta*.105;cacheStale=true;}}if(cacheStale){CacheState.textContent="Probe cache stale (direct remains live)";CacheState.classList.add("Stale");}++frame;UpdateScene(false);const camera=Camera(),sun=SunDirection(),point=PointPosition(),timer=BeginTimer(),shadow=RenderShadows(camera,sun,point);
        // Deferred G-buffer.
        gl.bindFramebuffer(gl.FRAMEBUFFER,targets.gbufferFbo);gl.viewport(0,0,width,height);gl.enable(gl.DEPTH_TEST);gl.enable(gl.CULL_FACE);gl.cullFace(gl.BACK);gl.clearColor(0,0,0,0);gl.clearDepth(1);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);gl.useProgram(programs.gbuffer);gl.uniformMatrix4fv(Uniform(gl,programs.gbuffer,"uViewProjection"),false,camera.viewProjection);DrawScene(gl,cube,ball);
        // Direct PBR with directional atlas and local-light cubemap shadows.
        gl.bindFramebuffer(gl.FRAMEBUFFER,targets.directFbo);gl.viewport(0,0,width,height);gl.disable(gl.DEPTH_TEST);gl.disable(gl.CULL_FACE);gl.clear(gl.COLOR_BUFFER_BIT);gl.useProgram(programs.direct);BindTexture(gl,programs.direct,"uPosition",targets.position,0);BindTexture(gl,programs.direct,"uNormalRoughness",targets.normal,1);BindTexture(gl,programs.direct,"uAlbedoMetalness",targets.albedo,2);BindTexture(gl,programs.direct,"uShadowAtlas",shadowAtlas,3);BindTexture(gl,programs.direct,"uPointShadow",pointShadow,4,gl.TEXTURE_CUBE_MAP);for(let i=0;i<3;++i)gl.uniformMatrix4fv(Uniform(gl,programs.direct,`uShadowMatrix[${i}]`),false,shadow.matrices[i]);gl.uniform3fv(Uniform(gl,programs.direct,"uShadowSplits"),shadow.splits);gl.uniform3fv(Uniform(gl,programs.direct,"uCameraPosition"),camera.eye);gl.uniform3fv(Uniform(gl,programs.direct,"uCameraForward"),camera.forward);gl.uniform3fv(Uniform(gl,programs.direct,"uSunDirection"),sun);gl.uniform3f(Uniform(gl,programs.direct,"uSunColour"),1,.9,.72);const proof=Number(ViewMode.value)===8;gl.uniform1f(Uniform(gl,programs.direct,"uSunIntensity"),proof?0:3.6);gl.uniform3fv(Uniform(gl,programs.direct,"uPointPosition"),point);gl.uniform3f(Uniform(gl,programs.direct,"uPointColour"),1,.42,.12);gl.uniform1f(Uniform(gl,programs.direct,"uPointIntensity"),proof?0:44);gl.uniform1f(Uniform(gl,programs.direct,"uPointRange"),PointLightRange);gl.uniform1f(Uniform(gl,programs.direct,"uSunAngle"),Number(SunAngle.value)*.1*Math.PI/180);gl.uniform1f(Uniform(gl,programs.direct,"uPointRadius"),Number(LightRadius.value)*.01);gl.uniform1i(Uniform(gl,programs.direct,"uShadowRayCount"),Number(ShadowRays.value));gl.uniform1i(Uniform(gl,programs.direct,"uShadowStepCount"),Number(ShadowSteps.value));gl.uniform1i(Uniform(gl,programs.direct,"uShadowTrace"),SoftShadows.checked);gl.uniform1i(Uniform(gl,programs.direct,"uShadowsEnabled"),Shadows.checked);Fullscreen();
        // Half-resolution screen ray tracing with volume-probe miss fallback.
        const halfW=Math.ceil(width/2),halfH=Math.ceil(height/2);gl.bindFramebuffer(gl.FRAMEBUFFER,targets.rawFbo);gl.viewport(0,0,halfW,halfH);gl.useProgram(programs.ray);BindTexture(gl,programs.ray,"uPosition",targets.position,0);BindTexture(gl,programs.ray,"uNormalRoughness",targets.normal,1);BindTexture(gl,programs.ray,"uDirectRadiance",targets.direct,2);BindProbeTextures(programs.ray,3);gl.uniformMatrix4fv(Uniform(gl,programs.ray,"uViewProjection"),false,camera.viewProjection);gl.uniform3fv(Uniform(gl,programs.ray,"uCameraPosition"),camera.eye);gl.uniform3fv(Uniform(gl,programs.ray,"uCameraForward"),camera.forward);gl.uniform1f(Uniform(gl,programs.ray,"uThickness"),Number(Thickness.value)*.01);gl.uniform1f(Uniform(gl,programs.ray,"uMaximumDistance"),18);gl.uniform1i(Uniform(gl,programs.ray,"uRaySteps"),Number(TraceSteps.value));gl.uniform1i(Uniform(gl,programs.ray,"uRayCount"),Number(RayCount.value));gl.uniform1i(Uniform(gl,programs.ray,"uFrame"),frame);gl.uniform1i(Uniform(gl,programs.ray,"uScreenTrace"),ScreenTrace.checked);gl.uniform1i(Uniform(gl,programs.ray,"uVolumeProbes"),VolumeProbes.checked);gl.uniform1i(Uniform(gl,programs.ray,"uLeakRejection"),LeakRejection.checked);gl.uniform1i(Uniform(gl,programs.ray,"uBackface"),true);Fullscreen();
        // Spatial reuse, temporal reprojection, clamp, and bilateral resolve.
        const currentHistory=1-historyIndex;gl.bindFramebuffer(gl.FRAMEBUFFER,targets.historyFbos[currentHistory]);gl.viewport(0,0,halfW,halfH);gl.useProgram(programs.denoise);BindTexture(gl,programs.denoise,"uRaw",targets.raw,0);BindTexture(gl,programs.denoise,"uPosition",targets.position,1);BindTexture(gl,programs.denoise,"uNormalRoughness",targets.normal,2);BindTexture(gl,programs.denoise,"uPreviousHistory",targets.histories[historyIndex],3);BindTexture(gl,programs.denoise,"uPreviousPosition",targets.historyPositions[historyIndex],4);gl.uniformMatrix4fv(Uniform(gl,programs.denoise,"uPreviousViewProjection"),false,previousViewProjection||camera.viewProjection);gl.uniform1i(Uniform(gl,programs.denoise,"uTemporal"),Temporal.checked);gl.uniform1i(Uniform(gl,programs.denoise,"uSpatialReuse"),SpatialReuse.checked);gl.uniform1i(Uniform(gl,programs.denoise,"uFrame"),frame);Fullscreen();
        // Final direct + indirect + probe-reflection resolve.
        gl.bindFramebuffer(gl.FRAMEBUFFER,null);gl.viewport(0,0,width,height);gl.useProgram(programs.present);BindTexture(gl,programs.present,"uPosition",targets.position,0);BindTexture(gl,programs.present,"uNormalRoughness",targets.normal,1);BindTexture(gl,programs.present,"uAlbedoMetalness",targets.albedo,2);BindTexture(gl,programs.present,"uDirectRadiance",targets.direct,3);BindTexture(gl,programs.present,"uIndirect",targets.histories[currentHistory],4);BindTexture(gl,programs.present,"uReflectionProbe",reflectionProbe,5,gl.TEXTURE_CUBE_MAP);BindProbeTextures(programs.present,6);gl.uniform3fv(Uniform(gl,programs.present,"uCameraPosition"),camera.eye);gl.uniform3fv(Uniform(gl,programs.present,"uCameraForward"),camera.forward);gl.uniform3fv(Uniform(gl,programs.present,"uCameraRight"),camera.right);gl.uniform3fv(Uniform(gl,programs.present,"uCameraUp"),camera.up);gl.uniform1f(Uniform(gl,programs.present,"uCameraTanHalfFov"),Math.tan(.78*.5));gl.uniform1f(Uniform(gl,programs.present,"uCameraAspect"),camera.aspect);gl.uniform1f(Uniform(gl,programs.present,"uExposure"),Number(Exposure.value)*.01);gl.uniform1i(Uniform(gl,programs.present,"uMode"),Number(ViewMode.value));gl.uniform1i(Uniform(gl,programs.present,"uLeakRejection"),LeakRejection.checked);gl.uniform1i(Uniform(gl,programs.present,"uReflections"),Reflections.checked);gl.uniform1i(Uniform(gl,programs.present,"uFastGI"),FastGI.checked);Fullscreen();
        if(ProbeDebug.checked){gl.enable(gl.BLEND);gl.blendFunc(gl.SRC_ALPHA,gl.ONE_MINUS_SRC_ALPHA);gl.useProgram(programs.probeDebug);gl.uniformMatrix4fv(Uniform(gl,programs.probeDebug,"uViewProjection"),false,camera.viewProjection);gl.uniform3fv(Uniform(gl,programs.probeDebug,"uProbeOrigin"),probeCache.origin);gl.uniform3fv(Uniform(gl,programs.probeDebug,"uProbeSpacing"),probeCache.spacing);gl.uniform3iv(Uniform(gl,programs.probeDebug,"uProbeDimensions"),probeCache.dims);BindTexture(gl,programs.probeDebug,"uProbeVisibility1",probeCache.visibility1,0,gl.TEXTURE_3D);gl.bindVertexArray(fullscreen);gl.drawArrays(gl.POINTS,0,probeCache.count);gl.disable(gl.BLEND);}
        EndTimer(timer);PollTimers();historyIndex=currentHistory;previousViewProjection=new Float32Array(camera.viewProjection);PanelLabels.hidden=Number(ViewMode.value)!==0;requestAnimationFrame(Render);
    }

    CaptureReflection();Status.classList.add("Ready");StatusText.textContent="WebGL2 · EEVEE Next screen/probe GI live";requestAnimationFrame(Render);
    ViewMode.addEventListener("change",()=>{frame=0;previousViewProjection=null;});for(const control of [ScreenTrace,VolumeProbes,LeakRejection,Temporal,SpatialReuse,Reflections,FastGI,Emissive])control.addEventListener("change",()=>{frame=0;previousViewProjection=null;});ShadowRays.addEventListener("input",()=>ShadowRayOutput.textContent=`${ShadowRays.value} ${ShadowRays.value==="1"?"ray":"rays"}`);ShadowSteps.addEventListener("input",()=>ShadowStepOutput.textContent=`${ShadowSteps.value} steps`);SunAngle.addEventListener("input",()=>SunAngleOutput.textContent=`${(Number(SunAngle.value)*.1).toFixed(1)}°`);LightRadius.addEventListener("input",()=>LightRadiusOutput.textContent=`${(Number(LightRadius.value)*.01).toFixed(2)} m`);RayCount.addEventListener("input",()=>RayOutput.textContent=`${RayCount.value} ${RayCount.value==="1"?"ray":"rays"}`);TraceSteps.addEventListener("input",()=>StepOutput.textContent=`${TraceSteps.value} steps`);Thickness.addEventListener("input",()=>ThicknessOutput.textContent=`${(Number(Thickness.value)*.01).toFixed(2)} m`);RenderScale.addEventListener("input",()=>ScaleOutput.textContent=`${RenderScale.value}%`);RenderScale.addEventListener("change",()=>{width=0;});Exposure.addEventListener("input",()=>ExposureOutput.textContent=`${(Number(Exposure.value)*.01).toFixed(2)}×`);PauseButton.addEventListener("click",()=>{paused=!paused;PauseButton.textContent=paused?"Resume simulation":"Pause simulation";});ResetButton.addEventListener("click",()=>{orbitYaw=.66;orbitPitch=.40;orbitDistance=20;width=0;frame=0;});RecaptureButton.addEventListener("click",()=>{CaptureReflection();frame=0;});Canvas.addEventListener("pointerdown",e=>{pointer=e.pointerId;pointerPosition=[e.clientX,e.clientY];Canvas.setPointerCapture(e.pointerId);});Canvas.addEventListener("pointermove",e=>{if(e.pointerId!==pointer)return;const dx=e.clientX-pointerPosition[0],dy=e.clientY-pointerPosition[1];pointerPosition=[e.clientX,e.clientY];orbitYaw-=dx*.006;orbitPitch=Clamp(orbitPitch+dy*.005,.08,1.28);});Canvas.addEventListener("pointerup",e=>{if(e.pointerId===pointer)pointer=null;});Canvas.addEventListener("pointercancel",e=>{if(e.pointerId===pointer)pointer=null;});Canvas.addEventListener("wheel",e=>{e.preventDefault();orbitDistance=Clamp(orbitDistance*Math.exp(e.deltaY*.001),8,34);},{passive:false});
}

Main().catch(error=>{console.error(error);Status.classList.add("Failed");StatusText.textContent="WebGL2 startup failed";ErrorPanel.hidden=false;ErrorPanel.querySelector("span").textContent=error instanceof Error?error.message:String(error);});
