#!/usr/bin/env python3
"""MeshToHeader.py — turn the extracted ControlVehicle body geometry into a C++ include.

Input : VehiclePhysics/CarModelling/ControlVehicle/controlvehicle_mesh.json
Output: Frontier/Projects/Project-Tractrix/Source/ControlVehicleMesh.inl

The .inl declares, in namespace Frontier::Tractrix::ControlVehicleMesh, two constexpr
arrays the drive scene bakes into the world-space triangle soup:
    kPositions[]  — float[3] body-local vertex positions (metres, +X fwd / +Y left / +Z up)
    kTriangles[]  — uint32_t[3] fan-triangulated corner indices into kPositions

Only the real body shell is emitted (the ControlVehicle mesh). Wheels are procedural
(the owner's instruction: do NOT import wheels). Interior / PROTO parts are skipped so the
driven silhouette is exactly the authored exterior.
"""
import json, pathlib, sys

ROOT = pathlib.Path(__file__).resolve().parents[3]
SRC  = ROOT / "VehiclePhysics/CarModelling/ControlVehicle/controlvehicle_mesh.json"
DST  = ROOT / "Frontier/Projects/Project-Tractrix/Source/ControlVehicleMesh.inl"
BODY = "ControlVehicle"

def main():
    data = json.loads(SRC.read_text())
    body = next(m for m in data["meshes"] if m["name"] == BODY)
    verts = body["verts"]; tris = body["tris"]
    xs=[v[0] for v in verts]; ys=[v[1] for v in verts]; zs=[v[2] for v in verts]
    bnds = (min(xs),max(xs),min(ys),max(ys),min(zs),max(zs))
    out=[]
    out.append("// ControlVehicleMesh.inl — GENERATED by CarModelling/Tools/MeshToHeader.py. Do not edit by hand.")
    out.append(f"// Source: controlvehicle_mesh.json  ({BODY}: {len(verts)} verts / {len(tris)} tris)")
    out.append(f"// Body-local bounds  X[{bnds[0]:.4f},{bnds[1]:.4f}]  Y[{bnds[2]:.4f},{bnds[3]:.4f}]  Z[{bnds[4]:.4f},{bnds[5]:.4f}]  (metres, +X fwd / +Y left / +Z up)")
    out.append("#pragma once")
    out.append("#include <cstdint>")
    out.append("namespace Frontier { namespace Tractrix { namespace ControlVehicleMesh {")
    out.append(f"inline constexpr uint32_t kVertexCount   = {len(verts)}u;")
    out.append(f"inline constexpr uint32_t kTriangleCount = {len(tris)}u;")
    out.append(f"inline constexpr float kBoundsMin[3] = {{ {bnds[0]:.6f}f, {bnds[2]:.6f}f, {bnds[4]:.6f}f }};")
    out.append(f"inline constexpr float kBoundsMax[3] = {{ {bnds[1]:.6f}f, {bnds[3]:.6f}f, {bnds[5]:.6f}f }};")
    # positions
    out.append("inline constexpr float kPositions[] = {")
    line=[]
    for v in verts:
        line.append(f"{v[0]:.5f}f,{v[1]:.5f}f,{v[2]:.5f}f,")
        if len(line)==4:
            out.append("  "+" ".join(line)); line=[]
    if line: out.append("  "+" ".join(line))
    out.append("};")
    # triangles
    out.append("inline constexpr uint32_t kTriangles[] = {")
    line=[]
    for t in tris:
        line.append(f"{t[0]}u,{t[1]}u,{t[2]}u,")
        if len(line)==6:
            out.append("  "+" ".join(line)); line=[]
    if line: out.append("  "+" ".join(line))
    out.append("};")
    out.append("} } } // namespace Frontier::Tractrix::ControlVehicleMesh")
    DST.parent.mkdir(parents=True, exist_ok=True)
    DST.write_text("\n".join(out)+"\n")
    print(f"wrote {DST}  ({len(verts)} verts, {len(tris)} tris, {DST.stat().st_size} bytes)")

if __name__ == "__main__":
    sys.exit(main())
