#!/usr/bin/env python3
# ======================================================================================================================
# SceneToHeader.py -- generate ControlVehicleMesh.inl from the extracted .blend scene.
#
# Supersedes MeshToHeader.py, which emitted positions and triangles only.  That omission is what forced
# DriveSceneAuthor to guess the material families from face positions.  This emits, in addition, a per-triangle
# material family stream taken from the authored `material_index` attribute, so the guess can be deleted outright.
#
#     python3 SceneToHeader.py            # writes Project-Drive/Source/ControlVehicleMesh.inl
# ======================================================================================================================
import json, os, sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, '..', '..'))
SCENE = os.path.join(ROOT, 'CarModelling', 'ControlVehicle', 'controlvehicle_scene.json')
OUT = os.path.join(ROOT, 'Overlay', 'Projects', 'Project-Drive', 'Source', 'ControlVehicleMesh.inl')
WHEEL_OUT = os.path.join(ROOT, 'Overlay', 'Projects', 'Project-Drive', 'Source', 'ControlVehicleWheelMesh.inl')

# .blend material slot name -> CourseMaterial family (DriveCourse.h).  Every authored slot must appear here;
# an unmapped slot is a hard error rather than a silent fallback, because a silent fallback is exactly the
# failure this generator exists to remove.
FAMILY = {
    'MetalicCoat':        ('MatBodyPaint',      6),
    'Glass':              ('MatVehicleGlass',   7),
    'Plastic':            ('MatVehiclePlastic', 8),
    'Rubber':             ('MatTyre',           9),
    'StandardRubber.002': ('MatTyre',           9),
    'Material.024':       ('MatHub',           10),
    'Plastic2':           ('MatVehicleTrim',   12),
    'FrontLight':         ('MatHeadlight',     13),
    'RearLight':          ('MatTaillight',     14),
    'Material.016':       ('MatVehicleDefault', 15),
    'Dots Stroke':        ('MatVehicleDefault', 15),
    None:                 ('MatVehicleDefault', 15),   # totcol = 0 in the .blend (PROTO-X.002)
}

# Objects that make up the BODY header.  The wheels are separate rigid parts driven by the suspension solver
# and are emitted by their own path, so they must not be baked into the body vertex stream.
BODY_OBJECTS = ('ControlVehicle', 'Interiror', 'PROTO-X.001', 'PROTO-X.002')
WHEEL_RIM = 'RimFL'
WHEEL_TYRE = 'RubberFL'


def emit_array(name, ctype, values, per_line, fmt):
    out = ['inline constexpr %s %s[] = {' % (ctype, name)]
    for i in range(0, len(values), per_line):
        out.append('  ' + ' '.join(fmt(v) for v in values[i:i + per_line]))
    out.append('};')
    return out


def collect(scene, names):
    """Merge the named objects into one vertex/triangle stream, carrying the authored family per triangle."""
    verts, tris, fams, unmapped = [], [], [], set()
    for o in scene['objects']:
        if o['name'] not in names:
            continue
        base = len(verts)
        verts.extend(o['verts'])
        slots = o['slots']
        for t, mi in zip(o['tris'], o['tri_material']):
            slot = slots[mi] if mi < len(slots) else None
            if slot not in FAMILY:
                unmapped.add(slot)
                slot = None
            tris.append([base + t[0], base + t[1], base + t[2]])
            fams.append(FAMILY[slot][1])
    return verts, tris, fams, unmapped


def main():
    scene = json.load(open(SCENE))
    verts, tris, fams, unmapped = collect(scene, BODY_OBJECTS)
    if unmapped:
        print('ERROR: unmapped material slots: %s' % sorted(x for x in unmapped if x), file=sys.stderr)
        return 2

    xs = [v[0] for v in verts]; ys = [v[1] for v in verts]; zs = [v[2] for v in verts]
    flat_p = [c for v in verts for c in v]
    flat_t = [i for t in tris for i in t]

    used = sorted(set(fams))
    names_by_id = {v[1]: v[0] for v in FAMILY.values()}
    hist = {names_by_id[f]: fams.count(f) for f in used}

    L = []
    L.append('// ControlVehicleMesh.inl — GENERATED by CarModelling/Tools/SceneToHeader.py. Do not edit by hand.')
    L.append('// Source: controlvehicle_scene.json  (%s)' % ', '.join(
        '%s %d tris' % (o['name'], len(o['tris'])) for o in scene['objects'] if o['name'] in BODY_OBJECTS))
    L.append('// Body-local bounds  X[%.4f,%.4f]  Y[%.4f,%.4f]  Z[%.4f,%.4f]  (metres, +X fwd / +Y left / +Z up)'
             % (min(xs), max(xs), min(ys), max(ys), min(zs), max(zs)))
    L.append('//')
    L.append('// kTriangleFamily carries the material slot the artist assigned to each face, recovered from the')
    L.append('// .blend `material_index` attribute.  Its values are CourseMaterial ids from DriveCourse.h.  Before')
    L.append('// this stream existed the consumer had to infer families from face positions, which painted the')
    L.append('// whole shell one colour.  Authored face counts: %s' % hist)
    L.append('#pragma once')
    L.append('#include <cstdint>')
    L.append('namespace Frontier { namespace Drive { namespace ControlVehicleMesh {')
    L.append('inline constexpr uint32_t kVertexCount   = %uu;' % len(verts))
    L.append('inline constexpr uint32_t kTriangleCount = %uu;' % len(tris))
    L.append('inline constexpr float kBoundsMin[3] = { %.6ff, %.6ff, %.6ff };' % (min(xs), min(ys), min(zs)))
    L.append('inline constexpr float kBoundsMax[3] = { %.6ff, %.6ff, %.6ff };' % (max(xs), max(ys), max(zs)))
    L += emit_array('kPositions', 'float', flat_p, 12, lambda v: '%.5ff,' % v)
    L += emit_array('kTriangles', 'uint32_t', flat_t, 18, lambda v: '%du,' % v)
    L += emit_array('kTriangleFamily', 'uint32_t', fams, 24, lambda v: '%du,' % v)
    L.append('} } } // namespace Frontier::Drive::ControlVehicleMesh')
    open(OUT, 'w').write('\n'.join(L) + '\n')

    print('wrote %s' % OUT)
    print('   %d verts / %d tris' % (len(verts), len(tris)))
    print('   family histogram: %s' % hist)

    # ---------------------------------------------------------------------------------------------- wheel rim
    # The RIM is a rigid part and comes straight from the .blend, mags and all -- the procedural wheel emitted
    # concentric bands with kDriveWheelSpokeCount = 0, i.e. no mags at all.  The TYRE is deliberately NOT baked
    # here: its surface is the live XPBDSoftTyre node lattice, because the whole point is that it deforms.
    #
    # Emitted in HUB-LOCAL metres (the authored rim centre subtracted) so DriveSceneAuthor can place one mesh at
    # all four hubs, and so a steering or spinning wheel rotates about its own axis rather than the world origin.
    rv, rt, rf, _ = collect(scene, (WHEEL_RIM,))
    if not rt:
        print('ERROR: %s produced no triangles' % WHEEL_RIM, file=sys.stderr)
        return 2
    cx = 0.5 * (min(v[0] for v in rv) + max(v[0] for v in rv))
    cy = 0.5 * (min(v[1] for v in rv) + max(v[1] for v in rv))
    cz = 0.5 * (min(v[2] for v in rv) + max(v[2] for v in rv))
    local = [[v[0] - cx, v[1] - cy, v[2] - cz] for v in rv]
    radius = max((v[0] ** 2 + v[2] ** 2) ** 0.5 for v in local)
    halfw = max(abs(v[1]) for v in local)

    rim_hist = {}
    for f in rf:
        rim_hist[names_by_id[f]] = rim_hist.get(names_by_id[f], 0) + 1

    W = []
    W.append('// ControlVehicleWheelMesh.inl — GENERATED by CarModelling/Tools/SceneToHeader.py. Do not edit by hand.')
    W.append('// Source: controlvehicle_scene.json, object %s (the authored rim WITH its mags).' % WHEEL_RIM)
    W.append('//')
    W.append('// Hub-local metres: the authored rim centre (%.5f, %.5f, %.5f) has been subtracted, so the mesh is' % (cx, cy, cz))
    W.append('// centred on its own axle and may be placed at all four hubs and rotated about +Y.')
    W.append('// Rim radius %.5f m, half-width %.5f m. Authored face counts: %s' % (radius, halfw, rim_hist))
    W.append('//')
    W.append('// The TYRE is not here on purpose. Its surface is XPBDSoftTyre\'s live node lattice, so baking a')
    W.append('// rest-pose tyre would freeze the deformation this whole subsystem exists to produce.')
    W.append('#pragma once')
    W.append('#include <cstdint>')
    W.append('namespace Frontier { namespace Drive { namespace ControlVehicleWheelMesh {')
    W.append('inline constexpr uint32_t kVertexCount   = %uu;' % len(local))
    W.append('inline constexpr uint32_t kTriangleCount = %uu;' % len(rt))
    W.append('inline constexpr float kRimRadius = %.6ff;' % radius)
    W.append('inline constexpr float kRimHalfWidth = %.6ff;' % halfw)
    W += emit_array('kPositions', 'float', [c for v in local for c in v], 12, lambda v: '%.5ff,' % v)
    W += emit_array('kTriangles', 'uint32_t', [i for t in rt for i in t], 18, lambda v: '%du,' % v)
    W += emit_array('kTriangleFamily', 'uint32_t', rf, 24, lambda v: '%du,' % v)
    W.append('} } } // namespace Frontier::Drive::ControlVehicleWheelMesh')
    open(WHEEL_OUT, 'w').write('\n'.join(W) + '\n')

    print('wrote %s' % WHEEL_OUT)
    print('   %s: %d verts / %d tris, radius %.4f m, half-width %.4f m' % (WHEEL_RIM, len(local), len(rt), radius, halfw))
    print('   rim family histogram: %s' % rim_hist)
    return 0


if __name__ == '__main__':
    sys.exit(main())
