#include "CelestialSequence.h"
#include "InspectorPanel.h"
#include "ControlPanel.h"
#include "StarFieldControls.h"
#include "CpuDraw.h"
#include "PngWriteCounterpart.h"
#include <imgui_internal.h>
#include <memory>
#include <cstring>
#include <cstdio>
#include <limits>
#include <stdexcept>
using namespace Frontier;using namespace Frontier::ProjectZero;
static unsigned Checks=0;static void Check(bool V,const char* N){++Checks;if(!V)throw std::runtime_error(N);}
static EditorProperty& Find(EditorSheet& S,const char* N){for(auto& G:S.Groups)for(unsigned I=0;I<G.PropertyCount;++I)if(!std::strcmp(G.Properties[I].Label,N))return G.Properties[I];throw std::runtime_error(N);}
static ImGuiWindow* Window(const char* N){for(auto* W:ImGui::GetCurrentContext()->Windows)if(W->Active&&std::strstr(W->Name,N))return W;throw std::runtime_error(N);}
int main(){
 auto Scene=std::make_unique<CelestialSequence>();auto Sheet=std::make_unique<EditorSheet>();const float Camera[]={0,0,2},Forward[]={0,1,0},Right[]={1,0,0},Up[]={0,0,1};Scene->Clock.Animate=false;Scene->Enabled=true;Scene->Shown[unsigned(CelestialEntity::Stars)]=true;
 Check(Scene->LoadStarCatalogue(".cache/cpp-sun-full/EngineContent/StarCatalogue/BrightStars.bin"),"real catalogue loads");Scene->Tick(0,Camera,0);Scene->BuildSheet(CelestialEntity::Stars,*Sheet);Check(Sheet->Appearance==EditorSheetAppearance::Stars,"typed native stars route");Check(Sheet->StarPreview.Count>5000&&Sheet->StarPreview.Records,"borrowed actual unbinned records");auto Apply=[&](){Scene->ApplySheet(CelestialEntity::Stars,*Sheet);Scene->Tick(0,Camera,0);Scene->BuildSheet(CelestialEntity::Stars,*Sheet);};auto Pack=[&](){return Scene->PackPostRecord(Forward,Right,Up,1,2,280,1);};
 for(const char* N:{"Brightness","Point Size","Limiting magnitude","Twinkle depth","Twinkle rate","Celestial rotation"}){auto& P=Find(*Sheet,N);float V=P.Minimum+(P.Maximum-P.Minimum)*.6f;P.Figure=V;Apply();Check(std::abs(Find(*Sheet,N).Figure-V)<.001f,"scalar round trip");Find(*Sheet,N).Figure=std::numeric_limits<float>::quiet_NaN();Apply();Check(Find(*Sheet,N).Figure==V,"nonfinite edit rejected");Find(*Sheet,N).Figure=-100;Apply();Check(Find(*Sheet,N).Figure==Find(*Sheet,N).Minimum,"lower clamp");Find(*Sheet,N).Figure=1000;Apply();Check(Find(*Sheet,N).Figure==Find(*Sheet,N).Maximum,"upper clamp");}
 Find(*Sheet,"Limiting magnitude").Figure=5.5f;Find(*Sheet,"Twinkle depth").Figure=30;Find(*Sheet,"Twinkle rate").Figure=1.2f;Find(*Sheet,"Celestial rotation").Figure=45;Find(*Sheet,"Brightness").Figure=1;Find(*Sheet,"Point Size").Figure=1;Apply();auto P=Pack();Check(sizeof(P)==544&&offsetof(PostConstantRecord,PostStarEffects)==192&&offsetof(PostConstantRecord,PostLayers)==128,"appended ABI preserves flare and cloud lanes");Check(std::abs(P.PostStar[0]-Scene->Frame().LocalSiderealTime-45)<.001,"authored rotation offsets sidereal rotation");Check(std::abs(P.PostStarEffects[0]-StarMinimumLuminance(5.5f))<1e-7f&&std::abs(P.PostStarEffects[1]-.3f)<1e-6f&&P.PostStarEffects[2]==1.2f,"magnitude and twinkle reach renderer record");Scene->Tick(.4f,Camera,0);Check(Pack().PostStarEffects[3]>.39f,"real simulation seconds drive signal");Scene->BuildSheet(CelestialEntity::Stars,*Sheet);Find(*Sheet,"Twinkle").On=false;Apply();Check(Pack().PostStarEffects[1]==0&&Pack().PostStarEffects[3]==0,"disabled twinkle is steady and stops uniform clock");Find(*Sheet,"Twinkle").On=true;Find(*Sheet,"Star field").On=false;Apply();Check(Pack().PostStar[3]==0,"field visibility disables actual stars");Find(*Sheet,"Star field").On=true;Apply();
 auto Raster=std::make_unique<VisibilityRaster>();Scene->ApplyTo(*Raster,CelestialBudget{});const auto& CPU=Raster->QueryCelestial();auto GPU=Pack();Check(CPU.Stars&&!CPU.Stars->Empty(),"actual CPU staging borrows loaded catalogue");Check(CPU.LocalSiderealTime==GPU.PostStar[0]&&CPU.Latitude==GPU.PostStar[1],"CPU and GPU rotation frames agree");Check(CPU.StarSize==GPU.PostStar[2]&&CPU.StarBrightness==GPU.PostStar[3],"CPU and GPU renderer scales agree");Check(CPU.StarMinimumLuminance==GPU.PostStarEffects[0]&&CPU.StarDepth==GPU.PostStarEffects[1]&&CPU.StarRate==GPU.PostStarEffects[2]&&CPU.StarSeconds==GPU.PostStarEffects[3],"real CPU staging matches all four appended GPU lanes");
 unsigned Bright=0,Faint=0;for(unsigned I=0;I<Sheet->StarPreview.Count;++I){auto& S=Sheet->StarPreview.Records[I];Bright+=S.Luminance>=StarMinimumLuminance(2);Faint+=S.Luminance>=StarMinimumLuminance(6);}Check(Faint>Bright*10,"limiting magnitude selects many more genuine faint stars");for(int I=0;I<100;++I){float T=I*.13f,F=StarTwinkleFlux(T,.3f,1.2f);Check(F>=.7f&&F<=1,"signal bounded to configured modulation depth");}Check(StarTwinkleFlux(3,0,2)==1,"zero depth exactly steady");Check(std::abs(StarTwinkleFlux(1,.5f,1)-StarTwinkleFlux(1,.5f,2))>.01,"frequency changes signal");
 ImGui::CreateContext();auto& IO=ImGui::GetIO();IO.IniFilename=nullptr;IO.DeltaTime=1.f/60;IO.BackendFlags|=ImGuiBackendFlags_RendererHasTextures|ImGuiBackendFlags_RendererHasVtxOffset;ImGui::StyleColorsDark();auto& Style=ImGui::GetStyle();Style.WindowPadding={0,0};Style.WindowRounding=0;Style.WindowBorderSize=0;Style.Colors[ImGuiCol_WindowBg]={.105f,.105f,.105f,1};Style.Colors[ImGuiCol_TitleBgActive]={.075f,.075f,.075f,1};auto Controls=std::make_unique<ControlPanel>();auto Inspector=std::make_unique<InspectorPanel>();Inspector->AssignControls(Controls.get());auto Row=std::make_unique<EditorInstance>();std::snprintf(Row->Label,sizeof(Row->Label),"Stars");int Width=1024,Height=1600;float Scale=1;
 auto Tick=[&](){IO.DisplaySize={float(Width),float(Height)};IO.DisplayFramebufferScale={Scale,Scale};ImGui::NewFrame();ImGui::SetNextWindowPos({0,0});ImGui::SetNextWindowSize(IO.DisplaySize);Inspector->Record(Row.get(),0,Sheet.get());Apply();ImGui::Render();FrontierProof::AcknowledgeTextures();};auto Rest=[&](){for(int I=0;I<3;++I)Tick();};auto Click=[&](ImVec2 V){IO.AddMousePosEvent(V.x,V.y);Tick();IO.AddMouseButtonEvent(0,true);Tick();IO.AddMouseButtonEvent(0,false);Tick();IO.AddMousePosEvent(-100,-100);Rest();};auto Capture=[&](const char* N){int PW=int(Width*Scale),PH=int(Height*Scale);std::vector<unsigned char> Pixels(size_t(PW)*PH*3,24);for(auto* L:ImGui::GetDrawData()->CmdLists)FrontierProof::Draw(L,Pixels.data(),PW,PH,{0,0},{Scale,Scale});std::string Path=std::string("Exhibits/Gallery/StarsNative/")+N+".png";Check(stbi_write_png(Path.c_str(),PW,PH,3,Pixels.data(),PW*3)!=0,"native capture");};
 Rest();Capture("Stars-Full");auto* Props=Window("##stars-properties");ImVec2 O=Props->DC.CursorStartPos;O.x+=20;O.y+=20;float W=Props->WorkRect.GetWidth()-40;auto* Limit=Window("/Limiting magnitude_");Click({Limit->Pos.x+Limit->Size.x*.8f,Limit->Pos.y+15});Check(Scene->StarMagnitude>5.5f,"real limiting magnitude slider interaction");Capture("Stars-Faint");float CW=(W-16)/2;Click({O.x+CW+16+CW/2+85,O.y+751+158+122});Check(Scene->StarRotation>60&&Scene->StarRotation<120,"native pole dial pointer changes real rotation");float Old=Scene->StarRotation;IO.AddKeyEvent(ImGuiKey_RightArrow,true);Tick();IO.AddKeyEvent(ImGuiKey_RightArrow,false);Tick();Check(Scene->StarRotation==Old+1,"pole keyboard step");Scene->Tick(.7f,Camera,0);Scene->BuildSheet(CelestialEntity::Stars,*Sheet);Rest();Capture("Stars-Rotated");float TW=(W-60)/4;Click({O.x+26+TW+TW/2,O.y+185});Check(!Scene->StarTwinkle,"native twinkle tile toggles actual control");Capture("Stars-Steady");Click({O.x+26+TW+TW/2,O.y+185});
 Width=480;Height=2200;Rest();Capture("Stars-Narrow");Width=320;Rest();Check(Window("/Limiting magnitude_")->Size.x<=320,"compact slider fits");Height=700;Rest();Check(Window("##stars-properties")->ScrollMax.y>1200,"narrow inspector scrolls");ImGui::SetScrollY(Window("##stars-properties"),900);Rest();Capture("Stars-Scrolled");Width=1024;Height=800;Scale=2;ImGui::SetScrollY(Window("##stars-properties"),0);Rest();Capture("Stars-2x");
 Check(!Scene->LoadStarCatalogue(".cache/nonexistent-stars.bin"),"missing catalogue degrades safely");Scene->BuildSheet(CelestialEntity::Stars,*Sheet);Check(Sheet->StarPreview.Count==0&&Pack().PostStar[3]==0,"missing catalogue renders no invented stars");Rest();Capture("Stars-Unavailable");Scene->BuildSheet(CelestialEntity::Moons,*Sheet);Check(!Sheet->StarPreview.Records&&Sheet->StarPreview.Count==0,"sheet reuse clears borrowed stars");ImGui::DestroyContext();std::printf("PASS %u checks: native Stars, real catalogue, bindings, signal, ABI, pointer/keyboard input, responsive layout and teardown. No scene-camera/GPU execution claim.\n",Checks);
}
