#!/usr/bin/env python3
"""Copy approved vector artwork and emit one typed C++ identifier per SVG."""
import hashlib, json, re
from pathlib import Path
ROOT=Path(__file__).resolve().parents[3]
destination=ROOT/'EngineContent/Icons'; destination.mkdir(parents=True,exist_ok=True)
entries=[]
for path in sorted((ROOT/'Experimental/FrontierEditor/custom-icons').glob('*.svg')):
    entries.append((path.stem, ''.join(p.title() for p in path.stem.split('-')), path, path.read_text()))
for path in sorted((ROOT/'Experimental/FrontierEditor/ui-icons').glob('*.svg')):
    entries.append((path.stem, ''.join(p.title() for p in path.stem.split('-')), path, path.read_text()))
for name,source in [('FolderScene','asset-folder-scenes'),('FolderWorld','asset-folder-models'),('FolderMaterials','asset-folder-materials')]:
    path=ROOT/'Experimental/FrontierEditor/custom-icons'/f'{source}.svg'; svg=re.sub(r'<text\b[^>]*>.*?</text>','',path.read_text(),flags=re.S)
    svg=re.sub(r'<title\b[^>]*>.*?</title>','',svg,flags=re.S)
    svg=re.sub(r'\saria-labelledby="[^"]*"','',svg)
    entries.append((re.sub(r'(?<!^)(?=[A-Z])','-',name).lower(),name,path,svg))
manifest=[]; symbols=['// Generated by ImportApprovedIcons.py. No per-panel filenames.\n']
for slug,name,path,svg in entries:
    (destination/f'{slug}.svg').write_bytes(svg.encode("utf-8"))
    symbols.append(f'FRONTIER_ICON({name}, "{slug}.svg")\n')
    manifest.append({'symbol':name,'file':slug+'.svg','reference':str(path.relative_to(ROOT)),'sha256':hashlib.sha256(svg.encode()).hexdigest()})
(ROOT/'Engine/DisplayPresentation/IconSymbols.inc').write_text(''.join(symbols))
(destination/'Manifest.json').write_text(json.dumps(manifest,indent=2)+'\n')
(destination/'Slate-NOTICE.md').write_text((ROOT/'Experimental/FrontierEditor/vendor/slate-new-icons/NOTICE.md').read_text())
print(f'{len(entries)} SVGs; {len(set(x[1] for x in entries))} unique identifiers')
