/**
 * Couture Dress Presets, Debug Render Channels, Colour Palettes, and Control Definitions
 * for the Frontier Experimental WebGPU Cloth & Dress Simulator.
 * Includes Zhang et al. (ACM SIGGRAPH 2025) "Physics-inspired Estimation of Optimal Cloth Mesh Resolution" (PIE).
 */

export const DEBUG_CHANNELS = [
  { id: 0, label: "Physically shaded fabric" },
  { id: 1, label: "Warp / weft strain heatmap" },
  { id: 2, label: "2D pattern panels & seams" },
  { id: 3, label: "Procedural weave normals" },
  { id: 4, label: "Cloth velocity vectors" },
  { id: 5, label: "Avatar SDF collision field" },
  { id: 6, label: "PIE sizing map r(u,v) [SIGGRAPH '25]" },
];

export const COLOR_PALETTES = [
  { id: 0, label: "Emerald charmeuse", primary: [0.09, 0.42, 0.31], sheen: [0.55, 0.92, 0.76], trim: [0.88, 0.76, 0.48] },
  { id: 1, label: "Champagne gold satin", primary: [0.76, 0.66, 0.54], sheen: [0.98, 0.92, 0.80], trim: [0.94, 0.82, 0.56] },
  { id: 2, label: "Crimson opera velvet", primary: [0.46, 0.06, 0.12], sheen: [0.92, 0.32, 0.40], trim: [0.85, 0.68, 0.38] },
  { id: 3, label: "Midnight sapphire", primary: [0.08, 0.16, 0.38], sheen: [0.48, 0.68, 0.98], trim: [0.78, 0.84, 0.94] },
  { id: 4, label: "Rose quartz organza", primary: [0.72, 0.42, 0.48], sheen: [0.98, 0.78, 0.84], trim: [0.92, 0.78, 0.72] },
  { id: 5, label: "Obsidian atelier noir", primary: [0.11, 0.11, 0.13], sheen: [0.52, 0.54, 0.60], trim: [0.86, 0.74, 0.48] },
  { id: 6, label: "Wisteria silk chiffon", primary: [0.44, 0.36, 0.62], sheen: [0.82, 0.74, 0.98], trim: [0.88, 0.84, 0.94] },
  { id: 7, label: "Ivory bridal brocade", primary: [0.86, 0.84, 0.79], sheen: [1.00, 0.98, 0.94], trim: [0.90, 0.78, 0.52] },
  { id: 8, label: "Noir & porcelain contrast", primary: [0.025, 0.025, 0.032], sheen: [0.24, 0.25, 0.28], trim: [0.92, 0.91, 0.88] },
  { id: 9, label: "Ivory & pewter atelier", primary: [0.84, 0.82, 0.77], sheen: [0.95, 0.92, 0.87], trim: [0.47, 0.49, 0.50] },
];

// Textile library values are authored as coherent physical + visual profiles.
// Areal density is in g/m²; compliance is the XPBD stretch/shear softness; bend is normalized.
export const FABRIC_PRESETS = [
  { id: 0, label: "Silk charmeuse · 85 gsm", arealDensity: 85, windResponse: 1.00, stretchCompliance: 0.0060, shearCompliance: 0.022, bendStiffness: 0.30, damping: 0.18, clothThickness: 0.009, weaveType: 0, weaveScale: 32, weaveBump: 0.36, sheenIntensity: 1.45, fabricRoughness: 0.23, subsurfaceScatter: 0.48 },
  { id: 1, label: "Silk chiffon · 25 gsm", arealDensity: 25, windResponse: 1.85, stretchCompliance: 0.0120, shearCompliance: 0.038, bendStiffness: 0.16, damping: 0.12, clothThickness: 0.006, weaveType: 4, weaveScale: 44, weaveBump: 0.22, sheenIntensity: 0.88, fabricRoughness: 0.40, subsurfaceScatter: 1.05 },
  { id: 2, label: "Cotton poplin · 145 gsm", arealDensity: 145, windResponse: 0.67, stretchCompliance: 0.0032, shearCompliance: 0.012, bendStiffness: 0.55, damping: 0.28, clothThickness: 0.010, weaveType: 6, weaveScale: 30, weaveBump: 0.34, sheenIntensity: 0.24, fabricRoughness: 0.64, subsurfaceScatter: 0.04 },
  { id: 3, label: "Heavy cotton canvas · 320 gsm", arealDensity: 320, windResponse: 0.42, stretchCompliance: 0.0020, shearCompliance: 0.008, bendStiffness: 0.80, damping: 0.40, clothThickness: 0.016, weaveType: 7, weaveScale: 22, weaveBump: 0.58, sheenIntensity: 0.12, fabricRoughness: 0.82, subsurfaceScatter: 0.00 },
  { id: 4, label: "Raw denim · 380 gsm", arealDensity: 380, windResponse: 0.36, stretchCompliance: 0.0018, shearCompliance: 0.007, bendStiffness: 0.84, damping: 0.38, clothThickness: 0.015, weaveType: 8, weaveScale: 27, weaveBump: 0.50, sheenIntensity: 0.18, fabricRoughness: 0.72, subsurfaceScatter: 0.02 },
  { id: 5, label: "Wool suiting · 320 gsm", arealDensity: 320, windResponse: 0.40, stretchCompliance: 0.0024, shearCompliance: 0.009, bendStiffness: 0.76, damping: 0.36, clothThickness: 0.013, weaveType: 9, weaveScale: 26, weaveBump: 0.30, sheenIntensity: 0.26, fabricRoughness: 0.66, subsurfaceScatter: 0.06 },
  { id: 6, label: "Leather · 850 gsm", arealDensity: 850, windResponse: 0.18, stretchCompliance: 0.0010, shearCompliance: 0.004, bendStiffness: 0.94, damping: 0.52, clothThickness: 0.022, weaveType: 10, weaveScale: 36, weaveBump: 0.42, sheenIntensity: 0.32, fabricRoughness: 0.60, subsurfaceScatter: 0.01 },
  { id: 7, label: "Velvet · 360 gsm", arealDensity: 360, windResponse: 0.34, stretchCompliance: 0.0026, shearCompliance: 0.010, bendStiffness: 0.70, damping: 0.34, clothThickness: 0.018, weaveType: 3, weaveScale: 22, weaveBump: 0.50, sheenIntensity: 0.72, fabricRoughness: 0.48, subsurfaceScatter: 0.14 },
  { id: 8, label: "Silk organza · 38 gsm", arealDensity: 38, windResponse: 1.55, stretchCompliance: 0.0100, shearCompliance: 0.032, bendStiffness: 0.24, damping: 0.16, clothThickness: 0.006, weaveType: 4, weaveScale: 48, weaveBump: 0.18, sheenIntensity: 0.72, fabricRoughness: 0.38, subsurfaceScatter: 0.70 },
  { id: 9, label: "Jacquard brocade · 280 gsm", arealDensity: 280, windResponse: 0.48, stretchCompliance: 0.0022, shearCompliance: 0.009, bendStiffness: 0.76, damping: 0.34, clothThickness: 0.014, weaveType: 5, weaveScale: 22, weaveBump: 0.66, sheenIntensity: 0.72, fabricRoughness: 0.48, subsurfaceScatter: 0.08 },
];

export function getFabricPresetParameters(id = 0) {
  const profile = FABRIC_PRESETS.find((item) => item.id === Number(id)) || FABRIC_PRESETS[0];
  const { id: fabricPreset, label, ...properties } = profile;
  return { fabricPreset, ...properties };
}

// The solver is unit-mass XPBD. This gentle load correction approximates the greater
// gravitational tension of heavier cloth without changing the user's world gravity.
export function getFabricLoadScale(arealDensity = 85) {
  return Math.max(0.78, Math.min(1.65, 1 + 0.24 * Math.log(Math.max(20, arealDensity) / 85)));
}

export const AVATAR_FINISHES = [
  { id: 0, label: "Warm porcelain mannequin" },
  { id: 1, label: "Sculpted bronze atelier" },
  { id: 2, label: "Charcoal studio matte" },
  { id: 3, label: "Alabaster satin form" },
];

export const DEFAULT_PARAMS = {
  // Garment pattern & tailoring
  garmentEnabled: true,
  dressStyle: 0,
  skirtLength: 0.92,
  skirtFlare: 0.62,
  waistCinch: 0.84,
  necklineDepth: 0.14,
  strapWidth: 0.065,
  sleeveDrape: 0.12,
  pleatCount: 16,
  pleatDepth: 0.018,
  asymmetry: 0.0,

  // Zhang et al. 2025 (SIGGRAPH '25) PIE Optimal Mesh Resolution & Anti-Locking
  pieAutoResolution: true,
  pieAnisotropy: 1.45,
  pieLockingRelief: 0.68,
  pieShirringRatio: 0.64,
  pieDownPressure: 0.0,

  // WebGPU XPBD Solver & Physics
  gridResolution: 192,
  substeps: 14,
  stretchCompliance: 0.006,
  shearCompliance: 0.022,
  bendStiffness: 0.30,
  gravity: 9.81,
  damping: 0.18,
  clothThickness: 0.009,
  bodyFriction: 0.28,
  windEnabled: true,
  windSpeed: 1.65,
  windDirection: 28,
  windTurbulence: 0.85,
  timeScale: 1.0,
  paused: false,

  // Human Avatar Collider
  avatarVisible: true,
  avatarBodyType: 0,
  avatarPose: 0,
  avatarMotionSpeed: 1.0,
  avatarFinish: 0,

  // Procedural Fabric & Shading
  colorPalette: 0,
  weaveType: 0,
  weaveScale: 32,
  weaveBump: 0.36,
  sheenIntensity: 1.45,
  fabricRoughness: 0.23,
  hemTrim: 0.55,
  subsurfaceScatter: 0.48,
  fabricPreset: 0,
  arealDensity: 85,
  windResponse: 1.0,
  sunIntensity: 2.6,
  sunElevation: 44,
  sunAzimuth: 36,
  ambientIntensity: 0.75,
  exposure: 1.15,
  renderScale: 1.0,
  renderChannel: 0,

  // Viewport Overlays & Interaction
  showWireframe: false,
  showSeamLines: true,
  showBoundingBox: false,
  showFloorGrid: true,
  showAtlasMinimap: false,
  autoTurntable: false,
  interactionMode: "orbit",
};

export const CONTROL_GROUPS = [
  {
    title: "Pattern & Silhouette",
    controls: [
      { key: "garmentEnabled", label: "Enable dress garment", type: "toggle" },
      {
        key: "dressStyle",
        label: "Dress silhouette",
        type: "select",
        options: [
          { id: 0, label: "Bias-cut evening gown" },
          { id: 1, label: "Sunburst pleated midi" },
          { id: 2, label: "Princess couture ballgown" },
          { id: 3, label: "Satin cocktail slip" },
          { id: 4, label: "Mermaid trumpet gown" },
          { id: 5, label: "Grecian chiffon column" },
          { id: 6, label: "Asymmetric wrap dress" },
          { id: 7, label: "Velvet opera gown" },
          { id: 8, label: "Noir tuxedo pleated coat gown" },
          { id: 9, label: "Embroidered ivory wrap coat gown" },
        ],
      },
      { key: "skirtLength", label: "Skirt length", type: "range", min: 0.35, max: 1.02, step: 0.01 },
      { key: "skirtFlare", label: "Skirt flare", type: "range", min: 0.10, max: 1.35, step: 0.01 },
      { key: "waistCinch", label: "Waist cinch", type: "range", min: 0.0, max: 1.0, step: 0.01 },
      { key: "necklineDepth", label: "Neckline drop", type: "range", min: 0.03, max: 0.24, step: 0.005 },
      { key: "strapWidth", label: "Shoulder strap width", type: "range", min: 0.02, max: 0.14, step: 0.005 },
      { key: "sleeveDrape", label: "Shoulder cape drape", type: "range", min: 0.0, max: 0.40, step: 0.01 },
      { key: "pleatCount", label: "Radial pleat count", type: "range", min: 0, max: 36, step: 2 },
      { key: "pleatDepth", label: "Pleat crease depth", type: "range", min: 0.0, max: 0.045, step: 0.001 },
      { key: "asymmetry", label: "Hemline asymmetry", type: "range", min: -0.60, max: 0.60, step: 0.02 },
    ],
  },
  {
    title: "PIE Sizing & Anti-Locking (SIGGRAPH '25)",
    controls: [
      { key: "pieAutoResolution", label: "PIE adaptive sizing map", type: "toggle" },
      { key: "pieAnisotropy", label: "Warp / weft anisotropy", type: "range", min: 0.6, max: 2.5, step: 0.05 },
      { key: "pieLockingRelief", label: "Compressive locking relief", type: "range", min: 0.0, max: 1.0, step: 0.02 },
      { key: "pieShirringRatio", label: "Waist shirring ratio (ρ_sh)", type: "range", min: 0.35, max: 1.0, step: 0.02 },
      { key: "pieDownPressure", label: "Down-fill inflation (p)", type: "range", min: 0.0, max: 1.0, step: 0.02 },
    ],
  },
  {
    title: "Human Avatar & Pose",
    controls: [
      { key: "avatarVisible", label: "Show human mannequin", type: "toggle" },
      {
        key: "avatarBodyType",
        label: "Mannequin body form",
        type: "select",
        options: [
          { id: 0, label: "Female couture form" },
          { id: 1, label: "Male tailoring form" },
        ],
      },
      {
        key: "avatarPose",
        label: "Character motion",
        type: "select",
        options: [
          { id: 0, label: "Studio contrapposto" },
          { id: 1, label: "Runway catwalk stride" },
          { id: 2, label: "Couture 360° twirl" },
          { id: 3, label: "Gentle breeze sway" },
        ],
      },
      { key: "avatarMotionSpeed", label: "Motion tempo", type: "range", min: 0.2, max: 2.5, step: 0.05 },
      {
        key: "avatarFinish",
        label: "Mannequin surface",
        type: "select",
        options: AVATAR_FINISHES,
      },
      { key: "clothThickness", label: "Collision offset", type: "range", min: 0.004, max: 0.028, step: 0.001 },
      { key: "bodyFriction", label: "Skin / cloth friction", type: "range", min: 0.0, max: 0.9, step: 0.02 },
    ],
  },
  {
    title: "XPBD Solver & Wind",
    controls: [
      { key: "gridResolution", label: "Garment mesh resolution", type: "range", min: 32, max: 320, step: 8 },
      { key: "substeps", label: "XPBD substeps", type: "range", min: 4, max: 24, step: 1 },
      { key: "stretchCompliance", label: "Warp / weft stretch", type: "range", min: 0.0, max: 0.08, step: 0.001 },
      { key: "shearCompliance", label: "Bias shear drape", type: "range", min: 0.0, max: 0.15, step: 0.002 },
      { key: "bendStiffness", label: "Fold stiffness", type: "range", min: 0.05, max: 1.0, step: 0.02 },
      { key: "gravity", label: "Gravity", type: "range", min: 0.0, max: 18.0, step: 0.1 },
      { key: "damping", label: "Air damping", type: "range", min: 0.02, max: 0.85, step: 0.01 },
      { key: "timeScale", label: "Simulation speed", type: "range", min: 0.25, max: 2.0, step: 0.05 },
      { key: "windEnabled", label: "Aerodynamic wind", type: "toggle" },
      { key: "windSpeed", label: "Wind velocity", type: "range", min: 0.0, max: 8.0, step: 0.1 },
      { key: "windDirection", label: "Wind azimuth", type: "range", min: -180, max: 180, step: 5 },
      { key: "windTurbulence", label: "Gust turbulence", type: "range", min: 0.0, max: 3.0, step: 0.05 },
    ],
  },
  {
    title: "Procedural Weave & Shading",
    controls: [
      { key: "fabricPreset", label: "Fabric material preset", type: "select", options: FABRIC_PRESETS },
      { key: "arealDensity", label: "Areal weight", type: "range", min: 20, max: 1000, step: 5 },
      { key: "windResponse", label: "Wind response", type: "range", min: 0.15, max: 2.0, step: 0.05 },
      { key: "colorPalette", label: "Dye palette", type: "select", options: COLOR_PALETTES },
      {
        key: "weaveType",
        label: "Procedural weave",
        type: "select",
        options: [
          { id: 0, label: "Silk charmeuse" },
          { id: 1, label: "Satin twill" },
          { id: 2, label: "Pleated crepe" },
          { id: 3, label: "Velvet pile" },
          { id: 4, label: "Sheer organza" },
          { id: 5, label: "Sequined brocade" },
          { id: 6, label: "Cotton plain weave" },
          { id: 7, label: "Heavy canvas basket weave" },
          { id: 8, label: "Denim diagonal twill" },
          { id: 9, label: "Wool suiting nap" },
          { id: 10, label: "Leather grain" },
        ],
      },
      { key: "weaveScale", label: "Thread density", type: "range", min: 8, max: 64, step: 2 },
      { key: "weaveBump", label: "Micro-weave relief", type: "range", min: 0.0, max: 1.0, step: 0.02 },
      { key: "sheenIntensity", label: "Anisotropic sheen", type: "range", min: 0.0, max: 2.5, step: 0.05 },
      { key: "fabricRoughness", label: "Surface roughness", type: "range", min: 0.08, max: 0.95, step: 0.02 },
      { key: "hemTrim", label: "Metallic couture trim", type: "range", min: 0.0, max: 1.0, step: 0.05 },
      { key: "subsurfaceScatter", label: "Material translucency", type: "range", min: 0.0, max: 1.5, step: 0.05 },
      { key: "sunIntensity", label: "Key light intensity", type: "range", min: 0.0, max: 5.0, step: 0.1 },
      { key: "sunElevation", label: "Key light elevation", type: "range", min: 5, max: 85, step: 1 },
      { key: "sunAzimuth", label: "Key light azimuth", type: "range", min: -180, max: 180, step: 5 },
      { key: "ambientIntensity", label: "Studio fill light", type: "range", min: 0.1, max: 2.0, step: 0.05 },
      { key: "exposure", label: "Exposure", type: "range", min: 0.4, max: 2.5, step: 0.05 },
      { key: "renderScale", label: "Viewport scale", type: "range", min: 0.5, max: 1.25, step: 0.05 },
      { key: "renderChannel", label: "Render channel", type: "select", options: DEBUG_CHANNELS },
      { key: "showWireframe", label: "Cloth mesh wireframe", type: "toggle" },
      { key: "showSeamLines", label: "Pattern seam stitching", type: "toggle" },
      { key: "showBoundingBox", label: "Avatar SDF capsules", type: "toggle" },
      { key: "showFloorGrid", label: "Studio runway grid", type: "toggle" },
      { key: "showAtlasMinimap", label: "2D weave & UV minimap", type: "toggle" },
    ],
  },
];

export const PRESETS = {
  emerald_evening_gown: {
    description: "Floor-length bias-cut emerald silk charmeuse evening gown with fluid drape and gold trim.",
    params: {
      fabricPreset: 0,
      dressStyle: 0,
      skirtLength: 0.94,
      skirtFlare: 0.68,
      waistCinch: 0.85,
      necklineDepth: 0.15,
      strapWidth: 0.06,
      sleeveDrape: 0.14,
      pleatCount: 14,
      pleatDepth: 0.016,
      asymmetry: 0.0,
      colorPalette: 0,
      weaveType: 0,
      weaveScale: 32,
      sheenIntensity: 1.55,
      fabricRoughness: 0.24,
      stretchCompliance: 0.005,
      shearCompliance: 0.022,
      bendStiffness: 0.35,
      pieAnisotropy: 1.45,
      pieLockingRelief: 0.72,
      pieShirringRatio: 0.62,
      pieDownPressure: 0.0,
      windSpeed: 1.6,
      avatarPose: 0,
    },
  },
  sunburst_pleated_midi: {
    description: "High-waisted champagne cotton-poplin knife-pleated midi dress that holds its folds during runway twirls.",
    triggerTwirlOnLoad: true,
    params: {
      fabricPreset: 2,
      dressStyle: 1,
      gridResolution: 256,
      skirtLength: 0.72,
      skirtFlare: 0.78,
      waistCinch: 0.92,
      necklineDepth: 0.10,
      strapWidth: 0.075,
      sleeveDrape: 0.06,
      pleatCount: 32,
      pleatDepth: 0.034,
      asymmetry: 0.0,
      colorPalette: 1,
      weaveType: 2,
      weaveScale: 40,
      sheenIntensity: 1.25,
      fabricRoughness: 0.32,
      stretchCompliance: 0.004,
      shearCompliance: 0.012,
      bendStiffness: 0.68,
      pieAnisotropy: 1.65,
      pieLockingRelief: 0.65,
      pieShirringRatio: 0.56,
      pieDownPressure: 0.0,
      windSpeed: 2.1,
      avatarPose: 2,
    },
  },
  couture_ballgown: {
    description: "Voluminous midnight sapphire princess-seam ballgown in structured jacquard brocade.",
    params: {
      fabricPreset: 9,
      dressStyle: 2,
      skirtLength: 0.98,
      skirtFlare: 1.18,
      waistCinch: 0.96,
      necklineDepth: 0.16,
      strapWidth: 0.055,
      sleeveDrape: 0.18,
      pleatCount: 20,
      pleatDepth: 0.026,
      asymmetry: 0.0,
      colorPalette: 3,
      weaveType: 1,
      weaveScale: 26,
      sheenIntensity: 1.75,
      fabricRoughness: 0.22,
      stretchCompliance: 0.003,
      shearCompliance: 0.008,
      bendStiffness: 0.78,
      pieAnisotropy: 1.55,
      pieLockingRelief: 0.60,
      pieShirringRatio: 0.52,
      pieDownPressure: 0.18,
      windSpeed: 1.4,
      avatarPose: 0,
    },
  },
  satin_cocktail_slip: {
    description: "Knee-length rose quartz bias-cut silk satin cocktail slip dress on a runway catwalk stride.",
    params: {
      fabricPreset: 0,
      dressStyle: 3,
      skirtLength: 0.52,
      skirtFlare: 0.38,
      waistCinch: 0.76,
      necklineDepth: 0.175,
      strapWidth: 0.035,
      sleeveDrape: 0.02,
      pleatCount: 8,
      pleatDepth: 0.008,
      asymmetry: 0.0,
      colorPalette: 4,
      weaveType: 0,
      weaveScale: 36,
      sheenIntensity: 1.85,
      fabricRoughness: 0.18,
      stretchCompliance: 0.008,
      shearCompliance: 0.032,
      bendStiffness: 0.24,
      pieAnisotropy: 1.35,
      pieLockingRelief: 0.78,
      pieShirringRatio: 0.74,
      pieDownPressure: 0.0,
      windSpeed: 1.8,
      avatarPose: 1,
    },
  },
  mermaid_trumpet_gown: {
    description: "Sculpted crimson velvet mermaid gown fitted through the hips with a dramatic lower flare.",
    params: {
      fabricPreset: 7,
      dressStyle: 4,
      skirtLength: 0.96,
      skirtFlare: 0.95,
      waistCinch: 0.94,
      necklineDepth: 0.165,
      strapWidth: 0.06,
      sleeveDrape: 0.10,
      pleatCount: 18,
      pleatDepth: 0.022,
      asymmetry: 0.0,
      colorPalette: 2,
      weaveType: 3,
      weaveScale: 24,
      sheenIntensity: 1.95,
      fabricRoughness: 0.44,
      stretchCompliance: 0.004,
      shearCompliance: 0.014,
      bendStiffness: 0.52,
      pieAnisotropy: 1.50,
      pieLockingRelief: 0.66,
      pieShirringRatio: 0.58,
      pieDownPressure: 0.0,
      windSpeed: 1.5,
      avatarPose: 0,
    },
  },
  grecian_chiffon_column: {
    description: "Lightweight wisteria silk chiffon column dress billowing gracefully in a studio breeze.",
    params: {
      fabricPreset: 1,
      dressStyle: 5,
      skirtLength: 0.93,
      skirtFlare: 0.46,
      waistCinch: 0.88,
      necklineDepth: 0.12,
      strapWidth: 0.09,
      sleeveDrape: 0.28,
      pleatCount: 24,
      pleatDepth: 0.020,
      asymmetry: 0.0,
      colorPalette: 6,
      weaveType: 4,
      weaveScale: 48,
      sheenIntensity: 1.15,
      fabricRoughness: 0.36,
      subsurfaceScatter: 1.15,
      stretchCompliance: 0.010,
      shearCompliance: 0.028,
      bendStiffness: 0.18,
      pieAnisotropy: 1.25,
      pieLockingRelief: 0.85,
      pieShirringRatio: 0.48,
      pieDownPressure: 0.0,
      windSpeed: 3.4,
      windTurbulence: 1.45,
      avatarPose: 3,
    },
  },
  asymmetric_wrap_dress: {
    description: "Avant-garde obsidian cotton-twill dress with diagonal wrap cut and high-low hemline.",
    params: {
      fabricPreset: 3,
      dressStyle: 6,
      skirtLength: 0.68,
      skirtFlare: 0.64,
      waistCinch: 0.86,
      necklineDepth: 0.15,
      strapWidth: 0.07,
      sleeveDrape: 0.16,
      pleatCount: 12,
      pleatDepth: 0.015,
      asymmetry: 0.42,
      colorPalette: 5,
      weaveType: 1,
      weaveScale: 30,
      sheenIntensity: 1.40,
      fabricRoughness: 0.26,
      stretchCompliance: 0.005,
      shearCompliance: 0.016,
      bendStiffness: 0.48,
      pieAnisotropy: 1.45,
      pieLockingRelief: 0.68,
      pieShirringRatio: 0.64,
      pieDownPressure: 0.0,
      windSpeed: 2.2,
      avatarPose: 1,
    },
  },
  ivory_bridal_brocade: {
    description: "Regal ivory bridal gown with sequined jacquard brocade relief, wide train flare, and golden trim.",
    params: {
      fabricPreset: 9,
      dressStyle: 2,
      skirtLength: 1.00,
      skirtFlare: 1.08,
      waistCinch: 0.92,
      necklineDepth: 0.13,
      strapWidth: 0.08,
      sleeveDrape: 0.22,
      pleatCount: 16,
      pleatDepth: 0.024,
      asymmetry: -0.18,
      colorPalette: 7,
      weaveType: 5,
      weaveScale: 20,
      weaveBump: 0.72,
      sheenIntensity: 1.65,
      fabricRoughness: 0.25,
      hemTrim: 0.85,
      stretchCompliance: 0.004,
      shearCompliance: 0.010,
      bendStiffness: 0.64,
      pieAnisotropy: 1.60,
      pieLockingRelief: 0.62,
      pieShirringRatio: 0.55,
      pieDownPressure: 0.12,
      windSpeed: 1.5,
      avatarPose: 0,
    },
  },

  noir_tuxedo_coat_gown: {
    description: "Floor-length black tuxedo-inspired coat gown with sculpted white peak lapels, fitted long sleeves, and a fan-pleated ivory side inset.",
    params: {
      fabricPreset: 5,
      dressStyle: 8,
      skirtLength: 1.00,
      skirtFlare: 0.38,
      waistCinch: 0.94,
      necklineDepth: 0.22,
      strapWidth: 0.06,
      sleeveDrape: 0.08,
      pleatCount: 12,
      pleatDepth: 0.012,
      asymmetry: 0.0,
      colorPalette: 8,
      hemTrim: 0.08,
      avatarPose: 0,
      windSpeed: 1.25,
    },
  },
  ivory_embroidered_wrap_gown: {
    description: "Full-length ivory wrap coat gown with long cuffed sleeves, silver vine-embroidered lapels, and paired metallic frog fasteners.",
    params: {
      fabricPreset: 5,
      dressStyle: 9,
      skirtLength: 1.00,
      skirtFlare: 0.42,
      waistCinch: 0.91,
      necklineDepth: 0.23,
      strapWidth: 0.06,
      sleeveDrape: 0.06,
      pleatCount: 12,
      pleatDepth: 0.004,
      asymmetry: 0.0,
      colorPalette: 9,
      hemTrim: 0.07,
      avatarPose: 0,
      windSpeed: 0.9,
    },
  },
};
