//============================================================================================================================================
//                                                      SKELETONSTRUCTURE.JS
//============================================================================================================================================
// 🧩 Bald eagle (Haliaeetus leucocephalus) skeleton, built from published osteology rather than eyeballed proportions.
//
//    Long-bone lengths — Royal BC Museum avian osteology, bald eagle means (male/female averaged, metres):
//        humerus 0.207 · ulna 0.238 · radius 0.227 · carpometacarpus 0.112 · femur 0.156 · tibiotarsus 0.232
//        tarsometatarsus 0.096 · coracoid 0.080
//    Whole-animal: body length 0.70–1.02 m, wingspan 1.80–2.30 m, tail 0.23–0.37 m, tarsus 0.08–0.11 m, mass 3.0–6.3 kg.
//    Feather counts follow Accipitridae: 10 primaries, 17 secondaries (incl. 4 tertials), 3 alula quills, 12 rectrices.
//
//    Frame: +X = bird's LEFT, +Y = up, +Z = forward (bill direction), right-handed, metres. The bind pose is the
//    fully spread mid-glide wing with the legs standing, and every non-feather joint's bind rotation is identity, so a
//    joint's rotation axes read directly as anatomy:
//        X = long-axis rotation (pronation/supination) · Y = sweep in the wing plane (protraction/flexion) · Z = elevation.
//    Feather joints carry a bind rotation whose +X is the shaft (rachis) direction, so twist = X, spread = Y, bend = Z.
//
//    The right side is generated by mirroring the left across X; a pose quaternion authored for the left side maps to
//    the right as (x, −y, −z, w).

import { Quat, M4, V3, DEG } from "./MathSpecification.js";

export const EagleSpecification = {
    bodyLength: 0.94,          // [m] bill tip → tail tip
    wingspan: 2.10,            // [m] tip to tip, spread
    mass: 4.8,                 // [kg]
    humerus: 0.207,            // [m]
    antebrachium: 0.238,       // [m] ulna
    carpometacarpus: 0.112,    // [m]
    digit: 0.052,              // [m] major digit beyond the carpometacarpus
    femur: 0.098,              // [m] projected (femur lies inside the body wall, largely horizontal)
    tibiotarsus: 0.150,        // [m] projected
    tarsometatarsus: 0.098,    // [m]
    primaries: 10,
    secondaries: 17,
    alulaQuills: 3,
    rectrices: 12,
};

//------------------------------------------------------------------------------------------------------------------------
//                                                      JOINT DECLARATION
//------------------------------------------------------------------------------------------------------------------------

export class SkeletonStructure
{
    constructor()
    {
        this.featherPlan = [];      // every covert/scapular/tail-covert joint the geometry must grow a feather on
        this.names = [];
        this.parents = [];
        this.bindOffset = [];      // [m] translation in parent space
        this.bindRotation = [];    // quaternion in parent space
        this.index = new Map();
        this.Build();
        this.Finalise();
    }

    AddJoint(name, parent, offset, rotation = Quat.identity())
    {
        const i = this.names.length;
        this.names.push(name);
        this.parents.push(parent === null ? -1 : this.index.get(parent));
        this.bindOffset.push(offset);
        this.bindRotation.push(rotation);
        this.index.set(name, i);
        return i;
    }

    Query(name) { return this.index.get(name); }

    // Bind position available *during* Build (every ancestor in the axial/limb chains has an identity bind rotation,
    //    so the world position is just the running sum of offsets).
    Anchor(name)
    {
        let i = this.index.get(name);
        const p = [0, 0, 0];
        while (i !== undefined && i >= 0)
        {
            p[0] += this.bindOffset[i][0]; p[1] += this.bindOffset[i][1]; p[2] += this.bindOffset[i][2];
            i = this.parents[i];
        }
        return p;
    }

    //--------------------------------------------------------------------------------------------------------------------
    //                                                     AXIAL SKELETON
    //--------------------------------------------------------------------------------------------------------------------

    Build()
    {
        const S = EagleSpecification;

        this.AddJoint("root", null, [0, 0, 0]);
        this.AddJoint("pelvis", "root", [0, 0, 0]);
        this.AddJoint("spine01", "pelvis", [0, 0.012, 0.088]);
        this.AddJoint("spine02", "spine01", [0, 0.014, 0.098]);
        this.AddJoint("chest", "spine02", [0, 0.006, 0.098]);

        // Cervical column: an eagle has 14 free cervicals; five animation joints reproduce the S-curve and carry the
        //    180°+ head turn distributed along the neck (no single joint exceeds ~40°).
        this.AddJoint("neck01", "chest", [0, 0.038, 0.030]);
        this.AddJoint("neck02", "neck01", [0, 0.038, -0.004]);
        this.AddJoint("neck03", "neck02", [0, 0.036, -0.006]);
        this.AddJoint("neck04", "neck03", [0, 0.030, 0.016]);
        this.AddJoint("neck05", "neck04", [0, 0.022, 0.030]);
        this.AddJoint("skull", "neck05", [0, 0.010, 0.036]);
        this.AddJoint("jaw", "skull", [0, -0.012, 0.030]);

        this.AddJoint("tailBase", "pelvis", [0, 0.028, -0.115]);

        for (const side of [1, -1])
        {
            const T = side > 0 ? "L" : "R";
            this.BuildWing(T, side, S);
            this.BuildLeg(T, side, S);
        }
        this.BuildTailFeathers(S);
        this.BuildTailCoverts();
    }

    //--------------------------------------------------------------------------------------------------------------------
    //                                                      WING CHAIN
    //--------------------------------------------------------------------------------------------------------------------

    BuildWing(T, side, S)
    {
        // Shoulder (glenoid) sits high and forward on the chest; the humerus runs out and very slightly back.
        this.AddJoint(`shoulder${T}`, "chest", [side * 0.050, 0.022, -0.006]);
        this.AddJoint(`elbow${T}`, `shoulder${T}`, [side * S.humerus * 0.985, 0.0, -0.028]);
        this.AddJoint(`wrist${T}`, `elbow${T}`, [side * S.antebrachium * 0.99, 0.0, -0.018]);
        this.AddJoint(`hand${T}`, `wrist${T}`, [side * 0.012, 0.0, 0.004]);
        this.AddJoint(`digit${T}`, `hand${T}`, [side * S.carpometacarpus, 0.0, 0.006]);
        this.AddJoint(`alula${T}`, `wrist${T}`, [side * 0.018, 0.004, 0.030]);

        // ── Remiges ───────────────────────────────────────────────────────────────────────────────────────────────────
        // Primaries P1 (innermost) … P10 (outermost) grow from the carpometacarpus and major digit. Emergence angle
        //    measured from the span axis swings from ~62° inboard to ~12° at the tip; the longest quills are P8–P9
        //    (0.46 m) with P10 slightly shorter — this is what produces the eagle's slotted "fingered" tip.
        for (let i = 0; i < S.primaries; ++i)
        {
            const t = i / (S.primaries - 1);
            const along = 0.004 + t * (S.carpometacarpus + S.digit - 0.010);   // [m] station along the hand
            const sweep = (62.0 - 50.0 * Math.pow(t, 0.85)) * DEG;             // [rad] back from the span axis
            const dihedral = (-1.0 + 5.0 * t) * DEG;
            this.AddJoint(`primary${T}${i}`, `hand${T}`,
                [side * along, -0.004 - 0.002 * t, -0.012 - 0.004 * t],
                MirrorQuaternion(Quat.fromEuler(0, sweep, dihedral), side));
        }

        // Secondaries S1 (at the wrist) … S17 (tertials at the body). They trail almost straight aft off the ulna.
        for (let i = 0; i < S.secondaries; ++i)
        {
            const t = i / (S.secondaries - 1);
            const along = 0.012 + (1.0 - t) * (S.antebrachium - 0.024);
            const sweep = (74.0 + 14.0 * t) * DEG;
            const dihedral = (-2.0 - 2.0 * t) * DEG;
            this.AddJoint(`secondary${T}${i}`, `elbow${T}`,
                [side * along, -0.004, -0.014],
                MirrorQuaternion(Quat.fromEuler(0, sweep, dihedral), side));
        }

        this.BuildCovertRows(T, side, S);

        // Alula (bastard wing): three short quills on the thumb, deployed as a leading-edge slat at high angle of attack.
        for (let i = 0; i < S.alulaQuills; ++i)
        {
            const t = i / (S.alulaQuills - 1);
            this.AddJoint(`alulaQuill${T}${i}`, `alula${T}`,
                [side * (0.002 + t * 0.016), 0.001, 0.004 - t * 0.004],
                MirrorQuaternion(Quat.fromEuler(0, (34.0 - 10.0 * t) * DEG, (4.0 + 4.0 * t) * DEG), side));
        }
    }


    //--------------------------------------------------------------------------------------------------------------------
    //                                                     COVERT ROWS
    //--------------------------------------------------------------------------------------------------------------------

    // Coverts get their own joints too. A folded wing turns the forearm through ~170°, so a covert rigidly bound to
    //    the ulna would end up pointing at the bird's face; with a joint each, every row can be re-aimed like the
    //    remiges and can carry its own secondary motion.
    BuildCovertRows(T, side, S)
    {
        const shoulder = this.Anchor(`shoulder${T}`), elbow = this.Anchor(`elbow${T}`);
        const wrist = this.Anchor(`wrist${T}`), digit = this.Anchor(`digit${T}`);
        const Mix = (a, b, t, o) => [a[0] + (b[0] - a[0]) * t + o[0] * side, a[1] + (b[1] - a[1]) * t + o[1], a[2] + (b[2] - a[2]) * t + o[2]];

        const rows = [
            // id                 count  from    to        offset A               offset B              sweep      dihedral  length          tone
            { id: "greaterCovert", n: 17, a: wrist, b: elbow, oa: [-0.010, 0.014, -0.010], ob: [0.005, 0.014, -0.010], sweep: [76, 88], dih: [-6, -6], len: [0.125, 0.105], tone: 0 },
            { id: "medianCovert", n: 16, a: wrist, b: elbow, oa: [-0.012, 0.020, 0.010], ob: [0.004, 0.020, 0.012], sweep: [74, 86], dih: [-4, -4], len: [0.082, 0.072], tone: 0 },
            { id: "lesserCovert", n: 14, a: wrist, b: elbow, oa: [-0.015, 0.023, 0.026], ob: [0.004, 0.024, 0.030], sweep: [70, 84], dih: [-2, -2], len: [0.055, 0.050], tone: 1 },
            { id: "marginalCovert", n: 16, a: wrist, b: shoulder, oa: [-0.020, 0.018, 0.050], ob: [0.020, 0.020, 0.030], sweep: [58, 74], dih: [2, 2], len: [0.040, 0.052], tone: 1 },
            { id: "primaryCovert", n: 10, a: wrist, b: digit, oa: [0.004, 0.012, 0.004], ob: [-0.006, 0.010, 0.008], sweep: [58, 26], dih: [-4, -4], len: [0.115, 0.075], tone: 2 },
            { id: "underCovert", n: 15, a: wrist, b: elbow, oa: [-0.010, -0.016, -0.004], ob: [0.005, -0.018, -0.004], sweep: [78, 90], dih: [6, 6], len: [0.100, 0.088], tone: 1 },
            { id: "underPrimaryCovert", n: 9, a: wrist, b: digit, oa: [0.006, -0.012, 0.004], ob: [-0.008, -0.010, 0.008], sweep: [56, 26], dih: [5, 5], len: [0.090, 0.060], tone: 0 },
        ];

        for (const row of rows)
        {
            for (let i = 0; i < row.n; ++i)
            {
                const t = row.n === 1 ? 0 : i / (row.n - 1);
                const offset = [row.oa[0] + (row.ob[0] - row.oa[0]) * t, row.oa[1] + (row.ob[1] - row.oa[1]) * t, row.oa[2] + (row.ob[2] - row.oa[2]) * t];
                const position = Mix(row.a, row.b, t, offset);
                // Parent to the bone the station lies *along* (not the next joint outboard), so every covert keeps a
                //    short, positive offset down its own bone and folds with it instead of being flung across the body.
                const span = Math.abs(position[0]);
                let parent = `shoulder${T}`;
                if (span > Math.abs(wrist[0])) parent = `hand${T}`;
                else if (span > Math.abs(elbow[0])) parent = `elbow${T}`;
                const anchor = this.Anchor(parent);
                const name = `${row.id}${T}${i}`;
                this.AddJoint(name, parent, [position[0] - anchor[0], position[1] - anchor[1], position[2] - anchor[2]],
                    MirrorQuaternion(Quat.fromEuler(0, (row.sweep[0] + (row.sweep[1] - row.sweep[0]) * t) * DEG,
                        (row.dih[0] + (row.dih[1] - row.dih[0]) * t) * DEG), side));
                this.featherPlan.push({
                    name, side, row: row.id, index: i, fraction: t,
                    length: row.len[0] + (row.len[1] - row.len[0]) * t, tone: row.tone,
                    seed: this.featherPlan.length,
                });
            }
        }

        // Scapulars bridging the wing root into the mantle.
        for (let i = 0; i < 9; ++i)
        {
            const t = i / 8;
            const position = [shoulder[0] + side * (-0.014 - 0.020 * t), shoulder[1] + 0.006 - 0.020 * t, shoulder[2] - 0.016 - 0.092 * t];
            const anchor = this.Anchor("chest");
            const name = `scapular${T}${i}`;
            this.AddJoint(name, "chest", [position[0] - anchor[0], position[1] - anchor[1], position[2] - anchor[2]],
                MirrorQuaternion(Quat.fromEuler(0, (104 + 22 * t) * DEG, (-16 - 10 * t) * DEG), side));
            this.featherPlan.push({ name, side, row: "scapular", index: i, fraction: t, length: 0.135 - 0.030 * t, tone: 0, seed: 900 + i });
        }
    }

    //--------------------------------------------------------------------------------------------------------------------
    //                                                       LEG CHAIN
    //--------------------------------------------------------------------------------------------------------------------

    BuildLeg(T, side, S)
    {
        // Avian leg: the femur is short and held nearly horizontal inside the body outline, the knee is hidden under the
        //    flank feathers, the visible "backwards knee" is the intertarsal (ankle) joint.
        this.AddJoint(`hip${T}`, "pelvis", [side * 0.036, -0.014, 0.020]);
        this.AddJoint(`knee${T}`, `hip${T}`, [side * 0.012, -0.062, 0.072]);
        this.AddJoint(`ankle${T}`, `knee${T}`, [side * 0.004, -0.146, -0.030]);
        this.AddJoint(`foot${T}`, `ankle${T}`, [side * -0.002, -0.094, 0.026]);

        // Anisodactyl foot: hallux (digit I) back, digits II–IV forward, all tipped with talons.
        const toes = [
            { name: "hallux", yaw: 180.0, spread: 0.0 },
            { name: "toe2", yaw: -26.0, spread: 0.0 },
            { name: "toe3", yaw: 0.0, spread: 0.0 },
            { name: "toe4", yaw: 30.0, spread: 0.0 },
        ];
        for (const toe of toes)
        {
            this.AddJoint(`${toe.name}${T}`, `foot${T}`, [side * 0.004, -0.004, 0.006],
                MirrorQuaternion(Quat.fromEuler(0, toe.yaw * DEG, 0), side));
        }
    }

    //--------------------------------------------------------------------------------------------------------------------
    //                                                    RECTRICES (TAIL)
    //--------------------------------------------------------------------------------------------------------------------

    BuildTailFeathers(S)
    {
        // 12 rectrices in overlapping pairs from the central pair outwards; central pair sits on top.
        for (let i = 0; i < S.rectrices; ++i)
        {
            const pairIndex = Math.floor(i / 2);                    // 0 = central pair
            const side = i % 2 === 0 ? 1 : -1;
            const spread = side * pairIndex * 7.0 * DEG;            // [rad] closed-tail fan angle
            this.AddJoint(`rectrix${i}`, "tailBase",
                [side * pairIndex * 0.004, 0.004 - pairIndex * 0.0025, -0.004],
                Quat.fromEuler(0, 90.0 * DEG - spread, side * pairIndex * 1.5 * DEG));
        }
    }

    BuildTailCoverts()
    {
        const tail = this.Anchor("tailBase");
        for (let i = 0; i < 12; ++i)
        {
            const t = i / 11;
            const lateral = (t - 0.5) * 2.0;
            for (const sign of [1, -1])
            {
                const name = `tailCovert${sign > 0 ? "U" : "D"}${i}`;
                this.AddJoint(name, "tailBase",
                    [lateral * 0.030, sign * 0.016, 0.004 - Math.abs(lateral) * 0.006],
                    Quat.fromEuler(0, (90 - lateral * 16) * DEG, sign * -8 * DEG));
                this.featherPlan.push({
                    name, side: lateral >= 0 ? 1 : -1, row: sign > 0 ? "tailCovertUpper" : "tailCovertLower",
                    index: i, fraction: t, length: 0.085 - Math.abs(lateral) * 0.016, tone: 3, seed: 1100 + i * 2 + (sign > 0 ? 0 : 1),
                });
            }
        }
    }

    //--------------------------------------------------------------------------------------------------------------------
    //                                                 BIND POSE / INVERSE BIND
    //--------------------------------------------------------------------------------------------------------------------

    Finalise()
    {
        const N = this.names.length;
        this.count = N;
        this.scratch = [];
        this.bindWorld = [];
        this.inverseBind = [];
        for (let i = 0; i < N; ++i)
        {
            const local = M4.compose(this.bindOffset[i], this.bindRotation[i]);
            this.scratch.push(new Float32Array(16));
            const p = this.parents[i];
            this.bindWorld.push(p < 0 ? local : M4.multiply(this.bindWorld[p], local));
            this.inverseBind.push(M4.invert(this.bindWorld[i]));
        }
    }

    // World-space bind position of a joint — used when laying out geometry around the skeleton.
    BindPosition(name)
    {
        const m = this.bindWorld[this.Query(name)];
        return [m[12], m[13], m[14]];
    }

    BindMatrix(name) { return this.bindWorld[this.Query(name)]; }

    // Composes a pose (array of local quaternions + optional local translations) into skinning matrices.
    Pose(localRotation, localTranslation, outWorld, outSkinning)
    {
        const N = this.count;
        for (let i = 0; i < N; ++i)
        {
            const q = localRotation[i] ? Quat.multiply(this.bindRotation[i], localRotation[i]) : this.bindRotation[i];
            const t = localTranslation && localTranslation[i]
                ? V3.add(this.bindOffset[i], localTranslation[i]) : this.bindOffset[i];
            const local = M4.compose(t, q, [1, 1, 1], this.scratch[i]);
            const p = this.parents[i];
            if (p < 0) outWorld[i].set(local);
            else M4.multiply(outWorld[p], local, outWorld[i]);
            M4.multiply(outWorld[i], this.inverseBind[i], outSkinning[i]);
        }
    }
}

// Mirrors a left-side pose quaternion to the right side (reflection across the X = 0 plane).
export function MirrorQuaternion(q, side)
{
    return side > 0 ? q : [q[0], -q[1], -q[2], q[3]];
}
