#include "CelestialSequence.h"
#include "InspectorPanel.h"
#include "ControlPanel.h"
#include "CloudDensityPreview.h"
#include "CpuDraw.h"
#include "PngWriteCounterpart.h"
#include <imgui_internal.h>
#include <memory>
#include <cstring>
#include <cstdio>
#include <limits>
#include <stdexcept>
using namespace Frontier;using namespace Frontier::ProjectZero;
static unsigned Checks=0;static void Check(bool V,const char* N){++Checks;if(!V)throw std::runtime_error(N);}
static EditorProperty& Find(EditorSheet& S,const char* N){for(auto& G:S.Groups)for(unsigned I=0;I<G.PropertyCount;++I)if(!std::strcmp(G.Properties[I].Label,N))return G.Properties[I];throw std::runtime_error(N);}
static ImGuiWindow* Window(const char* N){for(auto* W:ImGui::GetCurrentContext()->Windows)if(W->Active&&std::strstr(W->Name,N))return W;throw std::runtime_error(N);}
int main(){
 auto Scene=std::make_unique<CelestialSequence>();auto Sheet=std::make_unique<EditorSheet>();auto Raster=std::make_unique<VisibilityRaster>();const float Camera[]={0,0,2};Scene->Enabled=true;Scene->Clock.Animate=false;Scene->Cloud.Enabled=true;Scene->LocalCloud.Enabled=true;Scene->Shown[unsigned(CelestialEntity::CloudLayer)]=Scene->Shown[unsigned(CelestialEntity::LocalCloud)]=true;CelestialEntity Entity=CelestialEntity::CloudLayer;
 auto Apply=[&](){Scene->ApplySheet(Entity,*Sheet);Scene->Tick(0,Camera,0);Scene->BuildSheet(Entity,*Sheet);};Scene->Tick(0,Camera,0);
 for(auto E:{CelestialEntity::CloudLayer,CelestialEntity::LocalCloud}){Entity=E;Scene->BuildSheet(E,*Sheet);Check(Sheet->Appearance==(E==CelestialEntity::CloudLayer?EditorSheetAppearance::GlobalCloud:EditorSheetAppearance::LocalCloud),"both scopes route to native clouds");for(const char* N:{"Coverage","Density","Feature Scale","Anisotropy"}){auto& P=Find(*Sheet,N);float V=P.Minimum+(P.Maximum-P.Minimum)*.6f;P.Figure=V;Apply();Check(std::abs(Find(*Sheet,N).Figure-V)<1e-5f,"scope scalar round trip");Find(*Sheet,N).Figure=std::numeric_limits<float>::infinity();Apply();Check(Find(*Sheet,N).Figure==V,"nonfinite scalar rejected");Find(*Sheet,N).Figure=-100;Apply();Check(Find(*Sheet,N).Figure==Find(*Sheet,N).Minimum,"lower range clamp");Find(*Sheet,N).Figure=10000;Apply();Check(Find(*Sheet,N).Figure==Find(*Sheet,N).Maximum,"upper range clamp");}Find(*Sheet,"Coverage").Figure=.55f;Find(*Sheet,"Density").Figure=1.4f;Find(*Sheet,"Feature Scale").Figure=E==CelestialEntity::CloudLayer?.7f:120.f;Find(*Sheet,"Anisotropy").Figure=.45f;Apply();}
 auto& Centre=Find(*Sheet,"Centre");auto& Half=Find(*Sheet,"Half Size");Centre.Axes[0]=120;Half.Axes[0]=-2;Half.Axes[1]=std::numeric_limits<float>::quiet_NaN();float Old=Scene->LocalCloud.HalfSize[1];Apply();Check(Scene->LocalCloud.Centre[0]==120&&Scene->LocalCloud.HalfSize[0]==.1f&&Scene->LocalCloud.HalfSize[1]==Old,"finite position and positive half extents enforced");Find(*Sheet,"Half Size").Axes[0]=300;Apply();float Move[]={-100,70,420};Scene->MoveMarker(unsigned(CelestialEntity::LocalCloud),Move);Scene->BuildSheet(Entity,*Sheet);Check(Find(*Sheet,"Centre").Axes[2]==420,"existing volume marker feeds native coordinates");VolumeMarker Markers[2];Check(Scene->CollectMarkers(Markers,2)>=1,"enabled local cloud keeps its existing marker");
 Entity=CelestialEntity::CloudLayer;Scene->BuildSheet(Entity,*Sheet);Find(*Sheet,"Base").Figure=19000;Find(*Sheet,"Ceiling").Figure=5000;Apply();Check(Scene->Cloud.Base==5000,"base clamps to updated ceiling");Find(*Sheet,"Base").Figure=1400;Find(*Sheet,"Ceiling").Figure=14000;Find(*Sheet,"Thickness").Figure=1800;Find(*Sheet,"Anvil").Figure=.7f;Apply();Check(Scene->Cloud.Anvil==.7f,"global anvil reaches real density model");Scene->ApplyTo(*Raster,CelestialBudget{});const auto& C=Raster->QueryCelestial();Check(C.CloudLayer.Enabled&&C.LocalCloud.Enabled,"both volumes staged together");Check(C.CloudLayer.Coverage==Scene->Cloud.Coverage&&C.LocalCloud.Coverage==Scene->LocalCloud.Coverage,"independent coverage reaches CPU staging");Check(C.LocalCloud.Centre[0]==Scene->LocalCloud.Centre[0]&&C.LocalCloud.HalfSize[0]==Scene->LocalCloud.HalfSize[0],"actual CPU local bounds agree");Check(C.CloudLayer.Anvil==Scene->Cloud.Anvil&&C.CloudLayer.Anisotropy==Scene->Cloud.Anisotropy,"global shape and scattering staged");
 std::vector<unsigned char> Top(32*16*4),Side(Top.size()),Clear(Top.size());auto G=Scene->Cloud;auto L=Scene->LocalCloud;G.Coverage=0;CloudDensityPreview(Clear.data(),Side.data(),32,16,G,L,false);G.Coverage=.55f;CloudDensityPreview(Top.data(),Side.data(),32,16,G,L,false);Check(Top!=Clear,"global continuous mask comes from density");auto Mid=Top;G.Coverage=1;CloudDensityPreview(Top.data(),Side.data(),32,16,G,L,false);Check(Top!=Mid,"higher global coverage changes mask");for(size_t I=0;I<Top.size();I+=4)Check(Top[I]>=Mid[I],"global mask monotonically fills gaps");L.Coverage=0;CloudDensityPreview(Clear.data(),Side.data(),32,16,G,L,true);L.Coverage=.8f;CloudDensityPreview(Top.data(),Side.data(),32,16,G,L,true);Check(Top!=Clear,"local mask uses real bounded density");auto LocalImage=Top;L.Centre[0]+=127;CloudDensityPreview(Top.data(),Side.data(),32,16,G,L,true);Check(Top!=LocalImage,"world translation changes world-anchored local noise");L.Enabled=false;CloudDensityPreview(Top.data(),Side.data(),32,16,G,L,true);Check(Top==Clear,"disabled local volume has no fabricated density");
 // Exercise the actual shared CPU volumetric march, not merely the diagnostic image.
 G.Enabled=true;G.Base=1000;G.Thickness=700;G.Coverage=1;G.Density=1;G.FollowWind=false;L.Enabled=true;L.Centre[0]=L.Centre[1]=0;L.Centre[2]=300;L.HalfSize[0]=L.HalfSize[1]=L.HalfSize[2]=150;L.Coverage=1;L.Density=1;L.FollowWind=false;float Origin[]={0,0,0},Ray[]={0,0,1},Sun[]={0,0,1},Radiance[]={1,1,1},Ambient[]={.1f,.1f,.1f};auto March=[&](){return VolumetricMedia::March(G,L,{},WindSettings{},VolumetricBudget{},Origin,Ray,4000,Sun,Radiance,Ambient,0);};auto Both=March();L.Enabled=false;auto Global=March();L.Enabled=true;G.Enabled=false;auto Local=March();G.Enabled=false;L.Enabled=false;auto Empty=March();Check(Global.Transmittance<1&&Local.Transmittance<1,"global and local each attenuate actual marched light");Check(Both.Transmittance<=std::min(Global.Transmittance,Local.Transmittance)+1e-5f,"combined march includes both media");Check(Both.Scatter[0]>0&&Both.StepsTaken>0&&Both.ShadowMarches>0,"combined clouds scatter and self-shadow");Check(Empty.Transmittance==1&&Empty.StepsTaken==0,"disabled volumes skip real march");
 ImGui::CreateContext();auto& IO=ImGui::GetIO();IO.IniFilename=nullptr;IO.DeltaTime=1.f/60;IO.BackendFlags|=ImGuiBackendFlags_RendererHasTextures|ImGuiBackendFlags_RendererHasVtxOffset;ImGui::StyleColorsDark();auto& Style=ImGui::GetStyle();Style.WindowPadding={0,0};Style.WindowRounding=0;Style.WindowBorderSize=0;Style.Colors[ImGuiCol_WindowBg]={.105f,.105f,.105f,1};Style.Colors[ImGuiCol_TitleBgActive]={.075f,.075f,.075f,1};auto Controls=std::make_unique<ControlPanel>();auto Inspector=std::make_unique<InspectorPanel>();Inspector->AssignControls(Controls.get());auto Row=std::make_unique<EditorInstance>();std::snprintf(Row->Label,sizeof(Row->Label),"Clouds");Row->Category=EditorInstanceCategory::Geometry;int Width=1024,Height=1850;float Scale=1;
 auto Tick=[&](){IO.DisplaySize={float(Width),float(Height)};IO.DisplayFramebufferScale={Scale,Scale};ImGui::NewFrame();ImGui::SetNextWindowPos({0,0});ImGui::SetNextWindowSize(IO.DisplaySize);Inspector->Record(Row.get(),0,Sheet.get());Apply();ImGui::Render();FrontierProof::AcknowledgeTextures();};auto Rest=[&](){for(int I=0;I<3;++I)Tick();};auto Click=[&](ImVec2 V){IO.AddMousePosEvent(V.x,V.y);Tick();IO.AddMouseButtonEvent(0,true);Tick();IO.AddMouseButtonEvent(0,false);Tick();IO.AddMousePosEvent(-100,-100);Rest();};auto Capture=[&](const char* N){int PW=int(Width*Scale),PH=int(Height*Scale);std::vector<unsigned char> Pixels(size_t(PW)*PH*3,24);for(auto* D:ImGui::GetDrawData()->CmdLists)FrontierProof::Draw(D,Pixels.data(),PW,PH,{0,0},{Scale,Scale});std::string Path=std::string("Exhibits/Gallery/CloudsNative/")+N+".png";Check(stbi_write_png(Path.c_str(),PW,PH,3,Pixels.data(),PW*3)!=0,"native capture");};
 Rest();Capture("Clouds-Global");auto* Props=Window("##cloud-properties");ImVec2 O=Props->DC.CursorStartPos;O.x+=20;O.y+=20;auto* Slider=Window("/Coverage_");Click({Slider->Pos.x+Slider->Size.x*.8f,Slider->Pos.y+15});Check(Scene->Cloud.Coverage>.7f&&Scene->Cloud.Coverage<=1,"native coverage percent converts to real 0..1 control");Capture("Clouds-Global-Dense");Click({O.x+160,O.y+717+220});Check(Scene->Cloud.Base>5000,"native base diagram edits altitude");float OldBase=Scene->Cloud.Base;IO.AddKeyEvent(ImGuiKey_UpArrow,true);Tick();IO.AddKeyEvent(ImGuiKey_UpArrow,false);Tick();Check(Scene->Cloud.Base==OldBase+100,"base diagram keyboard step");Find(*Sheet,"Base").Figure=1400;Find(*Sheet,"Coverage").Figure=.55f;Apply();
 Entity=CelestialEntity::LocalCloud;Scene->BuildSheet(Entity,*Sheet);Rest();Capture("Clouds-Local");float GlobalCoverage=Scene->Cloud.Coverage;Slider=Window("/Coverage_");Click({Slider->Pos.x+Slider->Size.x*.85f,Slider->Pos.y+15});Check(Scene->LocalCloud.Coverage>.7f&&Scene->Cloud.Coverage==GlobalCoverage,"local UI edits do not change global layer");auto* Axis=Window("/Centre_");float X=Scene->LocalCloud.Centre[0];IO.AddMousePosEvent(Axis->Pos.x+10,Axis->Pos.y+13);Tick();IO.AddMouseButtonEvent(0,true);Tick();IO.AddMousePosEvent(Axis->Pos.x+90,Axis->Pos.y+13);Tick();IO.AddMouseButtonEvent(0,false);Tick();Rest();Check(Scene->LocalCloud.Centre[0]!=X,"native local centre axis drag");Capture("Clouds-Local-Moved");Click({O.x+80,O.y+192});Check(!Scene->LocalCloud.Enabled&&Scene->Cloud.Enabled,"local enable tile does not disable global layer");Capture("Clouds-Local-Disabled");Click({O.x+80,O.y+192});
 Width=480;Height=2450;Rest();Capture("Clouds-Local-Narrow");Entity=CelestialEntity::CloudLayer;Scene->BuildSheet(Entity,*Sheet);Rest();Capture("Clouds-Global-Narrow");Width=320;Height=850;Rest();Check(Window("/Coverage_")->Size.x<=320,"compact coverage slider fits");Check(Window("##cloud-properties")->ScrollMax.y>1000,"narrow clouds scroll");ImGui::SetScrollY(Window("##cloud-properties"),1200);Rest();Capture("Clouds-Scrolled");Width=1024;Height=900;Scale=2;ImGui::SetScrollY(Window("##cloud-properties"),0);Rest();Capture("Clouds-2x");Scene->BuildSheet(CelestialEntity::LocalFog,*Sheet);Check(Sheet->Appearance==EditorSheetAppearance::LocalFog,"local fog has its own native route");ImGui::DestroyContext();std::printf("PASS %u checks: global and local native clouds together, real density projections, shared CPU volume march, bindings, input, invalid values, bounds and teardown. No full GPU cloud-volume claim.\n",Checks);
}
