// src/presets.js
// Atmospheric and Sea State Presets for GTA 6 / AAA Graphics Fidelity

export const PRESETS = {
  TROPICAL: {
    name: '🏝️ Tropical Paradise',
    description: 'Crystal-clear turquoise lagoon, gentle rolling swells, visible seabed caustics',
    windSpeed: 6.5,
    windAngle: Math.PI * 0.2,
    waveAmplitude: 0.65,
    waveSteepness: 0.85,
    waveSpeed: 0.95,
    sunElevation: 62.0,
    sunAzimuth: 40.0,
    turbidity: 1.8,
    waterClarity: 1.9,
    sssIntensity: 1.35,
    foamEmissionRate: 0.65,
    sprayIntensity: 0.45,
    bioluminescence: 0.0,
    deepColor: 0x06324b,
    shallowColor: 0x009ea8,
    sssColor: 0x18e8b0
  },

  OPEN_OCEAN: {
    name: '🌊 Open Ocean Swell',
    description: 'Deep Atlantic blue, 3m cascading ocean swells, cross-seas, and Langmuir foam streaks',
    windSpeed: 13.5,
    windAngle: Math.PI * 0.35,
    waveAmplitude: 1.25,
    waveSteepness: 1.05,
    waveSpeed: 1.0,
    sunElevation: 36.0,
    sunAzimuth: 55.0,
    turbidity: 2.3,
    waterClarity: 1.0,
    sssIntensity: 1.1,
    foamEmissionRate: 1.25,
    sprayIntensity: 1.0,
    bioluminescence: 0.0,
    deepColor: 0x04162a,
    shallowColor: 0x0a4d68,
    sssColor: 0x0bd09c
  },

  STORM: {
    name: '⛈️ North Atlantic Storm (Beaufort 8)',
    description: 'Giant 5.5m turbulent swells, 45-knot gale wind, violent breaking crests and heavy spray spindrift',
    windSpeed: 24.0,
    windAngle: Math.PI * 0.42,
    waveAmplitude: 2.3,
    waveSteepness: 1.35,
    waveSpeed: 1.18,
    sunElevation: 18.0,
    sunAzimuth: 120.0,
    turbidity: 4.8,
    waterClarity: 0.55,
    sssIntensity: 0.85,
    foamEmissionRate: 2.4,
    sprayIntensity: 2.6,
    bioluminescence: 0.0,
    deepColor: 0x050e18,
    shallowColor: 0x142c3d,
    sssColor: 0x1f7278
  },

  GOLDEN_HOUR: {
    name: '🌅 Golden Hour Sunset',
    description: 'Cinematic low sun, fiery golden specular path, backlit glowing wave crests and warm spray glitter',
    windSpeed: 9.5,
    windAngle: Math.PI * 0.15,
    waveAmplitude: 0.95,
    waveSteepness: 1.0,
    waveSpeed: 0.92,
    sunElevation: 8.5,
    sunAzimuth: 65.0,
    turbidity: 2.8,
    waterClarity: 1.2,
    sssIntensity: 1.6,
    foamEmissionRate: 0.95,
    sprayIntensity: 1.1,
    bioluminescence: 0.0,
    deepColor: 0x071e33,
    shallowColor: 0x13546b,
    sssColor: 0x22f2aa
  },

  BIOLUMINESCENT: {
    name: '🌌 Midnight Bioluminescence',
    description: 'Silvery moonlit ocean where breaking waves and boat wake ignite electric neon-cyan glowing particles',
    windSpeed: 10.5,
    windAngle: Math.PI * 0.25,
    waveAmplitude: 1.05,
    waveSteepness: 1.1,
    waveSpeed: 0.9,
    sunElevation: -14.0,
    sunAzimuth: 50.0,
    turbidity: 1.5,
    waterClarity: 1.4,
    sssIntensity: 0.4,
    foamEmissionRate: 1.6,
    sprayIntensity: 1.3,
    bioluminescence: 1.0,
    deepColor: 0x01050c,
    shallowColor: 0x021626,
    sssColor: 0x028880
  }
};
