// Slate Pre-configured Terrain Presets modeled after Gaea recipes

import type { TerrainLayer } from '../types/terrain';

export interface TerrainPreset {
  id: string;
  name: string;
  description: string;
  badge: string;
  layers: TerrainLayer[];
}

export const TERRAIN_PRESETS: TerrainPreset[] = [
  {
    id: 'alpine_glacial_horn',
    name: 'Alpine Glacial Horn & Valleys',
    description: 'Knife-edge arêtes, glacial cirques, deep fluvial gorges, and talus scree aprons.',
    badge: 'Alpine / Fluvial',
    layers: [
      {
        id: 'gen_ridge',
        name: 'Alpine Ridge Spine',
        type: 'ridge_generator',
        enabled: true,
        opacity: 1.0,
        blendMode: 'normal',
        maskAltitudeMin: 0,
        maskAltitudeMax: 1,
        maskSlopeMin: 0,
        maskSlopeMax: 90,
        maskInvert: false,
        scale: 1.6,
        height: 0.95,
        octaves: 6,
        gain: 0.55,
        sharpness: 2.2,
        seed: 4281,
      },
      {
        id: 'gen_mountains',
        name: 'Secondary Peaks',
        type: 'mountain_generator',
        enabled: true,
        opacity: 0.45,
        blendMode: 'add',
        maskAltitudeMin: 0,
        maskAltitudeMax: 1,
        maskSlopeMin: 0,
        maskSlopeMax: 90,
        maskInvert: false,
        scale: 2.5,
        height: 0.5,
        octaves: 5,
        roughness: 0.45,
        lacunarity: 2.0,
        peakSharpness: 2.0,
        seed: 8812,
      },
      {
        id: 'sculpt_layer',
        name: 'SDF Sculpt & Directed Cuts',
        type: 'sdf_sculpt',
        enabled: true,
        opacity: 1.0,
        blendMode: 'normal',
        maskAltitudeMin: 0,
        maskAltitudeMax: 1,
        maskSlopeMin: 0,
        maskSlopeMax: 90,
        maskInvert: false,
        strokes: [],
      },
      {
        id: 'rain_layer',
        name: 'Orographic Precipitation',
        type: 'rain_precipitation',
        enabled: true,
        opacity: 1.0,
        blendMode: 'normal',
        maskAltitudeMin: 0,
        maskAltitudeMax: 1,
        maskSlopeMin: 0,
        maskSlopeMax: 90,
        maskInvert: false,
        precipitationAmount: 1.2,
        windAngle: 135,
        windStrength: 0.65,
        altitudeMin: 0.25,
        altitudeMax: 0.9,
        rainShadowStrength: 0.7,
        dropletCount: 50000,
        seed: 3912,
      },
      {
        id: 'hydraulic_layer',
        name: 'Hydraulic Fluvial Incision',
        type: 'hydraulic_erosion',
        enabled: true,
        opacity: 1.0,
        blendMode: 'normal',
        maskAltitudeMin: 0,
        maskAltitudeMax: 1,
        maskSlopeMin: 0,
        maskSlopeMax: 90,
        maskInvert: false,
        iterations: 60,
        erosionScale: 1.1,
        downcutting: 0.65,
        inhibition: 0.4,
        baseLevel: 0.12,
        sedimentCapacity: 0.18,
        depositionRate: 0.12,
        evaporationRate: 0.02,
        rockSoftness: 0.65,
        sedimentRemoval: 0.1,
        seed: 7721,
      },
      {
        id: 'rocky_layer',
        name: 'Talus Scree & Rock Shatter',
        type: 'rocky_thermal',
        enabled: true,
        opacity: 0.85,
        blendMode: 'normal',
        maskAltitudeMin: 0,
        maskAltitudeMax: 1,
        maskSlopeMin: 0,
        maskSlopeMax: 90,
        maskInvert: false,
        iterations: 25,
        angleRepose: 34,
        talusVolume: 0.7,
        rockSoftness: 0.5,
        shatterStrength: 0.35,
        shatterScale: 28.0,
        strataSteps: 8,
        seed: 9012,
      },
      {
        id: 'alluvial_layer',
        name: 'Valley Alluvial Fill',
        type: 'alluvial_deposits',
        enabled: true,
        opacity: 0.7,
        blendMode: 'normal',
        maskAltitudeMin: 0,
        maskAltitudeMax: 1,
        maskSlopeMin: 0,
        maskSlopeMax: 90,
        maskInvert: false,
        iterations: 15,
        amount: 0.35,
        settling: 0.6,
        hardness: 0.4,
        power: 1.2,
        chaos: 0.25,
        mode: 'valley_fans',
        seed: 6614,
      },
      {
        id: 'satmap_layer',
        name: 'Alpine SatMap Grading',
        type: 'satmap_color',
        enabled: true,
        opacity: 1.0,
        blendMode: 'normal',
        maskAltitudeMin: 0,
        maskAltitudeMax: 1,
        maskSlopeMin: 0,
        maskSlopeMax: 90,
        maskInvert: false,
        presetId: 'rocky_alpine_granite',
        category: 'rocky',
        driver: 'composite',
        slopeInfluence: 0.7,
        altitudeBias: 0.05,
        rockHighlightStrength: 0.65,
        flowWetness: 0.75,
        depositSiltBlend: 0.7,
        contrast: 1.2,
        brightness: 0.02,
        saturation: 1.1,
      },
    ],
  },
  {
    id: 'grand_canyon_ravine',
    name: 'Grand Canyon Strata & Ravines',
    description: 'Terraced sedimentary tablelands cut by profound river downcutting and red rock scree.',
    badge: 'Canyon / Strata',
    layers: [
      {
        id: 'gen_mesa',
        name: 'Table Mesa Plateau',
        type: 'plateau_generator',
        enabled: true,
        opacity: 1.0,
        blendMode: 'normal',
        maskAltitudeMin: 0,
        maskAltitudeMax: 1,
        maskSlopeMin: 0,
        maskSlopeMax: 90,
        maskInvert: false,
        scale: 1.3,
        height: 0.9,
        bevelWidth: 0.2,
        terraceSteps: 6,
        roughness: 0.3,
        seed: 2049,
      },
      {
        id: 'gen_canyon',
        name: 'Sinuous River Gorge',
        type: 'canyon_generator',
        enabled: true,
        opacity: 0.9,
        blendMode: 'multiply',
        maskAltitudeMin: 0,
        maskAltitudeMax: 1,
        maskSlopeMin: 0,
        maskSlopeMax: 90,
        maskInvert: false,
        depth: 0.75,
        width: 0.24,
        meander: 1.4,
        terraces: 4,
        seed: 512,
      },
      {
        id: 'sculpt_layer',
        name: 'SDF Sculpt & Directed Cuts',
        type: 'sdf_sculpt',
        enabled: true,
        opacity: 1.0,
        blendMode: 'normal',
        maskAltitudeMin: 0,
        maskAltitudeMax: 1,
        maskSlopeMin: 0,
        maskSlopeMax: 90,
        maskInvert: false,
        strokes: [],
      },
      {
        id: 'strata_mod',
        name: 'Sedimentary Beds',
        type: 'strata_terrace',
        enabled: true,
        opacity: 0.5,
        blendMode: 'normal',
        maskAltitudeMin: 0,
        maskAltitudeMax: 1,
        maskSlopeMin: 0,
        maskSlopeMax: 90,
        maskInvert: false,
        frequency: 14,
        sharpness: 0.8,
        warpStrength: 0.15,
      },
      {
        id: 'hydraulic_layer',
        name: 'Deep Canyon Downcutting',
        type: 'hydraulic_erosion',
        enabled: true,
        opacity: 1.0,
        blendMode: 'normal',
        maskAltitudeMin: 0,
        maskAltitudeMax: 1,
        maskSlopeMin: 0,
        maskSlopeMax: 90,
        maskInvert: false,
        iterations: 75,
        erosionScale: 1.4,
        downcutting: 0.85,
        inhibition: 0.35,
        baseLevel: 0.08,
        sedimentCapacity: 0.25,
        depositionRate: 0.1,
        evaporationRate: 0.015,
        rockSoftness: 0.75,
        sedimentRemoval: 0.25,
        seed: 9411,
      },
      {
        id: 'satmap_layer',
        name: 'Grand Canyon SatMap',
        type: 'satmap_color',
        enabled: true,
        opacity: 1.0,
        blendMode: 'normal',
        maskAltitudeMin: 0,
        maskAltitudeMax: 1,
        maskSlopeMin: 0,
        maskSlopeMax: 90,
        maskInvert: false,
        presetId: 'rocky_grand_canyon',
        category: 'rocky',
        driver: 'composite',
        slopeInfluence: 0.75,
        altitudeBias: 0.0,
        rockHighlightStrength: 0.7,
        flowWetness: 0.85,
        depositSiltBlend: 0.8,
        contrast: 1.25,
        brightness: 0.0,
        saturation: 1.2,
      },
    ],
  },
  {
    id: 'shattered_slope',
    name: 'Gaea Shattered Slope Recipe',
    description: 'Perturbed Voronoi cell facets eroded into dramatic jagged rock spurs and crevice deposits.',
    badge: 'Gaea Classic',
    layers: [
      {
        id: 'gen_voronoi',
        name: 'Displaced Voronoi Facets',
        type: 'voronoi_generator',
        enabled: true,
        opacity: 1.0,
        blendMode: 'normal',
        maskAltitudeMin: 0,
        maskAltitudeMax: 1,
        maskSlopeMin: 0,
        maskSlopeMax: 90,
        maskInvert: false,
        scale: 1.8,
        height: 0.9,
        jitter: 0.85,
        ridgeSharpness: 1.5,
        inverted: false,
        seed: 6732,
      },
      {
        id: 'mod_displace',
        name: 'Domain Perturb',
        type: 'displace_perturb',
        enabled: true,
        opacity: 0.6,
        blendMode: 'normal',
        maskAltitudeMin: 0,
        maskAltitudeMax: 1,
        maskSlopeMin: 0,
        maskSlopeMax: 90,
        maskInvert: false,
        strength: 0.35,
        frequency: 4.5,
        seed: 1289,
      },
      {
        id: 'sculpt_layer',
        name: 'SDF Sculpt & Directed Cuts',
        type: 'sdf_sculpt',
        enabled: true,
        opacity: 1.0,
        blendMode: 'normal',
        maskAltitudeMin: 0,
        maskAltitudeMax: 1,
        maskSlopeMin: 0,
        maskSlopeMax: 90,
        maskInvert: false,
        strokes: [],
      },
      {
        id: 'hydraulic_layer',
        name: 'Fluvial Groove Erosion',
        type: 'hydraulic_erosion',
        enabled: true,
        opacity: 1.0,
        blendMode: 'normal',
        maskAltitudeMin: 0,
        maskAltitudeMax: 1,
        maskSlopeMin: 0,
        maskSlopeMax: 90,
        maskInvert: false,
        iterations: 50,
        erosionScale: 0.9,
        downcutting: 0.5,
        inhibition: 0.5,
        baseLevel: 0.1,
        sedimentCapacity: 0.16,
        depositionRate: 0.14,
        evaporationRate: 0.02,
        rockSoftness: 0.6,
        sedimentRemoval: 0.05,
        seed: 4501,
      },
      {
        id: 'rocky_layer',
        name: 'Rocky Shatter & Talus',
        type: 'rocky_thermal',
        enabled: true,
        opacity: 0.9,
        blendMode: 'normal',
        maskAltitudeMin: 0,
        maskAltitudeMax: 1,
        maskSlopeMin: 0,
        maskSlopeMax: 90,
        maskInvert: false,
        iterations: 30,
        angleRepose: 36,
        talusVolume: 0.8,
        rockSoftness: 0.6,
        shatterStrength: 0.45,
        shatterScale: 32.0,
        strataSteps: 0,
        seed: 8321,
      },
      {
        id: 'satmap_layer',
        name: 'Dolomite / Glencoe Grading',
        type: 'satmap_color',
        enabled: true,
        opacity: 1.0,
        blendMode: 'normal',
        maskAltitudeMin: 0,
        maskAltitudeMax: 1,
        maskSlopeMin: 0,
        maskSlopeMax: 90,
        maskInvert: false,
        presetId: 'rocky_dolomite_crags',
        category: 'rocky',
        driver: 'composite',
        slopeInfluence: 0.6,
        altitudeBias: 0.0,
        rockHighlightStrength: 0.8,
        flowWetness: 0.6,
        depositSiltBlend: 0.7,
        contrast: 1.15,
        brightness: 0.0,
        saturation: 1.05,
      },
    ],
  },
  {
    id: 'volcanic_caldera',
    name: 'Icelandic Volcanic Caldera',
    description: 'Massive impact caldera rim, resurgent volcanic cone, and neon moss on dark basalt.',
    badge: 'Volcanic / Basin',
    layers: [
      {
        id: 'gen_caldera',
        name: 'Volcanic Caldera Basin',
        type: 'caldera_generator',
        enabled: true,
        opacity: 1.0,
        blendMode: 'normal',
        maskAltitudeMin: 0,
        maskAltitudeMax: 1,
        maskSlopeMin: 0,
        maskSlopeMax: 90,
        maskInvert: false,
        radius: 0.45,
        rimHeight: 0.4,
        floorDepth: 0.35,
        centralConeHeight: 0.25,
        roughness: 0.45,
        seed: 9918,
      },
      {
        id: 'sculpt_layer',
        name: 'SDF Sculpt & Directed Cuts',
        type: 'sdf_sculpt',
        enabled: true,
        opacity: 1.0,
        blendMode: 'normal',
        maskAltitudeMin: 0,
        maskAltitudeMax: 1,
        maskSlopeMin: 0,
        maskSlopeMax: 90,
        maskInvert: false,
        strokes: [],
      },
      {
        id: 'hydraulic_layer',
        name: 'Radial Caldera Runoff',
        type: 'hydraulic_erosion',
        enabled: true,
        opacity: 0.9,
        blendMode: 'normal',
        maskAltitudeMin: 0,
        maskAltitudeMax: 1,
        maskSlopeMin: 0,
        maskSlopeMax: 90,
        maskInvert: false,
        iterations: 50,
        erosionScale: 0.85,
        downcutting: 0.45,
        inhibition: 0.45,
        baseLevel: 0.15,
        sedimentCapacity: 0.2,
        depositionRate: 0.16,
        evaporationRate: 0.025,
        rockSoftness: 0.8,
        sedimentRemoval: 0.0,
        seed: 3102,
      },
      {
        id: 'satmap_layer',
        name: 'Iceland Moss SatMap',
        type: 'satmap_color',
        enabled: true,
        opacity: 1.0,
        blendMode: 'normal',
        maskAltitudeMin: 0,
        maskAltitudeMax: 1,
        maskSlopeMin: 0,
        maskSlopeMax: 90,
        maskInvert: false,
        presetId: 'volcanic_iceland_moss',
        category: 'volcanic',
        driver: 'composite',
        slopeInfluence: 0.7,
        altitudeBias: -0.05,
        rockHighlightStrength: 0.6,
        flowWetness: 0.9,
        depositSiltBlend: 0.85,
        contrast: 1.25,
        brightness: 0.0,
        saturation: 1.3,
      },
    ],
  },
  {
    id: 'badlands_danxia',
    name: 'Danxia Rainbow Badlands',
    description: 'Hyper-dense gully networks cutting through multicolored mineral strata.',
    badge: 'Badlands / Minerals',
    layers: [
      {
        id: 'gen_voronoi',
        name: 'Badland Facets',
        type: 'voronoi_generator',
        enabled: true,
        opacity: 1.0,
        blendMode: 'normal',
        maskAltitudeMin: 0,
        maskAltitudeMax: 1,
        maskSlopeMin: 0,
        maskSlopeMax: 90,
        maskInvert: false,
        scale: 2.2,
        height: 0.85,
        jitter: 0.9,
        ridgeSharpness: 1.8,
        inverted: false,
        seed: 5543,
      },
      {
        id: 'strata_mod',
        name: 'Mineral Strata Beds',
        type: 'strata_terrace',
        enabled: true,
        opacity: 0.7,
        blendMode: 'normal',
        maskAltitudeMin: 0,
        maskAltitudeMax: 1,
        maskSlopeMin: 0,
        maskSlopeMax: 90,
        maskInvert: false,
        frequency: 20,
        sharpness: 0.9,
        warpStrength: 0.2,
      },
      {
        id: 'sculpt_layer',
        name: 'SDF Sculpt & Directed Cuts',
        type: 'sdf_sculpt',
        enabled: true,
        opacity: 1.0,
        blendMode: 'normal',
        maskAltitudeMin: 0,
        maskAltitudeMax: 1,
        maskSlopeMin: 0,
        maskSlopeMax: 90,
        maskInvert: false,
        strokes: [],
      },
      {
        id: 'hydraulic_layer',
        name: 'Dense Gully Downcutting',
        type: 'hydraulic_erosion',
        enabled: true,
        opacity: 1.0,
        blendMode: 'normal',
        maskAltitudeMin: 0,
        maskAltitudeMax: 1,
        maskSlopeMin: 0,
        maskSlopeMax: 90,
        maskInvert: false,
        iterations: 70,
        erosionScale: 0.6,
        downcutting: 0.75,
        inhibition: 0.3,
        baseLevel: 0.05,
        sedimentCapacity: 0.22,
        depositionRate: 0.1,
        evaporationRate: 0.018,
        rockSoftness: 0.9,
        sedimentRemoval: 0.2,
        seed: 2841,
      },
      {
        id: 'satmap_layer',
        name: 'Danxia Rainbow SatMap',
        type: 'satmap_color',
        enabled: true,
        opacity: 1.0,
        blendMode: 'normal',
        maskAltitudeMin: 0,
        maskAltitudeMax: 1,
        maskSlopeMin: 0,
        maskSlopeMax: 90,
        maskInvert: false,
        presetId: 'badlands_danxia_rainbow',
        category: 'badlands',
        driver: 'composite',
        slopeInfluence: 0.8,
        altitudeBias: 0.0,
        rockHighlightStrength: 0.7,
        flowWetness: 0.7,
        depositSiltBlend: 0.7,
        contrast: 1.25,
        brightness: 0.02,
        saturation: 1.25,
      },
    ],
  },
];
