#include "FogInspectorPanel.h"
#include "WindBindingControls.h"
#include "ControlPanel.h"
#include "SunReferenceDraw.h"
#include "FogModel.h"
#include <array>
#include <imgui_internal.h>
#include <cstdio>
#include <cstring>
namespace Frontier { namespace {
using namespace SunReference;
constexpr ImU32 Ink=IM_COL32(233,233,233,255),Muted=IM_COL32(145,145,145,255);
EditorProperty* Find(EditorSheet& S,const char* N){for(auto& G:S.Groups)for(unsigned I=0;I<G.PropertyCount;++I)if(!std::strcmp(G.Properties[I].Label,N))return &G.Properties[I];return nullptr;}
struct Panel {
 ControlPanel& Controls;EditorSheet& Sheet;ImDrawList* D;ImVec2 O;ImFont* Font;
 ImVec2 At(float X,float Y){return {O.x+X,O.y+Y};}
 void Text(float X,float Y,const char* T,float Size=12,ImU32 C=Ink){D->AddText(Font,Size,At(X,Y),C,T);}
 void Wrap(float X,float Y,float W,const char* T){D->AddText(Font,11,At(X,Y),Muted,T,nullptr,W);}
 void Card(float X,float Y,float W,float H,const char* Title){int Start=D->VtxBuffer.Size;D->AddRectFilled(At(X,Y),At(X+W,Y+H),IM_COL32_WHITE,22);ImGui::ShadeVertsLinearColorGradientKeepAlpha(D,Start,D->VtxBuffer.Size,At(X,Y),At(X+W,Y+H),IM_COL32(37,37,37,255),IM_COL32(32,32,32,255));D->AddRect(At(X,Y),At(X+W,Y+H),IM_COL32(52,52,52,255),22);Text(X+24,Y+23,Title);}
 void Slider(float X,float Y,float W,const char* N){auto& P=*Find(Sheet,N);Text(X,Y,N,11,Muted);ImGui::SetCursorScreenPos(At(X,Y+22));ImGui::PushID(N);ImGui::BeginChild(N,{W,30},ImGuiChildFlags_None,ImGuiWindowFlags_NoScrollbar|ImGuiWindowFlags_NoScrollWithMouse);Controls.SliderPill("##value",&P.Figure,P.Minimum,P.Maximum,P.Decimals,P.Unit,false,false,true);ImGui::EndChild();ImGui::PopID();}
 void Tile(float X,float Y,float W,const char* N,bool* Value){ImGui::SetCursorScreenPos(At(X,Y));ImGui::BeginDisabled(!Value);if(ImGui::InvisibleButton(N,{W,65})&&Value)*Value=!*Value;ImGui::EndDisabled();bool On=Value&&*Value;ImU32 C=!Value?Muted:On?IM_COL32(131,207,158,255):IM_COL32(221,137,137,255);D->AddRectFilled(At(X,Y),At(X+W,Y+65),IM_COL32(34,34,34,255),13);D->AddRect(At(X,Y),At(X+W,Y+65),IM_COL32(56,56,56,255),13);if(Value){D->AddCircle(At(X+W/2,Y+20),7,C,20,1.4f);D->AddLine(At(X+W/2,Y+10),At(X+W/2,Y+18),C,1.5f);}else{float M=X+W/2;D->AddRect(At(M-7,Y+15),At(M+7,Y+28),C,2);D->AddLine(At(M-11,Y+12),At(M+2,Y+12),C,1.4f);D->AddLine(At(M-2,Y+8),At(M+2,Y+12),C,1.4f);D->AddLine(At(M-2,Y+16),At(M+2,Y+12),C,1.4f);}float L=Font->CalcTextSizeA(10,10000,0,N).x;Text(X+(W-L)/2,Y+42,N,10,C);}
};
struct Models {FogSettings Fog;AtmosphereMedium Air;LocalVolumeSettings Volume;bool Local=false,Aerial=false;};
Models Read(EditorSheet& S){Models M;M.Local=S.Appearance==EditorSheetAppearance::LocalFog;M.Aerial=S.Appearance==EditorSheetAppearance::AerialFog;auto F=[&](const char* N){return Find(S,N)->Figure;};bool On=Find(S,"Enabled")->On;
 for(int C=0;C<3;++C){M.Air.RayleighScattering[C]=S.FogPreview.Rayleigh[C];}M.Air.MieScattering=S.FogPreview.Mie;M.Air.RayleighScaleHeight=S.FogPreview.RayleighHeight;M.Air.MieScaleHeight=S.FogPreview.MieHeight;
 if(M.Local){auto& V=M.Volume;V.Enabled=On;V.Density=F("Density");V.Coverage=F("Coverage");V.Scale=F("Feature Scale");V.Anisotropy=F("Anisotropy");V.FollowWind=Find(S,"Follow Wind")->On;for(int C=0;C<3;++C){V.Centre[C]=Find(S,"Centre")->Axes[C];V.HalfSize[C]=Find(S,"Half Size")->Axes[C];}}
 else if(M.Aerial){M.Fog.AerialEnabled=On;M.Fog.AerialDensity=F("Density");M.Fog.AerialStart=F("Start");M.Fog.AerialMie=F("Mie Blend");}
 else{M.Fog.HeightEnabled=On;M.Fog.HeightDensity=F("Density");M.Fog.FalloffHeight=F("Falloff Height");M.Fog.SunScatter=F("Sun Scatter");for(int C=0;C<3;++C)M.Fog.HeightColour[C]=Find(S,"Colour")->ColourTint[C];}return M;}
void Sample(const Models& M,float D,float T[3],float RGB[3]){if(M.Local){auto S=FogModel::LocalProbe(M.Volume,D);for(int C=0;C<3;++C){T[C]=S.Transmittance;RGB[C]=.8f*T[C]+S.Scatter[C];}}else{FogModel::Transmission(M.Fog,M.Air,2,2,D,T);AtmosphereLight L;L.Direction[0]=0;L.Direction[1]=L.Direction[2]=.70710678f;L.Intensity=1;float Dir[]={0,1,0},Ambient[]={.18f,.18f,.18f};for(int C=0;C<3;++C)RGB[C]=.8f;FogModel::Apply(M.Fog,M.Air,L,2,2,D,Dir,Ambient,RGB);}}
struct Profile {std::array<float,32> Key{};float Values[65][3]{};bool Valid=false;};
void Cleanup(ImGuiContext*,ImGuiContextHook* H){delete static_cast<Profile*>(H->UserData);}
Profile& Cache(){constexpr ImGuiID Owner=0x464f4730;for(auto& H:ImGui::GetCurrentContext()->Hooks)if(H.Owner==Owner)return *static_cast<Profile*>(H.UserData);auto* P=new Profile;ImGuiContextHook H;H.Owner=Owner;H.Type=ImGuiContextHookType_Shutdown;H.Callback=Cleanup;H.UserData=P;ImGui::AddContextHook(ImGui::GetCurrentContext(),&H);return *P;}
void Update(Profile& P,const Models& M,float Range){const auto& F=M.Fog;const auto& V=M.Volume;const auto& A=M.Air;std::array<float,32> K={float(M.Local),float(M.Aerial),Range,float(F.HeightEnabled),F.HeightDensity,F.FalloffHeight,F.SunScatter,float(F.AerialEnabled),F.AerialDensity,F.AerialStart,F.AerialMie,float(V.Enabled),V.Density,V.Coverage,V.Scale,V.Anisotropy,V.Centre[0],V.Centre[1],V.Centre[2],V.HalfSize[0],V.HalfSize[1],V.HalfSize[2],A.RayleighScattering[0],A.RayleighScattering[1],A.RayleighScattering[2],A.MieScattering,A.RayleighScaleHeight,A.MieScaleHeight,F.HeightColour[0],F.HeightColour[1],F.HeightColour[2],float(V.FollowWind)};if(P.Valid&&K==P.Key)return;P.Valid=true;P.Key=K;for(int I=0;I<=64;++I){float RGB[3];Sample(M,Range*I/64,P.Values[I],RGB);}}
void Axes(Panel& U,float X,float Y,float W,const char* N,const char* Caption){auto& P=*Find(U.Sheet,N);U.Text(X,Y,Caption,11,Muted);ImGui::SetCursorScreenPos(U.At(X,Y+24));ImGui::BeginChild(N,{W,32},ImGuiChildFlags_None,ImGuiWindowFlags_NoScrollbar|ImGuiWindowFlags_NoScrollWithMouse);U.Controls.AxisVec3("##axes",P.Axes,1,true);ImGui::EndChild();}
}
void RecordFogInspector(ControlPanel& Controls,EditorInstance&,EditorSheet& Sheet){
 RecordWindBindingControls(Sheet);
 if(!Find(Sheet,"Density")||!Find(Sheet,"Enabled")){ImGui::TextUnformatted("Fog properties unavailable");return;}
 auto* Font=ImGui::GetFont();for(auto* F:ImGui::GetIO().Fonts->Fonts)if(!std::strcmp(F->GetDebugName(),"Sun reference / regular"))Font=F;ImGui::PushFont(Font,14);ImGui::PushID(static_cast<int>(Sheet.Appearance));ImVec2 O=ImGui::GetCursorScreenPos();O.x+=20;O.y+=20;float W=std::max(240.f,ImGui::GetContentRegionAvail().x-40);Panel U{Controls,Sheet,ImGui::GetWindowDrawList(),O,Font};Models M=Read(Sheet);char Text[160];
 U.Text(0,8,"Inspector / Environment",8,Muted);U.Text(0,48,"Fog",25);U.Text(0,83,M.Local?"LOCAL VOLUMETRIC FOG · bounded medium":M.Aerial?"AERIAL PERSPECTIVE · surface-distance fog":"HEIGHT FOG · exponential vertical density",10,Muted);
 U.Card(0,110,W,142,"Fog settings");U.Tile(24,164,112,"Enabled",&Find(Sheet,"Enabled")->On);if(M.Local)U.Tile(148,164,std::min(132.f,W-172),"Follow wind",&Find(Sheet,"Follow Wind")->On);
 float Range=M.Local?2*M.Volume.HalfSize[1]:M.Aerial?20000:500;ImGuiID ProbeID=ImGui::GetID("##probe-distance");float Probe=std::clamp(ImGui::GetStateStorage()->GetFloat(ProbeID,Range*.4f),0.f,Range);auto& P=Cache();Update(P,M,Range);float T[3],RGB[3];Sample(M,Probe,T,RGB);float Mean=T[0]*.2126f+T[1]*.7152f+T[2]*.0722f;
 U.Card(0,268,W,435,"Visibility through fog");std::snprintf(Text,sizeof(Text),"%.1f%%",double(Mean*100));U.Text(24,331,Text,32);std::snprintf(Text,sizeof(Text),"Light transmitted at %.0f m",double(Probe));U.Wrap(24,378,W-48,Text);U.Wrap(24,402,W-48,M.Local?"Sampled +Y path through the volume centre · static at time zero":"Horizontal probe at world Z = 2 m · selected medium only");
 float X0=48,X1=W-28,Y0=459,Y1=594;U.D->AddRectFilled(U.At(X0-8,Y0-12),U.At(X1+8,Y1+12),IM_COL32(26,30,33,255),12);for(int I=0;I<3;++I){float Y=Y0+(Y1-Y0)*I*.5f;U.D->AddLine(U.At(X0,Y),U.At(X1,Y),IM_COL32(147,178,182,28));}U.Text(12,Y0-5,"100",9,Muted);U.Text(25,Y1-5,"0",9,Muted);
 const ImU32 Colours[]={IM_COL32(203,142,142,255),IM_COL32(153,204,165,255),IM_COL32(150,184,225,255)};
 for(int C=0;C<(M.Aerial?3:1);++C)for(int I=1;I<=64;++I)U.D->AddLine(U.At(X0+(X1-X0)*(I-1)/64,Y1-P.Values[I-1][C]*(Y1-Y0)),U.At(X0+(X1-X0)*I/64,Y1-P.Values[I][C]*(Y1-Y0)),M.Aerial?Colours[C]:IM_COL32(168,209,210,255),1.6f);
 float PX=X0+Probe/Range*(X1-X0);U.D->AddLine(U.At(PX,Y0),U.At(PX,Y1),IM_COL32(206,224,221,65));U.D->AddCircleFilled(U.At(PX,Y1-Mean*(Y1-Y0)),4,IM_COL32(217,234,230,255));ImGui::SetCursorScreenPos(U.At(X0,Y0-12));ImGui::InvisibleButton("##fog-probe",{X1-X0,Y1-Y0+24},ImGuiButtonFlags_EnableNav);if(ImGui::IsItemActive()&&ImGui::IsMouseDown(0))Probe=std::clamp((ImGui::GetIO().MousePos.x-U.At(X0,0).x)/(X1-X0)*Range,0.f,Range);if(ImGui::IsItemFocused()){float Step=Range/100;if(ImGui::IsKeyPressed(ImGuiKey_LeftArrow))Probe=std::max(0.f,Probe-Step);if(ImGui::IsKeyPressed(ImGuiKey_RightArrow))Probe=std::min(Range,Probe+Step);if(ImGui::IsKeyPressed(ImGuiKey_Home))Probe=0;}ImGui::GetStateStorage()->SetFloat(ProbeID,Probe);
 U.Text(X0,614,"0 m",10,Muted);std::snprintf(Text,sizeof(Text),"%.0f m",double(Range));U.Text(X1-54,614,Text,10,Muted);U.Wrap(24,647,W-48,"Drag the probe · arrow keys adjust diagnostic distance, not scene settings");
 bool Wide=W>=760;float CW=Wide?(W-16)/2:W,X2=Wide?CW+16:0,Y=719,Y2=Wide?Y:Y+432;
 U.Card(0,Y,CW,416,"Medium");U.Slider(24,Y+66,CW-48,"Density");U.Slider(24,Y+145,CW-48,M.Local?"Coverage":M.Aerial?"Start":"Falloff Height");U.Slider(24,Y+224,CW-48,M.Local?"Feature Scale":M.Aerial?"Mie Blend":"Sun Scatter");if(M.Local)U.Slider(24,Y+303,CW-48,"Anisotropy");else U.Wrap(24,Y+324,CW-48,M.Aerial?"Uses the current atmosphere coefficients. Mie blend moves from spectral Rayleigh extinction toward grey aerosol extinction.":"Height fog uses the reference exp(-optical depth²) law. Falloff is the e-folding height; sun scatter changes in-scattered light, not extinction.");
 U.Card(X2,Y2,CW,416,M.Local?"Local bounds":M.Aerial?"Spectral transmission":"Height and tint");
 if(M.Local){auto& V=M.Volume;std::snprintf(Text,sizeof(Text),"%.0f × %.0f × %.0f m",double(V.HalfSize[0]*2),double(V.HalfSize[1]*2),double(V.HalfSize[2]*2));U.Wrap(X2+24,Y2+64,CW-48,Text);Canvas C=Fit(U.D,U.At(X2+24,Y2+95),{CW-48,162},340,200);float Max=std::max({V.HalfSize[0],V.HalfSize[1],V.HalfSize[2],.1f});float SX=V.HalfSize[0]/Max*85,SY=V.HalfSize[1]/Max*45,SZ=V.HalfSize[2]/Max*80;auto Q=[&](int I){float X=I&1?SX:-SX,T0=I&2?SY:-SY,Z=I&4?SZ:-SZ;return ImVec2(170+X+T0,100+T0*.5f-Z);};for(int I=0;I<8;++I)for(int Bit:{1,2,4})if(!(I&Bit))C.Line(Q(I),Q(I|Bit),Colour(159,194,193,.65f));C.Line({170-SY,100-SY*.5f},{170+SY,100+SY*.5f},Colour(217,233,228),1.8f);C.Text(170,194,"Centre probe · +Y direction",Muted,9);
  Axes(U,X2+24,Y2+270,CW-48,"Centre","Centre · world X / Y / Z (m)");Axes(U,X2+24,Y2+343,CW-48,"Half Size","Half extents · X / Y / Z (m)");
 }else if(M.Aerial){for(int C=0;C<3;++C){std::snprintf(Text,sizeof(Text),"%s     %.1f%%",C==0?"RED":C==1?"GREEN":"BLUE",double(T[C]*100));U.Text(X2+24,Y2+76+C*61,Text,22,Colours[C]);}U.Wrap(X2+24,Y2+277,CW-48,"At the selected probe distance. These values come from the same analytic extinction used by the CPU surface renderer.");}
 else{U.Wrap(X2+24,Y2+64,CW-48,"Relative density versus height above world Z = 0");float L=X2+50,R=X2+CW-30,Top=Y2+112,Bottom=Y2+265;U.D->AddLine(U.At(L,Top),U.At(L,Bottom),IM_COL32(130,164,165,100));U.D->AddLine(U.At(L,Bottom),U.At(R,Bottom),IM_COL32(130,164,165,100));for(int I=1;I<=64;++I){float H0=(I-1)*3000.f/64,H1=I*3000.f/64;U.D->AddLine(U.At(L+std::exp(-H0/M.Fog.FalloffHeight)*(R-L),Bottom-H0/3000*(Bottom-Top)),U.At(L+std::exp(-H1/M.Fog.FalloffHeight)*(R-L),Bottom-H1/3000*(Bottom-Top)),IM_COL32(168,209,210,255),1.5f);}U.Text(X2+24,Top-16,"3 km",9,Muted);U.Text(X2+24,Bottom+9,"0 m",9,Muted);U.Text(R-54,Bottom+9,"100%",9,Muted);U.Text(X2+24,Y2+329,"Fog tint · linear RGB",11,Muted);ImGui::SetCursorScreenPos(U.At(X2+24,Y2+353));ImGui::BeginChild("Colour",{CW-48,32},ImGuiChildFlags_None,ImGuiWindowFlags_NoScrollbar);Controls.ColourChip("##fog-colour",Find(Sheet,"Colour")->ColourTint);ImGui::EndChild();}
 float End=Y2+432;U.Card(0,End,W,132,"Neutral-light reference");for(int C=0;C<3;++C)RGB[C]=std::clamp(RGB[C],0.f,1.f);U.D->AddRectFilled(U.At(24,End+67),U.At(70,End+108),Colour(255*RGB[0],255*RGB[1],255*RGB[2]),8);U.Wrap(88,End+67,W-112,"A neutral target through this medium under fixed probe lighting. Not a scene-camera render; changing scattering may change this swatch without changing transmission.");End+=154;U.Wrap(0,End,W,"Live CPU/GPU fog controls. Local fog uses its selected wind source; analytic fog has no horizontal noise to advect.");ImGui::SetCursorScreenPos(U.At(0,End+86));ImGui::Dummy({W,1});ImGui::PopID();ImGui::PopFont();
}
}
