#include "LightInspectorPanel.h"
#include "ControlPanel.h"
#include "EditorInstance.h"
#include <imgui.h>
#include <imgui_internal.h>
#include <algorithm>
#include <cmath>
#include <cstdio>
#include <cstring>
namespace Frontier { namespace {
constexpr ImU32 Ink=IM_COL32(234,234,234,255),Muted=IM_COL32(145,145,145,255),Gold=IM_COL32(227,194,112,255);
EditorProperty* Find(EditorSheet& S,const char* N){for(uint32_t G=0;G<S.GroupCount;++G)for(uint32_t I=0;I<S.Groups[G].PropertyCount;++I)if(!std::strcmp(S.Groups[G].Properties[I].Label,N))return &S.Groups[G].Properties[I];return nullptr;}
struct Panel {ControlPanel& C;EditorSheet& S;ImDrawList* D;ImVec2 O;ImFont* F;ImVec2 At(float X,float Y)const{return {O.x+X,O.y+Y};}void Text(float X,float Y,const char* T,float Z=12,ImU32 K=Ink){D->AddText(F,Z,At(X,Y),K,T);}void Wrap(float X,float Y,float W,const char* T){D->AddText(F,11,At(X,Y),Muted,T,nullptr,W);}void Card(float X,float Y,float W,float H,const char* T){int A=D->VtxBuffer.Size;D->AddRectFilled(At(X,Y),At(X+W,Y+H),IM_COL32_WHITE,22);ImGui::ShadeVertsLinearColorGradientKeepAlpha(D,A,D->VtxBuffer.Size,At(X,Y),At(X+W,Y+H),IM_COL32(38,37,34,255),IM_COL32(31,31,31,255));D->AddRect(At(X,Y),At(X+W,Y+H),IM_COL32(55,53,48,255),22);Text(X+24,Y+23,T);}void Slider(float X,float Y,float W,const char* N){auto* P=Find(S,N);if(!P)return;Text(X,Y,N,11,Muted);ImGui::SetCursorScreenPos(At(X,Y+22));ImGui::PushID(N);ImGui::BeginChild(N,{W,30},ImGuiChildFlags_None,ImGuiWindowFlags_NoScrollbar|ImGuiWindowFlags_NoScrollWithMouse);C.SliderPill("##value",&P->Figure,P->Minimum,P->Maximum,P->Decimals,P->Unit,false,false,true);ImGui::EndChild();ImGui::PopID();}void Tile(float X,float Y,float W,const char* N){auto* P=Find(S,N);ImGui::SetCursorScreenPos(At(X,Y));ImGui::BeginDisabled(!P);if(ImGui::InvisibleButton(N,{W,65})&&P)P->On=!P->On;ImGui::EndDisabled();bool On=P&&P->On;ImU32 K=!P?Muted:On?IM_COL32(132,207,157,255):IM_COL32(221,137,137,255);D->AddRectFilled(At(X,Y),At(X+W,Y+65),IM_COL32(34,34,34,255),13);D->AddRect(At(X,Y),At(X+W,Y+65),IM_COL32(58,56,51,255),13);D->AddCircle(At(X+W/2,Y+20),7,K,20,1.4f);D->AddLine(At(X+W/2,Y+10),At(X+W/2,Y+18),K,1.5f);float L=F->CalcTextSizeA(10,10000,0,N).x;Text(X+(W-L)/2,Y+42,N,10,K);}void Select(float X,float Y,float W,const char* N){auto* P=Find(S,N);if(!P)return;Text(X,Y,N,11,Muted);ImGui::SetCursorScreenPos(At(X,Y+22));ImGui::BeginChild(N,{W,32},ImGuiChildFlags_None,ImGuiWindowFlags_NoScrollbar|ImGuiWindowFlags_NoScrollWithMouse);C.DropDown("##select",&P->Picked,P->Options,P->OptionCount);ImGui::EndChild();}};
const char* TypeName(unsigned T){static const char* N[]={"Directional","Point","Spot","Rectangle / Area","Tube","Strip"};return T<6?N[T]:"Light";}
}
void RecordLightInspector(ControlPanel& Controls,EditorInstance&,EditorSheet& Sheet){
 auto* Type=Find(Sheet,"Type");auto* Intensity=Find(Sheet,"Intensity");auto* Position=Find(Sheet,"Position");if(!Type||!Intensity||!Position){ImGui::TextUnformatted("Light component unavailable");return;}auto* Font=ImGui::GetFont();ImGui::PushFont(Font,14);ImVec2 O=ImGui::GetCursorScreenPos();O.x+=20;O.y+=20;float W=std::max(240.f,ImGui::GetContentRegionAvail().x-40);Panel U{Controls,Sheet,ImGui::GetWindowDrawList(),O,Font};char T[160];unsigned Kind=std::min(Type->Picked,5u);const bool Extended=Kind>=3,Spot=Kind==2;
 U.Text(0,8,"Inspector / Lighting",8,Muted);U.Text(0,48,"Light",25);std::snprintf(T,sizeof(T),"%s component · persistent scene source",TypeName(Kind));U.Text(0,83,T,10,Muted);
 float Y=110;U.Card(0,Y,W,290,"Main light visual / data");std::snprintf(T,sizeof(T),"%.1f %s",double(Intensity->Figure),Intensity->Unit);U.Text(24,Y+67,T,34);U.Wrap(24,Y+111,W-48,TypeName(Kind));float CX=W*.68f,CY=Y+151,R=std::min(74.f,W*.12f);for(int I=5;I>0;--I)U.D->AddCircleFilled(U.At(CX,CY),R*I/5,IM_COL32(228,193,108,8+I*5),48);U.D->AddCircleFilled(U.At(CX,CY),10,Gold,32);if(Spot){U.D->AddTriangleFilled(U.At(CX-8,CY+8),U.At(CX-64,CY+82),U.At(CX+48,CY+82),IM_COL32(226,193,113,42));}else if(Kind==5){U.D->AddLine(U.At(CX-66,CY),U.At(CX+66,CY),Gold,5);}U.Wrap(24,Y+238,W-48,Extended?"AUTHORING · extended emitter sampling is not implemented in the scene renderer":"LIVE COMPONENT · renderer support depends on the active lighting backend");
 Y+=306;U.Card(0,Y,W,176,"Statistics");float SW=(W-64)/3;const char* Labels[]={"TYPE","OUTPUT","WORLD XYZ"};std::snprintf(T,sizeof(T),"%.1f, %.1f, %.1f",double(Position->Axes[0]),double(Position->Axes[1]),double(Position->Axes[2]));const char* Values[]={TypeName(Kind),Intensity->Unit,T};for(int I=0;I<3;++I){float X=24+I*(SW+8);U.D->AddRectFilled(U.At(X,Y+62),U.At(X+SW,Y+145),IM_COL32(27,27,27,255),12);U.Text(X+14,Y+78,Labels[I],8,Muted);U.Wrap(X+14,Y+104,SW-28,Values[I]);}
 Y+=192;U.Card(0,Y,W,138,"Quick controls");float TW=(W-58)/2;U.Tile(24,Y+53,TW,"Enabled");U.Tile(34+TW,Y+53,TW,"Cast Shadows");
 Y+=154;U.Card(0,Y,W,184,"Transform");U.Text(24,Y+59,"Position · world X / Y / Z (m)",11,Muted);ImGui::SetCursorScreenPos(U.At(24,Y+84));ImGui::BeginChild("Position",{W-48,32},ImGuiChildFlags_None,ImGuiWindowFlags_NoScrollbar);Controls.AxisVec3("##light-position",Position->Axes,Position->AxisStep,true);ImGui::EndChild();auto* Direction=Find(Sheet,"Direction");U.Wrap(24,Y+137,W-48,Direction?Direction->Text:"Direction unavailable");
 Y+=200;const bool ResponseWide=W>=700;const float ResponseH=ResponseWide?418:500;U.Card(0,Y,W,ResponseH,"Source & response");float CW=ResponseWide?(W-72)/2:W-48;U.Slider(24,Y+65,CW,"Intensity");U.Slider(ResponseWide?(W+24)/2:24,Y+65+(ResponseWide?0:76),CW,"Range");auto* Colour=Find(Sheet,"Colour");float ColourY=ResponseWide?Y+158:Y+218;U.Text(24,ColourY,"Colour · linear RGB",11,Muted);if(Colour){ImGui::SetCursorScreenPos(U.At(24,ColourY+23));Controls.ColourChip("##light-colour",Colour->ColourTint);}float L=24,Rr=W-24,Top=Y+(ResponseWide?250:310),Bottom=Y+(ResponseWide?350:410),Range=Find(Sheet,"Range")?Find(Sheet,"Range")->Figure:0;for(int I=1;I<=64;++I){auto F=[&](int J){float X=float(J)/64,D=std::max(.01f,Range*X);return Range<=0?1.f:1.f/(1.f+4*D*D/std::max(1.f,Range*Range));};U.D->AddLine(U.At(L+(Rr-L)*(I-1)/64,Bottom-F(I-1)*(Bottom-Top)),U.At(L+(Rr-L)*I/64,Bottom-F(I)*(Bottom-Top)),Gold,1.5f);}U.Wrap(24,Y+(ResponseWide?371:431),W-48,"Physical inverse-square response with a bounded authoring-range envelope; graph is diagnostic only.");
 if(Spot||Extended){Y+=ResponseH+16;U.Card(0,Y,W,Spot?338:276,"Distribution");U.Select(24,Y+59,std::min(310.f,W-48),"Distribution");if(Spot){U.Slider(24,Y+128,CW,"Inner Cone");U.Slider(W>=700?(W+24)/2:24,Y+128+(W>=700?0:72),CW,"Outer Cone");}else{U.Slider(24,Y+128,CW,"Width");U.Slider(W>=700?(W+24)/2:24,Y+128+(W>=700?0:72),CW,"Height");}U.Wrap(24,Y+(Spot?286:224),W-48,Kind==5?"Strip emits along one horizontal source direction.":"Distribution is component-owned; profile selection survives inspector rebuilds.");Y+=Spot?354:292;}
 else Y+=ResponseH+16;
 U.Card(0,Y,W,174,"Baking / renderer status");U.D->AddRectFilled(U.At(24,Y+56),U.At(W-24,Y+112),IM_COL32(27,27,27,255),12);U.Text(40,Y+77,Extended?"AUTHORING ONLY":"LIVE SOURCE",10,Extended?IM_COL32(224,151,137,255):IM_COL32(132,207,157,255));U.Wrap(24,Y+127,W-48,Extended?"Rectangle, Tube and Strip persist and edit correctly; renderer sampling and baking remain explicitly unavailable.":"No lightmap bake path is available. Point/Spot/Directional records remain native scene components.");Y+=194;ImGui::SetCursorScreenPos(U.At(0,Y));ImGui::Dummy({W,1});ImGui::PopFont();
}
}
