#include "PostProcessInspectorPanel.h"
#include "ControlPanel.h"
#include "EditorInstance.h"
#include <imgui.h>
#include <imgui_internal.h>
#include <algorithm>
#include <cmath>
#include <cstring>
namespace Frontier { namespace {constexpr ImU32 Ink=IM_COL32(234,234,234,255),Muted=IM_COL32(145,145,145,255),Accent=IM_COL32(226,145,116,255);EditorProperty* Find(EditorSheet& S,const char* N){for(uint32_t G=0;G<S.GroupCount;++G)for(uint32_t I=0;I<S.Groups[G].PropertyCount;++I)if(!std::strcmp(S.Groups[G].Properties[I].Label,N))return &S.Groups[G].Properties[I];return nullptr;}struct P{ControlPanel& C;EditorSheet& S;ImDrawList* D;ImVec2 O;ImFont* F;ImVec2 At(float X,float Y){return {O.x+X,O.y+Y};}void Text(float X,float Y,const char* T,float Z=12,ImU32 K=Ink){D->AddText(F,Z,At(X,Y),K,T);}void Wrap(float X,float Y,float W,const char* T){D->AddText(F,11,At(X,Y),Muted,T,nullptr,W);}void Card(float X,float Y,float W,float H,const char* T){int A=D->VtxBuffer.Size;D->AddRectFilled(At(X,Y),At(X+W,Y+H),IM_COL32_WHITE,22);ImGui::ShadeVertsLinearColorGradientKeepAlpha(D,A,D->VtxBuffer.Size,At(X,Y),At(X+W,Y+H),IM_COL32(38,35,34,255),IM_COL32(31,31,31,255));D->AddRect(At(X,Y),At(X+W,Y+H),IM_COL32(55,51,49,255),22);Text(X+24,Y+23,T);}void Slider(float X,float Y,float W,const char* N){auto* Q=Find(S,N);if(!Q)return;Text(X,Y,N,11,Muted);ImGui::SetCursorScreenPos(At(X,Y+22));ImGui::PushID(N);ImGui::BeginChild(N,{W,30},ImGuiChildFlags_None,ImGuiWindowFlags_NoScrollbar);C.SliderPill("##value",&Q->Figure,Q->Minimum,Q->Maximum,Q->Decimals,Q->Unit,false,false,true);ImGui::EndChild();ImGui::PopID();}};}
void RecordPostProcessInspector(ControlPanel& C,EditorInstance&,EditorSheet& S){if(!Find(S,"EV Compensation")){ImGui::TextUnformatted("Post-process properties unavailable");return;}auto* F=ImGui::GetFont();ImGui::PushFont(F,14);ImVec2 O=ImGui::GetCursorScreenPos();O.x+=20;O.y+=20;float W=std::max(240.f,ImGui::GetContentRegionAvail().x-40);P U{C,S,ImGui::GetWindowDrawList(),O,F};U.Text(0,8,"Inspector / Camera",8,Muted);U.Text(0,48,"Post Process",25);U.Text(0,83,"Real project-owned exposure, tone and lens controls",10,Muted);float Y=110;U.Card(0,Y,W,226,"Exposure");float EV=Find(S,"EV Compensation")->Figure;char T[64];std::snprintf(T,sizeof(T),"%+.2f EV",double(EV));U.Text(24,Y+65,T,36);U.Wrap(24,Y+111,W-48,"Exposure compensation · session state, no fabricated histogram");U.Slider(24,Y+151,W-48,"EV Compensation");Y+=242;U.Card(0,Y,W,342,"Tone response");bool Wide=W>=700;float CW=Wide?(W-72)/2:W-48;U.Slider(24,Y+61,CW,"Saturation");U.Slider(Wide?(W+24)/2:24,Y+61+(Wide?0:72),CW,"Contrast");float L=24,R=W-24,Top=Y+179,Bottom=Y+284,Contrast=Find(S,"Contrast")->Figure;for(int I=1;I<=80;++I){auto Curve=[&](int J){float X=float(J)/80;return .5f+.5f*std::tanh((X-.5f)*Contrast*4);};U.D->AddLine(U.At(L+(R-L)*(I-1)/80,Bottom-Curve(I-1)*(Bottom-Top)),U.At(L+(R-L)*I/80,Bottom-Curve(I)*(Bottom-Top)),Accent,1.6f);}U.Wrap(24,Y+301,W-48,"Interactive tone curve from authored contrast; saturation remains a separate chroma control.");Y+=358;float LensH=Wide?246:290;U.Card(0,Y,W,LensH,"Lens effects");U.Slider(24,Y+62,CW,"Bloom Intensity");U.Slider(Wide?(W+24)/2:24,Y+62+(Wide?0:72),CW,"Vignette");U.Wrap(24,Y+(Wide?177:225),W-48,"Controls write back to the project session. Renderer statistics and camera previews are not invented here.");Y+=LensH+20;ImGui::SetCursorScreenPos(U.At(0,Y));ImGui::Dummy({W,1});ImGui::PopFont();}
}
