//============================================================================================================================================
//                                                  ATROUSDENOISEMIRROR.CPP
//============================================================================================================================================
// See AtrousDenoiseMirror.h. This TU is the ONLY place the shim's macros are in scope: it includes the transformed
//    halves of Engine/Shaders/AtrousDenoise.slang and exposes plain-float entry points.
//
//    `AtrousDenoise.cpu.1.h` / `.2.h` are generated by CheckMaterialDenoise.sh from the real .slang file — the split
//    exists so the push-constant struct body is preprocessed WITHOUT the member macros and `main` is preprocessed
//    WITH them. If the shader grows a push-constant member, the list below stops matching and the build fails loudly
//    rather than silently reading the wrong field.

#include "AtrousDenoiseMirror.h"
#include "DenoiseCpuShim.h"

#include <algorithm>

#define main AtrousDenoiseEntry
#include "AtrousDenoise.cpu.1.h"

// GLSL reaches a uniform block's members bare; C++ reaches them through the block instance. One macro per member,
//    scope-closed at the end of this TU.
#define Extent           DenoiseParameters.Extent
#define StepSize         DenoiseParameters.StepSize
#define Enabled          DenoiseParameters.Enabled
#define NormalPower      DenoiseParameters.NormalPower
#define DepthScale       DenoiseParameters.DepthScale
#define LuminanceScale   DenoiseParameters.LuminanceScale
#define Exposure         DenoiseParameters.Exposure
#define FinalLevel       DenoiseParameters.FinalLevel
#define WriteFilteredHistory DenoiseParameters.WriteFilteredHistory
#define ColourSaturation DenoiseParameters.ColourSaturation

#include "AtrousDenoise.cpu.2.h"

#undef Extent
#undef StepSize
#undef Enabled
#undef NormalPower
#undef DepthScale
#undef LuminanceScale
#undef Exposure
#undef FinalLevel
#undef WriteFilteredHistory
#undef ColourSaturation
#undef main

//------------------------------------------------------------------------------------------------------------------------
//                                                    GLSL GLOBALS
//------------------------------------------------------------------------------------------------------------------------

InvocationId gl_GlobalInvocationID;

namespace DenoiseMirror {

namespace {

void LoadImage(image2D& Image, uint32_t ExtentPixels, const float* Values)
{
    Image.Assign(static_cast<int>(ExtentPixels), static_cast<int>(ExtentPixels));
    for (uint32_t Y = 0u; Y < ExtentPixels; ++Y)
        for (uint32_t X = 0u; X < ExtentPixels; ++X)
        {
            const size_t I = (static_cast<size_t>(Y) * ExtentPixels + static_cast<size_t>(X)) * 4u;
            Image.Texels[Image.Offset(static_cast<int>(X), static_cast<int>(Y))] =
                vec4(Values[I + 0u], Values[I + 1u], Values[I + 2u], Values[I + 3u]);
        }
}

void StoreImage(const image2D& Image, uint32_t ExtentPixels, float* Values)
{
    for (uint32_t Y = 0u; Y < ExtentPixels; ++Y)
        for (uint32_t X = 0u; X < ExtentPixels; ++X)
        {
            const size_t I = (static_cast<size_t>(Y) * ExtentPixels + static_cast<size_t>(X)) * 4u;
            const vec4 V = Image.Texels[Image.Offset(static_cast<int>(X), static_cast<int>(Y))];
            Values[I + 0u] = V.x; Values[I + 1u] = V.y; Values[I + 2u] = V.z; Values[I + 3u] = V.w;
        }
}

} // namespace

//------------------------------------------------------------------------------------------------------------------------
//                                                       DISPATCH
//------------------------------------------------------------------------------------------------------------------------

void Run(const RunConfiguration& Configuration, const float* Source, const float* Surface, float* Target, float* Output,
         float* FilteredHistory)
{
    const uint32_t ExtentPixels = Configuration.Extent;
    LoadImage(SourceImage, ExtentPixels, Source);
    LoadImage(SurfaceImage, ExtentPixels, Surface);
    LoadImage(TargetImage, ExtentPixels, Source);        // pre-fill: an untouched texel must be visibly untouched, not zero
    // Pre-fill makes a disabled/non-history-writing invocation observable without inventing a value the shader never
    // writes. Level zero replaces every texel whenever WriteFilteredHistory is set.
    LoadImage(FilteredHistoryImage, ExtentPixels, Source);
    OutputImage.Assign(static_cast<int>(ExtentPixels), static_cast<int>(ExtentPixels));

    DenoiseParameters.Extent[0]        = ExtentPixels;
    DenoiseParameters.Extent[1]        = ExtentPixels;
    DenoiseParameters.StepSize         = Configuration.StepSize;
    DenoiseParameters.Enabled          = Configuration.Enabled ? 1u : 0u;
    DenoiseParameters.NormalPower      = Configuration.NormalPower;
    DenoiseParameters.DepthScale       = Configuration.DepthScale;
    DenoiseParameters.LuminanceScale   = Configuration.LuminanceScale;
    DenoiseParameters.Exposure         = Configuration.Exposure;
    DenoiseParameters.FinalLevel       = Configuration.FinalLevel ? 1u : 0u;
    DenoiseParameters.WriteFilteredHistory = Configuration.WriteFilteredHistory ? 1u : 0u;
    DenoiseParameters.ColourSaturation = Configuration.ColourSaturation;

    for (uint32_t Y = 0u; Y < ExtentPixels; ++Y)
        for (uint32_t X = 0u; X < ExtentPixels; ++X)
        {
            gl_GlobalInvocationID.x = X;
            gl_GlobalInvocationID.y = Y;
            AtrousDenoiseEntry();
        }

    if (Target != nullptr) StoreImage(TargetImage, ExtentPixels, Target);
    if (Output != nullptr) StoreImage(OutputImage, ExtentPixels, Output);
    if (FilteredHistory != nullptr) StoreImage(FilteredHistoryImage, ExtentPixels, FilteredHistory);
}

//------------------------------------------------------------------------------------------------------------------------
//                                                 SHADER FUNCTIONS, DIRECT
//------------------------------------------------------------------------------------------------------------------------

float AcesFilm(float X) { return ::AcesFilm(X); }

void ToneMap(float R, float G, float B, float ExposureValue, float ColourSaturationValue, float* Out3)
{
    DenoiseParameters.Exposure         = ExposureValue;
    DenoiseParameters.ColourSaturation = ColourSaturationValue;
    const vec3 Mapped = ToneMap(vec3(R, G, B));
    Out3[0] = Mapped.x; Out3[1] = Mapped.y; Out3[2] = Mapped.z;
}

float KernelWeight(int32_t Offset) { return ::KernelWeight(static_cast<int>(Offset)); }

float EarlyOutVariance() { return ::kEarlyOutVariance; }

//------------------------------------------------------------------------------------------------------------------------
//                                             ACCUMULATOR (kernel mirror)
//------------------------------------------------------------------------------------------------------------------------

void Accumulator::Resolve(const float SampleRadiance[3], float* OutRadiance, float* OutVariance)
{
    // ReSTIRViewport.slang `ResolveSurface`, in order: count += 1; mean += (x − mean)/count; moments += (luma,
    //    luma² − moments)/count; variance = max(E[x²] − E[x]², 0)/count; a first sample reports luma².
    // This mirror is the zero-motion progressive path. ReSTIRViewport.slang applies its finite 32-sample confidence
    // only when a validated history actually reprojects across pixels; a still pixel stays an unbiased progressive
    // mean and can reach the filter early-out. ReactiveTemporalMirror.h separately executes the capped moved-history
    // policy, including moving shadows and animated emission.
    Count += 1.0f;
    for (int C = 0; C < 3; ++C) Mean[C] += (SampleRadiance[C] - Mean[C]) / Count;

    const float Luma = SampleRadiance[0] * 0.2126f + SampleRadiance[1] * 0.7152f + SampleRadiance[2] * 0.0722f;
    Moments[0] += (Luma - Moments[0]) / Count;
    Moments[1] += (Luma * Luma - Moments[1]) / Count;

    float SampleVariance = Moments[1] - Moments[0] * Moments[0];
    if (SampleVariance < 0.0f) SampleVariance = 0.0f;
    float Variance = SampleVariance / Count;
    if (Count < 2.0f) Variance = Luma * Luma;

    OutRadiance[0] = Mean[0]; OutRadiance[1] = Mean[1]; OutRadiance[2] = Mean[2];
    *OutVariance = Variance;
}

} // namespace DenoiseMirror
