/**
 * Plumage Presets & Material Definitions for Eagle Model
 */
export const EAGLE_PLUMAGE_PRESETS = {
  bald: {
    name: 'Adult Bald Eagle (Haliaeetus leucocephalus)',
    description: 'Iconic North American sea eagle with pure white head & tail, dark chocolate brown plumage, and bright yellow hooked bill and talons.',
    headColor: 'white',
    bodyColor: 'dark',
    tailColor: 'white',
    wingColor: 'dark',
    beakPreset: 'bald',
    beakColor: '#ffc820',
    eyeIrisColor: '#f2d438',
    legColor: '#fab800',
    talonColor: '#151311',
    cereColor: '#f5b800',
    roughness: 0.65,
    metalness: 0.05,
    anisotropy: 0.8
  },
  golden: {
    name: 'Golden Eagle (Aquila chrysaetos)',
    description: 'Apex mountain predator with rich amber-brown body, golden-buff crown and nape feathers, dark-tipped bill, and feathered tarsi.',
    headColor: 'golden',
    bodyColor: 'golden',
    tailColor: 'golden',
    wingColor: 'golden',
    beakPreset: 'golden',
    beakColor: '#c8a030',
    eyeIrisColor: '#c48b20',
    legColor: '#e0a010',
    talonColor: '#0a0807',
    cereColor: '#d49810',
    roughness: 0.6,
    metalness: 0.08,
    anisotropy: 0.9
  },
  harpy: {
    name: 'Harpy Eagle (Harpia harpyja)',
    description: 'Immense Neotropical rainforest raptor with double crest crown feathers, ash-slate mantle, barred wings, and massive crushing talons.',
    headColor: 'white',
    bodyColor: 'dark',
    tailColor: 'dark',
    wingColor: 'dark',
    beakPreset: 'golden',
    beakColor: '#303030',
    eyeIrisColor: '#604020',
    legColor: '#f0c030',
    talonColor: '#050505',
    cereColor: '#404040',
    roughness: 0.6,
    metalness: 0.05,
    anisotropy: 0.7
  },
  arctic: {
    name: 'Arctic White Falcon Eagle (Morph)',
    description: 'Pristine arctic snow morph plumage with frost-white flight feathers, silvery mantle, and striking golden eyes.',
    headColor: 'white',
    bodyColor: 'white',
    tailColor: 'white',
    wingColor: 'white',
    beakPreset: 'bald',
    beakColor: '#ffbb10',
    eyeIrisColor: '#ffcc00',
    legColor: '#f5c020',
    talonColor: '#222222',
    cereColor: '#e5aa00',
    roughness: 0.55,
    metalness: 0.1,
    anisotropy: 0.9
  },
  shadow: {
    name: 'Shadow Tactical Raptor (Apex Variant)',
    description: 'Stealth melanistic dark raptor with obsidian plumage, crimson-amber eyes, and polished jet-black talons for cinematic AAA games.',
    headColor: 'dark',
    bodyColor: 'dark',
    tailColor: 'dark',
    wingColor: 'dark',
    beakPreset: 'golden',
    beakColor: '#1c1a18',
    eyeIrisColor: '#ff4400',
    legColor: '#2a2622',
    talonColor: '#080808',
    cereColor: '#22201d',
    roughness: 0.5,
    metalness: 0.15,
    anisotropy: 0.95
  }
};
