// A genuinely standalone page for raw.githack.com: no dev server, CDN imports,
// relative JS chunks, font requests or image/material-map downloads.
import { build } from "vite";
import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
const root = fileURLToPath(new URL("../", import.meta.url));
const outDir = path.join(root, "site");
await build({
  configFile: false,
  root,
  base: "./",
  build: {
    outDir,
    emptyOutDir: true,
    assetsInlineLimit: 2000000,
    cssCodeSplit: false,
    modulePreload: false,
    rollupOptions: { output: { inlineDynamicImports: true } },
    chunkSizeWarningLimit: 2000,
  },
});
let html = await fs.readFile(path.join(outDir, "index.html"), "utf8");
for (const match of [
  ...html.matchAll(/<script\b[^>]*src="([^"]+)"[^>]*><\/script>/g),
]) {
  const source = await fs.readFile(path.resolve(outDir, match[1]), "utf8");
  html = html.replace(
    match[0],
    () =>
      `<script type="module">${source.replace(/<\/script/gi, "<\\/script")}</script>`,
  );
}
for (const match of [
  ...html.matchAll(/<link\b[^>]*rel="stylesheet"[^>]*href="([^"]+)"[^>]*>/g),
]) {
  const css = await fs.readFile(path.resolve(outDir, match[1]), "utf8");
  html = html.replace(
    match[0],
    () => `<style>${css.replace(/<\/style/gi, "<\\/style")}</style>`,
  );
}
if (/(?:src|href)="\.\/assets\//.test(html))
  throw new Error("Standalone build still references an external asset.");
html = html.replace(
  "<head>",
  "<head>\n<!-- Generated by npm run build:githack. All runtime assets are embedded. -->",
);
// Three.js embeds GLSL templates with whitespace-only lines; keep the tracked artifact clean.
html = html.replace(/[\t ]+$/gm, "");
await fs.writeFile(path.join(outDir, "index.html"), html);
await fs.rm(path.join(outDir, "assets"), { recursive: true, force: true });
console.log(
  `Standalone GitHack page: site/index.html (${(Buffer.byteLength(html) / 1024 / 1024).toFixed(2)} MB).`,
);
