#include "LightInspectorPanel.h"
#include "PostProcessInspectorPanel.h"
#include "ControlPanel.h"
#include "EditorInstance.h"
#include "CpuDraw.h"
#include "PngWriteCounterpart.h"
#include <imgui_internal.h>
#include <filesystem>
#include <memory>
#include <stdexcept>
#include <cstdio>
#include <cstring>
using namespace Frontier;
static unsigned Checks=0;static void Check(bool V,const char* N){++Checks;if(!V)throw std::runtime_error(N);}
static EditorProperty& Add(EditorPropertyGroup& G,const char* N,EditorPropertyCategory C){auto& P=G.Properties[G.PropertyCount++];std::snprintf(P.Label,sizeof(P.Label),"%s",N);P.Category=C;return P;}
static EditorSheet SheetFor(unsigned Kind){EditorSheet S;S.Appearance=EditorSheetAppearance::Light;auto& A=S.Groups[S.GroupCount++];std::snprintf(A.Title,sizeof(A.Title),"Light source");auto& E=Add(A,"Enabled",EditorPropertyCategory::Switch);E.On=true;auto& C=Add(A,"Cast Shadows",EditorPropertyCategory::Switch);C.On=true;if(Kind==5){auto& Draw=Add(A,"Draw emitter",EditorPropertyCategory::Switch);Draw.On=true;}auto& T=Add(A,"Type",EditorPropertyCategory::Select);T.Picked=Kind;T.OptionCount=6;const char* TN[]={"Directional","Point","Spot","Rectangle / Area","Tube","Strip"};for(int I=0;I<6;++I)std::snprintf(T.Options[I],sizeof(T.Options[I]),"%s",TN[I]);auto Slider=[&](EditorPropertyGroup& G,const char* N,float V,float Min,float Max,const char* U){auto& P=Add(G,N,EditorPropertyCategory::Slider);P.Figure=V;P.Minimum=Min;P.Maximum=Max;P.Decimals=!std::strcmp(N,"Load per metre")||!std::strcmp(N,"Strip length")?1:(!std::strcmp(N,"Dimmer")?2:0);std::snprintf(P.Unit,sizeof(P.Unit),"%s",U);};Slider(A,"Intensity",Kind?1200:10,0,100000,Kind?"cd":"lx");auto& Hue=Add(A,"Colour",EditorPropertyCategory::Colour);Hue.ColourTint[0]=1;Hue.ColourTint[1]=.82f;Hue.ColourTint[2]=.58f;Slider(A,"Range",25,0,1000,"m");auto& X=S.Groups[S.GroupCount++];std::snprintf(X.Title,sizeof(X.Title),"Transform");auto& P=Add(X,"Position",EditorPropertyCategory::AxisVec3);P.Axes[0]=2;P.Axes[1]=4;P.Axes[2]=3;P.AxisStep=.05f;P.Editable=true;auto& D=Add(X,"Direction",EditorPropertyCategory::Readout);std::snprintf(D.Text,sizeof(D.Text),"−Z · 0, −1, 0");auto& G=S.Groups[S.GroupCount++];std::snprintf(G.Title,sizeof(G.Title),"Distribution");auto& Dist=Add(G,"Distribution",EditorPropertyCategory::Select);Dist.OptionCount=3;Dist.Picked=Kind==2?1:0;for(int I=0;I<3;++I)std::snprintf(Dist.Options[I],sizeof(Dist.Options[I]),"%s",I==0?"Uniform":I==1?"IES profile":"ECE low beam");Slider(G,"Inner Cone",25,0,89,"deg");Slider(G,"Outer Cone",45,1,90,"deg");Slider(G,"Width",Kind==5?2.4f:1,.01f,100,"m");Slider(G,"Height",Kind==5?.04f:1,.01f,100,"m");if(Kind==5){auto& O=S.Groups[S.GroupCount++];std::snprintf(O.Title,sizeof(O.Title),"Output per metre");Slider(O,"Flux per metre",1200,10,4000,"lm/m");Slider(O,"Load per metre",12,1,50,"W/m");Slider(O,"Dimmer",.5f,0,1,"");Slider(O,"Colour temperature",4000,1800,12000,"K");auto& L=S.Groups[S.GroupCount++];std::snprintf(L.Title,sizeof(L.Title),"Layout & segments");Slider(L,"Strip length",3.f,.1f,20,"m");Slider(L,"Emitter density",120,10,240,"/m");Slider(L,"Supply voltage",24,5,48,"V");auto& Diff=Add(L,"Opal diffuser",EditorPropertyCategory::Switch);Diff.On=true;}return S;}
static EditorSheet PostSheet(){EditorSheet S;S.Appearance=EditorSheetAppearance::PostProcess;auto& A=S.Groups[S.GroupCount++];auto& EV=Add(A,"EV Compensation",EditorPropertyCategory::Slider);EV.Minimum=-4;EV.Maximum=4;EV.Figure=.75f;EV.Decimals=2;std::snprintf(EV.Unit,sizeof(EV.Unit),"EV");auto& B=S.Groups[S.GroupCount++];auto F=[&](EditorPropertyGroup& G,const char* N,float V,float Min,float Max){auto& P=Add(G,N,EditorPropertyCategory::Slider);P.Minimum=Min;P.Maximum=Max;P.Figure=V;P.Decimals=2;};F(B,"Saturation",1.1f,0,2);F(B,"Contrast",1.25f,.5f,2);auto& C=S.Groups[S.GroupCount++];F(C,"Bloom Intensity",.12f,0,1);F(C,"Vignette",.18f,0,1);return S;}
int main(){std::filesystem::create_directories("Exhibits/Gallery/LightNative");ImGui::CreateContext();auto& IO=ImGui::GetIO();IO.IniFilename=nullptr;IO.DeltaTime=1.f/60;IO.BackendFlags|=ImGuiBackendFlags_RendererHasTextures|ImGuiBackendFlags_RendererHasVtxOffset;ImFontConfig FontConfig;std::snprintf(FontConfig.Name,sizeof(FontConfig.Name),"Sun reference / regular");auto* Ui=IO.Fonts->AddFontFromFileTTF("EngineContent/Fonts/SunReference/DMSans-Regular.ttf",14,&FontConfig);ImFontConfig DisplayConfig;std::snprintf(DisplayConfig.Name,sizeof(DisplayConfig.Name),"Sun reference / light");auto* Display=IO.Fonts->AddFontFromFileTTF("EngineContent/Fonts/SunReference/DMSans-Light.ttf",40,&DisplayConfig);ImGui::StyleColorsDark();auto Controls=std::make_unique<ControlPanel>();Controls->AssignFonts(Ui,Ui,Ui,Ui,Ui,Display);EditorInstance Row;std::snprintf(Row.Label,sizeof(Row.Label),"Light");int W=1024,H=2300;float Scale=1;EditorSheet Sheet;const char* FooterLabel="Light · native authoring";
 auto Tick=[&](){IO.DisplaySize={float(W),float(H)};IO.DisplayFramebufferScale={Scale,Scale};ImGui::NewFrame();ImGui::SetNextWindowPos({0,0});ImGui::SetNextWindowSize(IO.DisplaySize);ImGui::Begin("Inspector",nullptr,ImGuiWindowFlags_NoTitleBar|ImGuiWindowFlags_NoScrollbar);ImGui::BeginChild("##light-properties",{0,float(H-40)},ImGuiChildFlags_None,ImGuiWindowFlags_NoScrollbar);if(Sheet.Appearance==EditorSheetAppearance::PostProcess)RecordPostProcessInspector(*Controls,Row,Sheet);else RecordLightInspector(*Controls,Row,Sheet);ImGui::EndChild();auto* FooterDraw=ImGui::GetForegroundDrawList();FooterDraw->AddRectFilled({0,float(H-40)},{float(W),float(H)},IM_COL32(21,21,21,255));FooterDraw->AddLine({0,float(H-40)},{float(W),float(H-40)},IM_COL32(255,255,255,8));FooterDraw->AddText(Ui,9,{12,float(H-17)},IM_COL32(105,105,105,255),FooterLabel);FooterDraw->AddText(Ui,9,{float(W-73),float(H-17)},IM_COL32(105,105,105,255),"HTML preview");ImGui::End();ImGui::Render();FrontierProof::AcknowledgeTextures();};auto Capture=[&](const char* N){for(int I=0;I<3;++I)Tick();std::vector<unsigned char> P(size_t(W)*H*3,24);for(auto* L:ImGui::GetDrawData()->CmdLists)FrontierProof::Draw(L,P.data(),W,H,{0,0},{Scale,Scale});std::string Path="Exhibits/Gallery/LightNative/"+std::string(N)+".png";Check(stbi_write_png(Path.c_str(),W,H,3,P.data(),W*3)!=0,"capture");};
 Sheet=SheetFor(2);Capture("Light-Spot");Check(Sheet.Appearance==EditorSheetAppearance::Light,"dedicated route");Sheet=SheetFor(3);Capture("Light-Area");W=339;H=864;FooterLabel="LED strip · HTML authoring";Sheet=SheetFor(5);Capture("Light-Strip-Viewport");W=352;H=3000;Capture("Light-Strip");auto SetStrip=[&](const char* Name,float Value){for(uint32_t G=0;G<Sheet.GroupCount;++G)for(uint32_t I=0;I<Sheet.Groups[G].PropertyCount;++I)if(!std::strcmp(Sheet.Groups[G].Properties[I].Label,Name))Sheet.Groups[G].Properties[I].Figure=Value;};SetStrip("Flux per metre",1000);SetStrip("Load per metre",14.4f);SetStrip("Dimmer",1);SetStrip("Strip length",2.4f);SetStrip("Emitter density",60);W=339;H=864;Capture("Light-Strip-Narrow-Viewport");W=480;H=3000;FooterLabel="Light · native authoring";Sheet=SheetFor(2);Capture("Light-Spot-Narrow");W=1024;H=1300;FooterLabel="Post process · native authoring";Sheet=PostSheet();Capture("Post-Process");W=480;H=1800;Capture("Post-Process-Narrow");ImGui::DestroyContext();std::printf("PASS %u checks: shared native Light cards, Point/Spot/Area family data, honest renderer status and narrow layout.\n",Checks);}
