// Preset graphs — curated starting points, each tuned to its landform.
// Node ids are strings for readability; main.js remaps them.
const N = (id, type, x, y, params = {}) => ({ id, type, x, y, params, enabled: true });
const L = (from, to, toInput = 'in') => ({ from, to, toInput });

export const PRESETS = [
  {
    name: 'Highlands & River', icon: '⛰',
    desc: 'Ridged highlands carved by rain, a source-fed river and talus slopes. Sea level low.',
    waterLevel: 0, sunAz: 132, sunEl: 32,
    run: { rain: true, river: true, wind: false, thermal: true },
    camera: { az: 0.85, el: 0.42, dist: 0.88 },
    nodes: [
      N('slab', 'terrainSlab', 40, 120, { top: 6, amp: 15, freq: 0.02, ridged: 0.2, seed: 7 }),
      N('ridge', 'ridged', 280, 110, { amp: 6.5, freq: 0.045, oct: 5, seed: 11 }),
      N('warp', 'warp', 520, 150, { str: 7, freq: 0.022, seed: 5 }),
      N('hyd', 'hydraulic', 760, 120, {}),
      N('therm', 'thermal', 1000, 200, { angle: 40, rate: 0.3 }),
      N('river', 'river', 1000, 60, { srcX: -42, srcZ: -38, spread: 5, intensity: 0.5, speed: 1.8 }),
      N('out', 'output', 1240, 120, {}),
    ],
    links: [
      L('slab', 'ridge'), L('ridge', 'warp'), L('warp', 'hyd'),
      L('hyd', 'therm'), L('hyd', 'river'), L('therm', 'out'), L('river', 'out'),
    ],
  },
  {
    name: 'Cave Coast', icon: '🕳',
    desc: 'Sea cliffs with sphere chambers and a smooth-union arch — subtracted volumes stay true 3D caves.',
    waterLevel: 3.5, sunAz: 205, sunEl: 22,
    run: { rain: true, river: false, wind: true, thermal: true },
    camera: { az: 2.4, el: 0.3, dist: 0.95 },
    nodes: [
      N('slab', 'terrainSlab', 40, 140, { top: 4, amp: 12, freq: 0.017, ridged: 0.5, seed: 21 }),
      N('c1', 'sphere', 40, 420, { x: -30, y: 5, z: 12, r: 11 }),
      N('c2', 'sphere', 40, 560, { x: -8, y: 10, z: -14, r: 9 }),
      N('c3', 'sphere', 40, 700, { x: 22, y: 7, z: 6, r: 12 }),
      N('cut', 'subtract', 300, 480, { k: 2.5 }),
      N('cut2', 'subtract', 540, 480, { k: 2.0 }),
      N('cut3', 'subtract', 780, 480, { k: 2.0 }),
      N('hyd', 'hydraulic', 1020, 300, {}),
      N('wind', 'wind', 1020, 460, { speed: 9, dir: 200, height: 10 }),
      N('out', 'output', 1260, 380, {}),
    ],
    links: [
      L('slab', 'cut', 'A'), L('c1', 'cut', 'B'),
      L('cut', 'cut2', 'A'), L('c2', 'cut2', 'B'),
      L('cut2', 'cut3', 'A'), L('c3', 'cut3', 'B'),
      L('cut3', 'hyd'), L('cut3', 'wind'),
      L('hyd', 'out'), L('wind', 'out'),
    ],
  },
  {
    name: 'Canyon Run', icon: '🛶',
    desc: 'A deep carved gorge with a river cutting its bed and sediment bars settling downstream.',
    waterLevel: -4, sunAz: 100, sunEl: 38,
    run: { rain: false, river: true, wind: false, thermal: true },
    camera: { az: 1.57, el: 0.35, dist: 0.8 },
    nodes: [
      N('slab', 'terrainSlab', 40, 140, { top: 10, amp: 10, freq: 0.012, ridged: 0.3, seed: 33 }),
      N('chan', 'capsule', 40, 420, { ax: -70, ay: 14, az: -60, bx: 40, by: 12, bz: 40, r: 14 }),
      N('bowl', 'sphere', 40, 560, { x: 48, y: 13, z: 48, r: 20 }),
      N('cut', 'subtract', 300, 440, { k: 3.0 }),
      N('cut2', 'subtract', 540, 440, { k: 2.0 }),
      N('ter', 'terrace', 780, 440, { step: 5, sharp: 0.35 }),
      N('river', 'river', 1020, 360, { srcX: -58, srcZ: -48, spread: 4, intensity: 0.65, speed: 2.2, brush: 1.4 }),
      N('therm', 'thermal', 1020, 520, { angle: 42, rate: 0.25 }),
      N('out', 'output', 1260, 440, {}),
    ],
    links: [
      L('slab', 'cut', 'A'), L('chan', 'cut', 'B'),
      L('cut', 'cut2', 'A'), L('bowl', 'cut2', 'B'),
      L('cut2', 'ter'), L('ter', 'river'), L('river', 'therm'), L('therm', 'out'),
    ],
  },
  {
    name: 'Dune Sea', icon: '🏜',
    desc: 'Wind regime: saltating grains ablate windward faces and build dune mantles in the lee.',
    waterLevel: -14, sunAz: 250, sunEl: 26,
    run: { rain: false, river: false, wind: true, thermal: true },
    camera: { az: 0.4, el: 0.3, dist: 0.95 },
    nodes: [
      N('plane', 'plane', 40, 200, { h: -12 }),
      N('dunes', 'noise', 280, 180, { amp: 9, freq: 0.022, oct: 4, seed: 44 }),
      N('fine', 'noise', 520, 240, { amp: 1.1, freq: 0.12, oct: 3, seed: 9 }),
      N('wind', 'wind', 760, 180, { speed: 12, dir: 40, height: 6, spread: 18, abrasion: 1.2 }),
      N('therm', 'thermal', 1000, 280, { angle: 34, rate: 0.4 }),
      N('out', 'output', 1240, 220, {}),
    ],
    links: [L('plane', 'dunes'), L('dunes', 'fine'), L('fine', 'wind'), L('wind', 'therm'), L('therm', 'out')],
  },
  {
    name: 'Badlands Mesa', icon: '🗿',
    desc: 'Terraced plateaus with hydraulic gully networks and thermal scree — stratified and dry.',
    waterLevel: -10, sunAz: 300, sunEl: 42,
    run: { rain: true, river: false, wind: true, thermal: true },
    camera: { az: 2.9, el: 0.45, dist: 0.9 },
    nodes: [
      N('slab', 'terrainSlab', 40, 160, { top: 2, amp: 18, freq: 0.014, ridged: 0.6, seed: 52 }),
      N('ter', 'terrace', 280, 160, { step: 6, sharp: 0.65 }),
      N('warp', 'warp', 520, 220, { str: 9, freq: 0.02, seed: 17 }),
      N('hyd', 'hydraulic', 760, 160, { intensity: 0.5 }),
      N('wind', 'wind', 760, 320, { speed: 6, dir: 120, height: 12 }),
      N('therm', 'thermal', 1000, 240, { angle: 44, rate: 0.3 }),
      N('out', 'output', 1240, 240, {}),
    ],
    links: [L('slab', 'ter'), L('ter', 'warp'), L('warp', 'hyd'), L('warp', 'wind'), L('hyd', 'therm'), L('wind', 'therm'), L('therm', 'out')],
  },
];
