// Original compositions informed by museum textile/carpet references. These are
// design blueprints, NOT a palette Cartesian product or reproductions of objects.
// See docs/rug-references.md for the research and the limits of these studies.
const rugBlueprints = {
  "African compositions": [
    // name | layout | field motif | secondary | border | center | grid | study
    "Chromatic Diamond Tapestry|triple|chevron|comb|hooks|stepped|6,8|reference",
    "Raffia Labyrinth Panels|patchwork|maze|quarters|meander|none|5,6|raffia",
    "Interrupted Lozenge Cloth|diagonal|hook|maze|teeth|none|5,7|raffia",
    "Embroidered Crossroads|cross|quarters|comb|diamonds|maze|6,6|raffia",
    "Split Diamond Raffia|compartments|quarters|hook|meander|none|4,5|raffia",
    "Angular River Cloth|bands|maze|chevron|hooks|none|6,7|raffia",
    "Raffia Window Mosaic|patchwork|nested|maze|teeth|none|6,5|raffia",
    "Golden Strip Counterpoint|strips|stripe|chevron|checks|none|8,7|strip",
    "Offset Weft Blocks|strips|checks|comb|teeth|none|7,8|strip",
    "Copper Ladder Strips|strips|comb|nested|diamonds|none|6,6|strip",
    "Festival Chevron Cloth|bands|chevron|checks|checks|none|7,9|strip",
    "Alternating Shield Strips|strips|hook|stripe|hooks|none|9,5|strip",
    "Woven Crossband Tapestry|garden|stripe|checks|meander|quarters|6,8|strip",
    "Indigo Resist Courtyard|compartments|rings|dots|dots|none|5,5|indigo",
    "Starlit Indigo Panels|patchwork|rosette|rings|diamonds|none|6,6|indigo",
    "Indigo Ladder Cloth|strips|comb|dots|checks|none|8,6|indigo",
    "Resist Rosette Field|trellis|rings|rosette|dots|none|6,8|indigo",
    "Tied Circle Constellation|diagonal|dots|rings|meander|none|7,7|indigo",
    "Indigo Crossed Paths|garden|rosette|comb|dots|nested|5,7|indigo",
    "Earthmark Nine Panels|compartments|comb|chevron|teeth|none|3,3|earth",
    "Ochre Broken Tracks|bands|chevron|dots|diamonds|none|5,8|earth",
    "Sand and Charcoal Signals|strips|quarters|comb|meander|none|7,9|earth",
    "Dotted Earth Windows|patchwork|dots|nested|hooks|none|5,7|earth",
    "Mud-Dye Lattice Study|trellis|nested|comb|teeth|none|6,5|earth",
    "Ivory Marked Steps|kilim|hook|dots|checks|none|5,6|earth",
    "Chromatic Diamond Cascade|vertical|quarters|stripe|checks|stepped|6,7|reference",
    "Vermilion Hooked Field|diagonal|hook|chevron|diamonds|none|4,6|reference",
    "Azure Shield Courtyard|garden|nested|quarters|hooks|stepped|4,4|reference",
    "Prismatic Cross Medallions|cross|comb|chevron|teeth|nested|5,7|reference",
    "Nested Diamond Columns|strips|nested|hook|diamonds|none|5,8|reference",
    "Mosaic Arrow Festival|compartments|chevron|maze|checks|none|4,6|reference",
    "Raffia Spiral Atlas|radial|maze|dots|meander|quarters|5,5|raffia",
    "Copper Patchwork Rhythm|patchwork|hook|stripe|diamonds|none|7,6|strip",
    "Indigo Lozenge Runner|vertical|rings|comb|dots|hook|4,8|indigo",
    "Earthmark Diamond Court|medallion|quarters|dots|teeth|maze|7,9|earth",
    "Rainbow Guardband Carpet|bordered|chevron|nested|checks|stepped|7,5|reference",
  ],
  "Islamic carpets": [
    "Saffron Rosette Court|radial|vine|palmette|cartouches|lobed|6,8|court",
    "Azure Arabesque Medallion|medallion|vine|flower|vine|lobed|7,9|court",
    "Ivory Palmette Garden|garden|palmette|flower|cartouches|rosette|4,6|garden",
    "Ruby Compartment Carpet|compartments|star8|palmette|rosettes|none|4,5|compartment",
    "Celadon Ogival Lattice|ogival|flower|paisley|vine|none|5,7|court",
    "Midnight Millefleur Court|medallion|flower|leaf|rosettes|lobed|8,10|floral",
    "Eightfold Knot Garden|trellis|star8|knot|stars|rosette|5,7|geometry",
    "Twelvefold Celestial Carpet|radial|star12|knot|cartouches|star12|6,6|geometry",
    "Emerald Garden Channels|garden|tree|flower|vine|palmette|4,4|garden",
    "Rosewater Vase Garden|vases|flower|leaf|rosettes|none|3,4|garden",
    "Cypress and Blossom Court|tree|vine|flower|cartouches|none|5,8|garden",
    "Indigo Arch Garden|arch|flower|palmette|vine|rosette|6,8|garden",
    "Crimson Twin Medallions|vertical|vine|paisley|rosettes|lobed|6,9|court",
    "Golden Star Ushak Study|ogival|star8|vine|cartouches|none|3,5|ushak",
    "Pearl Cartouche Lattice|compartments|lobed|flower|vine|none|3,4|compartment",
    "Sapphire Interlace Field|trellis|knot|star8|stars|none|7,7|geometry",
    "Rose and Cypress Panels|compartments|tree|flower|cartouches|none|4,4|garden",
    "Ivory Boteh Orchard|diagonal|paisley|flower|vine|none|6,8|floral",
    "Midnight Blossom Spiral|radial|vine|flower|rosettes|rosette|7,9|floral",
    "Ruby Fourfold Paradise|garden|palmette|paisley|cartouches|lobed|4,6|garden",
    "Teal Star Compartments|compartments|star12|knot|stars|none|5,6|geometry",
    "Saffron Palmette Chains|strips|palmette|vine|rosettes|none|5,7|floral",
    "Celadon Ribbon Cartouches|ogival|lobed|leaf|cartouches|none|4,6|compartment",
    "Indigo Cross Garden|cross|flower|palmette|vine|star8|7,8|garden",
    "Copper Blossom Medallion|medallion|paisley|leaf|rosettes|rosette|8,9|court",
    "Moonlit Lattice Garden|trellis|flower|knot|stars|lobed|6,8|geometry",
    "Crimson Arch Palmettes|arch|palmette|vine|cartouches|star12|5,7|garden",
    "Pearl Vase Compartments|vases|vine|palmette|vine|none|4,5|compartment",
    "Azure Triple Rosettes|triple|flower|paisley|rosettes|lobed|7,7|ushak",
    "Ochre Saz Leaf Field|diagonal|leaf|palmette|cartouches|none|5,8|floral",
    "Sapphire Eightfold Court|radial|knot|star8|stars|lobed|5,7|geometry",
    "Ruby Leaf Scrolls|bands|vine|leaf|vine|none|6,9|floral",
    "Emerald Millefleur Arch|arch|flower|paisley|rosettes|none|8,10|floral",
    "Ivory Star Rosette Pavilion|cross|star12|vine|cartouches|star8|6,6|geometry",
    "Celadon Garden Windows|patchwork|palmette|tree|vine|none|5,5|garden",
    "Saffron Pendant Medallions|vertical|paisley|flower|stars|lobed|7,8|court",
  ],
  "Rug atelier": [
    "Hooked Diamond Caravan|vertical|hook|quarters|hooks|stepped|5,8|kilim",
    "Octagonal Shield Runner|vertical|nested|comb|diamonds|octagon|4,9|caucasus",
    "Red Kilim Stairway|kilim|chevron|hook|teeth|none|4,7|kilim",
    "Ivory Walled Garden|garden|flower|leaf|vine|rosette|3,5|garden",
    "Blue Dragon Lattice Study|trellis|hook|palmette|diamonds|none|5,7|caucasus",
    "Madder Three Guls|triple|octagon|hook|hooks|octagon|6,8|geometric",
    "Amber Serrated Medallion|medallion|hook|quarters|teeth|stepped|6,8|kilim",
    "Mountain Star Lattice|diagonal|star8|hook|stars|none|5,6|caucasus",
    "Patchwork Rose Salon|patchwork|flower|paisley|vine|none|5,5|floral",
    "Cypress Panel Runner|strips|tree|flower|cartouches|none|3,7|garden",
    "Charcoal Ivory Maze Rug|compartments|maze|nested|meander|none|4,6|geometric",
    "Copper Diamond Pavilion|cross|hook|rosette|diamonds|octagon|6,7|caucasus",
    "Terracotta Palmette Salon|ogival|palmette|flower|vine|none|5,6|floral",
    "Midnight Boteh Runner|strips|paisley|leaf|rosettes|none|4,8|floral",
    "Ochre Chain of Shields|vertical|quarters|hook|checks|nested|5,7|geometric",
    "Saffron Cartouche Mosaic|compartments|lobed|palmette|cartouches|none|4,6|compartment",
    "Stepped Cross Kilim|cross|chevron|comb|teeth|hook|6,6|kilim",
    "Ruby Diamond River|bands|nested|hook|hooks|none|5,9|kilim",
    "Cobalt Rosette Quilt|patchwork|rosette|knot|stars|none|6,5|geometric",
    "Moss Tree of Life Rug|tree|flower|paisley|vine|none|6,9|garden",
    "Sandstone Octagon Field|trellis|octagon|quarters|meander|none|6,8|caucasus",
    "Indigo Ivory Guardbands|bordered|rings|leaf|rosettes|lobed|7,8|floral",
    "Madder Latch Hook Garden|garden|hook|comb|hooks|stepped|4,5|kilim",
    "Ivory Embroidered Rosettes|radial|flower|leaf|cartouches|rosette|7,8|court",
    "Blue Palmette Crossings|cross|palmette|vine|vine|lobed|5,8|floral",
    "Ochre Tile and Vine Rug|compartments|star8|vine|rosettes|none|6,4|compartment",
    "Crimson Stair Diamond Field|diagonal|stepped|quarters|teeth|none|5,8|kilim",
    "Twelvefold Compass Rug|radial|star12|octagon|stars|knot|6,7|geometry",
    "Juniper Garden Canals|garden|tree|palmette|diamonds|star8|5,6|garden",
    "Rose Lattice and Buds|trellis|vine|flower|cartouches|none|7,9|floral",
    "Bronze Split Shield Mosaic|patchwork|quarters|octagon|meander|none|5,7|geometric",
    "Ivory Hooked Cartouches|ogival|hook|nested|hooks|none|4,7|caucasus",
    "Sapphire Star Garland|bands|star8|knot|stars|none|6,8|geometry",
    "Rust Blossom Gateway|arch|vine|flower|rosettes|palmette|5,9|garden",
    "Caravan Stripe and Lozenge|strips|nested|chevron|checks|none|7,5|kilim",
    "Golden Pendant Garden|medallion|tree|flower|cartouches|octagon|6,10|court",
  ],
};
export const rugDesignCatalog = Object.entries(rugBlueprints).flatMap(
  ([group, lines]) =>
    lines.map((line, index) => {
      const [name, layout, motif, secondary, border, center, grid, study] =
        line.split("|");
      return {
        name,
        group,
        layout,
        motif,
        secondary,
        border,
        center,
        cols: +grid.split(",")[0],
        rows: +grid.split(",")[1],
        study,
        index,
        id: name.toLowerCase().replaceAll(" ", "-"),
        palette: "Designed composition",
        detailed: true,
        description: `${layout} layout · ${motif} and ${secondary} field · ${border} borders`,
      };
    }),
);
export const rugStudySources = {
  reference: { label: "Earlier supplied diamond-rug reference", url: null },
  raffia: {
    label: "Kuba raffia embroidery research · V&A",
    url: "https://collections.vam.ac.uk/item/O89315/kuba-cloth-kuba-cloth-unknown/",
  },
  strip: {
    label: "Asante/Ewe strip-weaving research · Quilt Museum",
    url: "https://www.internationalquiltmuseum.org/exhibition/kente-kuba",
  },
  indigo: {
    label: "Adire resist-panel research · Quilt Museum",
    url: "https://www.internationalquiltmuseum.org/exhibition/kente-kuba",
  },
  earth: {
    label: "Bògòlanfini layout research · FIT",
    url: "https://fashionhistory.fitnyc.edu/bogolanfini/",
  },
  court: {
    label: "Medallion and floral carpet research · The Met",
    url: "https://www.metmuseum.org/essays/carpets-from-the-islamic-world-1600-1800",
  },
  garden: {
    label: "Garden/vase carpet research · The Met",
    url: "https://www.metmuseum.org/essays/carpets-from-the-islamic-world-1600-1800",
  },
  floral: {
    label: "Floral carpet research · The Met",
    url: "https://www.metmuseum.org/essays/carpets-from-the-islamic-world-1600-1800",
  },
  ushak: {
    label: "Ogival medallion research · The Met",
    url: "https://www.metmuseum.org/art/collection/search/445311",
  },
  compartment: {
    label: "Compartment carpet research · The Met",
    url: "https://www.metmuseum.org/art/collection/search/445996",
  },
  geometry: {
    label: "Geometric carpet research · The Met",
    url: "https://www.metmuseum.org/essays/carpets-from-the-islamic-world-1600-1800",
  },
  caucasus: {
    label: "Caucasus geometric carpet research · The Met",
    url: "https://www.metmuseum.org/art/collection/search/447580",
  },
  kilim: {
    label: "Hook/star/diamond design research · Kilim",
    url: "https://www.kilim.com/kilim-wiki/what-is-a-turkish-rug",
  },
  geometric: {
    label: "Geometric carpet research · The Met",
    url: "https://www.metmuseum.org/art/collection/search/447580",
  },
};
