// Phase 32g — exact complete four-edge parallel family and thin-section feasibility.
#include "Kernel/BlendSolver.h"
#include "Console/ConsoleHost.h"
#include "VerificationPanel.h"
#include <algorithm>
#include <cmath>
#include <filesystem>
#include <string>
#include <vector>
using namespace Frontier;
namespace{
struct Check{bool Topology=false,Supports=false,Exact=false;};
Check Inspect(const BrepBody&B,double R){Check Q;auto V=B.Validate();Q.Topology=V.Solid()&&V.Hulls==1&&V.Genus==0&&B.Vertices.size()==16&&B.Edges.size()==24&&B.Coedges.size()==48&&B.Loops.size()==10&&B.Faces.size()==10;int P=0,C=0;bool E=true;for(auto&F:B.Faces){if(F.Surface.Classification==SurfaceClassification::Plane)++P;if(F.Surface.Classification==SurfaceClassification::Cylinder){++C;E&=F.Surface.Rational()&&std::fabs(F.Surface.RadiusMajor-R)<1e-10;}}Q.Supports=P==6&&C==4;Q.Exact=E;return Q;}
double Volume(double L,double A,double B,double R){return L*(A*B-4*R*R*(1-ScalarCriteria::Pi/4));}
}
int main(){VerificationPanel P("SolidArc · Phase 32g · Rounded Prism Edge-Family Verification");auto S=BrepBody::Box({0,0,0},{20,16,12});auto Before=S.Payload.Validate();std::vector<int>X{0,2,4,6};
P.Section("Complete parallel family");int Applied=-1;auto R=BlendSolver::FilletEdges(S.Payload,X,2,&Applied);P.Expect("Four parallel X edges commit as one transaction",R&&Applied==4);Check Q=R?Inspect(R.Payload,2):Check{};P.Expect("The rounded prism has V16/E24/C48/L10/F10 topology",Q.Topology);P.Expect("Six planes and four exact cylindrical rolls remain",Q.Supports);P.Expect("All four rolling supports retain rational radius identity",Q.Exact);P.Expect("The rounded prism removes material",R&&R.Payload.Validate().Volume<Before.Volume);P.Within("Rounded-section volume follows the exact extrusion formula",R?std::fabs(R.Payload.Validate().Volume-Volume(20,16,12,2)):1e9,0.5);P.Expect("The blend preserves the full box extents",R&&R.Payload.Bounds().Low.Distance(S.Payload.Bounds().Low)<1e-9&&R.Payload.Bounds().High.Distance(S.Payload.Bounds().High)<1e-9);P.Expect("The source remains unchanged",S.Payload.Edges.size()==12&&std::fabs(S.Payload.Validate().Volume-Before.Volume)<1e-12);
P.Section("Axis, ordering, transform, and thin-wall bounds");std::vector<int>Reverse{6,0,4,2,6,0};int RC=-1;auto RR=BlendSolver::FilletEdges(S.Payload,Reverse,2,&RC);P.Expect("Order and repeated family seeds deduplicate to four",RR&&RC==4);P.Within("Reordered and canonical volumes are identical",R&&RR?std::fabs(R.Payload.Validate().Volume-RR.Payload.Validate().Volume):1e9,1e-9);int YC=-1;auto Y=BlendSolver::FilletEdges(S.Payload,{1,3,5,7},2,&YC);P.Expect("The orthogonal Y-edge family uses the same exact topology",Y&&YC==4&&Inspect(Y.Payload,2).Topology);int ZC=-1;auto Z=BlendSolver::FilletEdges(S.Payload,{8,9,10,11},2,&ZC);P.Expect("The vertical edge family uses the same exact topology",Z&&ZC==4&&Inspect(Z.Payload,2).Topology);Mat4 M=Mat4::Translation({2,-5,3})*Mat4::Rotation({1,3,2},0.54);BrepBody T=S.Payload.Transformed(M);int TC=-1;auto TR=BlendSolver::FilletEdges(T,X,2,&TC);P.Expect("Rigid transforms preserve family classification",TR&&TC==4&&Inspect(TR.Payload,2).Topology);P.Within("Rigid transformation preserves prism volume",R&&TR?std::fabs(R.Payload.Validate().Volume-TR.Payload.Validate().Volume):1e9,0.5);auto Thin=BrepBody::Box({0,0,0},{20,4,12});int Refused=99;auto TooLarge=BlendSolver::FilletEdges(Thin.Payload,X,2,&Refused);P.Expect("A 2r-equals-wall family refuses before construction",!TooLarge&&Refused==0&&std::string(TooLarge.Denial.Detail)=="parallel-edge fillet radius consumes the rounded-prism cross-section");Refused=99;auto Mixed=BlendSolver::FilletEdges(S.Payload,{0,1,4,5},1,&Refused);P.Expect("A mixed interacting four-edge set still refuses transactionally",!Mixed&&Refused==0);
P.Section("Console and proof");
#ifndef SOLIDARC_PROOF_FOLDER
#error proof folder required
#endif
ConsoleHost H(SOLIDARC_PROOF_FOLDER,1280,800);bool OK=H.Execute("box (0,0,0) (20,16,12) --name=Box")&&H.Execute("fillet Box 2 --edges=0,2,4,6 --name=Prism");auto*F=H.Document().Find("Prism");P.Expect("The console commits a four-edge family",OK);P.Expect("The console result retains four exact rolls",F&&Inspect(F->Body,2).Supports);std::filesystem::path Proof=std::filesystem::path(SOLIDARC_PROOF_FOLDER)/"Phase32g_RoundedPrism.png";std::error_code E;std::filesystem::remove(Proof,E);ConsoleHost V(SOLIDARC_PROOF_FOLDER,1280,800);auto Reset=[&](){return V.Execute("reset")&&V.Execute("gizmo off");};auto Add=[&](const char*N,BrepBody B,uint8_t C){auto&G=V.Document().AddBody(N,std::move(B));G.Matcap=C;return true;};bool Rendered=Reset()&&Add("Sharp",S.Payload.Transformed(Mat4::Translation({-24,0,0})),0)&&Add("XPrism",R.Payload.Transformed(Mat4::Translation({8,0,0})),3)&&V.Execute("view iso")&&V.Execute("view fit")&&V.Execute("render sheet 0")&&Reset()&&Add("XFamily",R.Payload,3)&&V.Execute("view right")&&V.Execute("view fit")&&V.Execute("render sheet 1")&&Reset()&&Add("YFamily",Y.Payload,2)&&V.Execute("view front")&&V.Execute("view fit")&&V.Execute("render sheet 2")&&Reset()&&Add("ZFamily",Z.Payload,5)&&V.Execute("view top")&&V.Execute("view fit")&&V.Execute("render sheet 3")&&V.Execute("render sheet finalize Phase32g_RoundedPrism");P.Expect("C++ rounded-prism proof commands complete",Rendered);P.Expect("C++ rounded-prism proof is written",std::filesystem::exists(Proof)&&std::filesystem::file_size(Proof,E)>100000);return P.Conclude();}
