// Phase 32k — preserve a bounded set of three to eight separated axis-parallel through-holes.
#include "Kernel/BlendSolver.h"
#include "Console/ConsoleHost.h"
#include "VerificationPanel.h"
#include <algorithm>
#include <cmath>
#include <filesystem>
#include <string>
#include <vector>
using namespace Frontier;
namespace{
struct Bore{double Y,Z,R;};
const std::vector<Bore> Main{{4,3,.7},{8,7,.9},{12,4,1.1}};
const std::vector<Bore> Eight{{3.2,3.5,.55},{6.4,3.5,.55},{9.6,3.5,.55},{12.8,3.5,.55},{3.2,8.5,.55},{6.4,8.5,.55},{9.6,8.5,.55},{12.8,8.5,.55}};
const std::vector<Bore> Nine{{4,3,.5},{4,6,.5},{4,9,.5},{8,3,.5},{8,6,.5},{8,9,.5},{12,3,.5},{12,6,.5},{12,9,.5}};
Deliver<BrepBody> Fixture(const std::vector<Bore>&Holes){auto Outer=NurbsCurve::Polyline({{0,0,0},{0,16,0},{0,16,12},{0,0,12}},true);if(!Outer)return Deliver<BrepBody>::Reject(RefusalReason::DegenerateInput,"fixture");std::vector<NurbsCurve>Loops{Outer.Payload};for(auto H:Holes){auto C=NurbsCurve::Circle({0,H.Y,H.Z},{1,0,0},H.R);if(!C)return Deliver<BrepBody>::Reject(C.Denial.Reason,C.Denial.Detail);Loops.push_back(std::move(C.Payload));}return BrepBody::Extrude(Loops,{1,0,0},20);}
std::vector<int> Rails(const BrepBody&B){std::vector<int>R;for(size_t I=0;I<B.Edges.size();++I){auto&E=B.Edges[I];if(E.Curve.Classification!=CurveClassification::Line||E.VertexStart<0||E.VertexEnd<0)continue;Vec3 P=B.Vertices[E.VertexStart].Point,Q=B.Vertices[E.VertexEnd].Point;if(std::fabs(std::fabs((Q-P).Normalised().Dot({1,0,0}))-1)>1e-8)continue;if((std::fabs(P.Y)<1e-8||std::fabs(P.Y-16)<1e-8)&&(std::fabs(P.Z)<1e-8||std::fabs(P.Z-12)<1e-8))R.push_back(static_cast<int>(I));}return R;}
struct Inspection{bool Topology=false,Supports=false,Caps=false;};Inspection Inspect(const BrepBody&B,size_t N){Inspection Q;auto V=B.Validate();Q.Topology=V.Solid()&&V.Hulls==1&&V.Genus==static_cast<int>(N)&&B.Vertices.size()==16+2*N&&B.Edges.size()==24+3*N&&B.Coedges.size()==48+6*N&&B.Loops.size()==10+3*N&&B.Faces.size()==10+N;int Planes=0,Cylinders=0,Rolls=0,Annular=0,Circles=0;bool Exact=true;for(auto&F:B.Faces){auto&S=F.Surface;if(S.Classification==SurfaceClassification::Plane){++Planes;Annular+=F.Loops.size()==N+1;}if(S.Classification==SurfaceClassification::Cylinder){++Cylinders;Exact&=S.Rational();Rolls+=std::fabs(S.RadiusMajor-2)<1e-9;}}for(auto&E:B.Edges)Circles+=E.Closed()&&E.Curve.Classification==CurveClassification::Circle&&E.Curve.Rational();Q.Supports=Planes==6&&Cylinders==static_cast<int>(4+N)&&Rolls==4&&Exact;Q.Caps=Annular==2&&Circles==static_cast<int>(2*N);return Q;}
bool Locations(const BrepBody&B,const std::vector<Bore>&Holes){int Found=0;for(auto H:Holes)for(auto&F:B.Faces)if(F.Surface.Classification==SurfaceClassification::Cylinder&&std::fabs(F.Surface.RadiusMajor-H.R)<1e-9&&F.Surface.Origin.Distance({0,H.Y,H.Z})<1e-8)++Found;return Found==static_cast<int>(Holes.size());}
double Exact(const std::vector<Bore>&Holes){double Area=16*12-4*4*(1-ScalarCriteria::Pi/4);for(auto H:Holes)Area-=ScalarCriteria::Pi*H.R*H.R;return 20*Area;}
}
int main(){VerificationPanel P("SolidArc · Phase 32k · Bounded Multi-Bore Rounded-Prism Verification");auto S=Fixture(Main);auto E=Rails(S.Payload);auto Source=S.Payload.Validate();P.Section("Three-hole exact reconstruction");P.Expect("Three-hole source has canonical V14/E21/C42/L15/F9 genus-three topology",S&&Source.Solid()&&Source.Genus==3&&S.Payload.Vertices.size()==14&&S.Payload.Edges.size()==21&&S.Payload.Coedges.size()==42&&S.Payload.Loops.size()==15&&S.Payload.Faces.size()==9);P.Expect("Exactly four outer axial rails remain selectable",E.size()==4);int Applied=-1;auto R=BlendSolver::FilletEdges(S.Payload,E,2,&Applied);P.Expect("Three separated bores commit with all four outer rolls",R&&Applied==4);auto Q=R?Inspect(R.Payload,3):Inspection{};P.Expect("Three-hole output reaches V22/E33/C66/L19/F13 genus-three topology",Q.Topology);P.Expect("Six planes, four rolls, and three rational bore cylinders remain",Q.Supports);P.Expect("Both end caps retain three exact circular inner loops",Q.Caps);P.Expect("Every distinct bore axis retains its original offset and radius",R&&Locations(R.Payload,Main));P.Within("Three-hole rounded-prism volume follows the exact area extrusion",R?std::fabs(R.Payload.Validate().Volume-Exact(Main)):1e9,.5);P.Expect("Outer bounds and source topology remain unchanged",R&&R.Payload.Bounds().Low.Distance(S.Payload.Bounds().Low)<1e-9&&R.Payload.Bounds().High.Distance(S.Payload.Bounds().High)<1e-9&&S.Payload.Edges.size()==21);
P.Section("Bounded count, order, clearance, and transforms");std::vector<int>Reverse{E[3],E[1],E[0],E[2],E[3]};int Reordered=-1;auto RR=BlendSolver::FilletEdges(S.Payload,Reverse,2,&Reordered);P.Expect("Repeated reordered rails deduplicate deterministically",RR&&Reordered==4&&std::fabs(RR.Payload.Validate().Volume-R.Payload.Validate().Volume)<1e-9);auto ReversedHoles=Main;std::reverse(ReversedHoles.begin(),ReversedHoles.end());auto RS=Fixture(ReversedHoles);int RA=-1;auto RSR=BlendSolver::FilletEdges(RS.Payload,Rails(RS.Payload),2,&RA);P.Expect("Profile-loop order does not alter geometric rim pairing",RSR&&RA==4&&Inspect(RSR.Payload,3).Topology&&Locations(RSR.Payload,Main));auto S8=Fixture(Eight);int A8=-1;auto R8=BlendSolver::FilletEdges(S8.Payload,Rails(S8.Payload),2,&A8);P.Expect("Eight separated bores reach the explicit V32/E48/C96/L34/F18 limit",R8&&A8==4&&Inspect(R8.Payload,8).Topology);P.Within("Eight-hole volume follows the same finite-set formula",R8?std::fabs(R8.Payload.Validate().Volume-Exact(Eight)):1e9,.5);auto Clash=Fixture({{4,4,1},{5.5,4,1},{11,8,1}});int Refused=99;auto CR=BlendSolver::FilletEdges(Clash.Payload,Rails(Clash.Payload),2,&Refused);P.Expect("Any intersecting pair refuses the complete multi-bore transaction",!CR&&Refused==0&&std::string(CR.Denial.Detail)=="rounded-prism holes consume the inter-hole ligament");auto Wall=Fixture({{1.2,1.2,1},{8,7,.8},{12,4,.8}});Refused=99;auto WR=BlendSolver::FilletEdges(Wall.Payload,Rails(Wall.Payload),2,&Refused);P.Expect("Any bore crossing the rounded wall refuses all holes",!WR&&Refused==0);auto S9=Fixture(Nine);Refused=99;auto R9=BlendSolver::FilletEdges(S9.Payload,Rails(S9.Payload),2,&Refused);P.Expect("Nine bores exceed the explicit bounded count",S9&&S9.Payload.Validate().Genus==9&&!R9&&Refused==0);Mat4 M=Mat4::Translation({3,-4,7})*Mat4::Rotation({1,3,2},.61);BrepBody T=S.Payload.Transformed(M);int TA=-1;auto TR=BlendSolver::FilletEdges(T,E,2,&TA);P.Expect("Rigid transforms preserve finite-set rim pairing and genus",TR&&TA==4&&TR.Payload.Validate().Genus==3);P.Within("Rigid transforms preserve multi-bore volume",R&&TR?std::fabs(R.Payload.Validate().Volume-TR.Payload.Validate().Volume):1e9,.5);
P.Section("Console and proof");
#ifndef SOLIDARC_PROOF_FOLDER
#error proof folder required
#endif
ConsoleHost H(SOLIDARC_PROOF_FOLDER,1280,800);auto&F=H.Document().AddBody("MultiBore",S.Payload);F.Matcap=6;std::string List;for(int I:E){if(!List.empty())List+=",";List+=std::to_string(I);}bool OK=H.Execute("fillet MultiBore 2 --edges="+List+" --name=MultiRound");auto*Output=H.Document().Find("MultiRound");P.Expect("Console fillet commits one genus-three multi-bore solid",OK&&Output&&Output->Body.Validate().Genus==3);
std::filesystem::path Proof=std::filesystem::path(SOLIDARC_PROOF_FOLDER)/"Phase32k_MultiBorePrism.png";std::error_code Error;std::filesystem::remove(Proof,Error);ConsoleHost V(SOLIDARC_PROOF_FOLDER,1280,800);auto Reset=[&](){return V.Execute("reset")&&V.Execute("gizmo off");};auto Add=[&](const char*N,BrepBody B,uint8_t C){auto&G=V.Document().AddBody(N,std::move(B));G.Matcap=C;return true;};bool Rendered=Reset()&&Add("MultiSharp",S.Payload.Transformed(Mat4::Translation({-24,0,0})),6)&&Add("MultiRound",R.Payload.Transformed(Mat4::Translation({8,0,0})),3)&&V.Execute("view iso")&&V.Execute("view fit")&&V.Execute("render sheet 0")&&Reset()&&Add("ThreeEnd",R.Payload,3)&&V.Execute("view right")&&V.Execute("view fit")&&V.Execute("render sheet 1")&&Reset()&&Add("EightEnd",R8.Payload,2)&&V.Execute("view right")&&V.Execute("view fit")&&V.Execute("render sheet 2")&&Reset()&&Add("MultiTilt",TR.Payload,5)&&V.Execute("view iso")&&V.Execute("view fit")&&V.Execute("render sheet 3")&&V.Execute("render sheet finalize Phase32k_MultiBorePrism");P.Expect("C++ multi-bore proof commands complete",Rendered);P.Expect("C++ multi-bore proof is written",std::filesystem::exists(Proof)&&std::filesystem::file_size(Proof,Error)>100000);return P.Conclude();}
